In [1]:
# Import base dependencies
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# Import ML dependencies
import numpy as np
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import SimpleRNN, Flatten, TimeDistributed, LSTM

In [1]:
# Import yfinance api
import yfinance as yf

In [ ]:
# Import available ETF/mutual funds from platform
# import raw data from platform export

# Convert to dataframe

# Extract list of ticker symbols from export

# Build into list

# convert to set to remove duplicates

# Join into string format to use in api call

In [21]:
# Query data via api
sono = yf.Ticker("SONO")
fselx = yf.Ticker("FSELX")
spmo = yf.Ticker("SPMO")

tickers = yf.Tickers('msft aapl goog')

# access each ticker using (example)
tickers.tickers['MSFT'].info
tickers.tickers['AAPL'].history(period="1mo")
tickers.tickers['GOOG'].actions

In [16]:
# get all stock info
fselx.info

{'address1': 'Boston MA 02109',
 'address2': '82 Devonshire Street',
 'address3': 'Fidelity Select Portfolios',
 'longBusinessSummary': "The fund invests primarily in common stocks. It invests at least 80% of its assets in securities of companies principally engaged in the design, manufacture, or sale of semiconductors and semiconductor equipment. The fund invests in domestic and foreign issuers. It uses fundamental analysis of factors such as each issuer's financial condition and industry position, as well as market and economic conditions, to select investments. The fund is non-diversified.",
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 30.55,
 'regularMarketPreviousClose': 30.55,
 'yield': 0.0008,
 'ytdReturn': 0.23257731,
 'totalAssets': 16760119296,
 'fiftyTwoWeekLow': 19.11,
 'fiftyTwoWeekHigh': 32.18,
 'fiftyDayAverage': 30.1576,
 'twoHundredDayAverage': 25.66435,
 'currency': 'USD',
 'morningStarOverallRating': 5,
 'morningStarRiskRating': 5,
 'annualReportExpenseRatio': 0.0064999997,
 'beta3Year': 1.84,
 'fundInceptionDate': 491443200,
 'lastDividendValue': 0.024,
 'lastCapGain': 45.0,
 'annualHoldingsTurnover': 0.32,
 'exchange': 'NAS',
 'quoteType': 'MUTUALFUND',
 'symbol': 'FSELX',
 'underlyingSymbol': 'FSELX',
 'shortName': 'Fidelity Select Semiconductors ',
 'longName': 'Fidelity Select Semiconductors',
 'firstTradeDateEpochUtc': 491491800,
 'timeZoneFullName': 'America/New_York',
 'timeZoneShortName': 'EDT',
 'uuid': '1f62e1f7-e31b-35a5-8efb-014d23d49908',
 'messageBoardId': 'finmb_28181084',
 'gmtOffSetMilliseconds': -14400000,
 'trailingPegRatio': None}

In [14]:
# get historical market data
hist = fselx.history(period="1mo")

In [15]:
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Capital Gains
Date,,,,,,,,
2024-04-11 00:00:00-04:00,31.120001,31.120001,31.120001,31.120001,0,0.0,0.0,0.0
2024-04-12 00:00:00-04:00,30.110001,30.110001,30.110001,30.110001,0,0.0,0.0,0.0
2024-04-15 00:00:00-04:00,29.540001,29.540001,29.540001,29.540001,0,0.0,0.0,0.0
2024-04-16 00:00:00-04:00,29.840000,29.840000,29.840000,29.840000,0,0.0,0.0,0.0
2024-04-17 00:00:00-04:00,28.900000,28.900000,28.900000,28.900000,0,0.0,0.0,0.0
2024-04-18 00:00:00-04:00,28.459999,28.459999,28.459999,28.459999,0,0.0,0.0,0.0
2024-04-19 00:00:00-04:00,26.950001,26.950001,26.950001,26.950001,0,0.0,0.0,0.0
2024-04-22 00:00:00-04:00,27.510000,27.510000,27.510000,27.510000,0,0.0,0.0,0.0
2024-04-23 00:00:00-04:00,28.280001,28.280001,28.280001,28.280001,0,0.0,0.0,0.0
2024-04-24 00:00:00-04:00,28.379999,28.379999,28.379999,28.379999,0,0.0,0.0,0.0
2024-04-25 00:00:00-04:00,29.150000,29.150000,29.150000,29.150000,0,0.0,0.0,0.0
2024-04-26 00:00:00-04:00,30.160000,30.160000,30.160000,30.160000,0,0.0,0.0,0.0
2024-04-29 00:00:00-04:00,30.330000,30.330000,30.330000,30.330000,0,0.0,0.0,0.0
2024-04-30 00:00:00-04:00,29.889999,29.889999,29.889999,29.889999,0,0.0,0.0,0.0
2024-05-01 00:00:00-04:00,28.870001,28.870001,28.870001,28.870001,0,0.0,0.0,0.0
2024-05-02 00:00:00-04:00,29.600000,29.600000,29.600000,29.600000,0,0.0,0.0,0.0
2024-05-03 00:00:00-04:00,30.340000,30.340000,30.340000,30.340000,0,0.0,0.0,0.0
2024-05-06 00:00:00-04:00,31.020000,31.020000,31.020000,31.020000,0,0.0,0.0,0.0
2024-05-07 00:00:00-04:00,30.820000,30.820000,30.820000,30.820000,0,0.0,0.0,0.0
2024-05-08 00:00:00-04:00,30.780001,30.780001,30.780001,30.780001,0,0.0,0.0,0.0
2024-05-09 00:00:00-04:00,30.549999,30.549999,30.549999,30.549999,0,0.0,0.0,0.0
2024-05-10 00:00:00-04:00,30.830000,30.830000,30.830000,30.830000,0,0.0,0.0,0.0

In [8]:
# show meta information about the history (requires history() to be called first)
sono.history_metadata

{'currency': 'USD',
 'symbol': 'SONO',
 'exchangeName': 'NMS',
 'fullExchangeName': 'NasdaqGS',
 'instrumentType': 'EQUITY',
 'firstTradeDate': 1533216600,
 'regularMarketTime': 1715371200,
 'hasPrePostMarketData': True,
 'gmtoffset': -14400,
 'timezone': 'EDT',
 'exchangeTimezoneName': 'America/New_York',
 'regularMarketPrice': 16.63,
 'fiftyTwoWeekHigh': 17.34,
 'fiftyTwoWeekLow': 16.41,
 'regularMarketDayHigh': 17.34,
 'regularMarketDayLow': 16.41,
 'regularMarketVolume': 1544844,
 'chartPreviousClose': 17.88,
 'priceHint': 2,
 'currentTradingPeriod': {'pre': {'timezone': 'EDT',
   'start': 1715328000,
   'end': 1715347800,
   'gmtoffset': -14400},
  'regular': {'timezone': 'EDT',
   'start': 1715347800,
   'end': 1715371200,
   'gmtoffset': -14400},
  'post': {'timezone': 'EDT',
   'start': 1715371200,
   'end': 1715385600,
   'gmtoffset': -14400}},
 'dataGranularity': '1d',
 'range': '1mo',
 'validRanges': ['1d',
  '5d',
  '1mo',
  '3mo',
  '6mo',
  '1y',
  '2y',
  '5y',
  '10y',
  'ytd',
  'max']}

In [ ]:
# show actions (dividends, splits, capital gains)
sono.actions
sono.dividends
sono.splits
sono.capital_gains  # only for mutual funds & etfs

In [9]:
# show share count
sono.get_shares_full(start="2022-01-01", end=None)

2022-01-25 00:00:00-05:00    128116000
2022-02-12 00:00:00-05:00    128116000
2022-02-15 00:00:00-05:00    127609000
2022-02-16 00:00:00-05:00    127609000
2022-02-17 00:00:00-05:00    127609000
                               ...
2024-05-04 00:00:00-04:00    123843000
2024-05-07 00:00:00-04:00    123843000
2024-05-09 00:00:00-04:00    122901000
2024-05-11 00:00:00-04:00    122901000
2024-05-11 00:00:00-04:00    127483000
Length: 177, dtype: int64

In [ ]:
# show financials:
# - income statement
sono.income_stmt
sono.quarterly_income_stmt
# - balance sheet
sono.balance_sheet
sono.quarterly_balance_sheet
# - cash flow statement
sono.cashflow
sono.quarterly_cashflow
# see `Ticker.get_income_stmt()` for more options

In [ ]:
# show holders
sono.major_holders
sono.institutional_holders
sono.mutualfund_holders
sono.insider_transactions
sono.insider_purchases
sono.insider_roster_holders

In [31]:
sono.recommendations

  period  strongBuy  buy  hold  sell  strongSell
0     0m          0    3     3     0           0
1    -1m          1    4     1     0           0
2    -2m          1    4     2     0           0
3    -3m          0    0     0     0           0

In [ ]:
# show recommendations
sono.recommendations
sono.recommendations_summary
sono.upgrades_downgrades

In [10]:
# Show future and historic earnings dates, returns at most next 4 quarters and last 8 quarters by default. 
# Note: If more are needed use msft.get_earnings_dates(limit=XX) with increased limit argument.
sono.earnings_dates

                           EPS Estimate  Reported EPS  Surprise(%)
Earnings Date
2025-05-05 16:00:00-04:00           NaN           NaN          NaN
2025-03-11 13:00:00-04:00           NaN           NaN          NaN
2025-02-04 05:00:00-05:00           NaN           NaN          NaN
2024-11-13 05:00:00-05:00           NaN           NaN          NaN
2024-08-07 06:00:00-04:00          0.06           NaN          NaN
2024-05-07 16:00:00-04:00         -0.46         -0.56      -0.2121
2024-03-11 13:00:00-04:00          0.39          0.64       0.6410
2024-03-04 14:00:00-05:00          0.39          0.64       0.6410
2024-02-06 16:00:00-05:00          0.40          0.64       0.6203
2023-11-15 16:00:00-05:00         -0.18         -0.25      -0.3672
2023-08-09 16:00:00-04:00         -0.20         -0.18       0.1000
2023-05-10 16:00:00-04:00         -0.18         -0.24      -0.3043

In [ ]:
# show ISIN code - *experimental*
# ISIN = International Securities Identification Number
sono.isin

In [ ]:
# show options expirations
sono.options

In [11]:
# show news
sono.news

[{'uuid': 'd8a21a0a-6014-3007-84a1-86d3d2386b0e',
  'title': 'Earnings Update: Sonos, Inc. (NASDAQ:SONO) Just Reported Its Second-Quarter Results And Analysts Are Updating Their Forecasts',
  'publisher': 'Simply Wall St.',
  'link': 'https://finance.yahoo.com/news/earnings-sonos-inc-nasdaq-sono-125837562.html',
  'providerPublishTime': 1715432317,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/gW2_smUq7ytmSGVYCfeuBw--~B/aD00MzI7dz0xMTk0O2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/simply_wall_st__316/0a28bd8b29649512bd7689bb7709759e',
     'width': 1194,
     'height': 432,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/nPbMAiH8669sjOTMAU50bA--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/simply_wall_st__316/0a28bd8b29649512bd7689bb7709759e',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['SONO']},
 {'uuid': 'ac54324f-3ca7-3486-a4cb-9e8f5d22dcf4',
  'title': 'SharkNinja Beats First-Quarter Goals With Strong Kitchen Device Sales',
  'publisher': "Investor's Business Daily",
  'link': 'https://finance.yahoo.com/m/ac54324f-3ca7-3486-a4cb-9e8f5d22dcf4/sharkninja-beats.html',
  'providerPublishTime': 1715288156,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/tKSAiWCMdUCXG4039_KYKg--~B/aD01NjM7dz0xMDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/ibd.com/75641bd0a3549a461c8e9d61b3602284',
     'width': 1000,
     'height': 563,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/MbWdrPj3P3Uv5_eGpBy4mA--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/ibd.com/75641bd0a3549a461c8e9d61b3602284',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['SONO', 'IRBT']},
 {'uuid': '70b3a545-b22b-3341-81e1-a56471192720',
  'title': 'Sonos (SONO) Swings to Loss in Q2, Revenues Decline Y/Y',
  'publisher': 'Zacks',
  'link': 'https://finance.yahoo.com/news/sonos-sono-swings-loss-q2-151300968.html',
  'providerPublishTime': 1715181180,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/hb34T5JpqfOKFdxuauyatA--~B/aD00MDA7dz02MzU7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/zacks.com/560ce7090345bb7408c706b8e0a8c3fc',
     'width': 635,
     'height': 400,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/WGxO6Lux22KyfhfK1ELLQA--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/zacks.com/560ce7090345bb7408c706b8e0a8c3fc',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['SONO', 'BMI']},
 {'uuid': '47b4a01f-26d5-3c7a-ae34-b9a4afea43bb',
  'title': 'Sonos, Inc. (NASDAQ:SONO) Q2 2024 Earnings Call Transcript',
  'publisher': 'Insider Monkey',
  'link': 'https://finance.yahoo.com/news/sonos-inc-nasdaq-sono-q2-135347618.html',
  'providerPublishTime': 1715176427,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/BW94SeP59bFc12D6yp.LFQ--~B/aD04MTY7dz0xNDU2O2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/insidermonkey.com/87911ac5f2069ba8525ff17932c3f68b',
     'width': 1456,
     'height': 816,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/kU.XA7qpFbh50Pf8admlCw--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/insidermonkey.com/87911ac5f2069ba8525ff17932c3f68b',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['SONO']},
 {'uuid': '4ac6fbee-a395-343d-b09c-53aba2dad401',
  'title': 'Q2 2024 Sonos Inc Earnings Call',
  'publisher': 'Thomson Reuters StreetEvents',
  'link': 'https://finance.yahoo.com/news/q2-2024-sonos-inc-earnings-111022756.html',
  'providerPublishTime': 1715166622,
  'type': 'STORY',
  'relatedTickers': ['SONO']},
 {'uuid': 'db766122-7f93-304e-93ab-8d6c2b9997de',
  'title': 'Sonos Inc (SONO) Q2 2024 Earnings Call Transcript Highlights: Navigating Market Challenges with ...',
  'publisher': 'GuruFocus.com',
  'link': 'https://finance.yahoo.com/news/sonos-inc-sono-q2-2024-081010625.html',
  'providerPublishTime': 1715155810,
  'type': 'STORY',
  'relatedTickers': ['SONO']},
 {'uuid': '7ddf46e1-a1e5-3e34-ae39-52a9c33d170b',
  'title': 'Sonos (SONO) Q2 2024 Earnings Call Transcript',
  'publisher': 'Motley Fool',
  'link': 'https://finance.yahoo.com/m/7ddf46e1-a1e5-3e34-ae39-52a9c33d170b/sonos-%28sono%29-q2-2024-earnings.html',
  'providerPublishTime': 1715139016,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/AgPxjmk.l0_x4qaFILkqiQ--~B/aD00Mjc7dz00MDA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/e48e86dda35543079ee2080fd9208b73',
     'width': 400,
     'height': 427,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/oVP_Q9NIziRyCtD.nB7xKw--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/e48e86dda35543079ee2080fd9208b73',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['SONO']},
 {'uuid': 'fcb9e7a4-91d4-3630-b439-1776d773f6ca',
  'title': 'Compared to Estimates, Sonos (SONO) Q2 Earnings: A Look at Key Metrics',
  'publisher': 'Zacks',
  'link': 'https://finance.yahoo.com/news/compared-estimates-sonos-sono-q2-233010967.html',
  'providerPublishTime': 1715124610,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/HIalcDlt7JZPKSITVlxPuw--~B/aD02MDA7dz05MDA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/zacks.com/c2fdcaac033e049c74f38d188afcc9f9',
     'width': 900,
     'height': 600,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/KwglccBRAqiWaro_ZvjSew--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/zacks.com/c2fdcaac033e049c74f38d188afcc9f9',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['SONO']}]

In [1]:
# Import base data

In [2]:
# Data processing and clearning
# Must be in numpy array or tf.Dataset object format

In [3]:
# Feature selection and normalization

In [4]:
# Build model

In [5]:
# Train model

In [6]:
# Evaluate model

In [7]:
# Refine model through hyperparameter tuning