# LSE list

### For (1) Finding the stocks that are relevant to BP and (2) Finding out more about BP

#### Contextual Information
I also supplemented this information with a **list of Companies and Securities from the London Stock Exchange** (spreadsheet `list-of-all-securites-ex-debt` from [this page](http://www.londonstockexchange.com/statistics/companies-and-issuers/companies-and-issuers.htm). The spreadsheet includes the following attributes for all securities (excluding debt) that were listed on the LSE as of the end of August 2016:
* Security Start Date, 
* Company Name, 
* Country of Incorporation, 
* LSE Market	(UK Main Market, International Main Market, AIM (Alternative Investment Market)...), 
* FCA Listing Category (Standard Shares, Standard Debt...) (FCA stands for Financial Conduct Authority), 
* ISIN (International Securities Identification Number), 
* Security Name (code, e.g. PELS'90' 20/11/17(WORLD BASKET P/WT)GBP1 for Barclays Bank PLC),
* TIDM (stock symbol: Tradable Instrument Display Mnemonic), 
* Mkt Cap £m, 	
* Shares in Issue, 
* Industry, 
* Supersector, 
* Sector, 
* Subsector, 
* Group (a number, e.g. 8355 for banks), 
* MarketSegmentCode, 
* MarketSectorCode, and 
* Trading Currency (GBX, USD, EUR).

Not every column of every row of this spreadsheet is filled. There are some blank cells.

I converted the spreadsheet to a CSV and imported it below:

In [1]:
import pandas as pd

In [2]:
lse_list = pd.read_csv("list-of-all-securities-ex-debt.csv")
# Delete extra columns of NaNs
for i in range(18,36):
    del lse_list['Unnamed: %s' % str(i)]
lse_list.head()

,Security Start Date,Company Name,Country of Incorporation,LSE Market,FCA Listing Category,ISIN,Security Name,TIDM,Mkt Cap £m,Shares in Issue,Industry,Supersector,Sector,Subsector,Group,MarketSegmentCode,MarketSectorCode,Trading Currency
0,2-Aug-06,1PM PLC,GB,AIM,NaN,GB00BCDBXK43,ORD GBP0.1,OPM,33.884729,"52,534,463.00",Financials,Financial Services,Financial Services,Specialty Finance,8775,AIM,AIM,GBX
1,2-Feb-09,1SPATIAL PLC,GB,AIM,NaN,GB00B09LQS34,ORD GBP0.01,SPA,32.293431,"738,135,558.00",Industrials,Industrial Goods & Services,Support Services,Business Support Services,2791,AIM,AIM,GBX
2,15-Apr-05,21ST CENTURY TECHNOLOGY PLC,GB,AIM,NaN,GB0008866310,ORD GBP0.065,C21,1.748245,"93,239,755.00",Industrials,Industrial Goods & Services,Support Services,Business Support Services,2791,AIM,AIM,GBX
3,23-Sep-05,32RED,GI,AIM,NaN,GI000A0F56M0,ORD GBP0.002,TTR,108.901996,"83,690,295.00",Consumer Services,Travel & Leisure,Travel & Leisure,Gambling,5752,AMSM,ASM6,GBX
4,21-Aug-15,365 AGILE GROUP PLC,GB,AIM,NaN,GB00BYY8NN14,ORD GBP0.30,365,5.012229,"18,914,073.00",Industrials,Industrial Goods & Services,Electronic & Electrical Equipment,Electrical Components & Equipment,2733,ASQ1,AMQ1,GBX

In [3]:
lse_list[368:371]

,Security Start Date,Company Name,Country of Incorporation,LSE Market,FCA Listing Category,ISIN,Security Name,TIDM,Mkt Cap £m,Shares in Issue,Industry,Supersector,Sector,Subsector,Group,MarketSegmentCode,MarketSectorCode,Trading Currency
368,20-Dec-54,BP,GB,UK Main Market,Standard Shares,GB0001385474,9% CUM 2ND PRF GBP1,BP.B,80288.531993,"5,473,414.00",Oil & Gas,Oil & Gas,Oil & Gas Producers,Integrated Oil & Gas,537,SSQ3,SQS3,GBX
369,20-Dec-54,BP,GB,UK Main Market,Standard Shares,GB0001385250,8% CUM 1ST PRF GBP1,BP.A,80288.531993,"7,232,838.00",Oil & Gas,Oil & Gas,Oil & Gas Producers,Integrated Oil & Gas,537,SSQ3,SQS3,GBX
370,20-Dec-54,BP,GB,UK Main Market,Premium Equity Commercial Companies,GB0007980591,ORD USD0.25,BP.,80288.531993,"18,758,751,584.00",Oil & Gas,Oil & Gas,Oil & Gas Producers,Integrated Oil & Gas,537,SET0,FE00,GBX

And let's look at all the stocks that are in that group:

In [4]:
print("Number of companies: ", len(lse_list[lse_list['Group'] == 537]))
lse_list[lse_list['Group'] == 537]

Number of companies:  27

,Security Start Date,Company Name,Country of Incorporation,LSE Market,FCA Listing Category,ISIN,Security Name,TIDM,Mkt Cap £m,Shares in Issue,Industry,Supersector,Sector,Subsector,Group,MarketSegmentCode,MarketSectorCode,Trading Currency
368,20-Dec-54,BP,GB,UK Main Market,Standard Shares,GB0001385474,9% CUM 2ND PRF GBP1,BP.B,80288.531993,"5,473,414.00",Oil & Gas,Oil & Gas,Oil & Gas Producers,Integrated Oil & Gas,537,SSQ3,SQS3,GBX
369,20-Dec-54,BP,GB,UK Main Market,Standard Shares,GB0001385250,8% CUM 1ST PRF GBP1,BP.A,80288.531993,"7,232,838.00",Oil & Gas,Oil & Gas,Oil & Gas Producers,Integrated Oil & Gas,537,SSQ3,SQS3,GBX
370,20-Dec-54,BP,GB,UK Main Market,Premium Equity Commercial Companies,GB0007980591,ORD USD0.25,BP.,80288.531993,"18,758,751,584.00",Oil & Gas,Oil & Gas,Oil & Gas Producers,Integrated Oil & Gas,537,SET0,FE00,GBX
499,18-Oct-00,CHINA PETROLEUM & CHEMICAL CORP,CN,International Main Market,Standard GDRs,US16941R1086,ADS EACH REP 100'H'SHS CNY1,SNP,8820.761210,"192,975,620.00",Oil & Gas,Oil & Gas,Oil & Gas Producers,Integrated Oil & Gas,537,IOBU,LLLU,USD
996,15-Nov-99,GAIL(INDIA),IN,PSM,Standard GDRs,US36268T1079,GDR EACH REP 6 ORD INR10 144A,GAIA,0.000000,0.00,Oil & Gas,Oil & Gas,Oil & Gas Producers,Integrated Oil & Gas,537,MISC,INPE,USD
997,15-Nov-99,GAIL(INDIA),IN,PSM,Standard GDRs,US36268T2069,GDR EACH REP 6 ORD INR10 REG'S',GAID,0.000000,"25,833,333.00",Oil & Gas,Oil & Gas,Oil & Gas Producers,Integrated Oil & Gas,537,IOBE,IPHE,USD
1009,12-Jun-06,GAZPROM NEFT PJSC,RU,Trading Only,NaN,US36829G1076,LEVEL 1 ADR EACH REPR 5 ORD SHS,GAZ,0.000000,"20,348,882.00",Oil & Gas,Oil & Gas,Oil & Gas Producers,Integrated Oil & Gas,537,IOBE,INHE,USD
1010,28-Oct-96,GAZPROM OAO,RU,International Main Market,Standard GDRs,US3682871088,ADS EACH REP 10 ORD REGD 144A,81JK,36475.696309,0.00,Oil & Gas,Oil & Gas,Oil & Gas Producers,Integrated Oil & Gas,537,MISC,INTM,USD
1011,28-Oct-96,GAZPROM OAO,RU,International Main Market,Standard GDRs,US3682872078,ADS EACH REPR 2 ORD SHS,OGZD,36475.696309,"11,836,756,000.00",Oil & Gas,Oil & Gas,Oil & Gas Producers,Integrated Oil & Gas,537,IOBE,LLHE,USD
1083,27-Oct-14,GREEN DRAGON GAS LTD,KY,International Main Market,Standard Shares,KYG409381053,ORD USD0.0001 (DI),GDG,359.348630,"142,316,289.00",Oil & Gas,Oil & Gas,Oil & Gas Producers,Integrated Oil & Gas,537,SSMU,SMEW,GBX
1164,30-Jun-98,HELLENIC PETROLEUM SA,GR,International Main Market,Standard GDRs,US4233231046,GDS EACH REPR 1 ORD SH'144A',98LQ,0.000000,0.00,Oil & Gas,Oil & Gas,Oil & Gas Producers,Integrated Oil & Gas,537,MISC,INTM,USD
1165,30-Jun-98,HELLENIC PETROLEUM SA,GR,International Main Market,Standard GDRs,US4233232036,GDS EACH REPR 1 ORD REG'S',HLPD,0.000000,"23,215,000.00",Oil & Gas,Oil & Gas,Oil & Gas Producers,Integrated Oil & Gas,537,IOBU,LLLN,USD
1562,7-May-97,LUKOIL PJSC,RU,International Main Market,Standard GDRs,US69343P2048,GDR EACH REPR 1 ORD RUB0.025 SPON 144A,LKOE,58934.583841,"3,450,000.00",Oil & Gas,Oil & Gas,Oil & Gas Producers,Integrated Oil & Gas,537,MISC,INTM,USD
1563,7-May-97,LUKOIL PJSC,RU,International Main Market,Standard GDRs,US69343P1057,ADR EACH REPR 1 ORD RUB0.025 SPON,LKOD,58934.583841,"850,563,000.00",Oil & Gas,Oil & Gas,Oil & Gas Producers,Integrated Oil & Gas,537,IOBE,LLHE,USD
1564,7-May-97,LUKOIL PJSC,RU,International Main Market,Standard Shares,RU0009024277,RUB0.025,LKOH,58934.583841,"850,563,255.00",Oil & Gas,Oil & Gas,Oil & Gas Producers,Integrated Oil & Gas,537,SSX4,SXSN,USD
1582,27-Sep-04,MAGYAR OLAJ-ES GAZIPARE RESZVENYTAR,HU,Trading Only,NaN,US6084642023,ADR EACH REP 0.50 ORD SHS(REG'S'),MOLD,0.000000,0.00,Oil & Gas,Oil & Gas,Oil & Gas Producers,Integrated Oil & Gas,537,IOBU,INLN,USD
1601,2-Jun-95,MANDO MACHINERY CORP,KR,International Main Market,Standard GDRs,USY576241019,GDR EACH REP 1/2 ORD,MNMD,0.000000,"806,234.00",Oil & Gas,Oil & Gas,Oil & Gas Producers,Integrated Oil & Gas,537,IOBU,LLLN,USD
1602,2-Jun-95,MANDO MACHINERY CORP,KR,International Main Market,Standard GDRs,US5626651096,GDR EACH REPR 1/2 SHARE(144A),05IS,0.000000,0.00,Oil & Gas,Oil & Gas,Oil & Gas Producers,Integrated Oil & Gas,537,MISC,INTM,USD
2177,19-Jul-06,ROSNEFT OIL CO,RU,International Main Market,Standard GDRs,US67812M1080,GDR EACH REPR 1 ORD '144A',40XT,38202.664097,0.00,Oil & Gas,Oil & Gas,Oil & Gas Producers,Integrated Oil & Gas,537,MISC,INTM,USD
2178,19-Jul-06,ROSNEFT OIL CO,RU,International Main Market,Standard GDRs,US67812M2070,GDR EACH REPR 1 ORD 'REGS',ROSN,38202.664097,"9,597,430,705.00",Oil & Gas,Oil & Gas,Oil & Gas Producers,Integrated Oil & Gas,537,IOBE,LLHE,USD
2204,20-Jul-05,ROYAL DUTCH SHELL,GB,UK Main Market,Premium Equity Commercial Companies,GB00B03MLX29,'A'ORD EUR0.07,RDSA,153220.715397,"4,325,899,655.00",Oil & Gas,Oil & Gas,Oil & Gas Producers,Integrated Oil & Gas,537,SET0,FE00,GBX
2205,20-Jul-05,ROYAL DUTCH SHELL,GB,UK Main Market,Premium Equity Commercial Companies,GB00B03MM408,ORD EUR0.07 B,RDSB,153220.715397,"3,745,486,731.00",Oil & Gas,Oil & Gas,Oil & Gas Producers,Integrated Oil & Gas,537,SET0,FE00,GBX
2222,8-Apr-11,SACOIL HLDGS LTD,ZA,AIM,NaN,ZAE000127460,NPV(DI),SAC,30.352694,"3,195,020,413.00",Oil & Gas,Oil & Gas,Oil & Gas Producers,Integrated Oil & Gas,537,ASQ1,AMQ1,GBX
2470,27-Sep-04,SURGUTNEFTEGAZ,RU,Trading Only,NaN,US8688612048,ADR EACH REPR 10 ORD,SGGD,0.000000,"340,597,744.00",Oil & Gas,Oil & Gas,Oil & Gas Producers,Integrated Oil & Gas,537,IOBE,INHE,USD
2504,13-Dec-96,TATNEFT PJSC,RU,International Main Market,Standard GDRs,US8766292051,ADR EACH REP 6 ORD SHS REGS,ATAD,8160.571386,"363,116,666.00",Oil & Gas,Oil & Gas,Oil & Gas Producers,Integrated Oil & Gas,537,IOBE,LLHE,USD
2564,26-Sep-73,TOTAL SA,FR,International Main Market,Standard Shares,FR0000120271,EUR2.5,TTA,88787.079286,"2,444,133,158.00",Oil & Gas,Oil & Gas,Oil & Gas Producers,Integrated Oil & Gas,537,SSMU,SMEU,EUR
2797,18-Jun-14,ZOLTAV RESOURCES INC,KY,AIM,NaN,KYG9895N1198,ORD USD0.2 (DI),ZOL,31.883712,"141,705,386.00",Oil & Gas,Oil & Gas,Oil & Gas Producers,Integrated Oil & Gas,537,ASQ1,AMQ1,GBX

In [5]:
# Print only company names
lse_list[lse_list['Group'] == 537]['Company Name'].unique()

array(['BP                                 ',
       'CHINA PETROLEUM & CHEMICAL CORP    ',
       'GAIL(INDIA)                        ',
       'GAZPROM NEFT PJSC                  ',
       'GAZPROM OAO                        ',
       'GREEN DRAGON GAS LTD               ',
       'HELLENIC PETROLEUM SA              ',
       'LUKOIL PJSC                        ',
       'MAGYAR OLAJ-ES GAZIPARE RESZVENYTAR',
       'MANDO MACHINERY CORP               ',
       'ROSNEFT OIL CO                     ',
       'ROYAL DUTCH SHELL                  ',
       'SACOIL HLDGS LTD                   ',
       'SURGUTNEFTEGAZ                     ',
       'TATNEFT PJSC                       ',
       'TOTAL SA                           ',
       'ZOLTAV RESOURCES INC               '], dtype=object)

In [6]:
companies = df['Symbol'].unique()
companies

NameError: name 'df' is not defined

OMG do I have to compile the freaking FTSE100 myself??

In [8]:
ftse100_csv = pd.read_csv("ftse100-list.csv")
ftse100_csv

   ticker                          name premium_code      free_code
0     ADN     Aberdeen Asset Management          NaN   GOOG/LON_ADN
1     ADM                 Admiral Group      EOD/ADM   GOOG/LON_ADM
2     AGK                       Aggreko          NaN   GOOG/LON_AGK
3    AMEC                          AMEC          NaN  GOOG/LON_AMEC
4     AAL            Anglo American plc      EOD/AAL   GOOG/LON_AAL
5    ANTO                   Antofagasta          NaN  GOOG/LON_ANTO
6     ARM                  ARM Holdings          NaN   GOOG/LON_ARM
7     ABF      Associated British Foods          NaN   GOOG/LON_ABF
8     AZN                   AstraZeneca      EOD/AZN   GOOG/LON_AZN
9      AV                         Aviva       EOD/AV            NaN
10    BAB         Babcock International      EOD/BAB   GOOG/LON_BAB
11     BA                   BAE Systems       EOD/BA            NaN
12   BARC                      Barclays          NaN  GOOG/LON_BARC
13     BG                      BG Group       EOD/BG            NaN
14    BLT                  BHP Billiton      EOD/BLT   GOOG/LON_BLT
15     BP                            BP       EOD/BP            NaN
16    BTI      British American Tobacco      EOD/BTI            NaN
17   BLND               British Land Co          NaN  GOOG/LON_BLND
18    BSY                         BSkyB          NaN   GOOG/LON_BSY
19   BT_A                      BT Group          NaN  GOOG/LON_BT_A
20   BNZL                         Bunzl          NaN  GOOG/LON_BNZL
21   BRBY                Burberry Group          NaN  GOOG/LON_BRBY
22    CPI                        Capita      EOD/CPI   GOOG/LON_CPI
23    CUK                  Carnival plc      EOD/CUK   GOOG/LON_CUK
24    CNA                      Centrica      EOD/CNA   GOOG/LON_CNA
25    CCH              Coca-Cola HBC AG          NaN            NaN
26    CPG                 Compass Group      EOD/CPG   GOOG/LON_CPG
27    CRH                       CRH plc      EOD/CRH   GOOG/LON_CRH
28   CRDA           Croda International          NaN  GOOG/LON_CRDA
29    DGE                        Diageo          NaN   GOOG/LON_DGE
..    ...                           ...          ...            ...
68    RIO               Rio Tinto Group      EOD/RIO   GOOG/LON_RIO
69     RR             Rolls-Royce Group          NaN            NaN
70    RBS  Royal Bank of Scotland Group      EOD/RBS   GOOG/LON_RBS
71   RDSA             Royal Dutch Shell          NaN  GOOG/LON_RDSA
72    RSA           RSA Insurance Group          NaN   GOOG/LON_RSA
73    SAB                     SABMiller          NaN   GOOG/LON_SAB
74    SGE                    Sage Group          NaN   GOOG/LON_SGE
75    SDR                     Schroders      EOD/SDR   GOOG/LON_SDR
76    SRP                         Serco          NaN   GOOG/LON_SRP
77    SVT                  Severn Trent      EOD/SVT   GOOG/LON_SVT
78   SHPG                     Shire plc     EOD/SHPG            NaN
79    SNN                Smith & Nephew      EOD/SNN            NaN
80   SMIN                  Smiths Group          NaN  GOOG/LON_SMIN
81    SSE                       SSE plc      EOD/SSE   GOOG/LON_SSE
82   STAN            Standard Chartered          NaN  GOOG/LON_STAN
83     SL                 Standard Life          NaN            NaN
84   TATE                   Tate & Lyle          NaN  GOOG/LON_TATE
85   TSCO                         Tesco     EOD/TSCO  GOOG/LON_TSCO
86     TT                    TUI Travel          NaN            NaN
87    TLW                    Tullow Oil          NaN   GOOG/LON_TLW
88   ULVR                      Unilever          NaN  GOOG/LON_ULVR
89     UU              United Utilities          NaN            NaN
90    VED             Vedanta Resources          NaN   GOOG/LON_VED
91    VOD                Vodafone Group      EOD/VOD   GOOG/LON_VOD
92   WEIR                    Weir Group          NaN  GOOG/LON_WEIR
93    WTB                     Whitbread          NaN   GOOG/LON_WTB
94    WOS                  Wolseley plc          NaN   GOOG/LON_WOS
95    WG_                    Wood Group          NaN   GOOG/LON_WG_
96    WPP                       WPP plc      EOD/WPP   GOOG/LON_WPP
97    XTA                       Xstrata          NaN   GOOG/LON_XTA

[98 rows x 4 columns]

Why are there only 98 rows?

In [13]:
ftse100 = ftse100_csv['ticker'].unique()

'ADN'

In [18]:
ftse100_csv = pd.read_csv("ftse100-figures.csv")
ftse100_csv

          Date     Open     High      Low    Close
0         Date     Open     High      Low    Close
1   2016-09-09   6858.7  6862.38   6762.3  6776.95
2   2016-09-08  6846.58  6889.64  6819.82   6858.7
3   2016-09-07  6826.05  6856.12  6814.87  6846.58
4   2016-09-06  6879.42  6887.92  6818.96  6826.05
5   2016-09-05   6894.6  6910.66  6867.08  6879.42
6   2016-09-02  6745.97  6928.25  6745.97   6894.6
7   2016-09-01  6781.51  6826.22  6723.21  6745.97
8   2016-08-31  6820.79  6832.89  6779.54  6781.51
9   2016-08-30  6838.05  6851.83  6808.07  6820.79
10  2016-08-26   6816.9  6857.29  6798.82  6838.05
11  2016-08-25  6835.78  6836.22  6779.15   6816.9
12  2016-08-24  6868.51  6868.51  6825.22  6835.78
13  2016-08-23  6828.54  6885.39  6828.54  6868.51
14  2016-08-22  6858.95  6884.61  6812.07  6828.54
15  2016-08-19  6868.96  6871.48  6840.94  6858.95
16  2016-08-18  6859.15  6893.35  6850.61  6868.96
17  2016-08-17  6893.92  6920.76   6849.9  6859.15
18  2016-08-16  6941.19  6941.19  6893.92  6893.92
19  2016-08-15  6916.02  6955.34  6907.17  6941.19
20  2016-08-12  6914.71  6931.04  6896.04  6916.02
21  2016-08-11  6866.42  6914.71  6812.73  6914.71
22  2016-08-10   6851.3  6866.42  6820.04  6866.42
23  2016-08-09  6809.13   6863.1  6807.76   6851.3
24  2016-08-08  6793.47  6829.47  6781.47  6809.13
25  2016-08-05  6740.16  6802.41  6738.57  6793.47
26  2016-08-04   6634.4  6749.67  6615.83  6740.16
27  2016-08-03   6645.4  6673.63  6621.42   6634.4
28  2016-08-02  6693.95  6694.14  6630.76   6645.4
29  2016-08-01  6724.43  6769.41  6678.45  6693.95
30  2016-07-29  6721.06  6740.47  6691.13  6724.43
31  2016-07-28  6750.43  6762.72   6718.9  6721.06
32  2016-07-27  6724.03  6780.05  6723.71  6750.43
33  2016-07-26  6710.13   6744.8  6708.58  6724.03
34  2016-07-25  6730.48  6756.13  6691.03  6710.13
35  2016-07-22  6699.89  6735.94  6663.72  6730.48
36  2016-07-21  6728.99  6732.07  6694.52  6699.89
37  2016-07-20  6697.37  6736.57  6694.36  6728.99
38  2016-07-19  6695.42  6711.69  6660.87  6697.37
39  2016-07-18  6669.24  6715.58  6653.67  6695.42
40  2016-07-15  6654.47  6669.24  6616.51  6669.24