# First Session

Python For Data Science With AI

In [1]:
1+2

3

In [2]:
1+2
3+5

8

In [3]:
print(1+2)
3+5

3

8

In [4]:
print(1+2)
print(3+5)

3
8

In [5]:
print(1+2) # We are on the 1st session
print(3+5)

3
8

In [6]:
We are on the 1st session

SyntaxError: invalid decimal literal (3219598487.py, line 1)

In [8]:
3+2*9-6+(8/2) # 10,19,31,43,11,13,4,23, PEMDAS

3+2*9-6+4
3+18-6+4
19

19

In [9]:
3+2*9-6+(8/2) # 10,19,31,43,11,13,4,23, PEMDAS

19.0

In [10]:
4/2

2.0

In [11]:
2+3

5

In [17]:
def readfile(file_name,header=True):
    if header==True:
        data=list(csv.reader(open(file_name,encoding = "utf-8")))
        _headers=data[0]
        data=data[1:]
    return headers,data
    
    else:
        data=list(csv.reader(open(file_name,encoding = "utf-8")))
        return data

SyntaxError: invalid syntax (3745698406.py, line 8)

In [24]:
import csv

def readfile(file_name, header=True):
    if header:
        data = list(csv.reader(open(file_name, encoding="utf-8")))
        headers = data[0]
        data = data[1:]
        return headers, data
    else:
        data = list(csv.reader(open(file_name, encoding="utf-8")))
        return data

In [26]:
headers,data=readfile("playstore.csv")

In [27]:
headers,data=readfile("world-happiness-report-2021.csv")

In [29]:
data

[['Finland',
  'Western Europe',
  '7.842',
  '0.032',
  '7.904',
  '7.780',
  '10.775',
  '0.954',
  '72.000',
  '0.949',
  '-0.098',
  '0.186',
  '2.430',
  '1.446',
  '1.106',
  '0.741',
  '0.691',
  '0.124',
  '0.481',
  '3.253'],
 ['Denmark',
  'Western Europe',
  '7.620',
  '0.035',
  '7.687',
  '7.552',
  '10.933',
  '0.954',
  '72.700',
  '0.946',
  '0.030',
  '0.179',
  '2.430',
  '1.502',
  '1.108',
  '0.763',
  '0.686',
  '0.208',
  '0.485',
  '2.868'],
 ['Switzerland',
  'Western Europe',
  '7.571',
  '0.036',
  '7.643',
  '7.500',
  '11.117',
  '0.942',
  '74.400',
  '0.919',
  '0.025',
  '0.292',
  '2.430',
  '1.566',
  '1.079',
  '0.816',
  '0.653',
  '0.204',
  '0.413',
  '2.839'],
 ['Iceland',
  'Western Europe',
  '7.554',
  '0.059',
  '7.670',
  '7.438',
  '10.878',
  '0.983',
  '73.000',
  '0.955',
  '0.160',
  '0.673',
  '2.430',
  '1.482',
  '1.172',
  '0.772',
  '0.698',
  '0.293',
  '0.170',
  '2.967'],
 ['Netherlands',
  'Western Europe',
  '7.464',
  '0.027',
  '7.518',
  '7.410',
  '10.932',
  '0.942',
  '72.400',
  '0.913',
  '0.175',
  '0.338',
  '2.430',
  '1.501',
  '1.079',
  '0.753',
  '0.647',
  '0.302',
  '0.384',
  '2.798'],
 ['Norway',
  'Western Europe',
  '7.392',
  '0.035',
  '7.462',
  '7.323',
  '11.053',
  '0.954',
  '73.300',
  '0.960',
  '0.093',
  '0.270',
  '2.430',
  '1.543',
  '1.108',
  '0.782',
  '0.703',
  '0.249',
  '0.427',
  '2.580'],
 ['Sweden',
  'Western Europe',
  '7.363',
  '0.036',
  '7.433',
  '7.293',
  '10.867',
  '0.934',
  '72.700',
  '0.945',
  '0.086',
  '0.237',
  '2.430',
  '1.478',
  '1.062',
  '0.763',
  '0.685',
  '0.244',
  '0.448',
  '2.683'],
 ['Luxembourg',
  'Western Europe',
  '7.324',
  '0.037',
  '7.396',
  '7.252',
  '11.647',
  '0.908',
  '72.600',
  '0.907',
  '-0.034',
  '0.386',
  '2.430',
  '1.751',
  '1.003',
  '0.760',
  '0.639',
  '0.166',
  '0.353',
  '2.653'],
 ['New Zealand',
  'North America and ANZ',
  '7.277',
  '0.040',
  '7.355',
  '7.198',
  '10.643',
  '0.948',
  '73.400',
  '0.929',
  '0.134',
  '0.242',
  '2.430',
  '1.400',
  '1.094',
  '0.785',
  '0.665',
  '0.276',
  '0.445',
  '2.612'],
 ['Austria',
  'Western Europe',
  '7.268',
  '0.036',
  '7.337',
  '7.198',
  '10.906',
  '0.934',
  '73.300',
  '0.908',
  '0.042',
  '0.481',
  '2.430',
  '1.492',
  '1.062',
  '0.782',
  '0.640',
  '0.215',
  '0.292',
  '2.784'],
 ['Australia',
  'North America and ANZ',
  '7.183',
  '0.041',
  '7.265',
  '7.102',
  '10.796',
  '0.940',
  '73.900',
  '0.914',
  '0.159',
  '0.442',
  '2.430',
  '1.453',
  '1.076',
  '0.801',
  '0.647',
  '0.291',
  '0.317',
  '2.598'],
 ['Israel',
  'Middle East and North Africa',
  '7.157',
  '0.034',
  '7.224',
  '7.090',
  '10.575',
  '0.939',
  '73.503',
  '0.800',
  '0.031',
  '0.753',
  '2.430',
  '1.376',
  '1.074',
  '0.788',
  '0.509',
  '0.208',
  '0.119',
  '3.083'],
 ['Germany',
  'Western Europe',
  '7.155',
  '0.040',
  '7.232',
  '7.077',
  '10.873',
  '0.903',
  '72.500',
  '0.875',
  '0.011',
  '0.460',
  '2.430',
  '1.480',
  '0.993',
  '0.757',
  '0.600',
  '0.195',
  '0.306',
  '2.824'],
 ['Canada',
  'North America and ANZ',
  '7.103',
  '0.042',
  '7.185',
  '7.021',
  '10.776',
  '0.926',
  '73.800',
  '0.915',
  '0.089',
  '0.415',
  '2.430',
  '1.447',
  '1.044',
  '0.798',
  '0.648',
  '0.246',
  '0.335',
  '2.585'],
 ['Ireland',
  'Western Europe',
  '7.085',
  '0.040',
  '7.164',
  '7.006',
  '11.342',
  '0.947',
  '72.400',
  '0.879',
  '0.077',
  '0.363',
  '2.430',
  '1.644',
  '1.092',
  '0.753',
  '0.606',
  '0.238',
  '0.367',
  '2.384'],
 ['Costa Rica',
  'Latin America and Caribbean',
  '7.069',
  '0.056',
  '7.179',
  '6.960',
  '9.880',
  '0.891',
  '71.400',
  '0.934',
  '-0.126',
  '0.809',
  '2.430',
  '1.134',
  '0.966',
  '0.722',
  '0.673',
  '0.105',
  '0.083',
  '3.387'],
 ['United Kingdom',
  'Western Europe',
  '7.064',
  '0.038',
  '7.138',
  '6.990',
  '10.707',
  '0.934',
  '72.500',
  '0.859',
  '0.233',
  '0.459',
  '2.430',
  '1.423',
  '1.062',
  '0.757',
  '0.580',
  '0.340',
  '0.306',
  '2.596'],
 ['Czech Republic',
  'Central and Eastern Europe',
  '6.965',
  '0.049',
  '7.062',
  '6.868',
  '10.556',
  '0.947',
  '70.807',
  '0.858',
  '-0.208',
  '0.868',
  '2.430',
  '1.370',
  '1.090',
  '0.703',
  '0.580',
  '0.052',
  '0.046',
  '3.124'],
 ['United States',
  'North America and ANZ',
  '6.951',
  '0.049',
  '7.047',
  '6.856',
  '11.023',
  '0.920',
  '68.200',
  '0.837',
  '0.098',
  '0.698',
  '2.430',
  '1.533',
  '1.030',
  '0.621',
  '0.554',
  '0.252',
  '0.154',
  '2.807'],
 ['Belgium',
  'Western Europe',
  '6.834',
  '0.034',
  '6.901',
  '6.767',
  '10.823',
  '0.906',
  '72.199',
  '0.783',
  '-0.153',
  '0.646',
  '2.430',
  '1.463',
  '0.998',
  '0.747',
  '0.489',
  '0.088',
  '0.187',
  '2.862'],
 ['France',
  'Western Europe',
  '6.690',
  '0.037',
  '6.762',
  '6.618',
  '10.704',
  '0.942',
  '74.000',
  '0.822',
  '-0.147',
  '0.571',
  '2.430',
  '1.421',
  '1.081',
  '0.804',
  '0.536',
  '0.092',
  '0.235',
  '2.521'],
 ['Bahrain',
  'Middle East and North Africa',
  '6.647',
  '0.068',
  '6.779',
  '6.514',
  '10.669',
  '0.862',
  '69.495',
  '0.925',
  '0.089',
  '0.722',
  '2.430',
  '1.409',
  '0.899',
  '0.662',
  '0.661',
  '0.246',
  '0.139',
  '2.631'],
 ['Malta',
  'Western Europe',
  '6.602',
  '0.044',
  '6.688',
  '6.516',
  '10.674',
  '0.931',
  '72.200',
  '0.927',
  '0.133',
  '0.653',
  '2.430',
  '1.411',
  '1.055',
  '0.747',
  '0.664',
  '0.275',
  '0.183',
  '2.268'],
 ['Taiwan Province of China',
  'East Asia',
  '6.584',
  '0.038',
  '6.659',
  '6.510',
  '10.871',
  '0.898',
  '69.600',
  '0.784',
  '-0.070',
  '0.721',
  '2.430',
  '1.480',
  '0.982',
  '0.665',
  '0.490',
  '0.142',
  '0.139',
  '2.687'],
 ['United Arab Emirates',
  'Middle East and North Africa',
  '6.561',
  '0.039',
  '6.637',
  '6.484',
  '11.085',
  '0.844',
  '67.333',
  '0.932',
  '0.074',
  '0.589',
  '2.430',
  '1.555',
  '0.860',
  '0.594',
  '0.670',
  '0.236',
  '0.223',
  '2.422'],
 ['Saudi Arabia',
  'Middle East and North Africa',
  '6.494',
  '0.056',
  '6.604',
  '6.384',
  '10.743',
  '0.891',
  '66.603',
  '0.877',
  '-0.149',
  '0.684',
  '2.430',
  '1.435',
  '0.964',
  '0.571',
  '0.603',
  '0.090',
  '0.163',
  '2.668'],
 ['Spain',
  'Western Europe',
  '6.491',
  '0.042',
  '6.574',
  '6.408',
  '10.571',
  '0.932',
  '74.700',
  '0.761',
  '-0.081',
  '0.745',
  '2.430',
  '1.375',
  '1.057',
  '0.826',
  '0.462',
  '0.135',
  '0.124',
  '2.513'],
 ['Italy',
  'Western Europe',
  '6.483',
  '0.045',
  '6.572',
  '6.395',
  '10.623',
  '0.880',
  '73.800',
  '0.693',
  '-0.084',
  '0.866',
  '2.430',
  '1.393',
  '0.940',
  '0.798',
  '0.379',
  '0.133',
  '0.047',
  '2.794'],
 ['Slovenia',
  'Central and Eastern Europe',
  '6.461',
  '0.043',
  '6.546',
  '6.376',
  '10.529',
  '0.948',
  '71.400',
  '0.949',
  '-0.101',
  '0.806',
  '2.430',
  '1.360',
  '1.093',
  '0.722',
  '0.690',
  '0.122',
  '0.085',
  '2.388'],
 ['Guatemala',
  'Latin America and Caribbean',
  '6.435',
  '0.073',
  '6.577',
  '6.292',
  '9.053',
  '0.813',
  '64.958',
  '0.906',
  '-0.038',
  '0.775',
  '2.430',
  '0.845',
  '0.790',
  '0.519',
  '0.638',
  '0.163',
  '0.105',
  '3.375'],
 ['Uruguay',
  'Latin America and Caribbean',
  '6.431',
  '0.046',
  '6.521',
  '6.341',
  '9.966',
  '0.925',
  '69.100',
  '0.896',
  '-0.092',
  '0.590',
  '2.430',
  '1.164',
  '1.042',
  '0.649',
  '0.625',
  '0.128',
  '0.223',
  '2.600'],
 ['Singapore',
  'Southeast Asia',
  '6.377',
  '0.043',
  '6.460',
  '6.293',
  '11.488',
  '0.915',
  '76.953',
  '0.927',
  '-0.018',
  '0.082',
  '2.430',
  '1.695',
  '1.019',
  '0.897',
  '0.664',
  '0.176',
  '0.547',
  '1.379'],
 ['Kosovo',
  'Central and Eastern Europe',
  '6.372',
  '0.059',
  '6.487',
  '6.257',
  '9.318',
  '0.821',
  '63.813',
  '0.869',
  '0.257',
  '0.917',
  '2.430',
  '0.937',
  '0.807',
  '0.483',
  '0.593',
  '0.356',
  '0.014',
  '3.182'],
 ['Slovakia',
  'Central and Eastern Europe',
  '6.331',
  '0.041',
  '6.411',
  '6.251',
  '10.369',
  '0.936',
  '69.201',
  '0.766',
  '-0.124',
  '0.911',
  '2.430',
  '1.304',
  '1.066',
  '0.653',
  '0.468',
  '0.107',
  '0.018',
  '2.714'],
 ['Brazil',
  'Latin America and Caribbean',
  '6.330',
  '0.043',
  '6.415',
  '6.245',
  '9.577',
  '0.882',
  '66.601',
  '0.804',
  '-0.071',
  '0.756',
  '2.430',
  '1.028',
  '0.944',
  '0.571',
  '0.514',
  '0.142',
  '0.117',
  '3.015'],
 ['Mexico',
  'Latin America and Caribbean',
  '6.317',
  '0.053',
  '6.420',
  '6.213',
  '9.859',
  '0.831',
  '68.597',
  '0.862',
  '-0.147',
  '0.799',
  '2.430',
  '1.126',
  '0.830',
  '0.634',
  '0.585',
  '0.092',
  '0.089',
  '2.961'],
 ['Jamaica',
  'Latin America and Caribbean',
  '6.309',
  '0.156',
  '6.615',
  '6.004',
  '9.186',
  '0.877',
  '67.500',
  '0.890',
  '-0.137',
  '0.884',
  '2.430',
  '0.891',
  '0.932',
  '0.599',
  '0.618',
  '0.099',
  '0.035',
  '3.135'],
 ['Lithuania',
  'Central and Eastern Europe',
  '6.255',
  '0.045',
  '6.344',
  '6.167',
  '10.499',
  '0.935',
  '67.906',
  '0.773',
  '-0.203',
  '0.826',
  '2.430',
  '1.350',
  '1.065',
  '0.612',
  '0.476',
  '0.056',
  '0.073',
  '2.624'],
 ['Cyprus',
  'Western Europe',
  '6.223',
  '0.049',
  '6.319',
  '6.128',
  '10.576',
  '0.802',
  '73.898',
  '0.763',
  '-0.015',
  '0.844',
  '2.430',
  '1.377',
  '0.765',
  '0.801',
  '0.464',
  '0.178',
  '0.061',
  '2.578'],
 ['Estonia',
  'Central and Eastern Europe',
  '6.189',
  '0.038',
  '6.263',
  '6.115',
  '10.481',
  '0.941',
  '68.800',
  '0.909',
  '-0.106',
  '0.527',
  '2.430',
  '1.344',
  '1.079',
  '0.640',
  '0.641',
  '0.119',
  '0.263',
  '2.103'],
 ['Panama',
  'Latin America and Caribbean',
  '6.180',
  '0.073',
  '6.323',
  '6.036',
  '10.350',
  '0.896',
  '69.652',
  '0.872',
  '-0.166',
  '0.856',
  '2.430',
  '1.298',
  '0.976',
  '0.667',
  '0.596',
  '0.079',
  '0.053',
  '2.509'],
 ['Uzbekistan',
  'Commonwealth of Independent States',
  '6.179',
  '0.068',
  '6.312',
  '6.045',
  '8.836',
  '0.918',
  '65.255',
  '0.970',
  '0.311',
  '0.515',
  '2.430',
  '0.769',
  '1.027',
  '0.528',
  '0.716',
  '0.391',
  '0.271',
  '2.477'],
 ['Chile',
  'Latin America and Caribbean',
  '6.172',
  '0.046',
  '6.262',
  '6.081',
  '10.071',
  '0.882',
  '70.000',
  '0.742',
  '-0.044',
  '0.830',
  '2.430',
  '1.200',
  '0.946',
  '0.678',
  '0.438',
  '0.159',
  '0.070',
  '2.682'],
 ['Poland',
  'Central and Eastern Europe',
  '6.166',
  '0.040',
  '6.245',
  '6.087',
  '10.382',
  '0.898',
  '69.702',
  '0.841',
  '-0.165',
  '0.735',
  '2.430',
  '1.309',
  '0.982',
  '0.668',
  '0.558',
  '0.080',
  '0.130',
  '2.438'],
 ['Kazakhstan',
  'Commonwealth of Independent States',
  '6.152',
  '0.047',
  '6.243',
  '6.060',
  '10.155',
  '0.952',
  '65.200',
  '0.853',
  '-0.069',
  '0.733',
  '2.430',
  '1.230',
  '1.103',
  '0.527',
  '0.573',
  '0.143',
  '0.132',
  '2.446'],
 ['Romania',
  'Central and Eastern Europe',
  '6.140',
  '0.057',
  '6.253',
  '6.027',
  '10.284',
  '0.832',
  '67.355',
  '0.845',
  '-0.219',
  '0.938',
  '2.430',
  '1.275',
  '0.832',
  '0.595',
  '0.564',
  '0.045',
  '0.001',
  '2.830'],
 ['Kuwait',
  'Middle East and North Africa',
  '6.106',
  '0.066',
  '6.235',
  '5.977',
  '10.817',
  '0.843',
  '66.900',
  '0.867',
  '-0.104',
  '0.736',
  '2.430',
  '1.461',
  '0.857',
  '0.580',
  '0.591',
  '0.120',
  '0.130',
  '2.368'],
 ['Serbia',
  'Central and Eastern Europe',
  '6.078',
  '0.053',
  '6.181',
  '5.974',
  '9.787',
  '0.873',
  '68.600',
  '0.778',
  '0.002',
  '0.835',
  '2.430',
  '1.101',
  '0.924',
  '0.634',
  '0.482',
  '0.189',
  '0.066',
  '2.682'],
 ['El Salvador',
  'Latin America and Caribbean',
  '6.061',
  '0.065',
  '6.188',
  '5.933',
  '9.054',
  '0.762',
  '66.402',
  '0.888',
  '-0.110',
  '0.688',
  '2.430',
  '0.845',
  '0.675',
  '0.565',
  '0.615',
  '0.116',
  '0.160',
  '3.085'],
 ['Mauritius',
  'Sub-Saharan Africa',
  '6.049',
  '0.059',
  '6.165',
  '5.933',
  '10.008',
  '0.905',
  '66.701',
  '0.867',
  '-0.054',
  '0.789',
  '2.430',
  '1.178',
  '0.996',
  '0.574',
  '0.590',
  '0.153',
  '0.096',
  '2.462'],
 ['Latvia',
  'Central and Eastern Europe',
  '6.032',
  '0.036',
  '6.103',
  '5.961',
  '10.315',
  '0.927',
  '67.100',
  '0.715',
  '-0.162',
  '0.800',
  '2.430',
  '1.285',
  '1.047',
  '0.587',
  '0.405',
  '0.082',
  '0.089',
  '2.536'],
 ['Colombia',
  'Latin America and Caribbean',
  '6.012',
  '0.061',
  '6.132',
  '5.892',
  '9.557',
  '0.847',
  '68.001',
  '0.837',
  '-0.135',
  '0.841',
  '2.430',
  '1.021',
  '0.866',
  '0.615',
  '0.554',
  '0.100',
  '0.063',
  '2.794'],
 ['Hungary',
  'Central and Eastern Europe',
  '5.992',
  '0.047',
  '6.085',
  '5.899',
  '10.358',
  '0.943',
  '68.000',
  '0.755',
  '-0.186',
  '0.876',
  '2.430',
  '1.301',
  '1.083',
  '0.615',
  '0.454',
  '0.067',
  '0.040',
  '2.432'],
 ['Thailand',
  'Southeast Asia',
  '5.985',
  '0.047',
  '6.077',
  '5.893',
  '9.805',
  '0.888',
  '67.401',
  '0.884',
  '0.287',
  '0.895',
  '2.430',
  '1.107',
  '0.957',
  '0.596',
  '0.611',
  '0.375',
  '0.028',
  '2.309'],
 ['Nicaragua',
  'Latin America and Caribbean',
  '5.972',
  '0.083',
  '6.134',
  '5.810',
  '8.620',
  '0.864',
  '67.657',
  '0.836',
  '0.020',
  '0.664',
  '2.430',
  '0.693',
  '0.904',
  '0.604',
  '0.553',
  '0.201',
  '0.176',
  '2.841'],
 ['Japan',
  'East Asia',
  '5.940',
  '0.040',
  '6.020',
  '5.861',
  '10.611',
  '0.884',
  '75.100',
  '0.796',
  '-0.258',
  '0.638',
  '2.430',
  '1.389',
  '0.949',
  '0.838',
  '0.504',
  '0.020',
  '0.192',
  '2.048'],
 ['Argentina',
  'Latin America and Caribbean',
  '5.929',
  '0.056',
  '6.040',
  '5.819',
  '9.962',
  '0.898',
  '69.000',
  '0.828',
  '-0.182',
  '0.834',
  '2.430',
  '1.162',
  '0.980',
  '0.646',
  '0.544',
  '0.069',
  '0.067',
  '2.461'],
 ['Portugal',
  'Western Europe',
  '5.929',
  '0.055',
  '6.037',
  '5.821',
  '10.421',
  '0.879',
  '72.600',
  '0.892',
  '-0.244',
  '0.887',
  '2.430',
  '1.323',
  '0.939',
  '0.760',
  '0.621',
  '0.029',
  '0.033',
  '2.225'],
 ['Honduras',
  'Latin America and Caribbean',
  '5.919',
  '0.082',
  '6.081',
  '5.758',
  '8.648',
  '0.812',
  '67.300',
  '0.857',
  '0.081',
  '0.809',
  '2.430',
  '0.703',
  '0.787',
  '0.593',
  '0.578',
  '0.241',
  '0.083',
  '2.934'],
 ['Croatia',
  'Central and Eastern Europe',
  '5.882',
  '0.048',
  '5.975',
  '5.788',
  '10.217',
  '0.924',
  '70.799',
  '0.754',
  '-0.118',
  '0.939',
  '2.430',
  '1.251',
  '1.039',
  '0.703',
  '0.453',
  '0.111',
  '0.000',
  '2.325'],
 ['Philippines',
  'Southeast Asia',
  '5.880',
  '0.052',
  '5.982',
  '5.778',
  '9.076',
  '0.830',
  '62.000',
  '0.917',
  '-0.097',
  '0.742',
  '2.430',
  '0.853',
  '0.828',
  '0.426',
  '0.651',
  '0.125',
  '0.126',
  '2.872'],
 ['South Korea',
  'East Asia',
  '5.845',
  '0.042',
  '5.928',
  '5.763',
  '10.651',
  '0.799',
  '73.900',
  '0.672',
  '-0.083',
  '0.727',
  '2.430',
  '1.403',
  '0.758',
  '0.801',
  '0.353',
  '0.134',
  '0.135',
  '2.262'],
 ['Peru',
  'Latin America and Caribbean',
  '5.840',
  '0.075',
  '5.988',
  '5.692',
  '9.458',
  '0.832',
  '68.250',
  '0.822',
  '-0.154',
  '0.891',
  '2.430',
  '0.986',
  '0.833',
  '0.623',
  '0.536',
  '0.087',
  '0.031',
  '2.744'],
 ['Bosnia and Herzegovina',
  'Central and Eastern Europe',
  '5.813',
  '0.050',
  '5.911',
  '5.715',
  '9.590',
  '0.870',
  '68.098',
  '0.706',
  '0.113',
  '0.931',
  '2.430',
  '1.032',
  '0.919',
  '0.618',
  '0.395',
  '0.261',
  '0.005',
  '2.583'],
 ['Moldova',
  'Commonwealth of Independent States',
  '5.766',
  '0.046',
  '5.856',
  '5.677',
  '9.454',
  '0.857',
  '65.699',
  '0.822',
  '-0.079',
  '0.918',
  '2.430',
  '0.985',
  '0.888',
  '0.542',
  '0.536',
  '0.137',
  '0.013',
  '2.665'],
 ['Ecuador',
  'Latin America and Caribbean',
  '5.764',
  '0.057',
  '5.875',
  '5.653',
  '9.313',
  '0.821',
  '68.800',
  '0.842',
  '-0.124',
  '0.843',
  '2.430',
  '0.935',
  '0.806',
  '0.640',
  '0.560',
  '0.107',
  '0.062',
  '2.653'],
 ['Kyrgyzstan',
  'Commonwealth of Independent States',
  '5.744',
  '0.046',
  '5.834',
  '5.653',
  '8.538',
  '0.893',
  '64.401',
  '0.935',
  '0.119',
  '0.908',
  '2.430',
  '0.665',
  '0.971',
  '0.501',
  '0.673',
  '0.266',
  '0.020',
  '2.648'],
 ['Greece',
  'Western Europe',
  '5.723',
  '0.046',
  '5.813',
  '5.632',
  '10.279',
  '0.823',
  '72.600',
  '0.582',
  '-0.288',
  '0.823',
  '2.430',
  '1.273',
  '0.811',
  '0.760',
  '0.243',
  '0.000',
  '0.074',
  '2.561'],
 ['Bolivia',
  'Latin America and Caribbean',
  '5.716',
  '0.053',
  '5.819',
  '5.613',
  '9.046',
  '0.810',
  '63.901',
  '0.875',
  '-0.077',
  '0.839',
  '2.430',
  '0.842',
  '0.782',
  '0.486',
  '0.600',
  '0.138',
  '0.064',
  '2.805'],
 ['Mongolia',
  'East Asia',
  '5.677',
  '0.042',
  '5.760',
  '5.595',
  '9.400',
  '0.935',
  '62.500',
  '0.708',
  '0.116',
  '0.856',
  '2.430',
  '0.966',
  '1.065',
  '0.442',
  '0.397',
  '0.263',
  '0.053',
  '2.492'],
 ['Paraguay',
  'Latin America and Caribbean',
  '5.653',
  '0.092',
  '5.832',
  '5.473',
  '9.448',
  '0.893',
  '65.900',
  '0.876',
  '0.028',
  '0.882',
  '2.430',
  '0.983',
  '0.970',
  '0.549',
  '0.602',
  '0.206',
  '0.037',
  '2.306'],
 ['Montenegro',
  'Central and Eastern Europe',
  '5.581',
  '0.054',
  '5.686',
  '5.475',
  '9.940',
  '0.858',
  '68.699',
  '0.708',
  '-0.034',
  '0.812',
  '2.430',
  '1.155',
  '0.891',
  '0.637',
  '0.397',
  '0.166',
  '0.081',
  '2.254'],
 ['Dominican Republic',
  'Latin America and Caribbean',
  '5.545',
  '0.071',
  '5.685',
  '5.405',
  '9.802',
  '0.853',
  '66.102',
  '0.860',
  '-0.133',
  '0.714',
  '2.430',
  '1.106',
  '0.879',
  '0.555',
  '0.581',
  '0.101',
  '0.144',
  '2.178'],
 ['North Cyprus',
  'Western Europe',
  '5.536',
  '0.051',
  '5.636',
  '5.435',
  '10.576',
  '0.820',
  '73.898',
  '0.795',
  '0.012',
  '0.626',
  '2.430',
  '1.377',
  '0.806',
  '0.801',
  '0.503',
  '0.196',
  '0.200',
  '1.653'],
 ['Belarus',
  'Commonwealth of Independent States',
  '5.534',
  '0.047',
  '5.625',
  '5.442',
  '9.853',
  '0.910',
  '66.253',
  '0.650',
  '-0.180',
  '0.627',
  '2.430',
  '1.124',
  '1.007',
  '0.560',
  '0.326',
  '0.070',
  '0.199',
  '2.247'],
 ['Russia',
  'Commonwealth of Independent States',
  '5.477',
  '0.033',
  '5.541',
  '5.413',
  '10.189',
  '0.903',
  '64.703',
  '0.718',
  '-0.111',
  '0.845',
  '2.430',
  '1.241',
  '0.992',
  '0.511',
  '0.409',
  '0.115',
  '0.060',
  '2.148'],
 ['Hong Kong S.A.R. of China',
  'East Asia',
  '5.477',
  '0.049',
  '5.573',
  '5.380',
  '11.000',
  '0.836',
  '76.820',
  '0.717',
  '0.067',
  '0.403',
  '2.430',
  '1.525',
  '0.841',
  '0.893',
  '0.408',
  '0.232',
  '0.342',
  '1.236'],
 ['Tajikistan',
  'Commonwealth of Independent States',
  '5.466',
  '0.034',
  '5.532',
  '5.400',
  '8.091',
  '0.860',
  '64.281',
  '0.832',
  '-0.056',
  '0.553',
  '2.430',
  '0.508',
  '0.895',
  '0.498',
  '0.548',
  '0.152',
  '0.247',
  '2.619'],
 ['Vietnam',
  'Southeast Asia',
  '5.411',
  '0.039',
  '5.488',
  '5.334',
  '8.973',
  '0.850',
  '68.034',
  '0.940',
  '-0.098',
  '0.796',
  '2.430',
  '0.817',
  '0.873',
  '0.616',
  '0.679',
  '0.124',
  '0.091',
  '2.211'],
 ['Libya',
  'Middle East and North Africa',
  '5.410',
  '0.076',
  '5.558',
  '5.262',
  '9.622',
  '0.827',
  '62.300',
  '0.771',
  '-0.087',
  '0.667',
  '2.430',
  '1.044',
  '0.821',
  '0.435',
  '0.474',
  '0.131',
  '0.174',
  '2.331'],
 ['Malaysia',
  'Southeast Asia',
  '5.384',
  '0.049',
  '5.480',
  '5.289',
  '10.238',
  '0.817',
  '67.102',
  '0.895',
  '0.125',
  '0.839',
  '2.430',
  '1.259',
  '0.797',
  '0.587',
  '0.624',
  '0.270',
  '0.064',
  '1.784'],
 ['Indonesia',
  'Southeast Asia',
  '5.345',
  '0.056',
  '5.454',
  '5.235',
  '9.365',
  '0.811',
  '62.236',
  '0.873',
  '0.542',
  '0.867',
  '2.430',
  '0.954',
  '0.786',
  '0.433',
  '0.598',
  '0.541',
  '0.046',
  '1.987'],

In [19]:
headers,data=readfile("playstore.csv")

In [20]:
headers

['App',
 'Category',
 'Rating',
 'Reviews',
 'Size',
 'Installs',
 'Type',
 'Price',
 'Content Rating',
 'Genres',
 'Last Updated',
 'Current Ver',
 'Android Ver']

In [1]:
l=list(range(15))

In [2]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [3]:
len(l)

15

In [8]:
total_count = 0
for _ in l:
    total_count +=1

In [9]:
total_count

15

In [14]:
def count(data):
    total_count = 0 
for _ in data:
    total_count +=1
return total_count

NameError: name 'data' is not defined

In [15]:
def count(data):
    total_count = 0 
    for _ in data:
        total_count += 1
    return total_count

In [16]:
count(l)

15

In [15]:
headers

['App',
 'Category',
 'Rating',
 'Reviews',
 'Size',
 'Installs',
 'Type',
 'Price',
 'Content Rating',
 'Genres',
 'Last Updated',
 'Current Ver',
 'Android Ver']

In [16]:


data[0]

['Photo Editor & Candy Camera & Grid & ScrapBook',
 'ART_AND_DESIGN',
 '4.1',
 '159',
 '19M',
 '10,000+',
 'Free',
 '0',
 'Everyone',
 'Art & Design',
 'January 7, 2018',
 '1.0.0',
 '4.0.3 and up']

In [1]:
import csv

In [2]:
with open("banana_quality.csv") as f:
    data=list(csv.reader(f))
    header=data[0]
    data=data[1:]

In [3]:
header

['Size',
 'Weight',
 'Sweetness',
 'Softness',
 'HarvestTime',
 'Ripeness',
 'Acidity',
 'Quality']

In [4]:
import pandas as pd

In [6]:
data_pd=pd.read_csv("banana_quality.csv")

In [10]:
data_pd.shape

(8000, 8)

In [16]:
sum_ac=0
for i in data:
    if i[-1]=="Good":
        sum_ac +=float(i[-2])

In [17]:
sum_ac

27.067004365719104

In [19]:
count=0
for i in data:
    if i[-1]=="Good":
        count +=1

In [20]:
count

4006

In [21]:
sum_ac/count

0.006756616167179008

In [33]:
data_pd.Quality=="Good"

0        True
1        True
2        True
3        True
4        True
        ...
7995    False
7996    False
7997    False
7998    False
7999    False
Name: Quality, Length: 8000, dtype: bool

In [29]:
data_pd.loc[data_pd.Quality=="Good"]["Acidity"].mean()

0.006756616167179255

In [43]:
data_pd.pivot_table(values="Acidity",columns="Quality",aggfunc="std")

Quality       Bad      Good
Acidity  2.211917  2.372258

In [58]:
main_list=[]
for i in data:
    sweet=float(i[-6])
    if sweet>=2.0 and sweet<=3.0:
        main_list.append(i)

In [59]:
len(main_list)

368

In [60]:
pd.DataFrame(main_list,columns=header)

,Size,Weight,Sweetness,Softness,HarvestTime,Ripeness,Acidity,Quality
0,-2.0318587,1.3767682,2.2734401,-2.2057126,0.41215587,3.757726,3.1004484,Good
1,2.0621698,1.5615295,2.5703752,-1.8647795,-0.44219488,2.2499652,4.70331,Good
2,-1.9652935,-0.06748736,2.6001945,-1.7930973,-1.6579864,1.0869076,2.335015,Good
3,-0.8328398,0.6344345,2.8857996,-1.018919,-1.476629,0.09706835,1.8400067,Good
4,-0.47838327,1.2760094,2.0892775,-0.27186796,-0.9304542,1.2834822,3.8400788,Good
...,...,...,...,...,...,...,...,...
363,-3.2349498,-2.6076138,2.6205332,1.8316296,-0.056623954,0.32338053,-0.8257309,Bad
364,-3.6606069,2.185512,2.7170763,1.2544135,0.35569912,-1.3294989,4.0603633,Bad
365,-4.3856716,1.0842898,2.1054387,1.3834324,-2.0792463,-0.042838756,3.800508,Bad
366,-3.0025156,-0.22629987,2.2006247,1.5567461,-1.269556,0.24930413,1.6283996,Bad
367,-3.9012096,0.36483932,2.0043974,1.8095461,-1.1069522,-1.5863168,1.8969749,Bad

In [57]:
((data_pd["Sweetness"]>=2)&(data_pd["Sweetness"]<=3)).sum()

368

In [66]:
data_pd[(data_pd["Sweetness"]>=2)&(data_pd["Sweetness"]<=3)]

,Size,Weight,Sweetness,Softness,HarvestTime,Ripeness,Acidity,Quality
11,-2.031859,1.376768,2.273440,-2.205713,0.412156,3.757726,3.100448,Good
12,2.062170,1.561530,2.570375,-1.864780,-0.442195,2.249965,4.703310,Good
16,-1.965294,-0.067487,2.600195,-1.793097,-1.657986,1.086908,2.335015,Good
23,-0.832840,0.634435,2.885800,-1.018919,-1.476629,0.097068,1.840007,Good
28,-0.478383,1.276009,2.089278,-0.271868,-0.930454,1.283482,3.840079,Good
...,...,...,...,...,...,...,...,...
7533,-3.234950,-2.607614,2.620533,1.831630,-0.056624,0.323381,-0.825731,Bad
7546,-3.660607,2.185512,2.717076,1.254414,0.355699,-1.329499,4.060363,Bad
7668,-4.385672,1.084290,2.105439,1.383432,-2.079246,-0.042839,3.800508,Bad
7670,-3.002516,-0.226300,2.200625,1.556746,-1.269556,0.249304,1.628400,Bad
7992,-3.901210,0.364839,2.004397,1.809546,-1.106952,-1.586317,1.896975,Bad

In [67]:
car_pd=pd.read_csv("car_prices.csv")

In [68]:
import func

In [70]:
header,car=func.read_csv("car_prices.csv")

In [71]:
header

['year',
 'make',
 'model',
 'trim',
 'body',
 'transmission',
 'vin',
 'state',
 'condition',
 'odometer',
 'color',
 'interior',
 'seller',
 'mmr',
 'sellingprice',
 'saledate']

In [73]:
car_pd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 558837 entries, 0 to 558836
Data columns (total 16 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   year          558837 non-null  int64
 1   make          548536 non-null  object
 2   model         548438 non-null  object
 3   trim          548186 non-null  object
 4   body          545642 non-null  object
 5   transmission  493485 non-null  object
 6   vin           558833 non-null  object
 7   state         558837 non-null  object
 8   condition     547017 non-null  float64
 9   odometer      558743 non-null  float64
 10  color         558088 non-null  object
 11  interior      558088 non-null  object
 12  seller        558837 non-null  object
 13  mmr           558799 non-null  float64
 14  sellingprice  558825 non-null  float64
 15  saledate      558825 non-null  object
dtypes: float64(4), int64(1), object(11)
memory usage: 68.2+ MB

In [85]:
(car_pd.make.isnull()).sum()

10301

In [86]:
10301+548536

558837

In [91]:
car_pd["make"]=car_pd["make"].fillna(method="ffill")

In [92]:
car_pd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 558837 entries, 0 to 558836
Data columns (total 16 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   year          558837 non-null  int64
 1   make          558837 non-null  object
 2   model         548438 non-null  object
 3   trim          548186 non-null  object
 4   body          545642 non-null  object
 5   transmission  493485 non-null  object
 6   vin           558833 non-null  object
 7   state         558837 non-null  object
 8   condition     547017 non-null  float64
 9   odometer      558743 non-null  float64
 10  color         558088 non-null  object
 11  interior      558088 non-null  object
 12  seller        558837 non-null  object
 13  mmr           558799 non-null  float64
 14  sellingprice  558825 non-null  float64
 15  saledate      558825 non-null  object
dtypes: float64(4), int64(1), object(11)
memory usage: 68.2+ MB

In [106]:
car_pd.iloc[744]

year                                               2012
make                                                Bmw
model                                          6 Series
trim                                               650i
body                                        Convertible
transmission                                  automatic
vin                                   wbalz3c5xcdl71530
state                                                ca
condition                                          38.0
odometer                                        28925.0
color                                             white
interior                                          black
seller           financial services remarketing (lease)
mmr                                             48500.0
sellingprice                                    50500.0
saledate        Thu Dec 18 2014 12:30:00 GMT-0800 (PST)
Name: 744, dtype: object

In [104]:
car_pd['make']=car_pd['make'].str.title()

In [113]:
car_pd['saledate']=car_pd['saledate'].fillna(method="ffill")

In [115]:
pd.to_datetime(car_pd['saledate'], format='%a %b %d %Y %H:%M:%S GMT%z (%Z)')

ValueError: Cannot parse both %Z and %z

In [116]:
pd.to_datetime(car_pd['saledate'], format='%a %b %d %Y %H:%M:%S GMT%z (%Z)')

ValueError: Cannot parse both %Z and %z

In [117]:
Extract UTC offset and timezone abbreviation
offsets = car_pd['saledate'].str.extract(r'GMT([-+]\d{4}) \((\w{3})\)')

# Add UTC offset and timezone abbreviation as separate columns
car_pd['utc_offset'] = pd.to_timedelta(offsets[0], unit='hour')
car_pd['timezone'] = offsets[1]

# Remove UTC offset and timezone abbreviation from the datetime strings
car_pd['saledate'] = car_pd['saledate'].str.replace(r'GMT[-+]\d{4} \(\w{3}\)', '').str.strip()

# Convert the 'saledate' column to datetime format
car_pd['saledate'] = pd.to_datetime(car_pd['saledate'], format='%a %b %d %Y %H:%M:%S')

SyntaxError: invalid syntax (468474341.py, line 1)

In [1]:
import pandas as pd

In [2]:
car_sales=pd.read_csv("car_prices.csv")

In [12]:
import datetime as dt

In [15]:
# Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
formt="Tue Dec 16 2014 12:30:00 GMT-0800 (PST)"

In [16]:
pd.to_datetime(formt)

Timestamp('2014-12-16 12:30:00+0800', tz='UTC+08:00')

In [3]:
car_sales.head()

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate
0,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg566472,ca,5.0,16639.0,white,black,kia motors america inc,20500.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
1,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg561319,ca,5.0,9393.0,white,beige,kia motors america inc,20800.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
2,2014,BMW,3 Series,328i SULEV,Sedan,automatic,wba3c1c51ek116351,ca,45.0,1331.0,gray,black,financial services remarketing (lease),31900.0,30000.0,Thu Jan 15 2015 04:30:00 GMT-0800 (PST)
3,2015,Volvo,S60,T5,Sedan,automatic,yv1612tb4f1310987,ca,41.0,14282.0,white,black,volvo na rep/world omni,27500.0,27750.0,Thu Jan 29 2015 04:30:00 GMT-0800 (PST)
4,2014,BMW,6 Series Gran Coupe,650i,Sedan,automatic,wba6b2c57ed129731,ca,43.0,2641.0,gray,black,financial services remarketing (lease),66000.0,67000.0,Thu Dec 18 2014 12:30:00 GMT-0800 (PST)

In [19]:
car_sales.iloc[2896]

year                                               2009
make                                      Mercedes-Benz
model                                           G-Class
trim                                               G550
body                                                SUV
transmission                                  automatic
vin                                   wdcyr37e19x180079
state                                                ca
condition                                           5.0
odometer                                        43506.0
color                                             black
interior                                          black
seller                              nova auto sales inc
mmr                                             64000.0
sellingprice                                    66500.0
saledate        Tue Jan 27 2015 04:30:00 GMT-0800 (PST)
Name: 2896, dtype: object

In [27]:
car_sales['saledate'].str.extract(r'(\d{4})')

AttributeError: Can only use .str accessor with string values!

In [29]:
type(car_sales['saledate'])

pandas.core.series.Series

In [31]:
car_sales['saledate']=pd.to_datetime(car_sales['saledate'],errors='coerce')

In [33]:
car_sales.set_index('saledate',inplace=True)

In [40]:
car_sales.head(2)

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice
saledate,,,,,,,,,,,,,,,
2014-12-16 12:30:00+08:00,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg566472,ca,5.0,16639.0,white,black,kia motors america inc,20500.0,21500.0
2014-12-16 12:30:00+08:00,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg561319,ca,5.0,9393.0,white,beige,kia motors america inc,20800.0,21500.0

In [61]:
car_sales.mmr.resample("H").sum().sort_values(ascending=False).head()

saledate
2015-02-11 02:00:00+08:00    96735950.0
2015-01-28 02:00:00+08:00    96488575.0
2015-02-04 02:00:00+08:00    96369025.0
2015-01-27 01:00:00+08:00    90635325.0
2015-02-18 02:00:00+08:00    89857075.0
Name: mmr, dtype: float64

In [78]:
ok=car_sales[['mmr', 'sellingprice']].resample("H").sum().sort_values(by='sellingprice', ascending=False)

In [79]:
ok["hour"]=ok.index.hour

In [81]:
ok.head()

                                  mmr  sellingprice  hour
saledate
2015-02-11 02:00:00+08:00  96735950.0    97297132.0     2
2015-02-04 02:00:00+08:00  96369025.0    96396179.0     2
2015-01-28 02:00:00+08:00  96488575.0    94842734.0     2
2015-02-18 02:00:00+08:00  89857075.0    90417910.0     2
2015-01-27 01:00:00+08:00  90635325.0    89835506.0     1

In [82]:
ok.reset_index

<bound method DataFrame.reset_index of                                   mmr  sellingprice  hour
saledate
2015-02-11 02:00:00+08:00  96735950.0    97297132.0     2
2015-02-04 02:00:00+08:00  96369025.0    96396179.0     2
2015-01-28 02:00:00+08:00  96488575.0    94842734.0     2
2015-02-18 02:00:00+08:00  89857075.0    90417910.0     2
2015-01-27 01:00:00+08:00  90635325.0    89835506.0     1
...                               ...           ...   ...
2014-06-06 17:00:00+08:00         0.0           0.0    17
2014-06-06 18:00:00+08:00         0.0           0.0    18
2014-06-06 19:00:00+08:00         0.0           0.0    19
2014-06-06 20:00:00+08:00         0.0           0.0    20
2014-08-03 20:00:00+08:00         0.0           0.0    20

[10295 rows x 3 columns]>

In [73]:
result["hour"]=result.index.hour

In [74]:
result.hour

saledate
2015-02-28 00:00:00+08:00    0
2015-01-31 00:00:00+08:00    0
2014-12-31 00:00:00+08:00    0
2015-03-31 00:00:00+08:00    0
2014-01-31 00:00:00+08:00    0
2014-02-28 00:00:00+08:00    0
2014-03-31 00:00:00+08:00    0
2014-04-30 00:00:00+08:00    0
2014-05-31 00:00:00+08:00    0
2014-06-30 00:00:00+08:00    0
2014-07-31 00:00:00+08:00    0
2014-08-31 00:00:00+08:00    0
2014-09-30 00:00:00+08:00    0
2014-10-31 00:00:00+08:00    0
2014-11-30 00:00:00+08:00    0
Name: hour, dtype: int32

In [26]:
car_sales

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 558837 entries, 0 to 558836
Data columns (total 16 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   year          558837 non-null  int64
 1   make          548536 non-null  object
 2   model         548438 non-null  object
 3   trim          548186 non-null  object
 4   body          545642 non-null  object
 5   transmission  493485 non-null  object
 6   vin           558833 non-null  object
 7   state         558837 non-null  object
 8   condition     547017 non-null  float64
 9   odometer      558743 non-null  float64
 10  color         558088 non-null  object
 11  interior      558088 non-null  object
 12  seller        558837 non-null  object
 13  mmr           558799 non-null  float64
 14  sellingprice  558825 non-null  float64
 15  saledate      558799 non-null  object
dtypes: float64(4), int64(1), object(11)
memory usage: 68.2+ MB

In [14]:
apple_price=pd.read_csv("AAPL.csv",index_col="Date")

In [15]:
apple_price

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2023-03-27,159.940002,160.770004,157.869995,158.279999,157.439651,52390300
2023-03-28,157.970001,158.490005,155.979996,157.649994,156.812973,45992200
2023-03-29,159.369995,161.050003,159.350006,160.770004,159.916428,51305700
2023-03-30,161.529999,162.470001,161.270004,162.360001,161.497986,49501700
2023-03-31,162.440002,165.000000,161.910004,164.899994,164.024475,68749800
...,...,...,...,...,...,...
2024-03-20,175.720001,178.669998,175.089996,178.669998,178.669998,53423100
2024-03-21,177.050003,177.490005,170.839996,171.369995,171.369995,106181300
2024-03-22,171.759995,173.050003,170.059998,172.279999,172.279999,71106600
2024-03-25,170.570007,171.940002,169.449997,170.850006,170.850006,54235800
2024-03-26,170.000000,171.068604,169.649994,170.679993,170.679993,16600695

In [9]:
apple_price=apple_price.set_index("Date")

In [24]:
apple_price.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252 entries, 0 to 251
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       252 non-null    datetime64[ns]
 1   Open       252 non-null    float64
 2   High       252 non-null    float64
 3   Low        252 non-null    float64
 4   Close      252 non-null    float64
 5   Adj Close  252 non-null    float64
 6   Volume     252 non-null    int64
dtypes: datetime64[ns](1), float64(5), int64(1)
memory usage: 13.9 KB

In [20]:
apple_price=apple_price.reset_index()

In [26]:
apple_price=apple_price["Date"]=pd.to_datetime(apple_price["Date"])

In [27]:
apple_price

RecursionError: maximum recursion depth exceeded while calling a Python object

In [25]:
apple_price.set_index("Date")

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2023-03-27,159.940002,160.770004,157.869995,158.279999,157.439651,52390300
2023-03-28,157.970001,158.490005,155.979996,157.649994,156.812973,45992200
2023-03-29,159.369995,161.050003,159.350006,160.770004,159.916428,51305700
2023-03-30,161.529999,162.470001,161.270004,162.360001,161.497986,49501700
2023-03-31,162.440002,165.000000,161.910004,164.899994,164.024475,68749800
...,...,...,...,...,...,...
2024-03-20,175.720001,178.669998,175.089996,178.669998,178.669998,53423100
2024-03-21,177.050003,177.490005,170.839996,171.369995,171.369995,106181300
2024-03-22,171.759995,173.050003,170.059998,172.279999,172.279999,71106600
2024-03-25,170.570007,171.940002,169.449997,170.850006,170.850006,54235800
2024-03-26,170.000000,171.068604,169.649994,170.679993,170.679993,16600695

In [17]:
apple_price["2023-03"]

KeyError: '2023-03'

In [13]:
apple_price["2023-03-27"]

KeyError: '2023-03-27'

In [29]:
apple_price=pd.read_csv("AAPL.csv",parse_dates=["Date"],index_col="Date")

In [30]:
apple_price.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 252 entries, 2023-03-27 to 2024-03-26
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Open       252 non-null    float64
 1   High       252 non-null    float64
 2   Low        252 non-null    float64
 3   Close      252 non-null    float64
 4   Adj Close  252 non-null    float64
 5   Volume     252 non-null    int64
dtypes: float64(5), int64(1)
memory usage: 13.8 KB

In [31]:
apple_price.head(4)

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2023-03-27,159.940002,160.770004,157.869995,158.279999,157.439651,52390300
2023-03-28,157.970001,158.490005,155.979996,157.649994,156.812973,45992200
2023-03-29,159.369995,161.050003,159.350006,160.770004,159.916428,51305700
2023-03-30,161.529999,162.470001,161.270004,162.360001,161.497986,49501700

In [32]:
apple_price["2023-03"]

KeyError: '2023-03'

In [1]:
import csv

In [2]:
data=list(csv.reader(open("world-happiness-report-2021.csv")))

In [4]:
header=data[0]
data=data[1:]

In [5]:
header

['ï»¿Country name',
 'Regional indicator',
 'Ladder score',
 'Standard error of ladder score',
 'upperwhisker',
 'lowerwhisker',
 'Logged GDP per capita',
 'Social support',
 'Healthy life expectancy',
 'Freedom to make life choices',
 'Generosity',
 'Perceptions of corruption',
 'Ladder score in Dystopia',
 'Explained by: Log GDP per capita',
 'Explained by: Social support',
 'Explained by: Healthy life expectancy',
 'Explained by: Freedom to make life choices',
 'Explained by: Generosity',
 'Explained by: Perceptions of corruption',
 'Dystopia + residual']

In [6]:
data

[['Finland',
  'Western Europe',
  '7.842',
  '0.032',
  '7.904',
  '7.780',
  '10.775',
  '0.954',
  '72.000',
  '0.949',
  '-0.098',
  '0.186',
  '2.430',
  '1.446',
  '1.106',
  '0.741',
  '0.691',
  '0.124',
  '0.481',
  '3.253'],
 ['Denmark',
  'Western Europe',
  '7.620',
  '0.035',
  '7.687',
  '7.552',
  '10.933',
  '0.954',
  '72.700',
  '0.946',
  '0.030',
  '0.179',
  '2.430',
  '1.502',
  '1.108',
  '0.763',
  '0.686',
  '0.208',
  '0.485',
  '2.868'],
 ['Switzerland',
  'Western Europe',
  '7.571',
  '0.036',
  '7.643',
  '7.500',
  '11.117',
  '0.942',
  '74.400',
  '0.919',
  '0.025',
  '0.292',
  '2.430',
  '1.566',
  '1.079',
  '0.816',
  '0.653',
  '0.204',
  '0.413',
  '2.839'],
 ['Iceland',
  'Western Europe',
  '7.554',
  '0.059',
  '7.670',
  '7.438',
  '10.878',
  '0.983',
  '73.000',
  '0.955',
  '0.160',
  '0.673',
  '2.430',
  '1.482',
  '1.172',
  '0.772',
  '0.698',
  '0.293',
  '0.170',
  '2.967'],
 ['Netherlands',
  'Western Europe',
  '7.464',
  '0.027',
  '7.518',
  '7.410',
  '10.932',
  '0.942',
  '72.400',
  '0.913',
  '0.175',
  '0.338',
  '2.430',
  '1.501',
  '1.079',
  '0.753',
  '0.647',
  '0.302',
  '0.384',
  '2.798'],
 ['Norway',
  'Western Europe',
  '7.392',
  '0.035',
  '7.462',
  '7.323',
  '11.053',
  '0.954',
  '73.300',
  '0.960',
  '0.093',
  '0.270',
  '2.430',
  '1.543',
  '1.108',
  '0.782',
  '0.703',
  '0.249',
  '0.427',
  '2.580'],
 ['Sweden',
  'Western Europe',
  '7.363',
  '0.036',
  '7.433',
  '7.293',
  '10.867',
  '0.934',
  '72.700',
  '0.945',
  '0.086',
  '0.237',
  '2.430',
  '1.478',
  '1.062',
  '0.763',
  '0.685',
  '0.244',
  '0.448',
  '2.683'],
 ['Luxembourg',
  'Western Europe',
  '7.324',
  '0.037',
  '7.396',
  '7.252',
  '11.647',
  '0.908',
  '72.600',
  '0.907',
  '-0.034',
  '0.386',
  '2.430',
  '1.751',
  '1.003',
  '0.760',
  '0.639',
  '0.166',
  '0.353',
  '2.653'],
 ['New Zealand',
  'North America and ANZ',
  '7.277',
  '0.040',
  '7.355',
  '7.198',
  '10.643',
  '0.948',
  '73.400',
  '0.929',
  '0.134',
  '0.242',
  '2.430',
  '1.400',
  '1.094',
  '0.785',
  '0.665',
  '0.276',
  '0.445',
  '2.612'],
 ['Austria',
  'Western Europe',
  '7.268',
  '0.036',
  '7.337',
  '7.198',
  '10.906',
  '0.934',
  '73.300',
  '0.908',
  '0.042',
  '0.481',
  '2.430',
  '1.492',
  '1.062',
  '0.782',
  '0.640',
  '0.215',
  '0.292',
  '2.784'],
 ['Australia',
  'North America and ANZ',
  '7.183',
  '0.041',
  '7.265',
  '7.102',
  '10.796',
  '0.940',
  '73.900',
  '0.914',
  '0.159',
  '0.442',
  '2.430',
  '1.453',
  '1.076',
  '0.801',
  '0.647',
  '0.291',
  '0.317',
  '2.598'],
 ['Israel',
  'Middle East and North Africa',
  '7.157',
  '0.034',
  '7.224',
  '7.090',
  '10.575',
  '0.939',
  '73.503',
  '0.800',
  '0.031',
  '0.753',
  '2.430',
  '1.376',
  '1.074',
  '0.788',
  '0.509',
  '0.208',
  '0.119',
  '3.083'],
 ['Germany',
  'Western Europe',
  '7.155',
  '0.040',
  '7.232',
  '7.077',
  '10.873',
  '0.903',
  '72.500',
  '0.875',
  '0.011',
  '0.460',
  '2.430',
  '1.480',
  '0.993',
  '0.757',
  '0.600',
  '0.195',
  '0.306',
  '2.824'],
 ['Canada',
  'North America and ANZ',
  '7.103',
  '0.042',
  '7.185',
  '7.021',
  '10.776',
  '0.926',
  '73.800',
  '0.915',
  '0.089',
  '0.415',
  '2.430',
  '1.447',
  '1.044',
  '0.798',
  '0.648',
  '0.246',
  '0.335',
  '2.585'],
 ['Ireland',
  'Western Europe',
  '7.085',
  '0.040',
  '7.164',
  '7.006',
  '11.342',
  '0.947',
  '72.400',
  '0.879',
  '0.077',
  '0.363',
  '2.430',
  '1.644',
  '1.092',
  '0.753',
  '0.606',
  '0.238',
  '0.367',
  '2.384'],
 ['Costa Rica',
  'Latin America and Caribbean',
  '7.069',
  '0.056',
  '7.179',
  '6.960',
  '9.880',
  '0.891',
  '71.400',
  '0.934',
  '-0.126',
  '0.809',
  '2.430',
  '1.134',
  '0.966',
  '0.722',
  '0.673',
  '0.105',
  '0.083',
  '3.387'],
 ['United Kingdom',
  'Western Europe',
  '7.064',
  '0.038',
  '7.138',
  '6.990',
  '10.707',
  '0.934',
  '72.500',
  '0.859',
  '0.233',
  '0.459',
  '2.430',
  '1.423',
  '1.062',
  '0.757',
  '0.580',
  '0.340',
  '0.306',
  '2.596'],
 ['Czech Republic',
  'Central and Eastern Europe',
  '6.965',
  '0.049',
  '7.062',
  '6.868',
  '10.556',
  '0.947',
  '70.807',
  '0.858',
  '-0.208',
  '0.868',
  '2.430',
  '1.370',
  '1.090',
  '0.703',
  '0.580',
  '0.052',
  '0.046',
  '3.124'],
 ['United States',
  'North America and ANZ',
  '6.951',
  '0.049',
  '7.047',
  '6.856',
  '11.023',
  '0.920',
  '68.200',
  '0.837',
  '0.098',
  '0.698',
  '2.430',
  '1.533',
  '1.030',
  '0.621',
  '0.554',
  '0.252',
  '0.154',
  '2.807'],
 ['Belgium',
  'Western Europe',
  '6.834',
  '0.034',
  '6.901',
  '6.767',
  '10.823',
  '0.906',
  '72.199',
  '0.783',
  '-0.153',
  '0.646',
  '2.430',
  '1.463',
  '0.998',
  '0.747',
  '0.489',
  '0.088',
  '0.187',
  '2.862'],
 ['France',
  'Western Europe',
  '6.690',
  '0.037',
  '6.762',
  '6.618',
  '10.704',
  '0.942',
  '74.000',
  '0.822',
  '-0.147',
  '0.571',
  '2.430',
  '1.421',
  '1.081',
  '0.804',
  '0.536',
  '0.092',
  '0.235',
  '2.521'],
 ['Bahrain',
  'Middle East and North Africa',
  '6.647',
  '0.068',
  '6.779',
  '6.514',
  '10.669',
  '0.862',
  '69.495',
  '0.925',
  '0.089',
  '0.722',
  '2.430',
  '1.409',
  '0.899',
  '0.662',
  '0.661',
  '0.246',
  '0.139',
  '2.631'],
 ['Malta',
  'Western Europe',
  '6.602',
  '0.044',
  '6.688',
  '6.516',
  '10.674',
  '0.931',
  '72.200',
  '0.927',
  '0.133',
  '0.653',
  '2.430',
  '1.411',
  '1.055',
  '0.747',
  '0.664',
  '0.275',
  '0.183',
  '2.268'],
 ['Taiwan Province of China',
  'East Asia',
  '6.584',
  '0.038',
  '6.659',
  '6.510',
  '10.871',
  '0.898',
  '69.600',
  '0.784',
  '-0.070',
  '0.721',
  '2.430',
  '1.480',
  '0.982',
  '0.665',
  '0.490',
  '0.142',
  '0.139',
  '2.687'],
 ['United Arab Emirates',
  'Middle East and North Africa',
  '6.561',
  '0.039',
  '6.637',
  '6.484',
  '11.085',
  '0.844',
  '67.333',
  '0.932',
  '0.074',
  '0.589',
  '2.430',
  '1.555',
  '0.860',
  '0.594',
  '0.670',
  '0.236',
  '0.223',
  '2.422'],
 ['Saudi Arabia',
  'Middle East and North Africa',
  '6.494',
  '0.056',
  '6.604',
  '6.384',
  '10.743',
  '0.891',
  '66.603',
  '0.877',
  '-0.149',
  '0.684',
  '2.430',
  '1.435',
  '0.964',
  '0.571',
  '0.603',
  '0.090',
  '0.163',
  '2.668'],
 ['Spain',
  'Western Europe',
  '6.491',
  '0.042',
  '6.574',
  '6.408',
  '10.571',
  '0.932',
  '74.700',
  '0.761',
  '-0.081',
  '0.745',
  '2.430',
  '1.375',
  '1.057',
  '0.826',
  '0.462',
  '0.135',
  '0.124',
  '2.513'],
 ['Italy',
  'Western Europe',
  '6.483',
  '0.045',
  '6.572',
  '6.395',
  '10.623',
  '0.880',
  '73.800',
  '0.693',
  '-0.084',
  '0.866',
  '2.430',
  '1.393',
  '0.940',
  '0.798',
  '0.379',
  '0.133',
  '0.047',
  '2.794'],
 ['Slovenia',
  'Central and Eastern Europe',
  '6.461',
  '0.043',
  '6.546',
  '6.376',
  '10.529',
  '0.948',
  '71.400',
  '0.949',
  '-0.101',
  '0.806',
  '2.430',
  '1.360',
  '1.093',
  '0.722',
  '0.690',
  '0.122',
  '0.085',
  '2.388'],
 ['Guatemala',
  'Latin America and Caribbean',
  '6.435',
  '0.073',
  '6.577',
  '6.292',
  '9.053',
  '0.813',
  '64.958',
  '0.906',
  '-0.038',
  '0.775',
  '2.430',
  '0.845',
  '0.790',
  '0.519',
  '0.638',
  '0.163',
  '0.105',
  '3.375'],
 ['Uruguay',
  'Latin America and Caribbean',
  '6.431',
  '0.046',
  '6.521',
  '6.341',
  '9.966',
  '0.925',
  '69.100',
  '0.896',
  '-0.092',
  '0.590',
  '2.430',
  '1.164',
  '1.042',
  '0.649',
  '0.625',
  '0.128',
  '0.223',
  '2.600'],
 ['Singapore',
  'Southeast Asia',
  '6.377',
  '0.043',
  '6.460',
  '6.293',
  '11.488',
  '0.915',
  '76.953',
  '0.927',
  '-0.018',
  '0.082',
  '2.430',
  '1.695',
  '1.019',
  '0.897',
  '0.664',
  '0.176',
  '0.547',
  '1.379'],
 ['Kosovo',
  'Central and Eastern Europe',
  '6.372',
  '0.059',
  '6.487',
  '6.257',
  '9.318',
  '0.821',
  '63.813',
  '0.869',
  '0.257',
  '0.917',
  '2.430',
  '0.937',
  '0.807',
  '0.483',
  '0.593',
  '0.356',
  '0.014',
  '3.182'],
 ['Slovakia',
  'Central and Eastern Europe',
  '6.331',
  '0.041',
  '6.411',
  '6.251',
  '10.369',
  '0.936',
  '69.201',
  '0.766',
  '-0.124',
  '0.911',
  '2.430',
  '1.304',
  '1.066',
  '0.653',
  '0.468',
  '0.107',
  '0.018',
  '2.714'],
 ['Brazil',
  'Latin America and Caribbean',
  '6.330',
  '0.043',
  '6.415',
  '6.245',
  '9.577',
  '0.882',
  '66.601',
  '0.804',
  '-0.071',
  '0.756',
  '2.430',
  '1.028',
  '0.944',
  '0.571',
  '0.514',
  '0.142',
  '0.117',
  '3.015'],
 ['Mexico',
  'Latin America and Caribbean',
  '6.317',
  '0.053',
  '6.420',
  '6.213',
  '9.859',
  '0.831',
  '68.597',
  '0.862',
  '-0.147',
  '0.799',
  '2.430',
  '1.126',
  '0.830',
  '0.634',
  '0.585',
  '0.092',
  '0.089',
  '2.961'],
 ['Jamaica',
  'Latin America and Caribbean',
  '6.309',
  '0.156',
  '6.615',
  '6.004',
  '9.186',
  '0.877',
  '67.500',
  '0.890',
  '-0.137',
  '0.884',
  '2.430',
  '0.891',
  '0.932',
  '0.599',
  '0.618',
  '0.099',
  '0.035',
  '3.135'],
 ['Lithuania',
  'Central and Eastern Europe',
  '6.255',
  '0.045',
  '6.344',
  '6.167',
  '10.499',
  '0.935',
  '67.906',
  '0.773',
  '-0.203',
  '0.826',
  '2.430',
  '1.350',
  '1.065',
  '0.612',
  '0.476',
  '0.056',
  '0.073',
  '2.624'],
 ['Cyprus',
  'Western Europe',
  '6.223',
  '0.049',
  '6.319',
  '6.128',
  '10.576',
  '0.802',
  '73.898',
  '0.763',
  '-0.015',
  '0.844',
  '2.430',
  '1.377',
  '0.765',
  '0.801',
  '0.464',
  '0.178',
  '0.061',
  '2.578'],
 ['Estonia',
  'Central and Eastern Europe',
  '6.189',
  '0.038',
  '6.263',
  '6.115',
  '10.481',
  '0.941',
  '68.800',
  '0.909',
  '-0.106',
  '0.527',
  '2.430',
  '1.344',
  '1.079',
  '0.640',
  '0.641',
  '0.119',
  '0.263',
  '2.103'],
 ['Panama',
  'Latin America and Caribbean',
  '6.180',
  '0.073',
  '6.323',
  '6.036',
  '10.350',
  '0.896',
  '69.652',
  '0.872',
  '-0.166',
  '0.856',
  '2.430',
  '1.298',
  '0.976',
  '0.667',
  '0.596',
  '0.079',
  '0.053',
  '2.509'],
 ['Uzbekistan',
  'Commonwealth of Independent States',
  '6.179',
  '0.068',
  '6.312',
  '6.045',
  '8.836',
  '0.918',
  '65.255',
  '0.970',
  '0.311',
  '0.515',
  '2.430',
  '0.769',
  '1.027',
  '0.528',
  '0.716',
  '0.391',
  '0.271',
  '2.477'],
 ['Chile',
  'Latin America and Caribbean',
  '6.172',
  '0.046',
  '6.262',
  '6.081',
  '10.071',
  '0.882',
  '70.000',
  '0.742',
  '-0.044',
  '0.830',
  '2.430',
  '1.200',
  '0.946',
  '0.678',
  '0.438',
  '0.159',
  '0.070',
  '2.682'],
 ['Poland',
  'Central and Eastern Europe',
  '6.166',
  '0.040',
  '6.245',
  '6.087',
  '10.382',
  '0.898',
  '69.702',
  '0.841',
  '-0.165',
  '0.735',
  '2.430',
  '1.309',
  '0.982',
  '0.668',
  '0.558',
  '0.080',
  '0.130',
  '2.438'],
 ['Kazakhstan',
  'Commonwealth of Independent States',
  '6.152',
  '0.047',
  '6.243',
  '6.060',
  '10.155',
  '0.952',
  '65.200',
  '0.853',
  '-0.069',
  '0.733',
  '2.430',
  '1.230',
  '1.103',
  '0.527',
  '0.573',
  '0.143',
  '0.132',
  '2.446'],
 ['Romania',
  'Central and Eastern Europe',
  '6.140',
  '0.057',
  '6.253',
  '6.027',
  '10.284',
  '0.832',
  '67.355',
  '0.845',
  '-0.219',
  '0.938',
  '2.430',
  '1.275',
  '0.832',
  '0.595',
  '0.564',
  '0.045',
  '0.001',
  '2.830'],
 ['Kuwait',
  'Middle East and North Africa',
  '6.106',
  '0.066',
  '6.235',
  '5.977',
  '10.817',
  '0.843',
  '66.900',
  '0.867',
  '-0.104',
  '0.736',
  '2.430',
  '1.461',
  '0.857',
  '0.580',
  '0.591',
  '0.120',
  '0.130',
  '2.368'],
 ['Serbia',
  'Central and Eastern Europe',
  '6.078',
  '0.053',
  '6.181',
  '5.974',
  '9.787',
  '0.873',
  '68.600',
  '0.778',
  '0.002',
  '0.835',
  '2.430',
  '1.101',
  '0.924',
  '0.634',
  '0.482',
  '0.189',
  '0.066',
  '2.682'],
 ['El Salvador',
  'Latin America and Caribbean',
  '6.061',
  '0.065',
  '6.188',
  '5.933',
  '9.054',
  '0.762',
  '66.402',
  '0.888',
  '-0.110',
  '0.688',
  '2.430',
  '0.845',
  '0.675',
  '0.565',
  '0.615',
  '0.116',
  '0.160',
  '3.085'],
 ['Mauritius',
  'Sub-Saharan Africa',
  '6.049',
  '0.059',
  '6.165',
  '5.933',
  '10.008',
  '0.905',
  '66.701',
  '0.867',
  '-0.054',
  '0.789',
  '2.430',
  '1.178',
  '0.996',
  '0.574',
  '0.590',
  '0.153',
  '0.096',
  '2.462'],
 ['Latvia',
  'Central and Eastern Europe',
  '6.032',
  '0.036',
  '6.103',
  '5.961',
  '10.315',
  '0.927',
  '67.100',
  '0.715',
  '-0.162',
  '0.800',
  '2.430',
  '1.285',
  '1.047',
  '0.587',
  '0.405',
  '0.082',
  '0.089',
  '2.536'],
 ['Colombia',
  'Latin America and Caribbean',
  '6.012',
  '0.061',
  '6.132',
  '5.892',
  '9.557',
  '0.847',
  '68.001',
  '0.837',
  '-0.135',
  '0.841',
  '2.430',
  '1.021',
  '0.866',
  '0.615',
  '0.554',
  '0.100',
  '0.063',
  '2.794'],
 ['Hungary',
  'Central and Eastern Europe',
  '5.992',
  '0.047',
  '6.085',
  '5.899',
  '10.358',
  '0.943',
  '68.000',
  '0.755',
  '-0.186',
  '0.876',
  '2.430',
  '1.301',
  '1.083',
  '0.615',
  '0.454',
  '0.067',
  '0.040',
  '2.432'],
 ['Thailand',
  'Southeast Asia',
  '5.985',
  '0.047',
  '6.077',
  '5.893',
  '9.805',
  '0.888',
  '67.401',
  '0.884',
  '0.287',
  '0.895',
  '2.430',
  '1.107',
  '0.957',
  '0.596',
  '0.611',
  '0.375',
  '0.028',
  '2.309'],
 ['Nicaragua',
  'Latin America and Caribbean',
  '5.972',
  '0.083',
  '6.134',
  '5.810',
  '8.620',
  '0.864',
  '67.657',
  '0.836',
  '0.020',
  '0.664',
  '2.430',
  '0.693',
  '0.904',
  '0.604',
  '0.553',
  '0.201',
  '0.176',
  '2.841'],
 ['Japan',
  'East Asia',
  '5.940',
  '0.040',
  '6.020',
  '5.861',
  '10.611',
  '0.884',
  '75.100',
  '0.796',
  '-0.258',
  '0.638',
  '2.430',
  '1.389',
  '0.949',
  '0.838',
  '0.504',
  '0.020',
  '0.192',
  '2.048'],
 ['Argentina',
  'Latin America and Caribbean',
  '5.929',
  '0.056',
  '6.040',
  '5.819',
  '9.962',
  '0.898',
  '69.000',
  '0.828',
  '-0.182',
  '0.834',
  '2.430',
  '1.162',
  '0.980',
  '0.646',
  '0.544',
  '0.069',
  '0.067',
  '2.461'],
 ['Portugal',
  'Western Europe',
  '5.929',
  '0.055',
  '6.037',
  '5.821',
  '10.421',
  '0.879',
  '72.600',
  '0.892',
  '-0.244',
  '0.887',
  '2.430',
  '1.323',
  '0.939',
  '0.760',
  '0.621',
  '0.029',
  '0.033',
  '2.225'],
 ['Honduras',
  'Latin America and Caribbean',
  '5.919',
  '0.082',
  '6.081',
  '5.758',
  '8.648',
  '0.812',
  '67.300',
  '0.857',
  '0.081',
  '0.809',
  '2.430',
  '0.703',
  '0.787',
  '0.593',
  '0.578',
  '0.241',
  '0.083',
  '2.934'],
 ['Croatia',
  'Central and Eastern Europe',
  '5.882',
  '0.048',
  '5.975',
  '5.788',
  '10.217',
  '0.924',
  '70.799',
  '0.754',
  '-0.118',
  '0.939',
  '2.430',
  '1.251',
  '1.039',
  '0.703',
  '0.453',
  '0.111',
  '0.000',
  '2.325'],
 ['Philippines',
  'Southeast Asia',
  '5.880',
  '0.052',
  '5.982',
  '5.778',
  '9.076',
  '0.830',
  '62.000',
  '0.917',
  '-0.097',
  '0.742',
  '2.430',
  '0.853',
  '0.828',
  '0.426',
  '0.651',
  '0.125',
  '0.126',
  '2.872'],
 ['South Korea',
  'East Asia',
  '5.845',
  '0.042',
  '5.928',
  '5.763',
  '10.651',
  '0.799',
  '73.900',
  '0.672',
  '-0.083',
  '0.727',
  '2.430',
  '1.403',
  '0.758',
  '0.801',
  '0.353',
  '0.134',
  '0.135',
  '2.262'],
 ['Peru',
  'Latin America and Caribbean',
  '5.840',
  '0.075',
  '5.988',
  '5.692',
  '9.458',
  '0.832',
  '68.250',
  '0.822',
  '-0.154',
  '0.891',
  '2.430',
  '0.986',
  '0.833',
  '0.623',
  '0.536',
  '0.087',
  '0.031',
  '2.744'],
 ['Bosnia and Herzegovina',
  'Central and Eastern Europe',
  '5.813',
  '0.050',
  '5.911',
  '5.715',
  '9.590',
  '0.870',
  '68.098',
  '0.706',
  '0.113',
  '0.931',
  '2.430',
  '1.032',
  '0.919',
  '0.618',
  '0.395',
  '0.261',
  '0.005',
  '2.583'],
 ['Moldova',
  'Commonwealth of Independent States',
  '5.766',
  '0.046',
  '5.856',
  '5.677',
  '9.454',
  '0.857',
  '65.699',
  '0.822',
  '-0.079',
  '0.918',
  '2.430',
  '0.985',
  '0.888',
  '0.542',
  '0.536',
  '0.137',
  '0.013',
  '2.665'],
 ['Ecuador',
  'Latin America and Caribbean',
  '5.764',
  '0.057',
  '5.875',
  '5.653',
  '9.313',
  '0.821',
  '68.800',
  '0.842',
  '-0.124',
  '0.843',
  '2.430',
  '0.935',
  '0.806',
  '0.640',
  '0.560',
  '0.107',
  '0.062',
  '2.653'],
 ['Kyrgyzstan',
  'Commonwealth of Independent States',
  '5.744',
  '0.046',
  '5.834',
  '5.653',
  '8.538',
  '0.893',
  '64.401',
  '0.935',
  '0.119',
  '0.908',
  '2.430',
  '0.665',
  '0.971',
  '0.501',
  '0.673',
  '0.266',
  '0.020',
  '2.648'],
 ['Greece',
  'Western Europe',
  '5.723',
  '0.046',
  '5.813',
  '5.632',
  '10.279',
  '0.823',
  '72.600',
  '0.582',
  '-0.288',
  '0.823',
  '2.430',
  '1.273',
  '0.811',
  '0.760',
  '0.243',
  '0.000',
  '0.074',
  '2.561'],
 ['Bolivia',
  'Latin America and Caribbean',
  '5.716',
  '0.053',
  '5.819',
  '5.613',
  '9.046',
  '0.810',
  '63.901',
  '0.875',
  '-0.077',
  '0.839',
  '2.430',
  '0.842',
  '0.782',
  '0.486',
  '0.600',
  '0.138',
  '0.064',
  '2.805'],
 ['Mongolia',
  'East Asia',
  '5.677',
  '0.042',
  '5.760',
  '5.595',
  '9.400',
  '0.935',
  '62.500',
  '0.708',
  '0.116',
  '0.856',
  '2.430',
  '0.966',
  '1.065',
  '0.442',
  '0.397',
  '0.263',
  '0.053',
  '2.492'],
 ['Paraguay',
  'Latin America and Caribbean',
  '5.653',
  '0.092',
  '5.832',
  '5.473',
  '9.448',
  '0.893',
  '65.900',
  '0.876',
  '0.028',
  '0.882',
  '2.430',
  '0.983',
  '0.970',
  '0.549',
  '0.602',
  '0.206',
  '0.037',
  '2.306'],
 ['Montenegro',
  'Central and Eastern Europe',
  '5.581',
  '0.054',
  '5.686',
  '5.475',
  '9.940',
  '0.858',
  '68.699',
  '0.708',
  '-0.034',
  '0.812',
  '2.430',
  '1.155',
  '0.891',
  '0.637',
  '0.397',
  '0.166',
  '0.081',
  '2.254'],
 ['Dominican Republic',
  'Latin America and Caribbean',
  '5.545',
  '0.071',
  '5.685',
  '5.405',
  '9.802',
  '0.853',
  '66.102',
  '0.860',
  '-0.133',
  '0.714',
  '2.430',
  '1.106',
  '0.879',
  '0.555',
  '0.581',
  '0.101',
  '0.144',
  '2.178'],
 ['North Cyprus',
  'Western Europe',
  '5.536',
  '0.051',
  '5.636',
  '5.435',
  '10.576',
  '0.820',
  '73.898',
  '0.795',
  '0.012',
  '0.626',
  '2.430',
  '1.377',
  '0.806',
  '0.801',
  '0.503',
  '0.196',
  '0.200',
  '1.653'],
 ['Belarus',
  'Commonwealth of Independent States',
  '5.534',
  '0.047',
  '5.625',
  '5.442',
  '9.853',
  '0.910',
  '66.253',
  '0.650',
  '-0.180',
  '0.627',
  '2.430',
  '1.124',
  '1.007',
  '0.560',
  '0.326',
  '0.070',
  '0.199',
  '2.247'],
 ['Russia',
  'Commonwealth of Independent States',
  '5.477',
  '0.033',
  '5.541',
  '5.413',
  '10.189',
  '0.903',
  '64.703',
  '0.718',
  '-0.111',
  '0.845',
  '2.430',
  '1.241',
  '0.992',
  '0.511',
  '0.409',
  '0.115',
  '0.060',
  '2.148'],
 ['Hong Kong S.A.R. of China',
  'East Asia',
  '5.477',
  '0.049',
  '5.573',
  '5.380',
  '11.000',
  '0.836',
  '76.820',
  '0.717',
  '0.067',
  '0.403',
  '2.430',
  '1.525',
  '0.841',
  '0.893',
  '0.408',
  '0.232',
  '0.342',
  '1.236'],
 ['Tajikistan',
  'Commonwealth of Independent States',
  '5.466',
  '0.034',
  '5.532',
  '5.400',
  '8.091',
  '0.860',
  '64.281',
  '0.832',
  '-0.056',
  '0.553',
  '2.430',
  '0.508',
  '0.895',
  '0.498',
  '0.548',
  '0.152',
  '0.247',
  '2.619'],
 ['Vietnam',
  'Southeast Asia',
  '5.411',
  '0.039',
  '5.488',
  '5.334',
  '8.973',
  '0.850',
  '68.034',
  '0.940',
  '-0.098',
  '0.796',
  '2.430',
  '0.817',
  '0.873',
  '0.616',
  '0.679',
  '0.124',
  '0.091',
  '2.211'],
 ['Libya',
  'Middle East and North Africa',
  '5.410',
  '0.076',
  '5.558',
  '5.262',
  '9.622',
  '0.827',
  '62.300',
  '0.771',
  '-0.087',
  '0.667',
  '2.430',
  '1.044',
  '0.821',
  '0.435',
  '0.474',
  '0.131',
  '0.174',
  '2.331'],
 ['Malaysia',
  'Southeast Asia',
  '5.384',
  '0.049',
  '5.480',
  '5.289',
  '10.238',
  '0.817',
  '67.102',
  '0.895',
  '0.125',
  '0.839',
  '2.430',
  '1.259',
  '0.797',
  '0.587',
  '0.624',
  '0.270',
  '0.064',
  '1.784'],
 ['Indonesia',
  'Southeast Asia',
  '5.345',
  '0.056',
  '5.454',
  '5.235',
  '9.365',
  '0.811',
  '62.236',
  '0.873',
  '0.542',
  '0.867',
  '2.430',
  '0.954',
  '0.786',
  '0.433',
  '0.598',
  '0.541',
  '0.046',
  '1.987'],

In [31]:
def readfile(filename):
        data=list(csv.reader(open(filename)))
        if header==True:
            headers=data[0]
            data=data[1:]
            return headers, data
        else:
            return data

In [33]:
headers,data=readfile("world-happiness-report-2021.csv")

ValueError: too many values to unpack (expected 2)

In [30]:
headers,data=readfile("world-happiness-report-2021.csv")