In [ ]:
!gdown 1jGFCFUz9QLie4LtOh620qa8AghvQCfHR

Downloading...
From: https://drive.google.com/uc?id=1jGFCFUz9QLie4LtOh620qa8AghvQCfHR
To: /content/your_file_transformed (2).csv
100% 16.6M/16.6M [00:00<00:00, 26.0MB/s]

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('your_file_transformed (2).csv')

In [ ]:
df

,Unnamed: 0,LOAN_TYPE,GENDER,OWN_CAR,OWN_HOUSE,CNT_CHILDREN,ANNUAL_INCOME,LOAN_AMOUNT,LOAN_ANNUITY,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,MARITAL_STATUS,OCCUPATION,Age
0,0,0,1,0,1,0,202500.0,406597.5,24700.5,7,4,3,8,67
1,1,0,0,0,0,0,270000.0,1293502.5,35698.5,4,1,1,3,65
2,2,1,1,1,1,0,67500.0,135000.0,6750.0,7,4,3,8,22
3,3,0,0,0,1,0,135000.0,312682.5,29686.5,7,4,0,8,40
4,4,0,1,0,1,0,121500.0,513000.0,21865.5,7,4,3,3,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,307506,0,1,0,0,0,157500.0,254700.0,27558.0,7,4,2,14,52
307507,307507,0,0,0,1,0,72000.0,269550.0,12001.5,3,4,5,18,66
307508,307508,0,0,0,1,0,153000.0,677664.0,29979.0,7,1,2,10,49
307509,307509,0,0,0,1,0,171000.0,370107.0,20205.0,1,4,1,8,48
307510,307510,0,0,0,0,0,157500.0,675000.0,49117.5,1,1,1,8,50

In [ ]:
import pandas as pd

# Assuming you have a DataFrame named 'df' with the attributes mentioned
# Create a new column 'RISK_CATEGORY' to store the risk labels
df['RISK_CATEGORY'] = ''

for index, row in df.iterrows():
    if (row['LOAN_AMOUNT'] > row['ANNUAL_INCOME'] and row['LOAN_ANNUITY'] > row['ANNUAL_INCOME']) \
        or row['Age'] < 50 \
        or (row['OWN_CAR'] == 0 and row['OWN_HOUSE'] == 0 and row['MARITAL_STATUS'] == 1 and row['CNT_CHILDREN'] < 1):
        df.at[index, 'RISK_CATEGORY'] = 'High Risk'
    elif (row['ANNUAL_INCOME'] == row['LOAN_AMOUNT'] and row['ANNUAL_INCOME'] == row['LOAN_ANNUITY']) \
        or row['Age'] < 45 \
        or (row['OWN_CAR'] == 0 and row['OWN_HOUSE'] == 0 and row['MARITAL_STATUS'] == 1 and row['CNT_CHILDREN'] < 1):
        df.at[index, 'RISK_CATEGORY'] = 'Medium Risk'
    elif (row['ANNUAL_INCOME'] >= row['LOAN_AMOUNT'] and row['ANNUAL_INCOME'] >= row['LOAN_ANNUITY']) \
        or row['Age'] >= 50 \
        or (row['OWN_CAR'] == 1 and row['OWN_HOUSE'] == 1 and row['MARITAL_STATUS'] == 1 and row['CNT_CHILDREN'] < 1):
        df.at[index, 'RISK_CATEGORY'] = 'Low Risk'

# Print the updated DataFrame
print(df)

        Unnamed: 0  LOAN_TYPE  GENDER  OWN_CAR  OWN_HOUSE  CNT_CHILDREN  \
0                0          0       1        0          1             0
1                1          0       0        0          0             0
2                2          1       1        1          1             0
3                3          0       0        0          1             0
4                4          0       1        0          1             0
...            ...        ...     ...      ...        ...           ...
307506      307506          0       1        0          0             0
307507      307507          0       0        0          1             0
307508      307508          0       0        0          1             0
307509      307509          0       0        0          1             0
307510      307510          0       0        0          0             0

        ANNUAL_INCOME  LOAN_AMOUNT  LOAN_ANNUITY  NAME_INCOME_TYPE  \
0            202500.0     406597.5       24700.5                 7
1            270000.0    1293502.5       35698.5                 4
2             67500.0     135000.0        6750.0                 7
3            135000.0     312682.5       29686.5                 7
4            121500.0     513000.0       21865.5                 7
...               ...          ...           ...               ...
307506       157500.0     254700.0       27558.0                 7
307507        72000.0     269550.0       12001.5                 3
307508       153000.0     677664.0       29979.0                 7
307509       171000.0     370107.0       20205.0                 1
307510       157500.0     675000.0       49117.5                 1

        NAME_EDUCATION_TYPE  MARITAL_STATUS  OCCUPATION  Age RISK_CATEGORY
0                         4               3           8   67      Low Risk
1                         1               1           3   65     High Risk
2                         4               3           8   22     High Risk
3                         4               0           8   40     High Risk
4                         4               3           3   22     High Risk
...                     ...             ...         ...  ...           ...
307506                    4               2          14   52      Low Risk
307507                    4               5          18   66      Low Risk
307508                    1               2          10   49     High Risk
307509                    4               1           8   48     High Risk
307510                    1               1           8   50     High Risk

[307511 rows x 15 columns]

In [ ]:
df

,Unnamed: 0,LOAN_TYPE,GENDER,OWN_CAR,OWN_HOUSE,CNT_CHILDREN,ANNUAL_INCOME,LOAN_AMOUNT,LOAN_ANNUITY,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,MARITAL_STATUS,OCCUPATION,Age,RISK_CATEGORY
0,0,0,1,0,1,0,202500.0,406597.5,24700.5,7,4,3,8,67,Low Risk
1,1,0,0,0,0,0,270000.0,1293502.5,35698.5,4,1,1,3,65,High Risk
2,2,1,1,1,1,0,67500.0,135000.0,6750.0,7,4,3,8,22,High Risk
3,3,0,0,0,1,0,135000.0,312682.5,29686.5,7,4,0,8,40,High Risk
4,4,0,1,0,1,0,121500.0,513000.0,21865.5,7,4,3,3,22,High Risk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,307506,0,1,0,0,0,157500.0,254700.0,27558.0,7,4,2,14,52,Low Risk
307507,307507,0,0,0,1,0,72000.0,269550.0,12001.5,3,4,5,18,66,Low Risk
307508,307508,0,0,0,1,0,153000.0,677664.0,29979.0,7,1,2,10,49,High Risk
307509,307509,0,0,0,1,0,171000.0,370107.0,20205.0,1,4,1,8,48,High Risk
307510,307510,0,0,0,0,0,157500.0,675000.0,49117.5,1,1,1,8,50,High Risk

In [ ]:
value_counts = df['RISK_CATEGORY'].value_counts()

In [ ]:
value_counts

High Risk    194977
Low Risk     112534
Name: RISK_CATEGORY, dtype: int64

In [ ]:
pip install eli5

Requirement already satisfied: eli5 in /usr/local/lib/python3.10/dist-packages (0.13.0)
Requirement already satisfied: attrs>17.1.0 in /usr/local/lib/python3.10/dist-packages (from eli5) (23.1.0)
Requirement already satisfied: jinja2>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from eli5) (3.1.2)
Requirement already satisfied: numpy>=1.9.0 in /usr/local/lib/python3.10/dist-packages (from eli5) (1.23.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from eli5) (1.10.1)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from eli5) (1.16.0)
Requirement already satisfied: scikit-learn>=0.20 in /usr/local/lib/python3.10/dist-packages (from eli5) (1.2.2)
Requirement already satisfied: graphviz in /usr/local/lib/python3.10/dist-packages (from eli5) (0.20.1)
Requirement already satisfied: tabulate>=0.7.7 in /usr/local/lib/python3.10/dist-packages (from eli5) (0.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2>=3.0.0->eli5) (2.1.3)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20->eli5) (1.3.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20->eli5) (3.2.0)

In [ ]:
df.to_csv('labelledData11Aug.csv')

In [ ]:




data =  pd.read_csv('labelledData11Aug.csv')# Replace 'your_dataset.csv' with the actual dataset fil

In [ ]:
data

,Unnamed: 0.1,Unnamed: 0,LOAN_TYPE,GENDER,OWN_CAR,OWN_HOUSE,CNT_CHILDREN,ANNUAL_INCOME,LOAN_AMOUNT,LOAN_ANNUITY,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,MARITAL_STATUS,OCCUPATION,Age,RISK_CATEGORY
0,0,0,0,1,0,1,0,202500.0,406597.5,24700.5,7,4,3,8,67,Low Risk
1,1,1,0,0,0,0,0,270000.0,1293502.5,35698.5,4,1,1,3,65,High Risk
2,2,2,1,1,1,1,0,67500.0,135000.0,6750.0,7,4,3,8,22,High Risk
3,3,3,0,0,0,1,0,135000.0,312682.5,29686.5,7,4,0,8,40,High Risk
4,4,4,0,1,0,1,0,121500.0,513000.0,21865.5,7,4,3,3,22,High Risk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,307506,307506,0,1,0,0,0,157500.0,254700.0,27558.0,7,4,2,14,52,Low Risk
307507,307507,307507,0,0,0,1,0,72000.0,269550.0,12001.5,3,4,5,18,66,Low Risk
307508,307508,307508,0,0,0,1,0,153000.0,677664.0,29979.0,7,1,2,10,49,High Risk
307509,307509,307509,0,0,0,1,0,171000.0,370107.0,20205.0,1,4,1,8,48,High Risk
307510,307510,307510,0,0,0,0,0,157500.0,675000.0,49117.5,1,1,1,8,50,High Risk

In [ ]:
data_without_nan = data.dropna()

# Save the cleaned data to a new CSV file
data_without_nan.to_csv('cleaned_data11AugLabel.csv', index=False)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd

# Load your dataset (replace this with your dataset)
data=pd.read_csv('cleaned_data11AugLabel.csv')

# Selecting features and target variable
X = data.drop('RISK_CATEGORY', axis=1)  # Features
y = data['RISK_CATEGORY']  # Target variable

# Splitting the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create and train the Random Forest model with hyperparameter tuning
rf_model = RandomForestClassifier(n_estimators=100, max_depth=20, min_samples_split=2, random_state=42)  # Adjust parameters
rf_model.fit(X_train, y_train)

# Make predictions using the Random Forest model
y_pred = rf_model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy of the Random Forest model: {accuracy:.2f}")

# Store predicted values in a new column
data['Predicted Risk Category'] = rf_model.predict(X)

# Save the DataFrame with predicted values to a new CSV file
data.to_csv('data_with_predictions.csv', index=False)

Accuracy of the Random Forest model: 1.00

In [ ]:
pip install eli5

Requirement already satisfied: eli5 in /usr/local/lib/python3.10/dist-packages (0.13.0)
Requirement already satisfied: attrs>17.1.0 in /usr/local/lib/python3.10/dist-packages (from eli5) (23.1.0)
Requirement already satisfied: jinja2>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from eli5) (3.1.2)
Requirement already satisfied: numpy>=1.9.0 in /usr/local/lib/python3.10/dist-packages (from eli5) (1.23.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from eli5) (1.10.1)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from eli5) (1.16.0)
Requirement already satisfied: scikit-learn>=0.20 in /usr/local/lib/python3.10/dist-packages (from eli5) (1.2.2)
Requirement already satisfied: graphviz in /usr/local/lib/python3.10/dist-packages (from eli5) (0.20.1)
Requirement already satisfied: tabulate>=0.7.7 in /usr/local/lib/python3.10/dist-packages (from eli5) (0.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2>=3.0.0->eli5) (2.1.3)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20->eli5) (1.3.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20->eli5) (3.2.0)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
import eli5  # For feature importance visualization

# Load and preprocess the dataset (replace with your data loading and preprocessing)
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a Decision Tree Classifier (you can choose other interpretable models)
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

# Predict using the trained model
y_pred = model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

# Generate feature importance using eli5 library
eli5.show_weights(model, feature_names=list(X_train.columns))

Accuracy: 1.00

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Load and preprocess the dataset (replace with your data loading and preprocessing)
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a Decision Tree Classifier (you can choose other interpretable models)
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

# Predict using the trained model
y_pred = model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

# Extract rules from the decision tree
def extract_rules(tree, feature_names, threshold, indent=0):
    rules = []

    for i, feature in enumerate(tree.feature):
        if feature == -2:  # Leaf node
            target = tree.value[i][0].argmax()
            rules.append(f"{'    ' * indent}Predict class: {target}")
        else:
            feature_name = feature_names[feature]
            left_tree = tree.children_left[i]
            right_tree = tree.children_right[i]
            if threshold is not None:
                if threshold[i] <= 0:
                    rules.append(f"{'    ' * indent}If {feature_name} <= {threshold[i]}:")
                else:
                    rules.append(f"{'    ' * indent}If {feature_name} > {threshold[i]}:")
            rules.extend(extract_rules(tree, feature_names, threshold, indent + 1))

    return rules

tree_rules = extract_rules(model.tree_, feature_names=list(X_train.columns), threshold=model.tree_.threshold)

# Print the explanation as a user-understandable paragraph
print("Decision Tree Explanation:")
for rule in tree_rules:
    print(rule)

Accuracy: 1.00

RecursionError: ignored

In [ ]:
import joblib
joblib.dump(model, 'explainableAi.pkl')

['explainableAi.pkl']

In [ ]:
pip install lime

Collecting lime
  Downloading lime-0.2.0.1.tar.gz (275 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 275.7/275.7 kB 4.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from lime) (3.7.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from lime) (1.23.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from lime) (1.10.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from lime) (4.65.0)
Requirement already satisfied: scikit-learn>=0.18 in /usr/local/lib/python3.10/dist-packages (from lime) (1.2.2)
Requirement already satisfied: scikit-image>=0.12 in /usr/local/lib/python3.10/dist-packages (from lime) (0.19.3)
Requirement already satisfied: networkx>=2.2 in /usr/local/lib/python3.10/dist-packages (from scikit-image>=0.12->lime) (3.1)
Requirement already satisfied: pillow!=7.1.0,!=7.1.1,!=8.3.0,>=6.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-image>=0.12->lime) (9.4.0)
Requirement already satisfied: imageio>=2.4.1 in /usr/local/lib/python3.10/dist-packages (from scikit-image>=0.12->lime) (2.25.1)
Requirement already satisfied: tifffile>=2019.7.26 in /usr/local/lib/python3.10/dist-packages (from scikit-image>=0.12->lime) (2023.7.18)
Requirement already satisfied: PyWavelets>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-image>=0.12->lime) (1.4.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from scikit-image>=0.12->lime) (23.1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.18->lime) (1.3.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.18->lime) (3.2.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->lime) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->lime) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->lime) (4.42.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->lime) (1.4.4)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->lime) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib->lime) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib->lime) (1.16.0)
Building wheels for collected packages: lime
  Building wheel for lime (setup.py) ... done
  Created wheel for lime: filename=lime-0.2.0.1-py3-none-any.whl size=283838 sha256=0c31546c82feef896c5541b358bb9ab95ab820f6382ce07d8052e05cec10d881
  Stored in directory: /root/.cache/pip/wheels/fd/a2/af/9ac0a1a85a27f314a06b39e1f492bee1547d52549a4606ed89
Successfully built lime
Installing collected packages: lime
Successfully installed lime-0.2.0.1

In [ ]:
# Mapping of target labels to numerical values
label_mapping = {'Low Risk': 0, 'Medium Risk': 1, 'High Risk': 2}

# Add a new column with numerical values based on "Risk_Category"
data['Risk_Category_Num'] = data['RISK_CATEGORY'].map(label_mapping)

# Print the updated DataFrame
print(data)

        Unnamed: 0.1  Unnamed: 0  LOAN_TYPE  GENDER  OWN_CAR  OWN_HOUSE  \
0                  0           0          0       1        0          1
1                  1           1          0       0        0          0
2                  2           2          1       1        1          1
3                  3           3          0       0        0          1
4                  4           4          0       1        0          1
...              ...         ...        ...     ...      ...        ...
307494        307506      307506          0       1        0          0
307495        307507      307507          0       0        0          1
307496        307508      307508          0       0        0          1
307497        307509      307509          0       0        0          1
307498        307510      307510          0       0        0          0

        CNT_CHILDREN  ANNUAL_INCOME  LOAN_AMOUNT  LOAN_ANNUITY  \
0                  0       202500.0     406597.5       24700.5
1                  0       270000.0    1293502.5       35698.5
2                  0        67500.0     135000.0        6750.0
3                  0       135000.0     312682.5       29686.5
4                  0       121500.0     513000.0       21865.5
...              ...            ...          ...           ...
307494             0       157500.0     254700.0       27558.0
307495             0        72000.0     269550.0       12001.5
307496             0       153000.0     677664.0       29979.0
307497             0       171000.0     370107.0       20205.0
307498             0       157500.0     675000.0       49117.5

        NAME_INCOME_TYPE  NAME_EDUCATION_TYPE  MARITAL_STATUS  OCCUPATION  \
0                      7                    4               3           8
1                      4                    1               1           3
2                      7                    4               3           8
3                      7                    4               0           8
4                      7                    4               3           3
...                  ...                  ...             ...         ...
307494                 7                    4               2          14
307495                 3                    4               5          18
307496                 7                    1               2          10
307497                 1                    4               1           8
307498                 1                    1               1           8

        Age RISK_CATEGORY Predicted Risk Category  Risk_Category_Num
0        67      Low Risk                Low Risk                  0
1        65     High Risk               High Risk                  2
2        22     High Risk               High Risk                  2
3        40     High Risk               High Risk                  2
4        22     High Risk               High Risk                  2
...     ...           ...                     ...                ...
307494   52      Low Risk                Low Risk                  0
307495   66      Low Risk                Low Risk                  0
307496   49     High Risk               High Risk                  2
307497   48     High Risk               High Risk                  2
307498   50     High Risk               High Risk                  2

[307499 rows x 18 columns]

In [ ]:
data

,Unnamed: 0.1,Unnamed: 0,LOAN_TYPE,GENDER,OWN_CAR,OWN_HOUSE,CNT_CHILDREN,ANNUAL_INCOME,LOAN_AMOUNT,LOAN_ANNUITY,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,MARITAL_STATUS,OCCUPATION,Age,RISK_CATEGORY,Predicted Risk Category,Risk_Category_Num
0,0,0,0,1,0,1,0,202500.0,406597.5,24700.5,7,4,3,8,67,Low Risk,Low Risk,0
1,1,1,0,0,0,0,0,270000.0,1293502.5,35698.5,4,1,1,3,65,High Risk,High Risk,2
2,2,2,1,1,1,1,0,67500.0,135000.0,6750.0,7,4,3,8,22,High Risk,High Risk,2
3,3,3,0,0,0,1,0,135000.0,312682.5,29686.5,7,4,0,8,40,High Risk,High Risk,2
4,4,4,0,1,0,1,0,121500.0,513000.0,21865.5,7,4,3,3,22,High Risk,High Risk,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307494,307506,307506,0,1,0,0,0,157500.0,254700.0,27558.0,7,4,2,14,52,Low Risk,Low Risk,0
307495,307507,307507,0,0,0,1,0,72000.0,269550.0,12001.5,3,4,5,18,66,Low Risk,Low Risk,0
307496,307508,307508,0,0,0,1,0,153000.0,677664.0,29979.0,7,1,2,10,49,High Risk,High Risk,2
307497,307509,307509,0,0,0,1,0,171000.0,370107.0,20205.0,1,4,1,8,48,High Risk,High Risk,2
307498,307510,307510,0,0,0,0,0,157500.0,675000.0,49117.5,1,1,1,8,50,High Risk,High Risk,2

In [ ]:
data.to_csv('final.csv')

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import lime
import lime.lime_tabular
import pandas as pd

# Load your dataset (replace this with your dataset)
data = pd.read_csv('final.csv')  # Replace 'your_dataset.csv' with the actual dataset file

# Selecting features and target variable
X = data.drop({'Risk_Category_Num','RISK_CATEGORY','Predicted Risk Category'}, axis=1)  # Features
y = data['Risk_Category_Num']  # Target variable

# Splitting the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create and train the Random Forest model with hyperparameter tuning
rf_model = RandomForestClassifier(n_estimators=100, max_depth=10, min_samples_split=2, random_state=42)  # Adjust parameters
rf_model.fit(X_train, y_train)

# Select a specific instance for explanation (replace this with your instance)
instance_to_explain = X_test.iloc[0]

# Create a LIME explainer
explainer = lime.lime_tabular.LimeTabularExplainer(X_train.values, mode="classification")

# Explain the prediction
explanation = explainer.explain_instance(instance_to_explain, rf_model.predict_proba)

# Print explanation
print("Explanation for the prediction:")
print(explanation.as_list())

In [ ]:
# Explanation for the prediction
explanation_list = explanation.as_list()

# Explanation mapping for user-friendly interpretation
def map_explanation(feature, weight):
    if "<=" in feature:
        threshold, condition = feature.split(" <= ")
        return f"The value of {condition} is less than or equal to {threshold}, which has an influence of {weight:.2f} on the prediction."
    elif "<" in feature:
        threshold, condition = feature.split(" < ")
        return f"The value of {condition} is less than {threshold}, which has an influence of {weight:.2f} on the prediction."
    else:
        return f"Feature '{feature}' has an influence of {weight:.2f} on the prediction."

# Convert explanation to user-friendly paragraph
explanation_paragraph = "The model's prediction is based on various attributes from the provided data. Here are some factors that influenced the prediction:\n\n"
for feature, weight in explanation_list:
    explanation_paragraph += map_explanation(feature, weight) + "\n"

# Print user-friendly explanation
print(explanation_paragraph)

In [ ]:
data

In [ ]:
joblib.dump(model, 'explainableAiWIthExplanation.pkl')