# API를 받아와서 전처리하는 코드

확인 시 clone후 read_csv 통해서 확인하면 바로 가능함.

코드 실행시키면 api 키 값도 없어서 진행도 안될뿐더러, csv를 새로 만들기 때문에 확인불가

In [1]:
import requests 
import json
import pandas as pd
import numpy as np
import matplotlib as mlp
import matplotlib.pyplot as plt
import seaborn as sns
import time
import pickle

In [2]:
api_key = ''
current_version = requests.get('https://ddragon.leagueoflegends.com/api/versions.json').json()[0]
current_version

'10.24.1'

In [3]:
# 챔피언 종류 받아와서 아이디, key 따로 저장하기

# 이미 실행되어 파일로 저장되어 있음, 재 실행 금지 (line값 수작업으로 넣었음)

# champion_dict = {}
# r = requests.get('http://ddragon.leagueoflegends.com/cdn/{}/data/ko_KR/champion.json'.format(current_version))
# info_df = pd.DataFrame(r.json())
# for i, champ in enumerate(info_df.data):
#     champion_dict[champ['id']] = champ['key']
    
# champion = pd.DataFrame()
# champion['id'] = 0
# champion['key'] = 0

# for i, champ in enumerate(info_df.data):
#     champion.loc[i] = [champ['id'], champ['key']]
    
# champion.to_csv('../data/champion.csv')

In [7]:
champion = pd.read_csv('../../data/champion.csv', index_col=[0])

In [8]:
champion.head()

        id  key  line
0   Aatrox  266     0
1     Ahri  103     2
2    Akali   84     2
3  Alistar   12     4
4    Amumu   32     1

In [ ]:
# 챌~그랜드마스터 구간 유저 1000명 값 불러와서 dataframe으로 만들고 필요없는 컬럼들 제거하기
# 라이엇게임즈 API 제공 데이터 제한으로 인해 챌-그랜드마스터로 우선 진행 후 데이터 추가적으로 필요할 시 더 받을 예정

# 이미 실행되어 파일로 저장되어 있음

# api_challenger = 'https://kr.api.riotgames.com/lol/league/v4/challengerleagues/by-queue/RANKED_SOLO_5x5?api_key=' + api_key
# api_grandmaster = 'https://kr.api.riotgames.com/lol/league/v4/grandmasterleagues/by-queue/RANKED_SOLO_5x5?api_key=' + api_key

# cgm_userData = pd.DataFrame(requests.get(api_challenger).json())
# r = requests.get(api_grandmaster)
# cgm_userData = pd.concat([cgm_userData, pd.DataFrame(r.json())], axis=0)

# cgm_userData.reset_index(inplace=True)
# league_entries_df = pd.DataFrame(dict(cgm_userData['entries'])).T
# cgm_userData = pd.concat([cgm_userData, league_entries_df], axis=1)
# cgm_userData = cgm_userData.drop(['index', 'queue', 'name', 'leagueId', 'entries', 'rank', 'freshBlood', 'hotStreak', 'inactive', 'veteran', 'wins', 'losses'], axis=1)

# cgm_userData['account_id'] = np.nan
# for i, summoner_id in enumerate(cgm_userData[:]['summonerId']):
#     api_url = 'https://kr.api.riotgames.com/lol/summoner/v4/summoners/' + summoner_id + '?api_key=' + api_key
#     r = requests.get(api_url)
#     while r.status_code!=200:
#         time.sleep(5)
#         r = requests.get(api_url)
#     account_id = r.json()['accountId']
#     cgm_userData.iloc[i, -1] = account_id

In [ ]:
# accountID로 순서대로 1계정당 100개씩 전적 불러오기

# 이미 실행되어 파일로 저장되어 있음

# season = str(13)
# queue = str(420)
# cgm_gameidInfo = pd.DataFrame()

# i = 0
# for account_id in cgm_userData[:]['account_id']:
#     api_url = 'https://kr.api.riotgames.com/lol/match/v4/matchlists/by-account/' + account_id + \
#                   '?queue=' + queue + '&season' + season + '&api_key=' + api_key
#     r = requests.get(api_url)
#     while r.status_code!=200:
#         time.sleep(5)
#         r = requests.get(api_url)
#     cgm_gameidInfo = pd.concat([cgm_gameidInfo, pd.DataFrame(r.json()['matches'])])
#     most = cgm_gameidInfo['champion'][i * 100:(i + 1) * 100].value_counts(sort=True).index[0]
#     cgm_userData['most_champion'][i] = most
#     i += 1

# cgm_userData.to_csv('../data/cgm_userData.csv')

# gameID가 겹치면 삭제. 상위티어이기 때문에 약 60%가량 발생 100000 -> 40812

# cgm_gameidInfo = cgm_gameidInfo.drop_duplicates('gameId')

# 재 실행하면 밑 2줄은 필요 없음
# select_indices = (cgm_gameidInfo['queue']==420) | (cgm_gameidInfo['queue']==440)
# cgm_gameidInfo = cgm_gameidInfo.loc[select_indices, :].reset_index(drop=True)
# cgm_gameidInfo.to_csv('../data/cgm_gameidInfo.csv')

In [10]:
cgm_userData = pd.read_csv('../../data/cgm_userData.csv', index_col=[0])

In [11]:
cgm_userData.head()

,tier,leaguePoints,summonerId,summonerName,account_id,most_champion
0,CHALLENGER,870,tHccq6Ajss5Je1pjcq47uMA-cYIAlgF3BvfZn2K_It_lyw,Interlude 2020,pv0TVyiyxKGLhG_BS3p8C4e7VCfeFnW4VKu_OdUtIO0n,105
1,CHALLENGER,1000,e2lk9X_WbJrwPk1C6LXnx48wDidQkctAxS0Ypa2W7SCxFAk,뷔스타,nTWkNKvrJhWBn2cHasUG-75laAOfA0tQfGJcKIbR3rOMTXw,80
2,CHALLENGER,855,sMFMTjmq8k8y2xAt4JMclw48H6kwxmOm0rwfU5_wh2VeguQ,da gong ren1,Sq4EPo-nQR6y-PJVyxAYSKvXjRiOFiLFwE65vkBSEd2H1Qo,80
3,CHALLENGER,912,AiTXlpKlG-rJeQ5iPzokceDykbPij8ujYvVZ1coryil5DB0U,Normal JG,_x0AIk0bvt3XLTp_UNKzERLg402jfk6mDAYzNwmBJCnBD1...,876
4,CHALLENGER,988,rI5bTcVLU1xUhILn55rSJJuVbDHUNet2l5S8vnqrBEUY8Q,DRX 게르세르끼,9CZB0svSmKPWTRuS8rD_Fedq0Cdo4SWUo5pTtMhwYxps,202

In [12]:
cgm_gameidInfo = pd.read_csv('../../data/cgm_gameidInfo.csv', index_col=[0])

In [13]:
cgm_gameidInfo.head()

,champion,gameId,lane,platformId,queue,role,season,timestamp
0,875,4771375338,NONE,KR,420,DUO_SUPPORT,13,1604844366180
1,875,4770146326,TOP,KR,420,DUO,13,1604818960847
2,875,4767376134,NONE,KR,420,DUO_SUPPORT,13,1604733123324
3,246,4767361959,MID,KR,420,SOLO,13,1604729191092
4,202,4761504494,NONE,KR,420,DUO_SUPPORT,13,1604485121523

In [ ]:
# 위에서 얻어낸 게임ID를 약 4만개의 실제 게임데이터를 받아옴
# 이미 실행되어 파일로 저장되어 있음

# cgm_match = pd.DataFrame()
# for game_id in cgm_gameidInfo[:]['gameId']:
#     api_url = 'https://kr.api.riotgames.com/lol/match/v4/matches/' + str(game_id) + '?api_key=' + api_key
#     r = requests.get(api_url)
#     while r.status_code!=200:
#         time.sleep(5)
#         r = requests.get(api_url)
#     r_json = r.json()
#     temp_df = pd.DataFrame(list(r_json.values()), index=list(r_json.keys())).T
#     cgm_match = pd.concat([cgm_match, temp_df])

# cgm_match.to_csv('../data/cgm_match.csv')

In [20]:
cgm_gameidInfo2 = pd.read_csv('../../data/cgm_gameidInfo2.csv')

        Unnamed: 0  Unnamed: 0.1        gameId
0                0             0  4.247263e+09
1                1             1  4.247156e+09
2                2             2  4.243963e+09
3                3             3  4.241678e+09
4                4             4  4.241539e+09
5                5             5  4.241394e+09
6                6             6  4.233222e+09
7                7             7  4.233114e+09
8                8             8  4.231101e+09
9                9             9  4.229230e+09
10              10            10  4.229039e+09
11              11            11  4.228953e+09
12              12            12  4.228245e+09
13              13            13  4.227124e+09
14              14            14  4.222796e+09
15              15            15  4.222632e+09
16              16            16  4.219737e+09
17              17            17  4.219648e+09
18              18            18  4.219546e+09
19              19            19  4.219464e+09
20              20            20  4.217069e+09
21              21            21  4.216998e+09
22              22            22  4.214820e+09
23              23            23  4.208036e+09
24              24            24  4.205806e+09
25              25            25  4.205778e+09
26              26            26  4.205718e+09
27              27            27  4.205609e+09
28              28            28  4.201063e+09
29              29            29  4.201003e+09
...            ...           ...           ...
108743      108799        108799  4.123100e+09
108744      108800        108800  4.130964e+09
108745      108801        108801  3.961619e+09
108746      108802        108802  4.082206e+09
108747      108803        108803  4.092167e+09
108748      108804        108804  4.035020e+09
108749      108805        108805  4.222191e+09
108750      108806        108806  4.026631e+09
108751      108807        108807  4.155082e+09
108752      108808        108808  4.025583e+09
108753      108809        108809  4.090594e+09
108754      108810        108810  3.929114e+09
108755      108811        108811  4.192830e+09
108756      108812        108812  4.003038e+09
108757      108813        108813  3.969484e+09
108758      108814        108814  4.163470e+09
108759      108815        108815  4.213802e+09
108760      108816        108816  4.048127e+09
108761      108817        108817  4.222191e+09
108762      108818        108818  4.061758e+09
108763      108819        108819  4.039738e+09
108764      108820        108820  4.170286e+09
108765      108821        108821  4.136207e+09
108766      108822        108822  4.177102e+09
108767      108823        108823  4.211705e+09
108768      108824        108824  4.088497e+09
108769      108825        108825  4.130964e+09
108770      108826        108826  4.119954e+09
108771      108827        108827  4.130440e+09
108772      108828        108828  4.225861e+09

[108773 rows x 3 columns]

In [19]:
cgm_match2 = pd.DataFrame()

In [ ]:
# # 따로 얻어온 gameID 약 8만개의 실제 게임데이터를 받아옴 59211

# for game_id in cgm_gameidInfo2[:]['gameId']:
#     api_url = 'https://kr.api.riotgames.com/lol/match/v4/matches/' + str(int(game_id)) + '?api_key=' + api_key
#     r = requests.get(api_url)
#     while r.status_code!=200:
#         time.sleep(5)
#         r = requests.get(api_url)
#     r_json = r.json()
#     temp_df = pd.DataFrame(list(r_json.values()), index=list(r_json.keys())).T
#     cgm_match2 = pd.concat([cgm_match2, temp_df])

In [21]:
cgm_match1 = pd.read_csv('../../data/cgm_match1.csv', index_col=[0])
cgm_match1.head()

,gameId,platformId,gameCreation,gameDuration,queueId,mapId,seasonId,gameVersion,gameMode,gameType,teams,participants,participantIdentities
0,4771375338,KR,1604844366180,1075,420,11,13,10.22.341.643,CLASSIC,MATCHED_GAME,"[{'teamId': 100, 'win': 'Win', 'firstBlood': T...","[{'participantId': 1, 'teamId': 100, 'champion...","[{'participantId': 1, 'player': {'platformId':..."
1,4770146326,KR,1604818960847,1606,420,11,13,10.22.341.643,CLASSIC,MATCHED_GAME,"[{'teamId': 100, 'win': 'Fail', 'firstBlood': ...","[{'participantId': 1, 'teamId': 100, 'champion...","[{'participantId': 1, 'player': {'platformId':..."
2,4767376134,KR,1604733123324,1069,420,11,13,10.22.341.643,CLASSIC,MATCHED_GAME,"[{'teamId': 100, 'win': 'Win', 'firstBlood': T...","[{'participantId': 1, 'teamId': 100, 'champion...","[{'participantId': 1, 'player': {'platformId':..."
3,4767361959,KR,1604729191092,1890,420,11,13,10.22.341.643,CLASSIC,MATCHED_GAME,"[{'teamId': 100, 'win': 'Win', 'firstBlood': F...","[{'participantId': 1, 'teamId': 100, 'champion...","[{'participantId': 1, 'player': {'platformId':..."
4,4761504494,KR,1604485121523,925,420,11,13,10.22.341.643,CLASSIC,MATCHED_GAME,"[{'teamId': 100, 'win': 'Fail', 'firstBlood': ...","[{'participantId': 1, 'teamId': 100, 'champion...","[{'participantId': 1, 'player': {'platformId':..."

In [ ]:
cgm_match2 = pd.read_csv('../data/cgm_match2.csv', index_col=[0])

In [ ]:
# match_df에 3가지 team, participants, participantIdentities들이 문자열로 받아지는 현상 방지

for column in ['teams', 'participants', 'participantIdentities']:
    cgm_match1[column] = cgm_match1[column].map(lambda v: eval(v))
    cgm_match2[column] = cgm_match2[column].map(lambda v: eval(v))

In [22]:
cgm_match1.head()

,gameId,platformId,gameCreation,gameDuration,queueId,mapId,seasonId,gameVersion,gameMode,gameType,teams,participants,participantIdentities
0,4771375338,KR,1604844366180,1075,420,11,13,10.22.341.643,CLASSIC,MATCHED_GAME,"[{'teamId': 100, 'win': 'Win', 'firstBlood': T...","[{'participantId': 1, 'teamId': 100, 'champion...","[{'participantId': 1, 'player': {'platformId':..."
1,4770146326,KR,1604818960847,1606,420,11,13,10.22.341.643,CLASSIC,MATCHED_GAME,"[{'teamId': 100, 'win': 'Fail', 'firstBlood': ...","[{'participantId': 1, 'teamId': 100, 'champion...","[{'participantId': 1, 'player': {'platformId':..."
2,4767376134,KR,1604733123324,1069,420,11,13,10.22.341.643,CLASSIC,MATCHED_GAME,"[{'teamId': 100, 'win': 'Win', 'firstBlood': T...","[{'participantId': 1, 'teamId': 100, 'champion...","[{'participantId': 1, 'player': {'platformId':..."
3,4767361959,KR,1604729191092,1890,420,11,13,10.22.341.643,CLASSIC,MATCHED_GAME,"[{'teamId': 100, 'win': 'Win', 'firstBlood': F...","[{'participantId': 1, 'teamId': 100, 'champion...","[{'participantId': 1, 'player': {'platformId':..."
4,4761504494,KR,1604485121523,925,420,11,13,10.22.341.643,CLASSIC,MATCHED_GAME,"[{'teamId': 100, 'win': 'Fail', 'firstBlood': ...","[{'participantId': 1, 'teamId': 100, 'champion...","[{'participantId': 1, 'player': {'platformId':..."

In [ ]:
cgm_match2.head()

In [ ]:
# 밴 리스트

In [ ]:
# numberWinsChampion = {}
# numberWinsCombination = {}
# numberLosesCombination = {}

# for a in champion_df['key']:
#     list = {}
#     for b in champion_df['key']:
#         if (a == b):
#             continue;
#         list[b] = 0
#     numberWinsChampion[a] = list
    
# for a in champion_df['key']:
#     list = {}
#     for b in champion_df['key']:
#         if (a == b):
#             continue;
#         list[b] = 0
#     numberWinsCombination[a] = list
    
# for a in champion_df['key']:
#     list = {}
#     for b in champion_df['key']:
#         if (a == b):
#             continue;
#         list[b] = 0
#     numberLosesCombination[a] = list

In [ ]:
# 게임데이터에서 챔피언 10개의 key값과, 해당 유저 accountID 정보 등 불러오기.
# cgm_match1, cgm_match2를 각각 넣고 실행시켜준다

# for i in range(len(cgm_match1[:])):
#     champion_list = []
#     for _ in range(10):
#         탑 0, 5 정글 1, 6 미드 2, 7 원딜 3, 8 서폿 4, 9로 맞추기 위한 작업필요
#         0~4, 5~9는 이긴 팀이 앞쪽으로 맞추기
#         lane = match_df['participants'][i][_]['timeline']['lane']
#         accountId = match_df['participantIdentities'][i][_]['player']['accountId']
#         championNum = cgm_match1['participants'][i][_]['championId']
#         champion_list.append(championNum)
#     if (cgm_match1['participants'][i][9]['stats']['win']):
#         champion_list = champion_list[5:] + champion_list[:5]
#     for _ in range(5):
#         numberWinsChampion[champion_list[_]][champion_list[_ + 5]] += 1
#     numberWinsCombination[champion_list[0]][champion_list[1]] += 1
#     numberWinsCombination[champion_list[1]][champion_list[0]] = numberWinsCombination[champion_list[0]][champion_list[1]]
#     numberWinsCombination[champion_list[1]][champion_list[2]] += 1
#     numberWinsCombination[champion_list[2]][champion_list[1]] = numberWinsCombination[champion_list[1]][champion_list[2]]
#     numberWinsCombination[champion_list[3]][champion_list[4]] += 1
#     numberWinsCombination[champion_list[4]][champion_list[3]] = numberWinsCombination[champion_list[3]][champion_list[4]]
#     numberLosesCombination[champion_list[5]][champion_list[6]] += 1
#     numberLosesCombination[champion_list[6]][champion_list[5]] = numberLosesCombination[champion_list[5]][champion_list[6]]
#     numberLosesCombination[champion_list[6]][champion_list[7]] += 1
#     numberLosesCombination[champion_list[7]][champion_list[6]] = numberLosesCombination[champion_list[6]][champion_list[7]]
#     numberLosesCombination[champion_list[8]][champion_list[9]] += 1
#     numberLosesCombination[champion_list[9]][champion_list[8]] = numberLosesCombination[champion_list[8]][champion_list[9]]

In [ ]:
# with open('../data/numberWinsChampion.pickle','wb') as fw:
#     pickle.dump(numberWinsChampion, fw)

In [ ]:
# with open('../data/numberWinsCombination.pickle','wb') as fw:
#     pickle.dump(numberWinsCombination, fw)

In [ ]:
# with open('../data/numberLosesCombination.pickle','wb') as fw:
#     pickle.dump(numberLosesCombination, fw)

### 동일한 챔피언인 경우의 NaN값을 -1로 바꿔줌 
### 랭크게임에서 동일한 챔피언은 선택 불가이기 때문에 -1가 152개 나와야 정상

In [2]:
with open('../data/numberWinsChampion.pickle', 'rb') as fr:
    numberWinsChampion = pickle.load(fr)
numberWinsChampion = pd.DataFrame(numberWinsChampion)
numberWinsChampion.fillna(-1, inplace=True)
numberWinsChampion.head()

,266,103,84,12,32,34,1,523,22,136,...,157,777,83,350,154,238,115,26,142,143
103,12,-1,6,6,0,1,0,19,5,0,...,8,1,0,6,7,9,2,4,18,0
84,24,10,-1,51,1,2,2,66,74,6,...,40,44,2,17,13,19,4,4,52,1
12,24,16,36,-1,0,3,2,47,41,2,...,14,14,0,17,6,14,1,8,38,4
32,0,0,1,1,-1,0,0,6,0,0,...,0,0,0,0,0,0,1,0,2,0
34,3,5,4,2,0,-1,0,7,5,0,...,3,3,0,1,1,2,1,1,2,0

In [8]:
with open('../../data/pickle/numberWinsCombination.pickle', 'rb') as fr:
    numberWinsCombination = pickle.load(fr)
numberWinsCombination = pd.DataFrame(numberWinsCombination)
numberWinsCombination.fillna(-1, inplace=True)
numberWinsCombination.head(30)

,266,103,84,12,32,34,1,523,22,136,...,157,777,83,350,154,238,115,26,142,143
1,1.0,0.0,2.0,1.0,0.0,0.0,-1.0,3.0,4.0,0.0,...,0.0,0.0,0.0,2.0,0.0,0.0,0.0,1.0,0.0,2.0
2,45.0,7.0,30.0,14.0,0.0,6.0,0.0,89.0,23.0,8.0,...,16.0,2.0,2.0,45.0,8.0,9.0,6.0,18.0,142.0,1.0
3,20.0,0.0,34.0,51.0,0.0,0.0,1.0,78.0,65.0,3.0,...,19.0,4.0,0.0,8.0,17.0,3.0,5.0,4.0,6.0,4.0
4,38.0,0.0,20.0,34.0,1.0,0.0,1.0,76.0,52.0,0.0,...,7.0,0.0,2.0,15.0,13.0,1.0,1.0,8.0,0.0,5.0
5,9.0,6.0,49.0,10.0,0.0,3.0,0.0,20.0,16.0,1.0,...,5.0,3.0,0.0,7.0,2.0,2.0,1.0,3.0,36.0,0.0
6,0.0,0.0,2.0,8.0,1.0,0.0,2.0,13.0,6.0,2.0,...,1.0,4.0,0.0,2.0,3.0,0.0,1.0,2.0,15.0,1.0
7,59.0,0.0,10.0,21.0,0.0,0.0,0.0,75.0,23.0,0.0,...,7.0,0.0,0.0,29.0,14.0,0.0,6.0,18.0,0.0,2.0
8,17.0,3.0,10.0,28.0,1.0,1.0,1.0,80.0,33.0,0.0,...,31.0,10.0,0.0,34.0,11.0,23.0,2.0,5.0,21.0,3.0
9,17.0,4.0,9.0,2.0,0.0,1.0,2.0,31.0,12.0,1.0,...,15.0,11.0,2.0,2.0,25.0,3.0,2.0,1.0,14.0,2.0
10,5.0,1.0,3.0,6.0,0.0,1.0,3.0,15.0,8.0,1.0,...,5.0,1.0,0.0,7.0,1.0,3.0,3.0,3.0,6.0,0.0
11,5.0,0.0,1.0,1.0,0.0,1.0,0.0,8.0,4.0,0.0,...,3.0,0.0,0.0,4.0,0.0,2.0,2.0,5.0,1.0,0.0
12,36.0,10.0,62.0,-1.0,3.0,4.0,1.0,73.0,60.0,6.0,...,83.0,31.0,0.0,0.0,14.0,22.0,2.0,5.0,63.0,0.0
13,2.0,0.0,4.0,8.0,0.0,0.0,0.0,22.0,6.0,2.0,...,5.0,1.0,0.0,3.0,5.0,4.0,0.0,4.0,7.0,1.0
14,1.0,0.0,1.0,1.0,0.0,1.0,1.0,5.0,6.0,0.0,...,3.0,1.0,1.0,3.0,0.0,0.0,1.0,0.0,3.0,0.0
15,4.0,2.0,9.0,3.0,0.0,1.0,0.0,0.0,0.0,0.0,...,2.0,0.0,0.0,31.0,1.0,3.0,0.0,12.0,11.0,1.0
16,16.0,3.0,8.0,2.0,0.0,1.0,1.0,40.0,24.0,4.0,...,12.0,4.0,1.0,1.0,4.0,6.0,3.0,2.0,27.0,0.0
17,1.0,0.0,1.0,1.0,1.0,0.0,1.0,4.0,3.0,0.0,...,1.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,4.0,0.0
18,10.0,2.0,5.0,10.0,0.0,0.0,3.0,3.0,3.0,0.0,...,3.0,2.0,0.0,11.0,4.0,5.0,0.0,3.0,19.0,2.0
19,20.0,1.0,4.0,1.0,0.0,1.0,0.0,7.0,4.0,0.0,...,1.0,1.0,0.0,3.0,0.0,8.0,1.0,11.0,4.0,1.0
20,17.0,5.0,12.0,13.0,0.0,1.0,0.0,22.0,21.0,5.0,...,17.0,8.0,0.0,10.0,8.0,8.0,2.0,7.0,14.0,0.0
21,158.0,36.0,81.0,115.0,1.0,11.0,8.0,1.0,3.0,15.0,...,61.0,25.0,1.0,98.0,55.0,49.0,8.0,47.0,156.0,11.0
22,45.0,11.0,102.0,60.0,3.0,6.0,4.0,0.0,-1.0,4.0,...,20.0,58.0,4.0,10.0,16.0,27.0,2.0,19.0,69.0,7.0
23,4.0,5.0,5.0,5.0,0.0,1.0,2.0,14.0,10.0,2.0,...,11.0,2.0,0.0,7.0,5.0,7.0,0.0,4.0,14.0,0.0
24,8.0,18.0,56.0,54.0,2.0,5.0,6.0,122.0,86.0,13.0,...,30.0,23.0,0.0,36.0,20.0,28.0,9.0,12.0,76.0,5.0
25,31.0,5.0,17.0,0.0,0.0,2.0,0.0,81.0,27.0,4.0,...,8.0,4.0,1.0,0.0,6.0,14.0,6.0,2.0,38.0,0.0
26,19.0,5.0,8.0,5.0,0.0,2.0,1.0,28.0,19.0,2.0,...,11.0,0.0,0.0,5.0,10.0,4.0,2.0,-1.0,25.0,2.0
27,5.0,2.0,7.0,12.0,0.0,2.0,1.0,22.0,5.0,4.0,...,11.0,3.0,0.0,11.0,3.0,6.0,2.0,3.0,14.0,0.0
28,12.0,4.0,8.0,3.0,0.0,0.0,0.0,17.0,10.0,0.0,...,2.0,8.0,0.0,25.0,1.0,3.0,0.0,0.0,7.0,1.0
29,6.0,6.0,21.0,2.0,0.0,3.0,0.0,2.0,2.0,1.0,...,8.0,2.0,1.0,22.0,5.0,6.0,1.0,3.0,16.0,1.0
30,91.0,12.0,42.0,49.0,0.0,7.0,1.0,115.0,73.0,5.0,...,47.0,44.0,3.0,35.0,12.0,60.0,4.0,9.0,47.0,5.0

In [9]:
with open('../../data/pickle/numberLosesCombination.pickle', 'rb') as fr:
    numberLosesCombination = pickle.load(fr)
numberLosesCombination = pd.DataFrame(numberLosesCombination)
numberLosesCombination.fillna(-1, inplace=True)
numberLosesCombination.head(30)

,266,103,84,12,32,34,1,523,22,136,...,157,777,83,350,154,238,115,26,142,143
1,3.0,0.0,3.0,3.0,0.0,0.0,-1.0,3.0,1.0,0.0,...,0.0,0.0,0.0,5.0,1.0,2.0,1.0,1.0,3.0,0.0
2,45.0,11.0,46.0,9.0,2.0,5.0,1.0,68.0,30.0,7.0,...,10.0,2.0,0.0,67.0,15.0,10.0,9.0,19.0,124.0,2.0
3,24.0,4.0,38.0,33.0,0.0,2.0,0.0,78.0,52.0,0.0,...,18.0,7.0,1.0,16.0,27.0,6.0,4.0,7.0,12.0,6.0
4,39.0,0.0,17.0,39.0,0.0,1.0,1.0,52.0,55.0,0.0,...,9.0,2.0,2.0,14.0,15.0,0.0,3.0,10.0,0.0,12.0
5,7.0,8.0,51.0,12.0,0.0,2.0,2.0,20.0,21.0,1.0,...,5.0,2.0,0.0,7.0,4.0,1.0,2.0,6.0,46.0,0.0
6,1.0,4.0,7.0,7.0,0.0,0.0,0.0,10.0,9.0,1.0,...,5.0,3.0,0.0,5.0,0.0,5.0,0.0,1.0,5.0,1.0
7,62.0,0.0,17.0,28.0,1.0,1.0,1.0,85.0,36.0,0.0,...,10.0,1.0,2.0,45.0,23.0,2.0,3.0,9.0,1.0,4.0
8,18.0,0.0,16.0,24.0,0.0,0.0,3.0,74.0,36.0,3.0,...,27.0,12.0,0.0,34.0,24.0,17.0,2.0,9.0,15.0,2.0
9,10.0,3.0,12.0,6.0,0.0,1.0,2.0,34.0,11.0,1.0,...,10.0,11.0,0.0,7.0,28.0,9.0,1.0,1.0,16.0,1.0
10,5.0,3.0,2.0,0.0,0.0,1.0,0.0,21.0,9.0,1.0,...,7.0,0.0,0.0,6.0,4.0,4.0,0.0,4.0,11.0,1.0
11,7.0,1.0,4.0,1.0,0.0,0.0,1.0,6.0,0.0,1.0,...,2.0,3.0,0.0,3.0,1.0,1.0,0.0,1.0,2.0,2.0
12,24.0,7.0,52.0,-1.0,0.0,5.0,3.0,93.0,57.0,4.0,...,55.0,33.0,1.0,0.0,5.0,16.0,6.0,5.0,41.0,1.0
13,14.0,0.0,6.0,11.0,0.0,1.0,1.0,28.0,11.0,0.0,...,5.0,3.0,0.0,13.0,8.0,3.0,1.0,2.0,10.0,3.0
14,3.0,1.0,5.0,6.0,1.0,0.0,0.0,12.0,6.0,1.0,...,2.0,3.0,0.0,2.0,4.0,2.0,0.0,2.0,4.0,0.0
15,10.0,1.0,2.0,5.0,0.0,0.0,1.0,0.0,0.0,1.0,...,4.0,1.0,0.0,28.0,2.0,1.0,0.0,4.0,13.0,0.0
16,14.0,1.0,12.0,4.0,0.0,4.0,0.0,34.0,20.0,4.0,...,5.0,4.0,0.0,5.0,5.0,4.0,3.0,3.0,22.0,0.0
17,2.0,0.0,3.0,2.0,0.0,0.0,0.0,6.0,8.0,1.0,...,5.0,3.0,0.0,5.0,2.0,1.0,0.0,1.0,4.0,1.0
18,11.0,3.0,11.0,23.0,0.0,1.0,2.0,3.0,2.0,1.0,...,5.0,2.0,0.0,12.0,5.0,4.0,0.0,1.0,11.0,2.0
19,13.0,2.0,4.0,5.0,0.0,2.0,2.0,9.0,0.0,1.0,...,1.0,0.0,0.0,5.0,0.0,9.0,1.0,11.0,2.0,0.0
20,13.0,3.0,17.0,8.0,1.0,3.0,1.0,25.0,23.0,2.0,...,19.0,16.0,2.0,19.0,7.0,8.0,2.0,6.0,9.0,3.0
21,168.0,26.0,100.0,95.0,2.0,21.0,8.0,1.0,3.0,18.0,...,66.0,19.0,3.0,135.0,77.0,47.0,9.0,53.0,143.0,18.0
22,40.0,9.0,111.0,57.0,2.0,8.0,1.0,2.0,-1.0,10.0,...,17.0,35.0,1.0,13.0,22.0,21.0,1.0,11.0,79.0,8.0
23,3.0,2.0,7.0,7.0,2.0,2.0,1.0,29.0,8.0,4.0,...,8.0,1.0,1.0,12.0,6.0,3.0,3.0,5.0,15.0,2.0
24,6.0,18.0,52.0,59.0,3.0,8.0,3.0,110.0,86.0,10.0,...,52.0,33.0,0.0,43.0,24.0,20.0,10.0,14.0,94.0,7.0
25,50.0,2.0,30.0,1.0,1.0,3.0,2.0,77.0,27.0,6.0,...,17.0,7.0,0.0,2.0,17.0,15.0,6.0,4.0,42.0,1.0
26,17.0,4.0,6.0,5.0,2.0,1.0,1.0,40.0,11.0,1.0,...,12.0,2.0,1.0,6.0,7.0,6.0,2.0,-1.0,17.0,1.0
27,3.0,0.0,2.0,9.0,0.0,1.0,0.0,19.0,13.0,1.0,...,9.0,4.0,0.0,8.0,4.0,3.0,2.0,2.0,18.0,1.0
28,9.0,1.0,8.0,4.0,0.0,0.0,0.0,7.0,10.0,1.0,...,8.0,5.0,0.0,17.0,3.0,8.0,0.0,1.0,7.0,1.0
29,9.0,2.0,18.0,4.0,0.0,5.0,0.0,2.0,1.0,1.0,...,11.0,3.0,0.0,31.0,3.0,5.0,0.0,4.0,13.0,1.0
30,94.0,12.0,33.0,25.0,0.0,3.0,0.0,97.0,54.0,9.0,...,62.0,40.0,1.0,29.0,16.0,55.0,4.0,15.0,28.0,7.0

## 라인별 챔피언

In [6]:
champ = pd.read_csv("../../data/champion.csv", index_col=[0])
def select_line(line):
    line = champ.key[champ.line == line]
    line = pd.DataFrame(line)
    lst = []
    for row in line['key']:
        lst.append(row)
    return lst

top_list = select_line(0)
jungle_list = select_line(1)
mid_list = select_line(2)
ad_list = select_line(3)
sup_list = select_line(4)

In [4]:
with open('../../data/numberWinsChampion.pickle', 'rb') as fr:
    numberWinsChampion = pickle.load(fr)
    
top_df = pd.DataFrame({k :v for k, v in numberWinsChampion.items() if k in top_list})
jungle_df = pd.DataFrame({k :v for k, v in numberWinsChampion.items() if k in jungle_list})
mid_df = pd.DataFrame({k :v for k, v in numberWinsChampion.items() if k in mid_list})
ad_df = pd.DataFrame({k :v for k, v in numberWinsChampion.items() if k in ad_list})
sup_df = pd.DataFrame({k :v for k, v in numberWinsChampion.items() if k in sup_list})

FileNotFoundError: [Errno 2] No such file or directory: '../../data/numberWinsChampion.pickle'

In [8]:
with open('../data/numberWinsChampion.pickle', 'rb') as fr:
    numberWinsChampion = pickle.load(fr)
numberWinsChampion = pd.DataFrame(numberWinsChampion)
numberWinsChampion = numberWinsChampion.astype(int)
numberWinsChampion.head()

,266,103,84,12,32,34,1,523,22,136,...,157,777,83,350,154,238,115,26,142,143
1,1,1,1,1,0,0,-1,6,1,0,...,1,0,0,4,2,1,1,1,4,1
2,35,6,15,12,2,2,1,55,27,5,...,16,3,0,19,21,13,4,16,45,3
3,40,7,35,35,0,1,4,65,62,2,...,28,31,0,17,6,10,3,5,41,0
4,19,4,37,27,1,2,0,39,38,3,...,15,9,0,21,8,5,1,6,49,4
5,13,5,19,13,0,0,2,23,19,2,...,4,8,1,4,3,3,1,3,18,0