In [1]:
import pandas as pd
import numpy as np
import os
import datetime

In [3]:
#import training dataset
trat = pd.read_csv("ratios_data_table.csv")
print("\nNumber of stocks (rows):", len(trdt))
print("\nNumber of ratios (columns):", len(trdt.columns))

Number of stocks (rows): 1795

Number of ratios (columns): 18

In [24]:
trat.head

<bound method NDFrame.head of       Unnamed: 0  permno     bm   pe_exi    npm    cfm    roa    roe  GProf  \
0              0   10025  0.273   13.679  0.025  0.054  0.210  0.308  0.484
1              1   10026  0.303   31.279  0.072  0.111  0.205  0.112  0.456
2              2   10032  0.659   12.745  0.036  0.054  0.100  0.115  0.169
3              3   10051  0.981 -548.330 -0.001  0.037  0.058 -0.002  0.058
4              4   10104  0.297   17.070  0.250  0.326  0.164  0.198  0.298
...          ...     ...    ...      ...    ...    ...    ...    ...    ...
1790        1790   93423  0.095   45.783  0.096  0.217  0.159  0.292  0.260
1791        1791   93426  1.229  -34.303 -0.019  0.030  0.077 -0.022  0.345
1792        1792   93428  0.284 -392.890 -0.009  0.050  0.057 -0.010  0.409
1793        1793   93429  0.049   26.708  0.316  0.386  1.010  0.799  0.990
1794        1794   93436  0.040  -45.030 -0.178 -0.087 -0.031 -0.791  0.202

      totdebt_invcap  capital_ratio  debt_ebitda  lt_debt  cash_debt  fcf_ocf  \
0              0.710          0.702        2.296    0.602      0.201   0.8270
1              0.002          0.002        0.010    0.008      0.736   0.5240
2              0.239          0.235        1.588    0.301      0.089   0.5420
3              0.553          0.524        7.474    0.658      0.061   0.3730
4              0.443          0.427        2.221    0.635      0.232   0.8780
...              ...            ...          ...      ...        ...      ...
1790           0.718          0.900        3.557    0.726      0.209   0.7680
1791           0.102          0.062        0.963    0.160      0.270   0.3050
1792           0.342          0.342        4.661    0.466      0.243   0.7020
1793           0.000          0.000        0.000    0.000      1.963   0.8640
1794           0.876          0.659      -13.879    0.350     -0.012   0.3578

      de_ratio  at_turn     ptb
0        3.910    2.573   3.534
1        0.238    1.349   3.385
2        1.021    1.603   1.364
3        1.675    0.834   1.216
4        1.173    0.365   3.259
...        ...      ...     ...
1790    12.406    0.472  12.501
1791     0.416    0.847   0.733
1792     1.117    0.521   4.192
1793     0.549    1.698  19.610
1794     5.533    0.583  23.994

[1795 rows x 18 columns]>

In [4]:
#Impute the ratiosets
trat.fillna(trat.mean(), inplace=True)

In [5]:
trat.to_csv('imprat.csv')

In [13]:
perm=trat.iloc[:, 1]

In [14]:
perm

0       10025
1       10026
2       10032
3       10051
4       10104
        ...
1790    93423
1791    93426
1792    93428
1793    93429
1794    93436
Name: permno, Length: 1795, dtype: int64

In [17]:
List=pd.DataFrame(perm).to_numpy()

In [18]:
List

array([[10025],
       [10026],
       [10032],
       ...,
       [93428],
       [93429],
       [93436]])

In [19]:
List.shape

(1795, 1)

In [20]:
L=List.reshape(1795)

In [21]:
L

array([10025, 10026, 10032, ..., 93428, 93429, 93436])

In [25]:
#Consider dataset without permno
ratdt=trat.iloc[:, 1:]

In [27]:
print("\nNumber of stocks (rows):", len(ratdt))
print("\nNumber of ratios (columns):", len(ratdt.columns))

Number of stocks (rows): 1795

Number of ratios (columns): 17

In [28]:
#perform pca on ratios set
from sklearn.preprocessing import StandardScaler
y = StandardScaler().fit_transform(ratdt)

In [123]:
y

array([[-2.03350668e+00, -6.68271076e-01,  1.50048937e-02, ...,
         1.47601868e-02,  2.20981360e+00, -3.21684294e-02],
       [-2.03347072e+00, -6.04014713e-01,  2.58833016e-01, ...,
        -5.40525267e-02,  6.21611332e-01, -5.82574934e-02],
       [-2.03325497e+00,  1.58494120e-01,  2.06537859e-03, ...,
        -3.93792275e-02,  9.51189253e-01, -4.12123254e-01],
       ...,
       [ 9.65639721e-01, -6.44710410e-01, -5.61754941e+00, ...,
        -3.75802023e-02, -4.52760789e-01,  8.30436786e-02],
       [ 9.65675681e-01, -1.14805192e+00,  1.95506973e-01, ...,
        -4.82244346e-02,  1.07445659e+00,  2.78264897e+00],
       [ 9.65927399e-01, -1.16732882e+00, -7.98341994e-01, ...,
         4.51749564e-02, -3.72312635e-01,  3.55026277e+00]])

In [29]:
l=5
from sklearn.decomposition import PCA
pca = PCA(n_components=l)
principalComponents2 = pca.fit_transform(y)

In [43]:
Rrat= pd.DataFrame(data = principalComponents2
             ,columns = ['R'+str(i+1) for i in range (l)])

In [44]:
Rrat.head

<bound method NDFrame.head of             R1        R2        R3        R4        R5
0    -1.384094  1.385935  0.766891 -0.222239 -0.842197
1    -1.698006 -1.272806 -0.030781 -0.119481 -0.274844
2    -0.083062 -0.467590 -0.277913  0.268865 -0.290834
3     2.021754  0.841441 -0.885256  1.022509 -0.174030
4    -0.067969  0.685425  0.007250  0.518252 -0.247333
...        ...       ...       ...       ...       ...
1790 -0.205655  2.009651  0.988718 -0.295876  0.725069
1791  0.109654 -1.240439 -0.720380  0.273972 -0.358169
1792  0.524841  0.239720 -0.043644 -0.348751  0.600760
1793 -6.799577 -0.151529  1.725028 -0.249195 -0.879708
1794  0.693968  1.281694  1.287057 -2.521550  2.361002

[1795 rows x 5 columns]>

In [33]:
L

array([10025, 10026, 10032, ..., 93428, 93429, 93436])

In [48]:
RRprices = pd.read_csv("Reducedprice.csv")

In [59]:
RRprices.head()

,Unnamed: 0,PERMNO,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,0,10025.0,2.660520,2.943234,0.090046,-1.894355,5.060483,6.981604,3.945201,3.734542,-0.276868,1.422848,0.063031,2.932515,1.326075,-1.871535,0.153400
1,1,10026.0,20.929629,10.413003,-3.344149,6.045255,0.540976,2.694806,1.459398,-1.228156,0.965623,0.791613,-0.136641,0.480383,-0.124342,-0.387490,-0.293852
2,2,10032.0,-6.393924,1.332993,2.746831,2.774044,-1.996780,-1.663309,0.074506,1.714567,0.236020,1.796485,0.674637,-0.401746,-1.121315,1.102451,0.071502
3,3,10051.0,-16.796843,4.370821,4.198720,2.511052,1.794202,-0.668591,1.052303,-0.942642,-0.853217,-0.581849,0.243187,-0.459938,0.085672,-0.150270,0.916823
4,4,10104.0,-7.988193,3.467485,2.660182,2.926140,-0.925021,-0.537990,-0.509021,-0.302044,0.209060,0.445765,-0.318472,0.356342,0.595305,-0.577343,0.236509

In [120]:
len(RRprices.T)

17

In [52]:
le=len(RRprices)

In [61]:
index=RRprices.iloc[:, 1]

In [62]:
index

0       10025.0
1       10026.0
2       10032.0
3       10051.0
4       10104.0
         ...
2055    93423.0
2056    93426.0
2057    93428.0
2058    93429.0
2059    93436.0
Name: PERMNO, Length: 2060, dtype: float64

In [64]:
In=pd.DataFrame(index).to_numpy();
Ind=In.reshape(2060)

In [65]:
Ind

array([10025., 10026., 10032., ..., 93428., 93429., 93436.])

In [78]:
pr=[]
sr=[]
for i in range (le):
 if Ind[i] in L:
    pr.append(i)
 else:
    sr.append(i)

In [79]:
len(pr)

1794

In [73]:
len(L)

1795

In [116]:
t=[]
ra=[]
for i in range(L.size):
    if L[i] not in Ind:
         t.append(i)
    else:
        ra.append(i)

In [117]:
t
#=954

[954]

In [100]:
L[954]

80640

In [88]:
L.size

1795

In [110]:
len(pr)

1794

In [109]:
pr

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 48,
 49,
 50,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 83,
 84,
 85,
 86,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 328,
 329,
 330,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 346,
 347,
 348,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 374,
 375,
 376,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 403,
 404,
 405,
 406,
 407,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 460,
 463,
 464,
 465,
 466,
 467,
 469,
 470,
 471,
 472,
 473,
 474,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 549,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 602,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 626,
 627,
 628,
 629,
 631,
 632,
 633,
 634,
 635,
 637,
 638,
 639,
 640,
 642,
 643,
 644,
 645,
 646,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 670,
 671,
 672,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 687,
 689,
 691,
 692,
 694,
 695,
 696,
 697,
 699,
 700,
 701,
 702,
 703,
 705,
 706,
 707,
 708,
 709,
 711,
 713,
 714,
 715,
 716,
 717,
 719,
 720,
 721,
 722,
 725,
 726,
 727,
 728,
 730,
 731,
 732,
 734,
 735,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 746,
 747,
 748,
 750,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 761,
 763,
 764,
 765,
 767,
 768,
 769,
 771,
 772,
 773,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 787,
 788,
 789,
 790,
 791,
 792,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 817,
 818,
 819,
 820,
 821,
 822,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 855,
 856,
 857,
 858,
 860,
 861,
 863,
 864,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 917,
 918,
 919,
 920,
 922,
 923,
 925,
 926,
 927,
 928,
 929,
 930,
 932,
 933,
 934,
 935,
 936,
 938,
 939,
 941,
 942,
 943,
 944,
 945,
 947,
 948,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 963,
 964,
 965,
 966,
 967,
 968,
 970,
 972,
 973,
 974,
 975,
 976,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 990,
 993,
 994,
 997,
 998,
 999,
 1000,
 1001,
 1002,
 1003,
 1004,
 1005,
 1006,
 1009,
 1010,
 1014,
 1015,
 1016,
 1017,
 1018,
 1019,
 1020,
 1021,
 1022,
 1023,
 1024,
 1025,
 1026,
 1028,
 1029,
 1030,
 1031,
 1032,
 1033,
 1034,
 1035,
 1037,
 1040,
 1041,
 1042,
 1044,
 1045,
 1046,
 1047,
 1048,
 1049,
 1050,
 1051,
 1052,
 1053,
 1054,
 1055,
 1056,
 1057,
 1059,
 1060,
 1064,
 1065,
 1066,
 1067,
 1068,
 1069,
 1076,
 1079,
 1082,
 1083,
 1084,
 1085,
 1086,
 1087,
 1088,
 1089,
 1090,
 1091,
 1092,
 1095,
 1096,
 1097,
 1098,
 1099,
 1100,
 1102,
 1103,
 1104,
 1105,
 1106,
 1108,
 1109,
 1110,
 1111,
 1112,
 1113,
 1114,
 1115,
 1116,
 1117,
 1119,
 1120,
 1121,
 1123,
 1124,
 1125,
 1126,
 1127,
 1128,
 1129,
 1130,
 1132,
 ...]

In [113]:
price1=RRprices.iloc[ pr,1:]

In [114]:
price1.head()

,PERMNO,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,10025.0,2.660520,2.943234,0.090046,-1.894355,5.060483,6.981604,3.945201,3.734542,-0.276868,1.422848,0.063031,2.932515,1.326075,-1.871535,0.153400
1,10026.0,20.929629,10.413003,-3.344149,6.045255,0.540976,2.694806,1.459398,-1.228156,0.965623,0.791613,-0.136641,0.480383,-0.124342,-0.387490,-0.293852
2,10032.0,-6.393924,1.332993,2.746831,2.774044,-1.996780,-1.663309,0.074506,1.714567,0.236020,1.796485,0.674637,-0.401746,-1.121315,1.102451,0.071502
3,10051.0,-16.796843,4.370821,4.198720,2.511052,1.794202,-0.668591,1.052303,-0.942642,-0.853217,-0.581849,0.243187,-0.459938,0.085672,-0.150270,0.916823
4,10104.0,-7.988193,3.467485,2.660182,2.926140,-0.925021,-0.537990,-0.509021,-0.302044,0.209060,0.445765,-0.318472,0.356342,0.595305,-0.577343,0.236509

In [119]:
len(ra)

1794

In [121]:
Redr=Rrat.iloc[ ra,:]

In [122]:
Redr

            R1        R2        R3        R4        R5
0    -1.384094  1.385935  0.766891 -0.222239 -0.842197
1    -1.698006 -1.272806 -0.030781 -0.119481 -0.274844
2    -0.083062 -0.467590 -0.277913  0.268865 -0.290834
3     2.021754  0.841441 -0.885256  1.022509 -0.174030
4    -0.067969  0.685425  0.007250  0.518252 -0.247333
...        ...       ...       ...       ...       ...
1790 -0.205655  2.009651  0.988718 -0.295876  0.725069
1791  0.109654 -1.240439 -0.720380  0.273972 -0.358169
1792  0.524841  0.239720 -0.043644 -0.348751  0.600760
1793 -6.799577 -0.151529  1.725028 -0.249195 -0.879708
1794  0.693968  1.281694  1.287057 -2.521550  2.361002

[1794 rows x 5 columns]

In [126]:
len(Redr)

1794

In [129]:
price1

,PERMNO,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,10025.0,2.660520,2.943234,0.090046,-1.894355,5.060483,6.981604,3.945201,3.734542,-0.276868,1.422848,0.063031,2.932515,1.326075,-1.871535,0.153400
1,10026.0,20.929629,10.413003,-3.344149,6.045255,0.540976,2.694806,1.459398,-1.228156,0.965623,0.791613,-0.136641,0.480383,-0.124342,-0.387490,-0.293852
2,10032.0,-6.393924,1.332993,2.746831,2.774044,-1.996780,-1.663309,0.074506,1.714567,0.236020,1.796485,0.674637,-0.401746,-1.121315,1.102451,0.071502
3,10051.0,-16.796843,4.370821,4.198720,2.511052,1.794202,-0.668591,1.052303,-0.942642,-0.853217,-0.581849,0.243187,-0.459938,0.085672,-0.150270,0.916823
4,10104.0,-7.988193,3.467485,2.660182,2.926140,-0.925021,-0.537990,-0.509021,-0.302044,0.209060,0.445765,-0.318472,0.356342,0.595305,-0.577343,0.236509
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2055,93423.0,15.777618,-10.594142,6.338839,7.215996,0.929844,3.271884,-0.679610,-2.068366,-1.368682,-1.963627,-1.187493,0.821640,4.304653,-2.683755,0.877770
2056,93426.0,-21.368934,-0.917884,2.110907,3.043956,0.093471,0.000680,-0.119001,-0.970771,0.542935,0.137086,-0.054146,-0.076399,-0.051533,-0.193659,0.037577
2057,93428.0,-5.218069,-4.361978,3.238453,3.990895,2.169036,1.693805,-2.491233,-2.467845,1.752326,-0.086207,-1.604853,1.746350,-0.920345,-0.002388,2.129242
2058,93429.0,5.331271,-6.564118,-5.006977,8.670424,4.199205,1.121739,0.687463,-0.846125,1.114698,1.094729,0.312194,-0.476296,-1.660148,0.065595,0.013863
2059,93436.0,76.632989,-19.339244,-46.261453,29.652452,15.124125,-5.874421,7.608810,-1.502741,3.365005,7.702647,-1.161093,-4.963169,-12.858289,2.720484,-1.364535

In [127]:
Reduced=pd.concat([price1, Redr], axis=1, sort=False)

In [128]:
Reduced

,PERMNO,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,R1,R2,R3,R4,R5
0,10025.0,2.660520,2.943234,0.090046,-1.894355,5.060483,6.981604,3.945201,3.734542,-0.276868,...,0.063031,2.932515,1.326075,-1.871535,0.153400,-1.384094,1.385935,0.766891,-0.222239,-0.842197
1,10026.0,20.929629,10.413003,-3.344149,6.045255,0.540976,2.694806,1.459398,-1.228156,0.965623,...,-0.136641,0.480383,-0.124342,-0.387490,-0.293852,-1.698006,-1.272806,-0.030781,-0.119481,-0.274844
2,10032.0,-6.393924,1.332993,2.746831,2.774044,-1.996780,-1.663309,0.074506,1.714567,0.236020,...,0.674637,-0.401746,-1.121315,1.102451,0.071502,-0.083062,-0.467590,-0.277913,0.268865,-0.290834
3,10051.0,-16.796843,4.370821,4.198720,2.511052,1.794202,-0.668591,1.052303,-0.942642,-0.853217,...,0.243187,-0.459938,0.085672,-0.150270,0.916823,2.021754,0.841441,-0.885256,1.022509,-0.174030
4,10104.0,-7.988193,3.467485,2.660182,2.926140,-0.925021,-0.537990,-0.509021,-0.302044,0.209060,...,-0.318472,0.356342,0.595305,-0.577343,0.236509,-0.067969,0.685425,0.007250,0.518252,-0.247333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2055,93423.0,15.777618,-10.594142,6.338839,7.215996,0.929844,3.271884,-0.679610,-2.068366,-1.368682,...,-1.187493,0.821640,4.304653,-2.683755,0.877770,NaN,NaN,NaN,NaN,NaN
2056,93426.0,-21.368934,-0.917884,2.110907,3.043956,0.093471,0.000680,-0.119001,-0.970771,0.542935,...,-0.054146,-0.076399,-0.051533,-0.193659,0.037577,NaN,NaN,NaN,NaN,NaN
2057,93428.0,-5.218069,-4.361978,3.238453,3.990895,2.169036,1.693805,-2.491233,-2.467845,1.752326,...,-1.604853,1.746350,-0.920345,-0.002388,2.129242,NaN,NaN,NaN,NaN,NaN
2058,93429.0,5.331271,-6.564118,-5.006977,8.670424,4.199205,1.121739,0.687463,-0.846125,1.114698,...,0.312194,-0.476296,-1.660148,0.065595,0.013863,NaN,NaN,NaN,NaN,NaN
2059,93436.0,76.632989,-19.339244,-46.261453,29.652452,15.124125,-5.874421,7.608810,-1.502741,3.365005,...,-1.161093,-4.963169,-12.858289,2.720484,-1.364535,NaN,NaN,NaN,NaN,NaN

In [131]:
Reduced.to_csv('Reduceddim.csv')

In [95]:
np.argwhere(np.isnan(x2))

array([[  47,    0],
       [  47,    1],
       [  47,    2],
       ...,
       [2002, 1365],
       [2002, 1366],
       [2002, 1367]])

In [56]:
k=15

In [81]:
k

15

In [57]:
from sklearn.decomposition import PCA
pca = PCA(n_components=k)
principalComponents1 = pca.fit_transform(x1)

In [59]:
type(Red1)

pandas.core.frame.DataFrame

In [61]:
Red1.head(12)

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,2.660520,2.943234,0.090046,-1.894355,5.060483,6.981604,3.945201,3.734542,-0.276868,1.422848,0.063031,2.932515,1.326075,-1.871535,0.153400
1,20.929629,10.413003,-3.344149,6.045255,0.540976,2.694806,1.459398,-1.228156,0.965623,0.791613,-0.136641,0.480383,-0.124342,-0.387490,-0.293852
2,-6.393924,1.332993,2.746831,2.774044,-1.996780,-1.663309,0.074506,1.714567,0.236020,1.796485,0.674637,-0.401746,-1.121315,1.102451,0.071502
3,-16.796843,4.370821,4.198720,2.511052,1.794202,-0.668591,1.052303,-0.942642,-0.853217,-0.581849,0.243187,-0.459938,0.085672,-0.150270,0.916823
4,-7.988193,3.467485,2.660182,2.926140,-0.925021,-0.537990,-0.509021,-0.302044,0.209060,0.445765,-0.318472,0.356342,0.595305,-0.577343,0.236509
5,-5.186191,-0.260557,-0.690565,1.957905,-0.162047,0.390312,-0.681610,1.090433,0.796172,1.349957,0.195855,-0.575791,-0.955132,-0.099653,-0.114947
6,25.911351,-0.943541,3.252015,0.638148,-0.360859,-2.152514,-0.030206,1.887221,-1.339725,0.561290,-0.605146,0.116826,0.221639,-0.437810,0.218557
7,25.530868,3.790936,-3.525778,-1.493869,1.075759,-2.476955,-1.074509,1.295786,0.227521,-0.690718,0.426071,0.168987,1.016485,-0.500910,-0.676816
8,-15.503851,3.088464,3.317643,0.673269,-1.097601,-0.094587,-0.730571,-0.070618,0.813732,0.951500,0.077168,0.118997,0.537312,-0.506164,-0.091903
9,-26.887160,0.366556,3.015344,2.017800,-0.292609,0.289536,-0.558734,-0.581357,0.732116,-0.062321,-0.048807,-0.086184,0.173956,0.102042,0.157273
10,-26.560303,9.683084,-4.333199,-0.116285,0.513347,-0.400748,-1.777834,0.203514,0.149195,1.127114,1.047434,0.327308,0.256815,0.346838,0.219209
11,9.670910,2.001549,3.655704,1.272686,-3.217738,0.665021,-0.303741,1.565494,1.126763,2.301349,-1.862494,0.504008,-1.068313,0.070023,-0.603558

In [ ]:
Red2 = pd.DataFrame(data = principalComponents2
             , columns = range(1,l+1))

In [70]:
Red2.head(12)

NameError: name 'Red2' is not defined

In [90]:
len(Red2)

2060

In [42]:
len(Red.columns)

20

In [101]:
Redp1.head()

,PERMNO,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,10025.0,2.660520,2.943234,0.090046,-1.894355,5.060483,6.981604,3.945201,3.734542,-0.276868,1.422848,0.063031,2.932515,1.326075,-1.871535,0.153400
1,10026.0,20.929629,10.413003,-3.344149,6.045255,0.540976,2.694806,1.459398,-1.228156,0.965623,0.791613,-0.136641,0.480383,-0.124342,-0.387490,-0.293852
2,10032.0,-6.393924,1.332993,2.746831,2.774044,-1.996780,-1.663309,0.074506,1.714567,0.236020,1.796485,0.674637,-0.401746,-1.121315,1.102451,0.071502
3,10051.0,-16.796843,4.370821,4.198720,2.511052,1.794202,-0.668591,1.052303,-0.942642,-0.853217,-0.581849,0.243187,-0.459938,0.085672,-0.150270,0.916823
4,10104.0,-7.988193,3.467485,2.660182,2.926140,-0.925021,-0.537990,-0.509021,-0.302044,0.209060,0.445765,-0.318472,0.356342,0.595305,-0.577343,0.236509