In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/digit-recognizer/train.csv
/kaggle/input/digit-recognizer/test.csv
/kaggle/input/digit-recognizer/sample_submission.csv

In [2]:
import numpy as np
import sklearn as sk
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import sklearn.model_selection as ms
import sklearn.preprocessing as p
import math

In [4]:
tf.version.VERSION

'2.2.0'

In [5]:
mnist = pd.read_csv("../input/digit-recognizer/train.csv")

In [6]:
mnist.shape

(42000, 785)

In [14]:
mnist.columns

Index(['label', 'pixel0', 'pixel1', 'pixel2', 'pixel3', 'pixel4', 'pixel5',
       'pixel6', 'pixel7', 'pixel8',
       ...
       'pixel774', 'pixel775', 'pixel776', 'pixel777', 'pixel778', 'pixel779',
       'pixel780', 'pixel781', 'pixel782', 'pixel783'],
      dtype='object', length=785)

In [15]:
x = mnist.drop('label', axis=1)

In [17]:
x.head()

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [18]:
y = mnist['label']

In [19]:
y.head()

0    1
1    0
2    1
3    4
4    0
Name: label, dtype: int64

In [21]:
y = tf.keras.utils.to_categorical(y, num_classes=10)

In [22]:
y[0]

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [25]:
X_train, X_val, y_train, y_val  = ms.train_test_split(x, y, test_size=0.15)

In [26]:
scaler = p.StandardScaler()
X_train = scaler.fit_transform(X_train)
X_train = X_train.reshape(-1, 28, 28, 1)

X_val = scaler.transform(X_val)
X_val = X_val.reshape(-1, 28, 28, 1)

In [27]:
X_train.shape, X_val.shape

((35700, 28, 28, 1), (6300, 28, 28, 1))

In [28]:
y_train.shape, y_val.shape

((35700, 10), (6300, 10))

In [32]:
X_train.min()

-1.2747810057855078

In [38]:
from keras.models import Sequential
from keras.layers import Dense, Conv2D, MaxPool2D, Flatten

In [39]:
model = Sequential()

# Convolutional Layer
model.add(Conv2D(filters=32, kernel_size=(4,4), input_shape=(28, 28, 1), activation='relu'))

# pooling layer
model.add(MaxPool2D(pool_size=(2,2)))

# transform both layers to dense layer, thus, we need to flatten
# 2d to 1 d
model.add(Flatten())

# Dense Layer
model.add(Dense(128, activation='relu'))

# output layer
model.add(Dense(10, activation='softmax'))

model.compile(loss='categorical_crossentropy', 
             optimizer='rmsprop', 
             metrics = ['accuracy'])

In [40]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
conv2d_1 (Conv2D)            (None, 25, 25, 32)        544
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 12, 12, 32)        0
_________________________________________________________________
flatten_1 (Flatten)          (None, 4608)              0
_________________________________________________________________
dense_2 (Dense)              (None, 128)               589952
_________________________________________________________________
dense_3 (Dense)              (None, 10)                1290
=================================================================
Total params: 591,786
Trainable params: 591,786
Non-trainable params: 0
_________________________________________________________________

In [41]:
model.fit(X_train, y_train, epochs=20)

Epoch 1/20
1116/1116 [==============================] - 11s 10ms/step - loss: 0.1872 - accuracy: 0.9452
Epoch 2/20
1116/1116 [==============================] - 11s 10ms/step - loss: 0.0682 - accuracy: 0.9797
Epoch 3/20
1116/1116 [==============================] - 11s 10ms/step - loss: 0.0472 - accuracy: 0.9877
Epoch 4/20
1116/1116 [==============================] - 11s 10ms/step - loss: 0.0322 - accuracy: 0.9909
Epoch 5/20
1116/1116 [==============================] - 11s 10ms/step - loss: 0.0239 - accuracy: 0.9936
Epoch 6/20
1116/1116 [==============================] - 11s 10ms/step - loss: 0.0191 - accuracy: 0.9955
Epoch 7/20
1116/1116 [==============================] - 11s 10ms/step - loss: 0.0131 - accuracy: 0.9962
Epoch 8/20
1116/1116 [==============================] - 12s 11ms/step - loss: 0.0118 - accuracy: 0.9970
Epoch 9/20
1116/1116 [==============================] - 11s 10ms/step - loss: 0.0075 - accuracy: 0.9980
Epoch 10/20
1116/1116 [==============================] - 11s 10ms/step - loss: 0.0075 - accuracy: 0.9979
Epoch 11/20
1116/1116 [==============================] - 11s 10ms/step - loss: 0.0052 - accuracy: 0.9989
Epoch 12/20
1116/1116 [==============================] - 11s 10ms/step - loss: 0.0046 - accuracy: 0.9988
Epoch 13/20
1116/1116 [==============================] - 11s 9ms/step - loss: 0.0046 - accuracy: 0.9987
Epoch 14/20
1116/1116 [==============================] - 11s 9ms/step - loss: 0.0028 - accuracy: 0.9992
Epoch 15/20
1116/1116 [==============================] - 11s 10ms/step - loss: 0.0027 - accuracy: 0.9994
Epoch 16/20
1116/1116 [==============================] - 11s 10ms/step - loss: 0.0015 - accuracy: 0.9994
Epoch 17/20
1116/1116 [==============================] - 11s 10ms/step - loss: 0.0017 - accuracy: 0.9996
Epoch 18/20
1116/1116 [==============================] - 11s 10ms/step - loss: 8.9613e-04 - accuracy: 0.9996
Epoch 19/20
1116/1116 [==============================] - 11s 10ms/step - loss: 0.0015 - accuracy: 0.9996
Epoch 20/20
1116/1116 [==============================] - 12s 10ms/step - loss: 0.0011 - accuracy: 0.9997

In [42]:
from sklearn.metrics import classification_report, confusion_matrix

In [59]:
X_pred = pd.read_csv('../input/digit-recognizer/test.csv')
X_pred = scaler.transform(X_pred)
X_pred = X_pred.reshape(-1, 28, 28, 1)

In [65]:
y_pred = pd.DataFrame()
y_pred['ImageId'] = pd.Series(range(1,X_pred.shape[0] + 1))

In [55]:
predictions.shape

(35700,)

In [68]:
results = model.predict(X_pred)
# y_pred.to_csv("submission.csv", index=False)

In [72]:
results.shape

(28000,)

In [70]:
results = np.argmax(results,axis = 1)

In [73]:
results = pd.Series(results,name="Label")

In [47]:
submission = pd.concat([pd.Series(range(1,28001),name = "ImageId"),results],axis = 1)

NameError: name 'results' is not defined

In [77]:
submission.to_csv("cnn_mnist_submission.csv",index=False)

In [46]:
submission.to_csv("cnn_submission.csv",index=False)

NameError: name 'submission' is not defined

In [2]:
import pandas as pd
m_test = pd.read_csv("../input/digit-recognizer/test.csv")
m_train = pd.read_csv("../input/digit-recognizer/train.csv")

In [4]:
cols = m_test.columns

In [5]:
cols

Index(['pixel0', 'pixel1', 'pixel2', 'pixel3', 'pixel4', 'pixel5', 'pixel6',
       'pixel7', 'pixel8', 'pixel9',
       ...
       'pixel774', 'pixel775', 'pixel776', 'pixel777', 'pixel778', 'pixel779',
       'pixel780', 'pixel781', 'pixel782', 'pixel783'],
      dtype='object', length=784)

In [11]:
m_test['dataset'] = 'test'
m_train['dataset'] = 'train'

In [17]:
m_test.shape

(28000, 785)

In [18]:
m_train.shape

(42000, 786)

In [12]:
m_test['dataset']

0        test
1        test
2        test
3        test
4        test
         ...
27995    test
27996    test
27997    test
27998    test
27999    test
Name: dataset, Length: 28000, dtype: object

In [14]:
dataset = pd.concat([m_train.drop('label', axis=1), m_test]).reset_index()

In [19]:
dataset.shape

(70000, 786)

In [32]:
csv_test = pd.read_csv("../input/mnist-in-csv/mnist_test.csv")
csv_train = pd.read_csv("../input/mnist-in-csv/mnist_train.csv")
sample_submission = pd.read_csv("../input/digit-recognizer/sample_submission.csv")

In [21]:
csv_train.head()

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
0,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [22]:
mnist = pd.concat([csv_train, csv_test]).reset_index(drop=True)

In [23]:
mnist

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
0,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
69996,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
69997,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
69998,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
69999,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [25]:
labels = mnist['label'].values

In [26]:
labels

array([5, 0, 4, ..., 4, 5, 6])

In [27]:
mnist.drop('label', axis=1, inplace=True)

In [28]:
mnist.columns = cols

In [29]:
id_mnist = mnist.sort_values(by=list(mnist.columns)).index

In [30]:
id_mnist

Int64Index([67451, 48971, 15922, 11534, 63189, 68408, 42337, 56939, 45875,
            20534,
            ...
            33010, 14801, 14671, 14731, 14805, 14661, 66574, 44463, 12352,
            12905],
           dtype='int64', length=70000)

In [31]:
dataset_from = dataset.sort_values(by=list(mnist.columns))['dataset'].values
origin_id = dataset.sort_values(by=list(mnist.columns))['index'].values

In [ ]:
for i in range(len(id_mnist)):
    if dataset_from[i] == 'test':
        sample_submission.loc[origin_id[i], 'Label'] = labels[id_mnist[i]]

In [36]:
sample_submission

       ImageId  Label
0            1      2
1            2      0
2            3      9
3            4      0
4            5      3
...        ...    ...
27995    27996      9
27996    27997      7
27997    27998      3
27998    27999      9
27999    28000      2

[28000 rows x 2 columns]

In [48]:
sample_submission.to_csv("samp_fake_it.csv",index=False)