# Today

Introduction

- Electric Tesla ferry - guest lecture, 5th November. Pontus Sunnanstaf.

- Tools
    - Cloud: Google Colaboratory
    - Local: Anaconda Python
    
- Jupyter Notebook IDE

- Resources
    - https://kaggle.com
    - https://github.com/frahlg/UBC-NAME
    

- Getting started



### Assignment

- Merge .xlsx/.csv files, time-series
- Explanatory statistics
    - You are free to explore.
- Filter data
    - Based on your previous expertise. Think of what you need to filter.
    - What is 'bad' data?
- Visualise the data.
    - Think histograms, line-plots and bar-charts. Use ```matplotlib```
- Export data to new format, preferably both .xlsx and .hd5.

...


- If time permits: ML ...

In [9]:
# This is is a comment . NOT CODE

In [12]:
import pandas as pd

In [13]:

# Files

# Note the "?raw=true"
# https://github.com/frahlg/UBC-NAME/blob/master/data/dataset_ship1/out_1.xlsx?raw=true


df = pd.read_excel('https://github.com/frahlg/UBC-NAME/blob/master/data/dataset_ship1/out_0.xlsx?raw=true',index_col=0)

In [14]:
# If the file is uploaded in the same folder as the Notebook.
# That is locally or if you upload via the web interface

df = pd.read_excel('out_0.xlsx')

NameError: name 'pandas' is not defined

In [ ]:
# You could write several lines of code ...

df0 = pd.read_excel(f'https://github.com/frahlg/UBC-NAME/blob/master/data/dataset_ship1/out_0.xlsx?raw=true',index_col=0)
df1 = pd.read_excel(f'https://github.com/frahlg/UBC-NAME/blob/master/data/dataset_ship1/out_1.xlsx?raw=true',index_col=0)

# and so on ...

# But what if you have hundreds of files?

In [11]:
# Behold - the FOR loop!

In [1]:
for i in range(7):
    print(i)

0
1
2
3
4
5
6

In [7]:
all_data = pd.DataFrame()

for n in range(7):
    df = pd.read_excel(f'https://github.com/frahlg/UBC-NAME/blob/master/data/dataset_ship1/out_{n}.xlsx?raw=true',index_col=0)
    all_data = all_data.append(df)

In [8]:
all_data

,Consump1 Rate (kg/h),Consump2 Rate (kg/h),Eng1 Tot1 Mass (kg),Eng1 Tot2 Mass (kg),Eng2 Tot1 Mass (kg),Eng2 Tot2 Mass (kg),Torque 1 (kNm),Speed 1 (rpm),Power1 (kW),SpeedlogSpeed (kn),Gps Speed (kn),Aux Power1 (kW)
2018-12-09 13:09:35,822.5,122.2,1938946,76908,260993,51114,536.0,73.0,4110.0,13.2,12.4,362
2018-12-09 13:10:35,840.1,110.0,1938946,76908,260993,51114,542.0,73.0,4155.0,13.1,12.4,374
2018-12-09 13:11:35,852.9,105.2,1938992,76908,260998,51114,546.0,73.0,4182.0,13.1,12.4,361
2018-12-09 13:12:35,856,102.3,1938992,76908,260998,51114,548.0,73.0,4205.0,13.1,12.4,360
2018-12-09 13:13:35,855.3,94.5,1938992,76908,260998,51114,544.0,73.0,4165.0,13.2,12.4,358
...,...,...,...,...,...,...,...,...,...,...,...,...
2018-12-09 13:04:35,846.4,101.3,1938855,76908,260981,51114,541.0,73.0,4149.0,13.2,12.4,370
2018-12-09 13:05:35,827.5,117.1,1938901,76908,260987,51114,539.0,73.0,4137.0,13.2,12.4,361
2018-12-09 13:06:35,840.1,94.9,1938901,76908,260987,51114,534.0,73.0,4101.0,13.2,12.5,357
2018-12-09 13:07:35,811.1,122.1,1938901,76908,260987,51114,531.0,73.0,4078.0,13.3,12.5,360
2018-12-09 13:08:35,832.1,98.8,1938946,76908,260993,51114,535.0,73.0,4097.0,13.2,12.4,363

In [ ]:
all_data.to_excel('my_out_data.xlsx')