In [1]:
import pandas as pd
import allel
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#BALB_CJ file names need changing 
strain=['AKR_J','A_J','C3H_HeJ','CBA_J','DBA_2J','LP_J']
tool=['breakdancer',
#'clever',
'delly',
'gasv',
'gridss',
#'indelminer',
'lumpexpress',
#'mistrvar',
#'pindel',
#'platypus',
'popdel',
'smoove',
'sniffles']

In [3]:
df_del=pd.read_csv('../analysis_files/del_summary.csv')
non_del=pd.read_csv('../analysis_files/nondel_summary.csv')

In [4]:
df_del.head()

          tool strain  length flag  position  threshold  cov  n
0  breakdancer    A_J     356   FP  10158232          0  0.5  1
1  breakdancer    A_J     919   FP  11576623          0  0.5  1
2  breakdancer    A_J    3696   FP  19763412          0  0.5  1
3  breakdancer    A_J    4601   FP  20139734          0  0.5  1
4  breakdancer    A_J    8258   FP  20766145          0  0.5  1

In [5]:
non_del.head()

          tool strain  length flag  position  threshold  cov  n
0  breakdancer    A_J   22114   TN  37595335      10000  0.5  7
1  breakdancer    A_J   35326   TN  41489854       1000  0.5  2
2  breakdancer    A_J   22114   TN  37595335       1000  0.5  7
3  breakdancer    A_J   40385   TN  50557978       1000  0.5  9
4  breakdancer    A_J  174239   TN  37624530       1000  1.0  1

In [6]:
df_merge=pd.merge(df_del, non_del,on=['tool','threshold','strain'])
df_merge.head()

,tool,strain,length_x,flag_x,position_x,threshold,cov_x,n_x,length_y,flag_y,position_y,cov_y,n_y
0,breakdancer,A_J,326,TP,10568090,10000,0.5,7,22114,TN,37595335,0.5,7
1,breakdancer,A_J,326,TP,10568090,10000,0.5,7,311673,TN,15527713,2.0,1
2,breakdancer,A_J,326,TP,10568090,10000,0.5,7,68429,TN,15846589,2.0,1
3,breakdancer,A_J,326,TP,10568090,10000,0.5,7,77773,TN,19985619,2.0,1
4,breakdancer,A_J,326,TP,10568090,10000,0.5,7,76080,TN,20063792,2.0,1

# Group Data

In [7]:
group_data_TP=df_del[df_del['flag'] == 'TP'].groupby(['tool','threshold','strain','n','cov'],as_index=False)['flag'].count()
group_data_TP=group_data_TP.rename(columns={"flag": "nTP"})


group_data_TP[pd.isnull(group_data_TP).any(axis=1)]

Empty DataFrame
Columns: [tool, threshold, strain, n, cov, nTP]
Index: []

In [8]:
group_data_FP=df_del[df_del['flag' == 'FP'].groupby(['tool','threshold','strain','n','cov'], as_index=False)['flag'].count()]
group_data_FP=group_data_FP.rename(columns={"flag":"nFP"})

group_data_FP[pd.isnull(group_data_FP).any(axis=1)]

KeyError: False