In [1]:
import sys
sys.path.append('..')
from configure.settings import DBSelector

In [2]:
client = DBSelector().mongo('qq')

In [29]:
doc_name = 'xueqiu_private_2024-01-22'
data = list(client['db_stock'][doc_name].find())

In [30]:
len(data)

627

In [31]:
import pandas as pd
df = pd.DataFrame(data)

In [21]:
df.head()

,priority,symbol,name,manager_nick_name,unit_net_value,end_date,end_date_val,profit_rate,max_drawdown_rate,annual_return_this_year,...,fd_code,has_select,risk_rating,is_open_day_tmp,is_raise,create_time,sharp_rate,half_a_year,crawltime,normal_Item
0,-1,P000777,大禾投资-掘金5号,大禾投资,12.8810,01-12,1704988800000,11.8810,0.5787,-0.0389,...,SM6778,False,None,None,None,None,1.09,False,2024-01-21 19:43:49.432,"{'nav_type': 'normal', 'max_draw_down': '-0.00..."
1,-1,P001029,仙人掌盈沣远航一号,上海仙人掌,7.5870,01-12,1704988800000,6.5870,0.3798,-0.0928,...,SS5579,False,None,None,None,None,1.09,False,2024-01-21 19:43:49.432,"{'nav_type': 'normal', 'max_draw_down': '-0.04..."
2,-1,P000865,达理1号,成于思,7.3130,01-12,1704988800000,6.3130,0.3404,-0.0757,...,SL3433,False,None,None,None,None,1.04,False,2024-01-21 19:43:49.432,"{'nav_type': 'normal', 'max_draw_down': '-0.03..."
3,-1,P000946,正圆壹号,正圆投资,4.3460,01-12,1704988800000,6.2330,0.5562,-0.4111,...,SJ5352,False,None,None,None,None,0.58,False,2024-01-21 19:43:49.432,"{'nav_type': 'normal', 'max_draw_down': '-0.09..."
4,-1,P000531,希瓦小牛1号,梁宏,5.5048,01-12,1704988800000,6.0854,0.4055,-0.0934,...,A00003,True,None,None,None,None,0.95,False,2024-01-21 19:43:49.432,"{'nav_type': 'normal', 'max_draw_down': '-0.00..."

In [32]:
del df['_id']

In [33]:
df.head(1)

,priority,symbol,name,manager_nick_name,unit_net_value,end_date,end_date_val,profit_rate,max_drawdown_rate,annual_return_this_year,...,fd_code,has_select,risk_rating,is_open_day_tmp,is_raise,create_time,sharp_rate,half_a_year,crawltime,normal_Item
0,-1,P000777,大禾投资-掘金5号,大禾投资,12.979,01-19,1705593600000,11.979,0.5787,-0.0779,...,SM6778,False,None,None,None,None,1.09,False,2024-01-22 18:11:32.741,"{'nav_type': 'normal', 'max_draw_down': '-0.00..."

In [34]:
df['annual_return_this_year']=df['annual_return_this_year'].map(lambda x:100*x)

In [8]:
df['combine-name']=df['name']+'-'+df['manager_nick_name']

In [ ]:
df.head(5)

In [9]:
top = df.sort_values('annual_return_this_year',ascending=False).head(20)
bottom =  df.sort_values('annual_return_this_year',ascending=True).head(20)

In [11]:
temp_data = df[df['symbol']=='P000531']['normal_Item']

In [16]:
df[df['symbol']=='P000531']['annual_return_this_year']

4   -0.0934
Name: annual_return_this_year, dtype: float64

In [14]:
temp_data.iloc[0]

{'nav_type': 'normal',
 'max_draw_down': '-0.0064',
 'sharp': '2.86',
 'desc': '本产品',
 'rate': '0.0082'}

In [35]:
def this_year_actual_return(x):
    # item = x['normal_Item']
    return float(x['rate'])*100

In [36]:
df['this_year_actual_return'] = df['normal_Item'].map(this_year_actual_return)

In [37]:
df.to_excel('xueqiu_private_fund.xlsx',encoding='utf8',index=False)

In [38]:
top = df.sort_values('this_year_actual_return',ascending=False).head(20)
bottom =  df.sort_values('this_year_actual_return',ascending=True).head(20)

In [27]:
df.head()

,priority,symbol,name,manager_nick_name,unit_net_value,end_date,end_date_val,profit_rate,max_drawdown_rate,annual_return_this_year,...,has_select,risk_rating,is_open_day_tmp,is_raise,create_time,sharp_rate,half_a_year,crawltime,normal_Item,this_year_actual_return
0,-1,P000777,大禾投资-掘金5号,大禾投资,12.8810,01-12,1704988800000,11.8810,0.5787,-0.0389,...,False,None,None,None,None,1.09,False,2024-01-21 19:43:49.432,"{'nav_type': 'normal', 'max_draw_down': '-0.00...",0.76
1,-1,P001029,仙人掌盈沣远航一号,上海仙人掌,7.5870,01-12,1704988800000,6.5870,0.3798,-0.0928,...,False,None,None,None,None,1.09,False,2024-01-21 19:43:49.432,"{'nav_type': 'normal', 'max_draw_down': '-0.04...",-4.43
2,-1,P000865,达理1号,成于思,7.3130,01-12,1704988800000,6.3130,0.3404,-0.0757,...,False,None,None,None,None,1.04,False,2024-01-21 19:43:49.432,"{'nav_type': 'normal', 'max_draw_down': '-0.03...",-1.96
3,-1,P000946,正圆壹号,正圆投资,4.3460,01-12,1704988800000,6.2330,0.5562,-0.4111,...,False,None,None,None,None,0.58,False,2024-01-21 19:43:49.432,"{'nav_type': 'normal', 'max_draw_down': '-0.09...",-9.04
4,-1,P000531,希瓦小牛1号,梁宏,5.5048,01-12,1704988800000,6.0854,0.4055,-0.0934,...,True,None,None,None,None,0.95,False,2024-01-21 19:43:49.432,"{'nav_type': 'normal', 'max_draw_down': '-0.00...",0.82

In [41]:
# 绘图部分
from pyecharts import options as opts
from pyecharts.charts import Bar
from pyecharts.globals import ThemeType

# simple_result ={}
# for k,v in industry_dict.items():
#     simple_result[k]=round(v['premium_rt'].mean(),0)

# simple_result = list(sorted(simple_result.items(),key=lambda x:x[1],reverse=True))
# X=[i[0] for i in simple_result]
# Y=[i[1] for i in simple_result]
X=top['name'].tolist()
Y=top['this_year_actual_return'].tolist()
Y=[round(i) for i in Y]
c = (
    Bar()
    .add_xaxis(X)
    .add_yaxis(y_axis=Y,series_name='收益率%',
    category_gap="70%"
    )
    # .reversal_axis()
    .set_series_opts(label_opts=opts.LabelOpts(position="right"))
    .set_global_opts(title_opts=opts.TitleOpts(title="雪球私募收益率2024年1-月排名前20"),
    xaxis_opts=opts.AxisOpts(axislabel_opts=opts.LabelOpts(rotate=45)),
      yaxis_opts=opts.AxisOpts(splitline_opts=opts.SplitLineOpts(is_show=True),),
    # datazoom_opts=opts.DataZoomOpts()
    )
    # .render("../plot_image/私募收益率靠前.html")
)

from pyecharts.charts import Bar, Grid, Line
grid = (
    Grid(init_opts=opts.InitOpts(theme= ThemeType.CHALK))
    .add(c, grid_opts=opts.GridOpts(pos_bottom="25%"))
    .render("../plot_image/私募收益率靠前top-20.html")
)

In [43]:
df['this_year_actual_return'].mean()

-4.24518341307815

In [44]:
df['this_year_actual_return'].median()

-4.24

In [48]:
df[df['end_date']>='01-19']['this_year_actual_return'].min()

-22.439999999999998

In [51]:
df[df['end_date']>='01-19']['this_year_actual_return'].argmin()

375

In [53]:
df['this_year_actual_return'].argmin()

594

In [54]:
df.iloc[594]

priority                                                                  -1
symbol                                                               P000685
name                                                              上海斯诺波-爱久量化
manager_nick_name                                                       爱久投资
unit_net_value                                                         0.736
end_date                                                               01-19
end_date_val                                                   1705593600000
profit_rate                                                           -0.264
max_drawdown_rate                                                     0.5482
annual_return_this_year                                               -45.76
annual_return_year                                                   -0.4576
show_profit_status                                                         1
fd_code                                                               SJV254
has_select                                                             False
risk_rating                                                             None
is_open_day_tmp                                                         None
is_raise                                                                None
create_time                                                             None
sharp_rate                                                             -0.28
half_a_year                                                            False
crawltime                                         2024-01-22 18:11:32.742000
normal_Item                {'nav_type': 'normal', 'max_draw_down': '-0.22...
this_year_actual_return                                               -22.44
Name: 594, dtype: object

In [42]:
X=bottom['name'].tolist()
Y=bottom['this_year_actual_return'].tolist()
Y=[round(i) for i in Y]
c = (
    Bar()
    .add_xaxis(X)
    .add_yaxis(y_axis=Y,series_name='收益率%',
    category_gap="70%"
    )
    .set_series_opts(label_opts=opts.LabelOpts(position="right"))
    .set_global_opts(title_opts=opts.TitleOpts(title="雪球私募收益率2024年1月排名倒数20"),
    xaxis_opts=opts.AxisOpts(axislabel_opts=opts.LabelOpts(rotate=45),splitline_opts=opts.SplitLineOpts(is_show=False),),
    yaxis_opts=opts.AxisOpts(splitline_opts=opts.SplitLineOpts(is_show=True),),
    )
)

from pyecharts.charts import Bar, Grid, Line
grid = (
    Grid(init_opts=opts.InitOpts(theme= ThemeType.CHALK))
    .add(c, grid_opts=opts.GridOpts(pos_bottom="25%"))
    .render("../plot_image/私募收益率靠后-tail.html")
)

In [7]:
df['max_drawdown_rate']=df['max_drawdown_rate'].map(lambda x:x*100)

In [30]:
df['max_drawdown_rate']=df['max_drawdown_rate'].map(lambda x:x*100)
top__ = df.sort_values('annual_return_this_year',ascending=False).head(50)
bottom__ =  df.sort_values('annual_return_this_year',ascending=True).head(50)
top_=top__.rename(columns={'name':'私募名称','manager_nick_name':'管理人','annual_return_this_year':'今年收益率','unit_net_value':'单位净值','max_drawdown_rate':'最大回撤'})
# top[['name','manager_nick_name','annual_return_this_year','unit_net_value']].head(50)

In [31]:
top_[['私募名称','管理人','今年收益率','单位净值','最大回撤']].reset_index(drop=True).head(50).to_excel('top.xlsx')

In [32]:
bottom_=bottom__.rename(columns={'name':'私募名称','manager_nick_name':'管理人','annual_return_this_year':'今年收益率','unit_net_value':'单位净值','max_drawdown_rate':'最大回撤'})

In [33]:
bottom_[['私募名称','管理人','今年收益率','单位净值','最大回撤']].reset_index(drop=True).head(50).to_excel('bottom.xlsx')

In [34]:
# 合并

In [6]:
data_full = list(client['db_stock']['xueqiu_private_2022-08-18_brute_force'].find())

In [7]:
data_full_df = pd.DataFrame(data_full)

In [37]:
data_full_df.head()

,_id,symbol,name,profit_rate,annual_return_this_year,manager_nick_name,netvalue_date,create_date,close_status,crwaltime
0,62fdfcde3662f56a59ea53cd,P000030,私募工场(格顿1期),58.15,NaN,None,2015-11-13,2014-01-17,True,2022-08-18 16:48:30.167
1,62fdfcde3662f56a59ea53ce,P000031,私募工场(英菲证券),90.44,NaN,None,2015-10-21,2014-01-17,True,2022-08-18 16:48:30.532
2,62fdfcdf3662f56a59ea53cf,P000032,私募工场(思考8号),11.47,NaN,None,2014-09-16,2014-01-20,True,2022-08-18 16:48:31.036
3,62fdfcdf3662f56a59ea53d0,P000033,私募工场(曦微成长精选1期),85.72,NaN,None,2015-12-08,2014-02-20,True,2022-08-18 16:48:31.380
4,62fdfceb3662f56a59ea53d1,P000048,私募工场(以恒1号),82.33,NaN,None,2016-08-24,2014-01-17,True,2022-08-18 16:48:43.106

In [8]:
del data_full_df['_id']

In [9]:
merge_df = pd.merge(df,data_full_df,left_on='symbol',right_on='symbol',how='outer')

In [10]:
merge_df.head()

,_id,priority,symbol,name_x,manager_nick_name_x,unit_net_value,end_date,end_date_val,profit_rate_x,max_drawdown_rate,...,half_a_year,crawltime,name_y,profit_rate_y,annual_return_this_year_y,manager_nick_name_y,netvalue_date,create_date,close_status,crwaltime
0,63063461e1b8ad401d34c646,-1.0,P000946,正圆壹号,正圆投资,9.4850,08-19,1.660838e+12,11.3720,0.3664,...,False,2022-08-24 22:23:29.646,正圆壹号,1067.60,8.90,正圆投资,2022-08-12,2016-07-14,False,2022-08-18 17:02:13.945
1,63063461e1b8ad401d34c647,-1.0,P000777,大禾投资-掘金5号,大禾投资,10.7110,08-19,1.660838e+12,9.7110,0.4272,...,False,2022-08-24 22:23:29.646,大禾投资-掘金5号,958.50,-17.26,大禾投资,2022-08-12,2016-10-12,False,2022-08-18 17:00:04.894
2,63063461e1b8ad401d34c648,-1.0,P001029,仙人掌盈沣远航一号,上海仙人掌,10.6380,08-19,1.660838e+12,9.6380,0.2797,...,False,2022-08-24 22:23:29.646,仙人掌盈沣远航一号,953.70,-9.30,None,2022-08-12,2017-04-12,False,2022-08-18 17:02:57.366
3,63063461e1b8ad401d34c649,-1.0,P000865,达理1号,成于思,7.8079,08-19,1.660838e+12,6.8079,0.3404,...,False,2022-08-24 22:23:29.646,达理1号,701.71,-15.58,None,2022-08-12,2016-07-28,False,2022-08-18 17:01:17.810
4,63063461e1b8ad401d34c64a,-1.0,P000531,希瓦小牛1号,梁宏,5.0318,08-19,1.660838e+12,5.6124,0.3726,...,False,2022-08-24 22:23:29.646,希瓦小牛1号,569.80,-12.08,None,2022-08-12,2015-04-21,False,2022-08-18 16:55:06.650

In [11]:
del merge_df['_id']

In [13]:
del merge_df['priority']

In [17]:
merge_df.head()

NameError: name 'merge_df' is not defined

In [15]:
len(merge_df)

1016

In [16]:
merge_df[merge_df['create_date'].isnull()]

,symbol,name_x,manager_nick_name_x,unit_net_value,end_date,end_date_val,profit_rate_x,max_drawdown_rate,annual_return_this_year_x,annual_return_year,...,half_a_year,crawltime,name_y,profit_rate_y,annual_return_this_year_y,manager_nick_name_y,netvalue_date,create_date,close_status,crwaltime
11,P666012,青骊长兴,青骊投资,4.9590,08-19,1.660838e+12,3.9590,0.3768,0.0897,0.1405,...,False,2022-08-24 22:23:29.646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
23,P666011,青骊长川,青骊投资,3.4640,08-19,1.660838e+12,2.4640,0.0988,0.0900,0.1028,...,False,2022-08-24 22:23:29.646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
24,P666013,兆天金牛精选2号,兆天投资,3.0900,08-19,1.660838e+12,2.3900,0.3670,-0.0888,-0.2075,...,False,2022-08-24 22:23:29.646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
60,P666007,赫富500指数增强一号,赫富投资,2.6480,08-19,1.660838e+12,1.6480,0.2749,-0.0123,0.0157,...,False,2022-08-24 22:23:29.646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
117,P666023,相聚畅联一期,相聚资本,2.0545,08-19,1.660838e+12,1.0545,0.2897,0.0376,0.1335,...,False,2022-08-24 22:23:29.646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
123,P666009,启林正兴东绣1号,启林投资,0.9780,08-19,1.660838e+12,1.0040,0.2642,-0.0190,0.0255,...,False,2022-08-24 22:23:29.646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
161,P666019,悟空对冲量化11期,深圳悟空投资,1.7916,08-19,1.660838e+12,0.7916,0.2364,-0.1979,-0.1445,...,False,2022-08-24 22:23:29.646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
181,P666020,翼虎成长23期,翼虎投资余定恒,1.4470,08-19,1.660838e+12,0.7034,0.2959,-0.2587,-0.1961,...,False,2022-08-24 22:23:29.646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
185,P101729,圆球财富增值计划FOF,私募FOF研究,1.6790,08-22,1.661098e+12,0.6790,0.5277,-0.2834,-0.3085,...,False,2022-08-24 22:23:29.646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
223,P666003,雪球私募精英荟3号偏股型FOF,私募FOF研究,1.5010,08-22,1.661098e+12,0.5010,0.3604,-0.1973,-0.2050,...,False,2022-08-24 22:23:29.646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
231,P666004,玖鹏稳健成长7号A,玖鹏资产,1.4820,08-22,1.661098e+12,0.4820,0.3834,-0.0789,-0.1434,...,False,2022-08-24 22:23:29.646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
241,P666018,翼虎成长18期,翼虎投资余定恒,1.4280,08-19,1.660838e+12,0.4280,0.2848,-0.2547,-0.2049,...,False,2022-08-24 22:23:29.646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
242,P666016,青骊长川3号,青骊投资,1.2360,08-19,1.660838e+12,0.4280,0.0879,0.1046,0.1226,...,False,2022-08-24 22:23:29.646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
243,P007128,飞龙FOF,None,1.4260,08-22,1.661098e+12,0.4260,0.3544,-0.1856,-0.1781,...,False,2022-08-24 22:23:29.646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
246,P123456,厚雪长坡,私募FOF研究,1.4210,08-22,1.661098e+12,0.4210,0.4841,-0.2790,-0.2958,...,False,2022-08-24 22:23:29.646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
277,P001272,殊馥馥源套利1号,殊馥投资,1.0018,08-19,1.660838e+12,0.3028,0.0147,0.0283,0.0396,...,False,2022-08-24 22:23:29.646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
285,P666021,熙德博远医疗优选1号,李秋实的投资修行,0.8060,08-19,1.660838e+12,0.2770,0.3162,-0.0562,-0.1213,...,False,2022-08-24 22:23:29.646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
357,P666014,汇升星泰FOF一号,汇鸿汇升投资,1.0741,08-19,1.660838e+12,0.0741,0.0579,-0.0089,0.0170,...,False,2022-08-24 22:23:29.646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
360,P666025,博孚利CTA-FOF1A号,wenson文灏,1.0688,08-19,1.660838e+12,0.0688,0.0619,0.0310,0.0867,...,False,2022-08-24 22:23:29.646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
362,P666027,博孚利CTA-FOF5A号,wenson文灏,1.0650,08-19,1.660838e+12,0.0650,0.0770,0.0503,0.1071,...,False,2022-08-24 22:23:29.646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
417,P001273,仲阳博观量化选股1号1期,仲阳天王星,0.9995,08-19,1.660838e+12,-0.0005,0.0005,-0.0005,NaN,...,True,2022-08-24 22:23:29.646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
420,P001271,殊馥馥荣2号,殊馥投资,0.9987,08-22,1.661098e+12,-0.0013,0.0060,-0.0013,NaN,...,True,2022-08-24 22:23:29.646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
485,P666010,熙德博远医疗优选3号A,李秋实的投资修行,0.8560,08-19,1.660838e+12,-0.1440,0.2532,-0.0404,NaN,...,False,2022-08-24 22:23:29.646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
493,P666024,悟空11期8号,深圳悟空投资,0.8203,08-19,1.660838e+12,-0.1797,0.2261,-0.2078,NaN,...,False,2022-08-24 22:23:29.646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
511,P666005,华宝证券华量安瑞1号FOF集合资产管理计划,华宝资管总部,1.2393,08-02,1.659370e+12,0.2393,0.0472,0.0422,0.0424,...,False,2022-08-24 22:23:41.368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
514,P666017,洛书裕和建安,洛书投资,1.1747,07-29,1.659024e+12,0.1747,0.1376,-0.0613,0.0256,...,False,2022-08-24 22:23:41.368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT

In [36]:
len(merge_df[merge_df['create_date']>'2022-01-01'])

60

In [10]:
df[df['annual_return_this_year'].isnull()]

Empty DataFrame
Columns: [priority, symbol, name, manager_nick_name, unit_net_value, end_date, end_date_val, profit_rate, max_drawdown_rate, annual_return_this_year, annual_return_year, show_profit_status, fd_code, has_select, risk_rating, is_open_day_tmp, is_raise, create_time, sharp_rate, half_a_year, crawltime]
Index: []

[0 rows x 21 columns]

In [26]:
len(merge_df[merge_df['close_status']==True])

238

In [27]:
len(merge_df[merge_df['close_status']==False])

752

In [ ]:
238

In [28]:
merge_df['close_status'].value_counts()

False    752
True     238
Name: close_status, dtype: int64

In [32]:
merge_df[merge_df[merge_df['close_status']==False]['create_date']<'2022-01-01']

/tmp/ipykernel_20055/1612014277.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  merge_df[merge_df[merge_df['close_status']==False]['create_date']<'2022-01-01']

IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).

In [33]:
t1=merge_df[merge_df['close_status']==False]

In [35]:
len(t1[t1['create_date']<'2022-01-01'])

692

In [40]:
t1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 752 entries, 0 to 1015
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   symbol                     752 non-null    object
 1   name_x                     494 non-null    object
 2   manager_nick_name_x        475 non-null    object
 3   unit_net_value             494 non-null    float64
 4   end_date                   494 non-null    object
 5   end_date_val               494 non-null    float64
 6   profit_rate_x              494 non-null    float64
 7   max_drawdown_rate          494 non-null    float64
 8   annual_return_this_year_x  494 non-null    float64
 9   annual_return_year         410 non-null    float64
 10  show_profit_status         494 non-null    float64
 11  fd_code                    494 non-null    object
 12  has_select                 494 non-null    object
 13  risk_rating                0 non-null      object
 14  is_open_day_tmp            0 non-null      object
 15  is_raise                   0 non-null      object
 16  create_time                0 non-null      object
 17  sharp_rate                 466 non-null    float64
 18  half_a_year                494 non-null    object
 19  crawltime                  494 non-null    datetime64[ns]
 20  name_y                     752 non-null    object
 21  profit_rate_y              672 non-null    float64
 22  annual_return_this_year_y  589 non-null    float64
 23  manager_nick_name_y        310 non-null    object
 24  netvalue_date              752 non-null    object
 25  create_date                752 non-null    object
 26  close_status               752 non-null    object
 27  crwaltime                  752 non-null    datetime64[ns]
dtypes: datetime64[ns](2), float64(10), object(16)
memory usage: 170.4+ KB

In [41]:
t1[t1['annual_return_this_year_x'].isnull()]

,symbol,name_x,manager_nick_name_x,unit_net_value,end_date,end_date_val,profit_rate_x,max_drawdown_rate,annual_return_this_year_x,annual_return_year,...,half_a_year,crawltime,name_y,profit_rate_y,annual_return_this_year_y,manager_nick_name_y,netvalue_date,create_date,close_status,crwaltime
570,P000145,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaT,私募工场(牛金),100.70,NaN,None,2019-11-29,2014-12-23,False,2022-08-18 16:49:57.213
627,P000220,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaT,沐海基金,66.39,-19.98,None,2022-08-15,2016-01-07,False,2022-08-18 16:50:46.413
628,P000223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaT,朴信起航一号,59.56,NaN,None,2021-09-10,2016-02-02,False,2022-08-18 16:50:48.161
631,P000230,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaT,私募工场鼎杉1期,12.84,NaN,None,2018-12-07,2014-08-28,False,2022-08-18 16:50:52.007
637,P000236,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaT,私募工场兴富进取1期,200.00,NaN,广东兴富投资,2017-07-21,2014-07-11,False,2022-08-18 16:50:59.576
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1011,P001231,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaT,衍复雪瑞500指增1期,NaN,NaN,None,,2022-08-22,False,2022-08-18 17:05:06.779
1012,P001233,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaT,稳博壬寅1000指数增强1－6号,NaN,NaN,稳博投资,,2022-08-25,False,2022-08-18 17:05:07.763
1013,P001248,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaT,展弘多策略21号,NaN,NaN,None,,2022-08-24,False,2022-08-18 17:05:18.894
1014,P001255,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaT,广金美好玻色1期,NaN,NaN,None,,2022-08-22,False,2022-08-18 17:05:31.547
1015,P001268,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaT,广金美好康德多策略1期,NaN,NaN,None,,2022-09-14,False,2022-08-18 17:05:42.691

In [47]:
t1[t1['netvalue_date']<'2022-01-01']

,symbol,name_x,manager_nick_name_x,unit_net_value,end_date,end_date_val,profit_rate_x,max_drawdown_rate,annual_return_this_year_x,annual_return_year,...,half_a_year,crawltime,name_y,profit_rate_y,annual_return_this_year_y,manager_nick_name_y,netvalue_date,create_date,close_status,crwaltime
570,P000145,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaT,私募工场(牛金),100.70,NaN,None,2019-11-29,2014-12-23,False,2022-08-18 16:49:57.213
628,P000223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaT,朴信起航一号,59.56,NaN,None,2021-09-10,2016-02-02,False,2022-08-18 16:50:48.161
631,P000230,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaT,私募工场鼎杉1期,12.84,NaN,None,2018-12-07,2014-08-28,False,2022-08-18 16:50:52.007
637,P000236,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaT,私募工场兴富进取1期,200.00,NaN,广东兴富投资,2017-07-21,2014-07-11,False,2022-08-18 16:50:59.576
647,P000267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaT,私募工场麟悦1期,39.46,NaN,None,2020-09-18,2016-03-28,False,2022-08-18 16:51:40.217
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1011,P001231,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaT,衍复雪瑞500指增1期,NaN,NaN,None,,2022-08-22,False,2022-08-18 17:05:06.779
1012,P001233,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaT,稳博壬寅1000指数增强1－6号,NaN,NaN,稳博投资,,2022-08-25,False,2022-08-18 17:05:07.763
1013,P001248,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaT,展弘多策略21号,NaN,NaN,None,,2022-08-24,False,2022-08-18 17:05:18.894
1014,P001255,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaT,广金美好玻色1期,NaN,NaN,None,,2022-08-22,False,2022-08-18 17:05:31.547
1015,P001268,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaT,广金美好康德多策略1期,NaN,NaN,None,,2022-09-14,False,2022-08-18 17:05:42.691

In [48]:
len(df)

520

In [50]:
df[df['annual_return_this_year']>0].reset_index().tail()

,index,_id,priority,symbol,name,manager_nick_name,unit_net_value,end_date,end_date_val,profit_rate,...,show_profit_status,fd_code,has_select,risk_rating,is_open_day_tmp,is_raise,create_time,sharp_rate,half_a_year,crawltime
139,411,6306346ae1b8ad401d34c7e1,-1,P001038,珠池景元雪球相对价值,珠池资产,1.0008,08-19,1660838400000,0.0009,...,0,STL168,False,None,None,None,None,NaN,True,2022-08-24 22:23:29.646
140,412,6306346ae1b8ad401d34c7e2,-1,P001166,SAP智龙雪球CTA,深圳前海智龙资本,1.0009,08-19,1660838400000,0.0009,...,0,SVJ630,False,None,None,None,None,NaN,True,2022-08-24 22:23:29.646
141,413,6306346ae1b8ad401d34c7e3,-1,P001172,鸿道创新改革尊享6号,鸿道投资,1.0008,08-22,1661097600000,0.0007,...,0,SVK522,False,None,None,None,None,NaN,True,2022-08-24 22:23:29.646
142,511,6306346de1b8ad401d34c845,-1,P666005,华宝证券华量安瑞1号FOF集合资产管理计划,华宝资管总部,1.2393,08-02,1659369600000,0.2393,...,0,E20112,False,None,None,None,None,1.09,False,2022-08-24 22:23:41.368
143,515,6306346fe1b8ad401d34c849,-1,P001264,素养鸣石量化18号,鸣石投资,1.1735,08-05,1659628800000,0.5080,...,0,SCX293,False,None,None,None,None,1.24,False,2022-08-24 22:23:41.368

In [1]:
len(df)

NameError: name 'df' is not defined

In [8]:
df.to_excel('xueqiu_private_fund.xlsx')

In [15]:
df['rank']=df['annual_return_this_year'].rank(ascending=False)

In [20]:
df[df['manager_nick_name']=='梁宏'][['name','rank']]

          name   rank
4       希瓦小牛1号  390.0
16      希瓦小牛3号  393.0
95      希瓦大牛1号  355.5
188     希瓦辉耀1号  385.0
251     希瓦大牛2号  384.0
269     希瓦小牛雪球  357.5
319    希瓦小牛17号  381.0
341   希瓦小牛雪球2号  386.0
471    希瓦小牛15号  367.0
483  希瓦刀塔FOF1号  335.0
497     希瓦大牛7号  343.0
499     希瓦大牛5号  330.0
501  希瓦刀塔FOF2号  326.0
504     希瓦大牛3号  329.0
507     希瓦辉耀2号  339.0

In [22]:
df[df['annual_return_this_year']==0]['rank']

414    145.0
Name: rank, dtype: float64

In [23]:
df['annual_return_this_year'].mean()

-6.254499999999999

In [62]:
len(df[df['manager_nick_name']=='梁宏'][['name','manager_nick_name','this_year_actual_return']])

16

In [59]:
df[df['manager_nick_name']=='梁宏'][['name','manager_nick_name','this_year_actual_return']]['this_year_actual_return'].mean()

-0.20125

In [61]:
df[df['manager_nick_name']=='梁宏']['max_drawdown_rate'].mean()

0.3988125