In [5]:
import pandas as pd
import dziban as dzi

ModuleNotFoundError: No module named 'dziban'

In [3]:
df = pd.read_csv('sunshine.csv')

             city         lon        lat month  monthnum  sunshine
0         Seattle -122.335167  47.608013   Jan         0        69
1         Seattle -122.335167  47.608013   Feb         1       108
2         Seattle -122.335167  47.608013   Mar         2       178
3         Seattle -122.335167  47.608013   Apr         3       207
4         Seattle -122.335167  47.608013   May         4       253
5         Seattle -122.335167  47.608013   Jun         5       268
6         Seattle -122.335167  47.608013   Jul         6       312
7         Seattle -122.335167  47.608013   Aug         7       281
8         Seattle -122.335167  47.608013   Sep         8       221
9         Seattle -122.335167  47.608013   Oct         9       142
10        Seattle -122.335167  47.608013   Nov        10        72
11        Seattle -122.335167  47.608013   Dec        11        52
12        Chicago  -87.623177  41.881832   Jan         0       135
13        Chicago  -87.623177  41.881832   Feb         1       136
14        Chicago  -87.623177  41.881832   Mar         2       187
15        Chicago  -87.623177  41.881832   Apr         3       215
16        Chicago  -87.623177  41.881832   May         4       281
17        Chicago  -87.623177  41.881832   Jun         5       311
18        Chicago  -87.623177  41.881832   Jul         6       318
19        Chicago  -87.623177  41.881832   Aug         7       283
20        Chicago  -87.623177  41.881832   Sep         8       226
21        Chicago  -87.623177  41.881832   Oct         9       193
22        Chicago  -87.623177  41.881832   Nov        10       113
23        Chicago  -87.623177  41.881832   Dec        11       106
24       New York  -73.935242  40.730610   Jan         0       154
25       New York  -73.935242  40.730610   Feb         1       171
26       New York  -73.935242  40.730610   Mar         2       213
27       New York  -73.935242  40.730610   Apr         3       237
28       New York  -73.935242  40.730610   May         4       268
29       New York  -73.935242  40.730610   Jun         5       289
..            ...         ...        ...   ...       ...       ...
42  San Francisco -122.446747  37.733795   Jul         6       300
43  San Francisco -122.446747  37.733795   Aug         7       272
44  San Francisco -122.446747  37.733795   Sep         8       267
45  San Francisco -122.446747  37.733795   Oct         9       243
46  San Francisco -122.446747  37.733795   Nov        10       189
47  San Francisco -122.446747  37.733795   Dec        11       156
48        Houston  -95.358421  29.749907   Jan         0       144
49        Houston  -95.358421  29.749907   Feb         1       141
50        Houston  -95.358421  29.749907   Mar         2       193
51        Houston  -95.358421  29.749907   Apr         3       212
52        Houston  -95.358421  29.749907   May         4       266
53        Houston  -95.358421  29.749907   Jun         5       298
54        Houston  -95.358421  29.749907   Jul         6       294
55        Houston  -95.358421  29.749907   Aug         7       281
56        Houston  -95.358421  29.749907   Sep         8       238
57        Houston  -95.358421  29.749907   Oct         9       239
58        Houston  -95.358421  29.749907   Nov        10       181
59        Houston  -95.358421  29.749907   Dec        11       146
60          Miami  -80.191788  25.761681   Jan         0       222
61          Miami  -80.191788  25.761681   Feb         1       227
62          Miami  -80.191788  25.761681   Mar         2       266
63          Miami  -80.191788  25.761681   Apr         3       275
64          Miami  -80.191788  25.761681   May         4       280
65          Miami  -80.191788  25.761681   Jun         5       251
66          Miami  -80.191788  25.761681   Jul         6       267
67          Miami  -80.191788  25.761681   Aug         7       263
68          Miami  -80.191788  25.761681   Sep         8       216
69          Miami  -80.191788  25.761681   Oct         9       215
70          Miami  -80.191788  25.761681   Nov        10       212
71          Miami  -80.191788  25.761681   Dec        11       209

[72 rows x 6 columns]