In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
os.chdir('C:\\Users\DELL\Documents')

In [3]:
data = pd.read_csv('salaries_clean.csv')

In [4]:
data.dtypes

index                          int64
salary_id                      int64
employer_name                 object
location_name                 object
location_state                object
location_country              object
location_latitude            float64
location_longitude           float64
job_title                     object
job_title_category            object
total_experience_years       float64
employer_experience_years    float64
annual_base_pay              float64
signing_bonus                float64
annual_bonus                 float64
submitted_at                  object
dtype: object

In [5]:
#removing datafile eg other and Applied science
#so as to work on just the other technical skill set  that is avaliable
for x in data.index:
    if data.loc[x,'job_title_category'] == 'Other':
        data.drop(x, inplace = True)

In [6]:
data

,index,salary_id,employer_name,location_name,location_state,location_country,location_latitude,location_longitude,job_title,job_title_category,total_experience_years,employer_experience_years,annual_base_pay,signing_bonus,annual_bonus,submitted_at
0,0,1,opower,"san francisco, ca",CA,US,37.77,-122.41,systems engineer,Engineering,13.0,2.0,125000.0,5000.0,0.0,3/21/2016 12:58
1,1,3,walmart,"bentonville, ar",AR,US,36.36,-94.20,senior developer,Software,15.0,8.0,65000.0,NaN,5000.0,3/21/2016 12:58
2,2,4,vertical knowledge,"cleveland, oh",OH,US,41.47,-81.67,software engineer,Software,4.0,1.0,86000.0,5000.0,6000.0,3/21/2016 12:59
4,4,12,apple,cupertino,NaN,NaN,NaN,NaN,software engineer,Software,4.0,3.0,110000.0,5000.0,7000.0,3/21/2016 13:02
7,7,17,knewton,new york city,NY,US,38.00,-97.00,senior software engineer,Software,8.0,2.0,135000.0,0.0,0.0,3/21/2016 13:03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1649,1649,3287,mainz brady group - contractor at nike,"beaverton, or",OR,US,45.49,-122.80,front-end developer,Web,2.0,1.0,50.0,NaN,NaN,3/23/2016 8:16
1650,1650,3289,sparkfun electronics,"boulder, co",CO,US,40.02,-105.25,junior software developer,Software,1.0,0.5,60500.0,0.0,800.0,3/23/2016 8:24
1651,1651,3290,intel,europe,NaN,NaN,NaN,NaN,staff software enginer,Software,6.0,4.0,164000.0,0.0,20000.0,3/23/2016 8:27
1652,1652,3293,$2bn valuation tech company,nyc,NaN,NaN,NaN,NaN,sr. frontend eng,Web,7.0,1.0,150000.0,0.0,0.0,3/23/2016 8:41
1653,1653,3294,of maryland,"college park, md",MD,US,38.99,-76.93,scientific programmer (faculty research assist...,Applied Science,5.0,1.0,75000.0,NaN,NaN,3/23/2016 8:43

In [7]:
for x in data.index:
    if data.loc[x,'job_title_category'] == 'Applied Science':
        data.drop(x, inplace = True)

In [8]:
data

,index,salary_id,employer_name,location_name,location_state,location_country,location_latitude,location_longitude,job_title,job_title_category,total_experience_years,employer_experience_years,annual_base_pay,signing_bonus,annual_bonus,submitted_at
0,0,1,opower,"san francisco, ca",CA,US,37.77,-122.41,systems engineer,Engineering,13.0,2.0,125000.0,5000.0,0.0,3/21/2016 12:58
1,1,3,walmart,"bentonville, ar",AR,US,36.36,-94.20,senior developer,Software,15.0,8.0,65000.0,NaN,5000.0,3/21/2016 12:58
2,2,4,vertical knowledge,"cleveland, oh",OH,US,41.47,-81.67,software engineer,Software,4.0,1.0,86000.0,5000.0,6000.0,3/21/2016 12:59
4,4,12,apple,cupertino,NaN,NaN,NaN,NaN,software engineer,Software,4.0,3.0,110000.0,5000.0,7000.0,3/21/2016 13:02
7,7,17,knewton,new york city,NY,US,38.00,-97.00,senior software engineer,Software,8.0,2.0,135000.0,0.0,0.0,3/21/2016 13:03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1648,1648,3285,facebook,menlo park,NaN,NaN,NaN,NaN,software engineer,Software,4.0,1.5,130000.0,20000.0,13000.0,3/23/2016 8:02
1649,1649,3287,mainz brady group - contractor at nike,"beaverton, or",OR,US,45.49,-122.80,front-end developer,Web,2.0,1.0,50.0,NaN,NaN,3/23/2016 8:16
1650,1650,3289,sparkfun electronics,"boulder, co",CO,US,40.02,-105.25,junior software developer,Software,1.0,0.5,60500.0,0.0,800.0,3/23/2016 8:24
1651,1651,3290,intel,europe,NaN,NaN,NaN,NaN,staff software enginer,Software,6.0,4.0,164000.0,0.0,20000.0,3/23/2016 8:27
1652,1652,3293,$2bn valuation tech company,nyc,NaN,NaN,NaN,NaN,sr. frontend eng,Web,7.0,1.0,150000.0,0.0,0.0,3/23/2016 8:41

In [9]:
data.dtypes

index                          int64
salary_id                      int64
employer_name                 object
location_name                 object
location_state                object
location_country              object
location_latitude            float64
location_longitude           float64
job_title                     object
job_title_category            object
total_experience_years       float64
employer_experience_years    float64
annual_base_pay              float64
signing_bonus                float64
annual_bonus                 float64
submitted_at                  object
dtype: object

In [10]:
data['location_country'].fillna('')

0       US
1       US
2       US
4
7       US
        ..
1648
1649    US
1650    US
1651
1652
Name: location_country, Length: 1359, dtype: object

In [11]:
data.dtypes

index                          int64
salary_id                      int64
employer_name                 object
location_name                 object
location_state                object
location_country              object
location_latitude            float64
location_longitude           float64
job_title                     object
job_title_category            object
total_experience_years       float64
employer_experience_years    float64
annual_base_pay              float64
signing_bonus                float64
annual_bonus                 float64
submitted_at                  object
dtype: object

In [12]:
df=data.dropna()

In [13]:
df

,index,salary_id,employer_name,location_name,location_state,location_country,location_latitude,location_longitude,job_title,job_title_category,total_experience_years,employer_experience_years,annual_base_pay,signing_bonus,annual_bonus,submitted_at
0,0,1,opower,"san francisco, ca",CA,US,37.77,-122.41,systems engineer,Engineering,13.0,2.0,125000.0,5000.0,0.0,3/21/2016 12:58
2,2,4,vertical knowledge,"cleveland, oh",OH,US,41.47,-81.67,software engineer,Software,4.0,1.0,86000.0,5000.0,6000.0,3/21/2016 12:59
7,7,17,knewton,new york city,NY,US,38.00,-97.00,senior software engineer,Software,8.0,2.0,135000.0,0.0,0.0,3/21/2016 13:03
10,10,24,pensco trust company,"denver, co",CO,US,39.82,-105.10,senior software engineer,Software,10.0,1.5,120000.0,0.0,6000.0,3/21/2016 13:04
22,22,48,nbc universal,new york,NY,US,38.00,-97.00,senior analyst,Data,2.0,1.5,55000.0,0.0,0.0,3/21/2016 13:07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1631,1631,3242,d2l,"kitchener, on",ON,CA,60.00,-95.00,software developer,Software,2.0,2.0,70000.0,0.0,3.0,3/22/2016 20:33
1632,1632,3243,tendril,"boulder, co",CO,US,40.02,-105.25,software engineer,Software,3.0,1.5,110000.0,2500.0,11000.0,3/22/2016 21:17
1646,1646,3276,homenet automotive,"exton, pa",PA,US,40.03,-75.63,software engineer i,Software,2.0,1.0,60000.0,0.0,10.0,3/23/2016 6:59
1647,1647,3278,comcast,"philadelphia, pa",PA,US,39.95,-75.16,software engineer,Software,6.0,2.5,111000.0,5000.0,8.0,3/23/2016 7:05
1650,1650,3289,sparkfun electronics,"boulder, co",CO,US,40.02,-105.25,junior software developer,Software,1.0,0.5,60500.0,0.0,800.0,3/23/2016 8:24

In [14]:
df =df.drop(columns = "submitted_at")

In [15]:
df =df.drop(columns = "index")

In [16]:
#checking for missing valuesin any of the columns.
df.isnull().sum()

salary_id                    0
employer_name                0
location_name                0
location_state               0
location_country             0
location_latitude            0
location_longitude           0
job_title                    0
job_title_category           0
total_experience_years       0
employer_experience_years    0
annual_base_pay              0
signing_bonus                0
annual_bonus                 0
dtype: int64

In [17]:
df.dtypes

salary_id                      int64
employer_name                 object
location_name                 object
location_state                object
location_country              object
location_latitude            float64
location_longitude           float64
job_title                     object
job_title_category            object
total_experience_years       float64
employer_experience_years    float64
annual_base_pay              float64
signing_bonus                float64
annual_bonus                 float64
dtype: object

In [18]:
df.to_csv("cleaned_tech_role.csv",index= False)

In [19]:
pd.read_csv("cleaned_tech_role.csv")

,salary_id,employer_name,location_name,location_state,location_country,location_latitude,location_longitude,job_title,job_title_category,total_experience_years,employer_experience_years,annual_base_pay,signing_bonus,annual_bonus
0,1,opower,"san francisco, ca",CA,US,37.77,-122.41,systems engineer,Engineering,13.0,2.0,125000.0,5000.0,0.0
1,4,vertical knowledge,"cleveland, oh",OH,US,41.47,-81.67,software engineer,Software,4.0,1.0,86000.0,5000.0,6000.0
2,17,knewton,new york city,NY,US,38.00,-97.00,senior software engineer,Software,8.0,2.0,135000.0,0.0,0.0
3,24,pensco trust company,"denver, co",CO,US,39.82,-105.10,senior software engineer,Software,10.0,1.5,120000.0,0.0,6000.0
4,48,nbc universal,new york,NY,US,38.00,-97.00,senior analyst,Data,2.0,1.5,55000.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
333,3242,d2l,"kitchener, on",ON,CA,60.00,-95.00,software developer,Software,2.0,2.0,70000.0,0.0,3.0
334,3243,tendril,"boulder, co",CO,US,40.02,-105.25,software engineer,Software,3.0,1.5,110000.0,2500.0,11000.0
335,3276,homenet automotive,"exton, pa",PA,US,40.03,-75.63,software engineer i,Software,2.0,1.0,60000.0,0.0,10.0
336,3278,comcast,"philadelphia, pa",PA,US,39.95,-75.16,software engineer,Software,6.0,2.5,111000.0,5000.0,8.0
337,3289,sparkfun electronics,"boulder, co",CO,US,40.02,-105.25,junior software developer,Software,1.0,0.5,60500.0,0.0,800.0

In [20]:
df['salary_id'] == 32

0       False
2       False
7       False
10      False
22      False
        ...
1631    False
1632    False
1646    False
1647    False
1650    False
Name: salary_id, Length: 338, dtype: bool

# Dataframe export

In [21]:
#SAVING IT IN A TEXT DIRECTORY FILE TO BE EXPORTED TO SQL SERVER.

In [22]:
y = []

for index, row in df.iterrows():
    x = tuple(row)
    y.append(x)

y

[(1,
  'opower',
  'san francisco, ca',
  'CA',
  'US',
  37.77,
  -122.41,
  'systems engineer',
  'Engineering',
  13.0,
  2.0,
  125000.0,
  5000.0,
  0.0),
 (4,
  'vertical knowledge',
  'cleveland, oh',
  'OH',
  'US',
  41.47,
  -81.67,
  'software engineer',
  'Software',
  4.0,
  1.0,
  86000.0,
  5000.0,
  6000.0),
 (17,
  'knewton',
  'new york city',
  'NY',
  'US',
  38.0,
  -97.0,
  'senior software engineer',
  'Software',
  8.0,
  2.0,
  135000.0,
  0.0,
  0.0),
 (24,
  'pensco trust company',
  'denver, co',
  'CO',
  'US',
  39.82,
  -105.1,
  'senior software engineer',
  'Software',
  10.0,
  1.5,
  120000.0,
  0.0,
  6000.0),
 (48,
  'nbc universal',
  'new york',
  'NY',
  'US',
  38.0,
  -97.0,
  'senior analyst',
  'Data',
  2.0,
  1.5,
  55000.0,
  0.0,
  0.0),
 (59,
  'quick left',
  'boulder co',
  'CO',
  'US',
  38.0,
  -97.0,
  'senior developer',
  'Software',
  6.0,
  1.0,
  120000.0,
  0.0,
  0.0),
 (70,
  'startup',
  'detroit, mi',
  'MI',
  'US',
  42.38,
  -83.1,
  'senior engineer',
  'Engineering',
  8.0,
  3.0,
  100000.0,
  0.0,
  0.0),
 (74,
  'sf startup',
  'san francisco, ca',
  'CA',
  'US',
  37.77,
  -122.41,
  'web developer',
  'Web',
  5.0,
  0.5,
  125000.0,
  5000.0,
  10.0),
 (91,
  'freelance',
  'denver, co',
  'CO',
  'US',
  39.82,
  -105.1,
  'software engineer',
  'Software',
  20.0,
  11.0,
  190000.0,
  0.0,
  0.0),
 (109,
  'comcast',
  'philadelphia, pa',
  'PA',
  'US',
  39.95,
  -75.16,
  'python engineer',
  'Engineering',
  5.0,
  1.0,
  138000.0,
  0.0,
  0.0),
 (125,
  'startup',
  'san francisco, ca',
  'CA',
  'US',
  37.77,
  -122.41,
  'software engineer',
  'Software',
  2.5,
  1.0,
  100000.0,
  0.0,
  0.0),
 (128,
  'microsoft',
  'redmond, wa',
  'WA',
  'US',
  47.68,
  -122.12,
  'sde',
  'Software',
  4.0,
  2.0,
  275000.0,
  0.0,
  2.0),
 (132,
  'too small to say',
  'oklahoma city, ok',
  'OK',
  'US',
  35.46,
  -97.51,
  'web developer general it',
  'Web',
  10.0,
  7.5,
  88000.0,
  0.0,
  8000.0),
 (152,
  'texas tech  system',
  'lubbock, tx',
  'TX',
  'US',
  33.57,
  -101.87,
  'programmer analyst iii',
  'Data',
  7.0,
  3.0,
  55000.0,
  0.0,
  0.0),
 (156,
  'investment bank',
  'new york, ny',
  'NY',
  'US',
  40.71,
  -73.99,
  'm&a analyst',
  'Data',
  1.0,
  1.0,
  85000.0,
  15000.0,
  70000.0),
 (162,
  'conde nast',
  'new york city, ny',
  'NY',
  'US',
  40.71,
  -73.99,
  'software engineer - level 2',
  'Software',
  8.0,
  4.0,
  112000.0,
  0.0,
  2.0),
 (167,
  'mid-size fundraising startup',
  'san francisco, ca',
  'CA',
  'US',
  37.77,
  -122.41,
  'senior software engineer',
  'Software',
  11.0,
  0.0,
  165000.0,
  0.0,
  0.0),
 (168,
  'starbucks coffee company',
  'seattel, wa',
  'WA',
  'US',
  38.0,
  -97.0,
  'senior application developer',
  'Software',
  10.0,
  3.0,
  127000.0,
  0.0,
  15.0),
 (195,
  'walmartlabs',
  '94086',
  'CA',
  'US',
  37.38,
  -122.01,
  'principal/lead software engineer',
  'Software',
  14.0,
  4.0,
  190000.0,
  150000.0,
  50000.0),
 (211,
  'intel',
  'hillsboro, oregon',
  'OR',
  'US',
  45.52,
  -122.85,
  'computer hardware engineer',
  'Engineering',
  1.5,
  1.5,
  72000.0,
  0.0,
  0.0),
 (222,
  'microsoft',
  '98004',
  'WA',
  'US',
  47.61,
  -122.21,
  'software engineer 2',
  'Software',
  4.0,
  3.5,
  115000.0,
  50000.0,
  15000.0),
 (230,
  'analyst warehouse',
  'dallas tx',
  'TX',
  'US',
  38.0,
  -97.0,
  'software developer',
  'Software',
  10.0,
  1.0,
  90000.0,
  0.0,
  0.0),
 (249,
  'dupont pioneer',
  'johnston, iowa',
  'IA',
  'US',
  41.68,
  -93.7,
  'software developer',
  'Software',
  10.0,
  3.0,
  125000.0,
  10000.0,
  15000.0),
 (252,
  'newspaper company',
  'california',
  'CA',
  'US',
  38.0,
  -97.0,
  'cto',
  'Management',
  8.0,
  1.0,
  100000.0,
  0.0,
  0.0),
 (253,
  'bhhc',
  'omaha, ne',
  'NE',
  'US',
  41.15,
  -95.92,
  'fp&a analyst',
  'Data',
  3.0,
  3.0,
  46500.0,
  0.0,
  0.0),
 (254,
  'optum',
  'plymouth, mn',
  'MN',
  'US',
  44.96,
  -93.26,
  'software engineer',
  'Software',
  6.0,
  1.0,
  85000.0,
  3000.0,
  5000.0),
 (265,
  'directv/at&t',
  'culver city, ca',
  'CA',
  'US',
  33.99,
  -118.39,
  'application engineer',
  'Engineering',
  5.0,
  4.0,
  79000.0,
  0.0,
  10000.0),
 (273,
  'sunpower',
  'richmond, ca',
  'CA',
  'US',
  37.96,
  -122.38,
  'financial engineer',
  'Engineering',
  0.0,
  1.0,
  87000.0,
  0.0,
  8000.0),
 (294,
  'justice systems',
  'albuquerque, nm',
  'NM',
  'US',
  35.11,
  -106.62,
  'software engineer',
  'Software',
  2.0,
  1.0,
  51000.0,
  0.0,
  0.0),
 (324,
  'series c saas provider',
  'san francisco, ca',
  'CA',
  'US',
  37.77,
  -122.41,
  'full stack engineer',
  'Web',
  16.0,
  2.0,
  132000.0,
  0.0,
  0.0),
 (325,
  'garmin',
  'olathe, ks',
  'KS',
  'US',
  38.88,
  -94.81,
  'software engineer 2',
  'Software',
  2.75,
  2.75,
  72200.0,
  4000.0,
  0.0),
 (327,
  'aig',
  'wilton, ct usa',
  'CT',
  'US',
  41.18,
  -73.42,
  'microsoft developer for release management (grade 22)',
  'Software',
  20.0,
  2.0,
  165000.0,
  20000.0,
  0.0),
 (342,
  'igs energy',
  'columbus, oh',
  'OH',
  'US',
  39.98,
  -82.98,
  'application developer',
  'Software',
  3.0,
  1.0,
  65000.0,
  0.0,
  5000.0),
 (351,
  'spotx',
  'denver, co',
  'CO',
  'US',
  39.82,
  -105.1,
  'software engineer',
  'Software',
  7.0,
  2.0,
  84000.0,
  1500.0,
  1500.0),
 (355,
  'perk',
  'austin, tx',
  'TX',
  'US',
  30.26,
  -97.74,
  'developer',
  'Software',
  2.0,
  0.0,
  54000.0,
  2500.0,
  0.0),
 (364,
  'ibm',
  'san diego, ca',
  'CA',
  'US',
  32.71,
  -117.16,
  'software developer',
  'Software',
  9.0,
  8.0,
  151000.0,
  15000.0,
  5000.0),
 (365,
  'quicken loans',
  'detroit, mi',
  'MI',
  'US',
  42.38,
  -83.1,
  'sr. software engineer',
  'Software',
  5.0,
  3.0,
  82000.0,
  0.0,
  13000.0),
 (371,
  'of washington',
  'seattle, wa',
  'WA',
  'US',
  47.61,
  -122.33,
  'data scientist',
  'Data',
  10.0,
  4.0,
  101000.0,
  0.0,
  0.0),
 (374,
  'state of oregon',
  'oregon',
  'OR',
  'US',
  38.0,
  -97.0,
  'senior software developer',
  'Software',
  10.0,
  5.0,
  80000.0,
  0.0,
  0.0),
 (411,
  'missouri  of science and technology',
  'rolla, mo, usa',
  'MO',
  'US',
  37.94,
  -91.76,
  'secondary cluster administrator',
  'Management',
  3.0,
  1.0,
  43000.0,
  0.0,
  0.0),
 (417,
  'solidfire',
  'boulder, co',
  'CO',
  'US',
  40.02,
  -105.25,
  'senior software engineer',
  'Software',
  4.0,
  2.0,
  113000.0,
  0.0,
  9000.0),
 (441,
  'microsoft',
  'seattle, wa',
  'WA',
  'US',
  47.61,
  -122.33,
  'software development engineer',
  'Software',
  10.0,
  10.0,
  190000.0,
  0.0,
  65000.0),
 (446,
  'popsugar',
  'san francisco, ca',
  'CA',
  'US',
  37.77,
  -122.41,
  'senior software engineer',
  'Software',
  12.0,
  1.0,
  135000.0,
  0.0,
  0.0),
 (466,
  'private',
  'stuart, fl',
  'FL',
  'US',
  27.19,
  -80.24,
  'web developer',
  'Web',
  10.0,
  2.0,
  75000.0,
  0.0,
  0.0),
 (475,
  'i.b.m.',
  'north carolina',
  'NC',
  'US',
  38.0,
  -97.0,
  'senior software engineer',
  'Software',
  18.0,
  12.0,
  29000.0,
  0.0,
  0.0),
 (480,
  'facebook',
  'seattle, wa usa',
  'WA',
  'US',
  47.61,
  -122.33,
  'software engineer',
  'Software',
  7.0,
  3.0,
  167000.0,
  25000.0,
  25000.0),
 (489,
  'ignition one',
  'new york city',
  'NY',
  'US',
  38.0,
  -97.0,
  'software engineer',
  'Software',
  8.0,
  1.0,
  155000.0,
  0.0,
  36000.0),
 (492,
  'lockheed martin',
  'owego, ny',
  'NY',
  'US',
  42.1,
  -76.26,
  'associate electrical engineer',
  'Engineering',
  1.0,
  1.0,
  60528.0,
  0.0,
  0.0),
 (495,
  'optum',
  'boston, ma',
  'MA',
  'US',
  42.35,
  -71.06,
  'junior systems engineer',
  'Engineering',
  1.0,
  3.0,
  80000.0,
  0.0,
  5.0),
 (499,
  'intel',
  'santa clara, ca',
  'CA',
  'US',
  37.34,
  -121.95,
  'senior software engineer',
  'Software',
  12.0,
  4.0,
  145000.0,
  0.0,
  30000.0),
 (501,
  'viacom',
  'new york city',
  'NY',
  'US',
  38.0,
  -97.0,
  'ios developer',
  'Software',
  1.0,
  0.0,
  92000.0,
  0.0,
  0.0),
 (518,
  'midstage startup',
  'san francisco, ca',
  'CA',
  'US',
  37.77,
  -122.41,
  'software developer',
  'Software',
  1.0,
  1.0,
  120000.0,
  0.0,
  12000.0),
 (519,
  'microsoft',
  'redmond, wa',
  'WA',
  'US',
  47.68,
  -122.12,
  'software developer',
  'Software',
  2.0,
  2.0,
  120000.0,
  8000.0,
  8000.0),
 (523,
  'city of college station',
  'college station, tx',
  'TX',
  'US',
  30.6,
  -96.31,
  'systems analyst',
  'Data',
  2.0,
  1.0,
  51000.0,
  0.0,
  0.0),
 (538,
  'linklaters',
  'new york city',
  'NY',
  'US',
  38.0,
  -97.0,
  'it support engineer',
  'Engineering',
  6.0,
  0.0,
  50000.0,
  0.0,
  0.0),
 (544,
  'netsuite',
  'oklahoma city, ok',
  'OK',
  'US',
  35.46,
  -97.51,
  'sr. software engineer ii',
  'Software',
  15.0,
  1.0,
  120000.0,
  0.0,
  0.0),
 (561,
  'vml',
  'kansas city, mo',
  'KS',
  'US',
  39.1,
  -94.62,
  'interactive web developer',
  'Web',
  4.0,
  1.0,
  55000.0,
  0.0,
  0.0),
 (562,
  'c2s tech',
  'redmond, wa',
  'WA',
  'US',
  47.68,
  -122.12,
  'front end developer',
  'Web',
  5.0,
  0.5,
  60000.0,
  0.0,
  0.0),
 (570,
  'amazon',
  'seattle, wa',
  'WA',
  'US',
  47.61,
  -122.33,
  'software development engineer ii',
  'Software',
  4.0,
  2.0,
  121000.0,
  38000.0,
  0.0),
 (582,
  'mobiquity',
  'gainesville, fl',
  'FL',
  'US',
  29.67,
  -82.33,
  'ios developer',
  'Software',
  2.0,
  1.25,
  55000.0,
  0.0,
  0.0),
 (592,
  'd-wave',
  'vancouver bc',
  'BC',
  'CA',
  60.0,
  -95.0,
  'algorithmic software developer',
  'Software',
  3.0,
  1.0,
  90000.0,
  0.0,
  0.0),
 (596,
  'wyle',
  'lexington park, md',
  'MD',
  'US',
  38.26,
  -76.44,
  'software engineer',
  'Software',
  7.0,
  3.0,
  79000.0,
  0.0,
  0.0),
 (599,
  'lockheed martin',
  'austin, tx',
  'TX',
  'US',
  30.26,
  -97.74,
  'senior business analyst',
  'Data',
  7.0,
  3.0,
  99500.0,
  0.0,
  4000.0),
 (601,
  'logic technology',
  'schenectady, ny',
  'NY',
  'US',
  42.85,
  -73.9,
  'technical director',
  'Management',
  13.0,
  12.0,
  93500.0,
  0.0,
  15000.0),
 (607,
  'self',
  'washington, dc',
  'WA',
  'US',
  38.0,
  -97.0,
  'independent software engineer',
  'Software',
  14.0,
  6.0,
  230000.0,
  0.0,
  0.0),
 (610,
  'government/higher education',
  'arizona',
  'AZ',
  'US',
  38.0,
  -97.0,
  'developer / system analyst',
  'Data',
  6.0,
  3.0,
  46000.0,
  0.0,
  0.0),
 (626,
  'aecom',
  'richmond, ky',
  'KY',
  'US',
  37.74,
  -84.29,
  'automation engineer',
  'Engineering',
  17.0,
  4.0,
  112000.0,
  0.0,
  0.0),
 (633,
  'financial software company',
  'washington, dc',
  'WA',
  'US',
  38.0,
  -97.0,
  'software engineer',
  'Software',
  4.0,
  2.0,
  140000.0,
  0.0,
  0.0),
 (638,
  'consulting company',
  'chicago, il',
  'IL',
  'US',
  41.85,
  -87.65,
  'devops engineer',
  'Engineering',
  6.0,
  3.0,
  95000.0,
  0.0,
  0.0),
 (649,
  'logic technology',
  'schenectady, ny',
  'NY',
  'US',
  42.85,
  -73.9,
  'technical director',
  'Management',
  13.0,
  12.0,
  73000.0,
  0.0,
  5000.0),
 (668,
  'luminoso',
  'cambridge, ma',
  'MA',
  'US',
  42.35,
  -71.06,
  'software engineer',
  'Software',
  2.0,
  1.0,
  75000.0,
  0.0,
  0.0),
 (672,
  'startup',
  'san francisco (palo alto), ca',
  'CA',
  'US',
  38.0,
  -97.0,
  'software engineer',
  'Software',
  3.0,
  1.0,
  100000.0,
  2500.0,
  1500.0),
 (676,
  'google',
  'new york',
  'NY',
  'US',
  38.0,
  -97.0,
  'software engineer',
  'Software',
  1.0,
  1.0,
  115000.0,
  15000.0,
  15000.0),
 (694,
  'enterprise software company',
  'pleasanton, ca',
  'CA',
  'US',
  37.65,
  -121.85,
  'front end developer',
  'Web',
  15.0,
  1.0,
  105000.0,
  0.0,
  0.0),
 (697,
  'teksystems',
  'lincoln, ne',
  'NE',
  'US',
  40.81,
  -96.68,
  'senior applications developer',
  'Software',
  10.0,
  3.0,
  80000.0,
  0.0,
  0.0),
 (712,
  'alliant energy',
  'madison, wi',
  'WI',
  'US',
  43.1,
  -89.5,
  'senior it analyst',
  'Data',
  8.0,
  1.0,
  103000.0,
  0.0,
  15450.0),
 (715,
  'expedia',
  'bellevue, wa',
  'WA',
  'US',
  47.61,
  -122.21,
  'software development engineer i',
  'Software',
  1.0,
  0.0,
  105500.0,
  20000.0,
  10.0),
 (719,
  'best buy',
  'minneapolis, mn',
  'MN',
  'US',
  44.96,
  -93.26,
  'web engineer ii',
  'Web',
  7.0,
  2.0,
  125000.0,
  5000.0,
  15000.0),
 (728,
  'iac applications',
  'yonkers, ny',
  'NY',
  'US',
  40.94,
  -73.86,
  'senior engineer',
  'Engineering',
  16.0,
  10.0,
  124000.0,
  3000.0,
  10000.0),
 (730,
  'microsoft',
  'redmond, wa',
  'WA',
  'US',
  47.68,
  -122.12,
  'software development engineer 2',
  'Software',
  7.0,
  3.0,
  124000.0,
  55000.0,
  2600.0),
 (734,
  'bloomberg',
  'new york city',
  'NY',
  'US',
  38.0,
  -97.0,
  'software engineer',
  'Software',
  0.0,
  0.0,
  117000.0,
  0.0,
  17000.0),
 (753,
  'nbcuniversal',
  'boise, id (remote, job is based in nyc)',
  'ID',
  'US',
  43.62,
  -116.32,
  'senior software engineer',
  'Software',
  10.0,
  1.5,
  113375.0,
  0.0,
  0.0),
 (780,
  'wpp',
  'new york',
  'NY',
  'US',
  38.0,
  -97.0,
  'executive director of user experience',
  'Management',
  18.0,
  2.0,
  195000.0,
  15000.0,
  10.0),
 (781,
  'square',
  'san francisco, ca',
  'CA',
  'US',
  37.77,
  -122.41,
  'software engineer',
  'Software',
  4.0,
  3.0,
  110000.0,
  0.0,
  0.0),
 (813,
  'startup',
  'cambridge, ma',
  'MA',
  'US',
  42.35,
  -71.06,
  'engineer',
  'Engineering',
  2.0,
  2.0,
  130000.0,
  0.0,
  10000.0),
 (830,
  'startup',
  'mississippi',
  'MS',
  'US',
  38.0,
  -97.0,
  'software developer',
  'Software',
  3.0,
  2.0,
  49000.0,
  0.0,
  700.0),
 (834,
  'sef',
  'san francisco, ca',
  'CA',
  'US',
  37.77,
  -122.41,
  'founder',
  'Management',
  20.0,
  1.0,
  0.0,
  0.0,
  0.0),
 (847,
  'careworks tech',
  'columbus, oh',
  'OH',
  'US',
  39.98,
  -82.98,
  'lead front-end web developer',
  'Web',
  5.0,
  2.0,
  77957.56,
  0.0,
  0.0),
 (848,
  'sacramento county',
  'sacramento, ca',
  'CA',
  'US',
  38.58,
  -121.49,
  'it analyst i',
  'Data',
  4.0,
  1.0,
  61000.0,
  0.0,
  0.0),
 (852,
  'niehs',
  'durham, nc',
  'NC',
  'US',
  35.98,
  -78.91,
  'software developer',
  'Software',
  2.0,
  1.0,
  68000.0,
  0.0,
  0.0),
 (854,
  'netspend',
  'austin, tx',
  'TX',
  'US',
  30.26,
  -97.74,
  'front-end developer',
  'Web',
  1.0,
  1.0,
  72000.0,
  0.0,
  5500.0),
 (868,
  'ad-tech',
  'new york',
  'NY',
  'US',
  38.0,
  -97.0,
  'senior data analyst',
  'Data',
  8.0,
  2.0,
  110000.0,
  0.0,
  10000.0),
 (873,
  'deka research',
  'manchester, nh',
  'NH',
  'US',
  42.99,
  -71.45,
  'software engineer',
  'Software',
  5.0,
  3.0,
  69000.0,
  2000.0,
  3000.0),
 (882,
  'domo',
  'american fork, ut',
  'UT',
  'US',
  40.39,
  -111.78,
  'account executive',
  'Management',
  5.0,
  1.0,
  80000.0,
  25000.0,
  140000.0),
 (888,
  'moven',
  'radnor, pa',
  'PA',
  'US',
  39.96,
  -75.35,
  'software engineer',
  'Software',
  8.0,
  1.0,
  105000.0,
  0.0,
  0.0),
 (912,
  'twitter',
  'new york city',
  'NY',
  'US',
  38.0,
  -97.0,
  'senior software engineer',
  'Software',
  15.0,
  2.0,
  155000.0,
  0.0,
  0.0),
 (932,
  'nike',
  'beaverton, or',
  'OR',
  'US',
  45.49,
  -122.8,
  'senior technical project manager',
  'Management',
  10.0,
  1.0,
  124000.0,
  0.0,
  0.0),
 (934,
  'fresh code',
  'salt lake city, utah',
  'UT',
  'US',
  40.75,
  -111.9,
  'software engineer',
  'Software',
  5.0,
  0.5,
  95000.0,
  0.0,
  0.0),
 (948,
  'cox automotive',
  'burlington, vt',
  'VT',
  'US',
  44.48,
  -73.22,
  'ui developer',
  'Software',
  4.0,
  1.5,
  73500.0,
  0.0,
  5.0),
 (958,
  'state farm',
  'phoenix, az',
  'AZ',
  'US',
  33.45,
  -112.06,
  'software developer',
  'Software',
  2.0,
  1.0,
  63000.0,
  4000.0,
  6000.0),
 (977,
  'google',
  'new york city',
  'NY',
  'US',
  38.0,
  -97.0,
  'software engineer ii (level 3)',
  'Software',
  4.0,
  1.0,
  117500.0,
  0.0,
  18000.0),
 (979,
  'twitter',
  'san francisco, ca',
  'CA',
  'US',
  37.77,
  -122.41,
  'software engineer',
  'Software',
  3.0,
  1.0,
  140000.0,
  0.0,
  0.0),
 (988,
  'facebook',
  'north carolina',
  'NC',
  'US',
  38.0,
  -97.0,
  'software engineer',
  'Software',
  12.0,
  2.0,
  198000.0,
  25000.0,
  40000.0),
 (998,
  'intel',
  'folsom, ca',
  'CA',
  'US',
  38.67,
  -121.14,
  'application developer',
  'Software',
  2.0,
  2.0,
  74000.0,
  6000.0,
  3000.0),
 (999,
  'sovrn holdings',
  'boulder, co',
  'CO',
  'US',
  40.02,
  -105.25,
  'software engineer',
  'Software',
  6.0,
  1.0,
  105000.0,
  0.0,
  0.0),
 (1009,
  'amazon',
  'santa monica, ca',
  'CA',
  'US',
  34.01,
  -118.49,
  'sde i',
  'Software',
  1.0,
  1.0,
  95000.0,
  27000.0,
  0.0),
 (1011,
  'digitalocean',
  'virginia',
  'VA',
  'US',
  38.0,
  -97.0,
  'ruby engineer',
  'Engineering',
  10.0,
  1.0,
  130000.0,
  0.0,
  7000.0),
 (1019,
  'photo hosting company',
  'mountain view, ca',
  'CA',
  'US',
  37.41,
  -122.05,
  'engineer',
  'Engineering',
  13.0,
  3.0,
  150000.0,
  0.0,
  2000.0),
 (1025,
  'ixl learning',
  'san mateo, ca',
  'CA',
  'US',
  37.57,
  -122.32,
  'sr. software engineer',
  'Software',
  4.0,
  3.0,
  125000.0,
  0.0,
  0.0),
 (1026,
  'mitre',
  'bedford ma',
  'MA',
  'US',
  38.0,
  -97.0,
  'lead software systems engineer',
  'Software',
  10.0,
  6.0,
  111500.0,
  3500.0,
  0.0),
 (1037,
  'e commerce company',
  'boston, ma',
  'MA',
  'US',
  42.35,
  -71.06,
  '\x89ÛÜsr engineer',
  'Engineering',
  12.0,
  4.0,
  135000.0,
  0.0,
  20000.0),
 (1040,
  'ecommerce startup',
  'salt lake city, ut',
  'UT',
  'US',
  40.75,
  -111.9,
  'magento developer',
  'Software',
  6.0,
  1.5,
  37500.0,
  0.0,
  15.0),
 (1043,
  'dish',
  'denver, co',
  'CO',
  'US',
  39.82,
  -105.1,
  'software engineer',
  'Software',
  1.0,
  1.0,
  70000.0,
  0.0,
  0.0),
 (1058,
  'datis hr cloud',
  'tampa, fl',
  'FL',
  'US',
  27.95,
  -82.48,
  'software developer',
  'Software',
  15.0,
  0.0,
  115000.0,
  5000.0,
  2500.0),
 (1063,
  'microsoft',
  'redmond, wa',
  'WA',
  'US',
  47.68,
  -122.12,
  'software engineer',
  'Software',
  7.0,
  7.0,
  144000.0,
  0.0,
  20000.0),
 (1075,
  'ontact',
  'salt lake city, ut',
  'UT',
  'US',
  40.75,
  -111.9,
  'senior software engineer',
  'Software',
  7.0,
  4.0,
  95000.0,
  0.0,
  8000.0),
 (1080,
  'accenture',
  'washington dc',
  'WA',
  'US',
  38.0,
  -97.0,
  'analyst',
  'Data',
  2.0,
  2.0,
  72000.0,
  5000.0,
  5000.0),
 (1091,
  'think big',
  'mountain view, ca',
  'CA',
  'US',
  37.41,
  -122.05,
  'senior data engineer',
  'Data',
  5.0,
  4.0,
  145000.0,
  0.0,
  15000.0),
 (1093,
  'microsoft',
  'redmond, wa',
  'WA',
  'US',
  47.68,
  -122.12,
  'software engineer ii',
  'Software',
  7.0,
  7.0,
  128000.0,
  30000.0,
  10000.0),
 (1094,
  '(private)',
  'boston, ma',
  'MA',
  'US',
  42.35,
  -71.06,
  'creative director + designer/developer',
  'Management',
  12.0,
  4.0,
  100000.0,
  0.0,
  0.0),
 (1120,
  'bah',
  'maryland',
  'MD',
  'US',
  38.0,
  -97.0,
  'senior software engineer',
  'Software',
  15.0,
  1.0,
  101000.0,
  0.0,
  0.0),
 (1126,
  'hcl america',
  'redmond, wa',
  'WA',
  'US',
  47.68,
  -122.12,
  'system administrator',
  'Management',
  10.0,
  2.0,
  55000.0,
  0.0,
  0.0),
 (1128,
  'fcsa',
  'omaha, ne',
  'NE',
  'US',
  41.15,
  -95.92,
  'software engineer - consultant',
  'Software',
  12.0,
  1.0,
  150000.0,
  0.0,
  0.0),
 (1133,
  'life time fitness',
  'louisville, co',
  'CO',
  'US',
  39.96,
  -105.14,
  'software engineer',
  'Software',
  5.0,
  1.0,
  75000.0,
  0.0,
  0.0),
 (1137,
  'billups',
  '97034',
  'OR',
  'US',
  45.4,
  -122.68,
  'director of product management',
  'Management',
  15.0,

In [23]:
# writing file as txt in a new directory

file = open('tech_role','w')

for tuple in y:
    file.write(str(tuple)+ ',' + '\n')
file.close()