# Naukri Data Job Posting Data Cleaning

This is the data cleaning step of a database file containing Jobs with details like Job Name,Company, rating, minimum years of experience , salary offered , date etc.

First process of data analysis is the data cleaning where we will give data a perfect shape for the upcoming analysis.This step is very important before taking insights and data driven decision from the data.

First we will import python libraries which are used for data cleaning and dealing effectively with data

In [1]:
import pandas as pd

In [2]:
import os

In [3]:
import re

In [4]:
os.listdir()

['Music',
 '.ipython',
 '.Xauthority',
 '.zoom',
 '.aspell.en.prepl',
 'WhiteSur-icon-theme',
 'pgadmin4',
 '.android',
 '.local',
 '.xsession-errors',
 '.mozilla',
 'proposal',
 'noukri_data2.csv',
 '.gtkrc-xfce',
 '.vcpkg',
 'Untitled4.ipynb',
 'Documents',
 '.bash_history',
 '.python_history',
 'post.php',
 'Templates',
 'Untitled.ipynb',
 'resumecoverletter',
 '.pki',
 '.ipynb_checkpoints',
 'noukri_data2 (copy).csv',
 'google-chrome-stable_current_amd64.deb',
 '.cache',
 'nookri.csv',
 '.profile',
 'New York Citibike Trips.csv',
 'file_name.csv',
 'Downloads',
 'winehq.key',
 '.hypnotix',
 '.cinnamon',
 '.bash_logout',
 '.jupyter',
 'Naukri Jobs Data.csv',
 '.themes',
 '.thunderbird',
 'ooouuu.csv',
 'Unsaved Document 1',
 'Appointment Reciept.pdf',
 '.sudo_as_admin_successful',
 'Public',
 'jobdata.ipynb',
 '.var',
 'career.pdf',
 '.mysql_history',
 '.config',
 'McMojave-cursors',
 '.dmrc',
 '.aspell.en.pws',
 '.ngrok2',
 'Release.key',
 'Untitled2.ipynb',
 'dhruvafgan',
 'bio linkdin',
 '.xinputrc',
 'noukri_data_project.ipynb',
 'getintopclink',
 'Desktop',
 'instapy-config.json',
 '.xsession-errors.old',
 '.linuxmint',
 '.bashrc',
 '.wine',
 'Pictures',
 '.gitconfig',
 'snap',
 'Untitled3.ipynb',
 'noukri_data2.xlsx',
 '.icons',
 '.gtkrc-2.0',
 'Videos',
 '.mysql',
 'blackeye-im',
 '.wget-hsts',
 'Untitled1.ipynb',
 '.parsehub',
 'Firefox_wallpaper.png',
 'namelink',
 '.gnupg',
 'vcpkg']

In [5]:
naukri_data = pd.read_csv('Naukri Jobs Data.csv')

In [6]:
naukri_data.head()

,job_post,company,company_rating,company_review,exp_required,salary_offered,job_location,job_description,required_skills,Posted_as_on_22_5_2022
0,Information Technology Executive,Marriott,4.2,(2907 Reviews),0-3 Yrs,Not disclosed,Bhopal,POSITION SUMMARY Troubleshoot and resolve tech...,Supervisor\nAdministration\nTactical planning\...,5 DAYS AGO
1,Associate Director-Information Technology(SAP),Unacademy,3.4,(544 Reviews),5-15 Yrs,Not disclosed,"Noida, Greater Noida",Support / manage timely delivery of custom dev...,Relationship management\nSAP MM\nPharma\nAnaly...,3 DAYS AGO
2,Lead - Information Technology,EchoIndia,4.0,(20 Reviews),11-13 Yrs,Not disclosed,Delhi / NCR,Experience in designing modern REST APIs that ...,Spring\nDocker\nSystem Design\nPaaS\nMicroserv...,1 DAY AGO
3,Information Technology - Project Manager,Tata International,4.1,(287 Reviews),4-8 Yrs,Not disclosed,Mumbai (All Areas),Should be able to manage a project using vario...,project management\nit projects\ninformation t...,2 DAYS AGO
4,Information Technology Trainee,Stefanini,3.8,(75 Reviews),2-7 Yrs,Not disclosed,Noida,The resource will be expected to cross skill\t...,POP\nTraining\nBasic\nNetworking\nIntern\nIT i...,4 DAYS AGO

# First and foremost we will drop all the NaN values from the database

In [9]:
non_df = naukri_data[naukri_data.isna().any(axis = 1)]
non_df.head(50)

naukri_data = naukri_data.dropna(how='all')
naukri_data.head()

,job_post,company,company_rating,company_review,exp_required,salary_offered,job_location,job_description,required_skills,Posted_as_on_22_5_2022
0,Information Technology Executive,Marriott,4.2,(2907 Reviews),0-3 Yrs,Not disclosed,Bhopal,POSITION SUMMARY Troubleshoot and resolve tech...,Supervisor\nAdministration\nTactical planning\...,5 DAYS AGO
1,Associate Director-Information Technology(SAP),Unacademy,3.4,(544 Reviews),5-15 Yrs,Not disclosed,"Noida, Greater Noida",Support / manage timely delivery of custom dev...,Relationship management\nSAP MM\nPharma\nAnaly...,3 DAYS AGO
2,Lead - Information Technology,EchoIndia,4.0,(20 Reviews),11-13 Yrs,Not disclosed,Delhi / NCR,Experience in designing modern REST APIs that ...,Spring\nDocker\nSystem Design\nPaaS\nMicroserv...,1 DAY AGO
3,Information Technology - Project Manager,Tata International,4.1,(287 Reviews),4-8 Yrs,Not disclosed,Mumbai (All Areas),Should be able to manage a project using vario...,project management\nit projects\ninformation t...,2 DAYS AGO
4,Information Technology Trainee,Stefanini,3.8,(75 Reviews),2-7 Yrs,Not disclosed,Noida,The resource will be expected to cross skill\t...,POP\nTraining\nBasic\nNetworking\nIntern\nIT i...,4 DAYS AGO

# Now we will separate the maximum years of experience required for certain job from certain company For this , we will use .str function to extract desired number of characters from the table

In [10]:
naukri_data['max_exp_years'] = naukri_data['exp_required'].str[-6:-3]
naukri_data.head()

,job_post,company,company_rating,company_review,exp_required,salary_offered,job_location,job_description,required_skills,Posted_as_on_22_5_2022,max_exp_years
0,Information Technology Executive,Marriott,4.2,(2907 Reviews),0-3 Yrs,Not disclosed,Bhopal,POSITION SUMMARY Troubleshoot and resolve tech...,Supervisor\nAdministration\nTactical planning\...,5 DAYS AGO,-3
1,Associate Director-Information Technology(SAP),Unacademy,3.4,(544 Reviews),5-15 Yrs,Not disclosed,"Noida, Greater Noida",Support / manage timely delivery of custom dev...,Relationship management\nSAP MM\nPharma\nAnaly...,3 DAYS AGO,15
2,Lead - Information Technology,EchoIndia,4.0,(20 Reviews),11-13 Yrs,Not disclosed,Delhi / NCR,Experience in designing modern REST APIs that ...,Spring\nDocker\nSystem Design\nPaaS\nMicroserv...,1 DAY AGO,13
3,Information Technology - Project Manager,Tata International,4.1,(287 Reviews),4-8 Yrs,Not disclosed,Mumbai (All Areas),Should be able to manage a project using vario...,project management\nit projects\ninformation t...,2 DAYS AGO,-8
4,Information Technology Trainee,Stefanini,3.8,(75 Reviews),2-7 Yrs,Not disclosed,Noida,The resource will be expected to cross skill\t...,POP\nTraining\nBasic\nNetworking\nIntern\nIT i...,4 DAYS AGO,-7

# As we can see after extracting the maximum years of exterience from the data we have got '-' sign additionalinto every two digit of experience years we extracted.To get rid off this sign we will use lambda and strip  function

In [11]:
naukri_data['max_exp_years'] = naukri_data['max_exp_years'].map(lambda x: x.lstrip('-').rstrip('-'))
naukri_data.head(60)

,job_post,company,company_rating,company_review,exp_required,salary_offered,job_location,job_description,required_skills,Posted_as_on_22_5_2022,max_exp_years
0,Information Technology Executive,Marriott,4.2,(2907 Reviews),0-3 Yrs,Not disclosed,Bhopal,POSITION SUMMARY Troubleshoot and resolve tech...,Supervisor\nAdministration\nTactical planning\...,5 DAYS AGO,3
1,Associate Director-Information Technology(SAP),Unacademy,3.4,(544 Reviews),5-15 Yrs,Not disclosed,"Noida, Greater Noida",Support / manage timely delivery of custom dev...,Relationship management\nSAP MM\nPharma\nAnaly...,3 DAYS AGO,15
2,Lead - Information Technology,EchoIndia,4.0,(20 Reviews),11-13 Yrs,Not disclosed,Delhi / NCR,Experience in designing modern REST APIs that ...,Spring\nDocker\nSystem Design\nPaaS\nMicroserv...,1 DAY AGO,13
3,Information Technology - Project Manager,Tata International,4.1,(287 Reviews),4-8 Yrs,Not disclosed,Mumbai (All Areas),Should be able to manage a project using vario...,project management\nit projects\ninformation t...,2 DAYS AGO,8
4,Information Technology Trainee,Stefanini,3.8,(75 Reviews),2-7 Yrs,Not disclosed,Noida,The resource will be expected to cross skill\t...,POP\nTraining\nBasic\nNetworking\nIntern\nIT i...,4 DAYS AGO,7
5,Information Technology,Stefanini,3.8,(75 Reviews),11-13 Yrs,Not disclosed,Noida,Certification in relevant technologies A minim...,Solution architecture\nNetworking\nArchitectur...,3 DAYS AGO,13
6,Information Technology & Telecom,Novo Nordisk India,4.1,(521 Reviews),6-11 Yrs,Not disclosed,Bangalore/Bengaluru,The role would also need to Contribute to IT S...,Security management\nIT security\nInfrastructu...,5 DAYS AGO,11
7,Manager-IT(Information Technology),Electropneumatics and Hydraulics (India) Pvt. ...,4.0,(107 Reviews),10-15 Yrs,Not disclosed,Pune(Chakan),"Candidate, having min 08-15 years of working e...",network administration\ncomputer networking\ni...,11 DAYS AGO,15
8,Senior Manager- Information Technology,Srinivasa Farms Private Limited,4.0,(47 Reviews),10-15 Yrs,Not disclosed,Hyderabad/Secunderabad,Key Roles and ResponsibilitiesOpenBravo ERP cu...,Enterprise Architecture\nERP System\nProgram M...,5 DAYS AGO,15
9,Information Technology & Telecom,Novo Nordisk India,4.1,(521 Reviews),8-13 Yrs,Not disclosed,Bangalore/Bengaluru,"MSC, MBA, BA or similar graduate degree in rel...",Computer science\nTelecom\nClient handling\nCh...,5 DAYS AGO,13
10,Software Developer - Information Technology,IIHS,3.5,(21 Reviews),6-8 Yrs,Not disclosed,Bangalore/Bengaluru,A Bachelor s and / or a Master s degree in Com...,Software Development\nCSS\nRest\nFront End\nRD...,26 DAYS AGO,8
11,Executive/ Sr. Executive - Information Technology,United Office Systems Pvt. Ltd,4.4,(22 Reviews),3-5 Yrs,Not disclosed,Mumbai,Any Graduate OR Bachelors degree in Computer S...,Installation\nWindows Administration\nsystem a...,8 DAYS AGO,5
12,Urgent Opening For Information Technology Analyst,ICICI Bank,4.0,(31065 Reviews),1-6 Yrs,Not disclosed,"Mumbai, Hyderabad/Secunderabad, Mumbai (All Ar...",Upto 5 years of experience as a system analyst...,Application Development\nSoftware Development\...,7 DAYS AGO,6
13,Hiring Deputy General Manager/ General Manager...,Max Healthcare,4.2,(1486 Reviews),10-15 Yrs,Not disclosed,Gurgaon/Gurugram,Minimum Qualifications : BTech / M.tech / MCA/...,IT Head\nDevelopment Management\nERP\nRequirem...,19 DAYS AGO,15
14,Assistant Manager - Information Technology,ORRA Fine Jewellers Private Limited,4.1,(111 Reviews),6-11 Yrs,Not disclosed,"Mumbai Suburban, Mumbai (All Areas)","Team Handling, Experience in Microsoft Dynamic...",Microsoft Dynamics Erp\nSQL Server\nAzure Func...,5 DAYS AGO,11
15,Information Technology,OPPO,4.0,(3410 Reviews),1-2 Yrs,"1,50,000 - 1,75,000 PA.",Mumbai (All Areas),Any Graduate Preferred*Immediate Joiners and c...,information technology\nDesktop Support\nAntiv...,12 DAYS AGO,2
16,Intern - Information Technology,Planys Technologies Private Limited,4.6,(8 Reviews),0-1 Yrs,Not disclosed,Chennai,Certification RequiredSkill Required (Function...,IT-Hardware & Networking\nSoftware management\...,18 DAYS AGO,1
17,Assistant Manager- Information Technology,Star TV,4.2,(71 Reviews),2-6 Yrs,Not disclosed,Mumbai,KEY RESPONSIBILITIES Responsible to map busine...,IT Skills\nTesting\nOracle\nRPA\nASP.Net\nProc...,30+ DAYS AGO,6
18,Information Technology ( IT ) Intern,Aera Technology,3.7,(13 Reviews),1-2 Yrs,Not disclosed,Pune,The IT intern will provide direct technical as...,Laptop\nApplication Software\nCustomer Service...,30+ DAYS AGO,2
19,Delivery Manager - Information Technology,Parkar Global Technologies Pvt Ltd,2.5,(8 Reviews),11-15 Yrs,Not disclosed,Indore,Job Description The role is to ensure successf...,IT Skills\nSoftware Development\nProject Manag...,30+ DAYS AGO,15
20,Delivery Manager - Information Technology,Parkar Consulting and Labs,2.2,(10 Reviews),10-15 Yrs,Not disclosed,Indore,The role is to ensure successful end-to-end de...,IT Skills\nSoftware Development\nProject Manag...,30+ DAYS AGO,15
21,Freshers in Information technology (DevOps Sup...,Vyom Labs Pvt Ltd,3.6,(132 Reviews),5-10 Yrs,Not disclosed,Pune,Job description for Fresher RIM Support : Expe...,IT Skills\nCloud\nDevOps\nAWS\nSAP\nAzure\nIns...,30+ DAYS AGO,10
22,"Associate Manager, Information and Technology ...",Red Hat,4.6,(155 Reviews),5-8 Yrs,Not disclosed,Pune,"In this role, you will be responsible for a mu...",Service management\nRedhat\nService level\nLin...,30+ DAYS AGO,8
23,"Associate Professional, Information Technology",Ingram Micro,3.9,(477 Reviews),3-8 Yrs,Not disclosed,Mumbai,Must have at least 3 years practical applicati...,IT Skills\nTesting\nQuality Assurance\nOracle\...,30+ DAYS AGO,8
24,Software Engineer Manager,IBM,4.2,(13315 Reviews),7-12 Yrs,Not disclosed,Ahmedabad,We are looking for you as a Software Engineeri...,Project development\nAccess management\nApplic...,5 DAYS AGO,12
25,Software Engineer,Orell Technosystems (India) Pvt Ltd.,4.0,(15 Reviews),0-3 Yrs,Not disclosed,Delhi,Tech / M. Tech / MCA / Msc,HTML5\ndebugging\nC#\nCSS\nMS SQL\nAjax\nASP N...,30+ DAYS AGO,3
26,Senior Software Engineer - DevOps,IHS Markit,4.1,(435 Reviews),7-12 Yrs,Not disclosed,Gurgaon/Gurugram,"Responsibilities Deploy scalable, highly avail...",Solution architecture\nAutomation\nSoftware de...,11 DAYS AGO,12
27,Hiring For IT Freshers || Software Support Eng...,Bar Code India Ltd,4.0,(35 Reviews),0-1 Yrs,Not disclosed,Gurgaon/Gurugram,Desire Candidate Profile- Candidate should be ...,C#\n.Net\nSQL Server\nSQL\ncommunication\n.NET...,3 DAYS AGO,1
28,Information Technology,INCREDIBLE VISIBILITY SOLUTIONS PRIVATE LIMITED,4.3,(2 Reviews),4-9 Yrs,Not disclosed,Kollam/Quilon,You must work well within a team environment a...,IT Skills\nJava\nSoftware Development\ncontinu...,30+ DAYS AGO,9
29,Information Technology,Sutherland Global Services Inc,3.9,(4496 Reviews),7-9 Yrs,Not disclosed,Bangalore/Bengaluru,9 years of experience in IT/ software engineer...,Hibernate\nLinux\nMySQL\nJavascript\nPHP\nJ2Ee...,30+ DAYS AGO,9
30,Information Technology,APEX Analytix,3.9,(4 Reviews),2-5 Yrs,Not disclosed,Remote,Provide Tier III / other support per request f...,GIS\nVMware\nPerformance tuning\nDNS\nWindows\...,30+ DAYS AGO,5
31,Head of Information Technology,MEDOPS TECHNOLOGY PRIVATE LIMITED,4.3,(3 Reviews),10-15 Yrs,Not disclosed,Bangalore/Bengaluru(Indira Nagar),"Have significant, demonstrated, leadership exp...",information technology\nproblem solving\nIT In...,15 DAYS AGO,15
32,Information Technology,Sutherland Global Services Inc,3.9,(4496 Reviews),1-5 Yrs,Not disclosed,Bangalore/Bengaluru,Hands on experience with Continuous Integratio...,FXCop\nJenkins\npython\nC#\nConsul\nobject ori...,30+ DAYS AGO,5
33,HCL || 5G-Software Engineer,HCL Technologies,3.8,(19170 Reviews),0-0 Yrs,"7,00,000 - 12,00,000 PA.","Chennai, Bangalore/Bengaluru, Delhi / NCR",Experience of working on related area either i...,Java\nIT Skills\nPython\nCloud\nC++\nCSS\nSix ...,6 DAYS AGO,0
34,Software Engineer Manager,IBM,4.2,(13315 Reviews),12-14 Yrs,Not disclosed,Ahmedabad,"IntroductionAt IBM Security, our mission is to...",Access management\nProject development\nInterp...,13 DAYS AGO,14
35,Software Developer,Hexagon Capability Center India Pvt.Ltd.,4.2,(129 Reviews),0-2 Yrs,Not disclosed,Hyderabad/Secunderabad,Responsibilities Work as an Agile Scrum team m...,analytical\nSupply Chain Management\nOracle PL...,3 DAYS AGO,2
36,Software Development Specialist,NTT DATA,4.0,(7279 Reviews),5-10 Yrs,Not disclosed,Noida,Minimum 5 years of experience in SharePoint De...,Telecom\nAutomation\njQuery\nConsulting\nJavas...,1 DAY AGO,10
37,Rocket Flyer Technology - Software Development...,Rocket Flyer Technology,4.5,(3 Reviews),0-4 Yrs,Not disclosed,"Gurgaon/Gurugram, Others, MP",Following skills are required : - In Depth exp...,Tensorflow\nPytorch\nPython\nArtificial Intell...,30 DAYS AGO,4
38,Specialist - Software Development Engineering,Fiserv,3.9,(1337 Reviews),8-12 Yrs,Not disclosed,Bangalore/Bengaluru,What you will do You ll always raise the bar w...,IT Skills\nTesting\nUnix\nComputer science\nAu...,5 DAYS AGO,12
39,Senior Software Engineer (Distribution Technol...,Dun & Bradstreet,4.0,(157 Reviews),3-5 Yrs,Not disclosed,Hyderabad,Experience of code quality reporting using too...,IT Skills\nJava\nSoftware Development\nTesting...,30+ DAYS AGO,5
40,"Senior Software Engineer, Distribution Technology",Dun & Bradstreet,4.0,(157 Reviews),3-5 Yrs,Not disclosed,Hyderabad,"Have a bachelor s degree in Computer Science, ...",Maven\nCloud computing\nCoding\nEclipse\nDebug...,30+ DAYS AGO,5
41,"Software Engineer II, Distribution Technology",Dun & Bradstreet,4.0,(157 Reviews),2-5 Yrs,Not disclosed,Hyderabad/Secunderabad,"Have a bachelors degree in Computer Science, I...",IT Skills\nJava\nPython\nSoftware Development\...,30+ DAYS AGO,5
42,IT Technology Services Specialist (DevOps Engi...,SAP,4.4,(1116 Reviews),5-10 Yrs,Not disclosed,Pune,"Bachelor s or master s degree or equivalent, p...",Redhat Linux\nDevOps\nSUSE Linux\nIT Skills\nC...,30+ DAYS AGO,10
43,Senior Software Engineer ( Java ),Infostretch solutions Pvt. Ltd.,3.6,(147 Reviews),0-2 Yrs,Not disclosed,Pune,Fluent in English is a must to collaborate wit...,Business process\nEngineering services\nSAN\nI...,30+ DAYS AGO,2
44,Senior Software Development Engineer,Oracle,3.9,(3298 Reviews),0-5 Yrs,"10,00,000 - 20,00,000 PA.","Hyderabad/Secunderabad, Pune, Bangalore/Bengal...","Atleast 1 years of relevant IT experience, pre...",Java\nj2ee\nIT Skills\nSoftware Development\nT...,24 DAYS AGO,5
45,SAP Master Data Governance MDG Tool Software D...,Accenture,4.1,(26528 Reviews),4-6 Yrs,Not disclosed,Hyderabad/Secunderabad,Educational Qualification : 16 yrs of Regular ...,SAP\nConsulting\ndata governance\nInformation ...,11 DAYS AGO,6
46,"Professional, Software Development Engineering",Fiserv,3.9,(1337 Reviews),1-4 Yrs,Not disclosed,Bangalore/Bengaluru,You ll always raise the bar when it comes to o...,IT Skills\nTesting\nUnix\nComputer science\nAu...,12 DAYS AGO,4
47,HCL || ERX-Software Engineer,HCL Technologies,3.8,(19170 Reviews),0-0 Yrs,"7,00,000 - 12,00,000 PA.","Chennai, Bangalore/Bengaluru, Delhi / NCR","HCL is #Hiring freshers (B.Tech, B.E) from Tie...",c++\nIT Skills\nPython\nHTML\nJavascript\nJava...,6 DAYS AGO,0
48,Software Engineer II,Cerner,3.9,(653 Reviews),2-4 Yrs,Not disclosed,Bangalore/Bengaluru,"As a Software Engineer II , you are required t...",IT Skills\nJava\nPython\nSoftware Development\...,2 DAYS AGO,4
49,HCL || 5G-Software Engineer,HCL Technologies,3.8,(19170 Reviews),0-0 Yrs,"7,00,000 - 12,00,000 PA.","Chennai, Bangalore/Bengaluru, Delhi / NCR",Experience of working on related area either i...,Java\nIT Skills\nPython\nCloud\nC++\nCSS\nSix ...,6 DAYS AGO,0
50,Software Engineer (.net),Blackboard Inc.,4.0,(5 Reviews),3-5 Yrs,Not disclosed,Chennai,5 years of experience with web application dev...,Computer science\nContent management\nFront en...,1 DAY AGO,5
51,Manager Software Engineering,Neustar,4.5,(25 Reviews),10-15 Yrs,Not disclosed,Hyderabad/Secunderabad,The Software Engineering Manager is a technolo...,IT Skills\nJ2EE\nCloud\nJavascript\nBig Data\n...,15 DAYS AGO,15
52,Software Engineer III,Cerner,3.9,(653 Reviews),6-10 Yrs,Not disclosed,Bangalore/Bengaluru,"Bachelor s degree in Computer Science, Compute...",Computer science\nProfessional\nSoftware Engin...,8 DAYS AGO,10
53,Software Engineering in Test II,Neustar,4.5,(25 Reviews),4-6 Yrs,Not disclosed,Hyderabad/Secunderabad,Bachelors degree in computer science or engine...,Computer science\nTelecom\nManager Quality Ass...,11 DAYS AGO,6
54,Software Engineer in Test II,Neustar,4.5,(25 Reviews),4-6 Yrs,Not disclosed,Hyderabad/Secunderabad,Bachelors degree in computer science or engine...,IT Skills\nTesting\nQuality Assurance\nCompute...,11 DAYS AGO,6
55,Software Development Specialist,NTT DATA,4.0,(7279 Reviews),5-10 Yrs,Not disclosed,Noida,Minimum 5 years of experience in SharePoint De...,Telecom\nAutomation\njQuery\nConsulting\nJavas...,1 DAY AGO,10
56,Rocket Flyer Technology - Software Development...,Rocket Flyer Technology,4.5,(3 Reviews),0-4 Yrs,Not disclosed,"Gurgaon/Gurugram, Others, MP",Following skills are required : - In Depth exp...,Tensorflow\nPytorch\nPython\nArtificial Intell...,30 DAYS AGO,4
57,Senior Software Engineer (.net),VeriFone India Technologies Pvt Ltd,3.8,(86 Reviews),2-5 Yrs,Not disclosed,Bangalore/Bengaluru,Bachelors degree /Master Degree -in Computer S...,agile\nIntegration Testing\nScrum\nwritten com...,30+ DAYS AGO,5
58,Senior Software Engineer ( . Net ),Infostretch solutions Pvt. Ltd.,3.6,(147 Reviews),5-10 Yrs,Not disclosed,Pune,Required Skills: 5+ years as a backend enginee...,CI / CD\nC# Net\nECS\nPostgresql\nAzure\nCloud...,4 DAYS AGO,10
59,Technology-2022 Intern,IHS Markit,4.1,(435 Reviews),0-2 Yrs,Not disclosed,"Gurgaon/Gurugram, Bangalore/Bengaluru",A core component of your internship is our tai...,IT Skills\nJava\nSoftware Development\nQuality...,30+ DAYS AGO,2

# Now we will extract number of days from the Posted_as_on_22_5_2022 column of the table and then substract them from the date on which data is collected

In [12]:
new = naukri_data["Posted_as_on_22_5_2022"].str.split(" ", n = 1, expand = True)
naukri_data["day_of_posting"]= new[0]
naukri_data

,job_post,company,company_rating,company_review,exp_required,salary_offered,job_location,job_description,required_skills,Posted_as_on_22_5_2022,max_exp_years,day_of_posting
0,Information Technology Executive,Marriott,4.2,(2907 Reviews),0-3 Yrs,Not disclosed,Bhopal,POSITION SUMMARY Troubleshoot and resolve tech...,Supervisor\nAdministration\nTactical planning\...,5 DAYS AGO,3,5
1,Associate Director-Information Technology(SAP),Unacademy,3.4,(544 Reviews),5-15 Yrs,Not disclosed,"Noida, Greater Noida",Support / manage timely delivery of custom dev...,Relationship management\nSAP MM\nPharma\nAnaly...,3 DAYS AGO,15,3
2,Lead - Information Technology,EchoIndia,4.0,(20 Reviews),11-13 Yrs,Not disclosed,Delhi / NCR,Experience in designing modern REST APIs that ...,Spring\nDocker\nSystem Design\nPaaS\nMicroserv...,1 DAY AGO,13,1
3,Information Technology - Project Manager,Tata International,4.1,(287 Reviews),4-8 Yrs,Not disclosed,Mumbai (All Areas),Should be able to manage a project using vario...,project management\nit projects\ninformation t...,2 DAYS AGO,8,2
4,Information Technology Trainee,Stefanini,3.8,(75 Reviews),2-7 Yrs,Not disclosed,Noida,The resource will be expected to cross skill\t...,POP\nTraining\nBasic\nNetworking\nIntern\nIT i...,4 DAYS AGO,7,4
...,...,...,...,...,...,...,...,...,...,...,...,...
32733,TIBCO Spotfire,Birlasoft,3.8,(1133 Reviews),4-9 Yrs,Not disclosed,Bangalore/Bengaluru,"JD : Tibco Spotfire or, Tableau Reporting Deve...",TIBCO\ndata analysis\ncommunication\nPython\nT...,26 DAYS AGO,9,26
32734,Sr Consultant,Birlasoft,3.8,(1133 Reviews),5-10 Yrs,Not disclosed,Pune,SAP BI/BW DeveloperKey SkillsSAP BW 7.5 on HAN...,SAP BI/BW\nSAP BEx\nHANA\nAgile\nMS SQL\nSAP B...,26 DAYS AGO,10,26
32735,Package Consultant: SAP SCM GTS,IBM,4.2,(13370 Reviews),6-10 Yrs,Not disclosed,Pune,Experience in performing project management fu...,Data analysis\nProject management\nScheduling\...,27 DAYS AGO,10,27
32736,Associate Manager-Marketing Operations,Accenture,4.1,(26627 Reviews),10-14 Yrs,Not disclosed,Mumbai,"Qualifications: BTech, Any Graduation Skill re...",Data analysis\nDirect marketing\nEmail marketi...,27 DAYS AGO,14,27
32737,Package Consultant: SAP SCM GTS,IBM,4.2,(13370 Reviews),6-10 Yrs,Not disclosed,Pune,Experience in performing project management fu...,Data analysis\nProject management\nScheduling\...,27 DAYS AGO,10,27

# Then we will check and review our data randomly

In [20]:
naukri_data.iloc[15000]

job_post                                    Guidewire Integration Developer
company                   Pricewater House Coopers Service Delivery Cent...
company_rating                                                          3.8
company_review                                               (3201 Reviews)
exp_required                                                        4-9 Yrs
salary_offered                                                Not disclosed
job_location              Kolkata, Hyderabad/Secunderabad, Pune, Ahmedab...
job_description           Well versed in one of streams - configuration ...
required_skills           Webservices\nTomcat\nAzure\nBillingCenter\nTFS...
Posted_as_on_22_5_2022                                          13 DAYS AGO
max_exp_years                                                            9
day_of_posting                                                           13
Name: 15000, dtype: object

In [21]:
naukri_data.iloc[32737]

job_post                                    Package Consultant: SAP SCM GTS
company                                                                 IBM
company_rating                                                          4.2
company_review                                              (13370 Reviews)
exp_required                                                       6-10 Yrs
salary_offered                                                Not disclosed
job_location                                                           Pune
job_description           Experience in performing project management fu...
required_skills           Data analysis\nProject management\nScheduling\...
Posted_as_on_22_5_2022                                          27 DAYS AGO
max_exp_years                                                           10
day_of_posting                                                           27
Name: 32737, dtype: object

In [24]:
naukri_data.iloc[23456]

job_post                                                  Sr Data Scientist
company                                                    Apptio India LLP
company_rating                                                          4.3
company_review                                                 (12 Reviews)
exp_required                                                       7-11 Yrs
salary_offered                                                Not disclosed
job_location                                            Bangalore/Bengaluru
job_description           Bachelor s degree in a highly quantitative fie...
required_skills           Data science\nDeep Learning\nScikit\nMachine L...
Posted_as_on_22_5_2022                                           5 DAYS AGO
max_exp_years                                                           11
day_of_posting                                                            5
Name: 23456, dtype: object

In [26]:
naukri_data.iloc[63]

job_post                                    Software Engineering in Test II
company                                                             Neustar
company_rating                                                          4.5
company_review                                                 (25 Reviews)
exp_required                                                        4-6 Yrs
salary_offered                                                Not disclosed
job_location                                         Hyderabad/Secunderabad
job_description           Bachelors degree in computer science or engine...
required_skills           Computer science\nTelecom\nManager Quality Ass...
Posted_as_on_22_5_2022                                          11 DAYS AGO
max_exp_years                                                            6
day_of_posting                                                           11
Name: 62, dtype: object

In [2]:
naukri_data['day_of_posting'] = pd.to_numeric(naukri_data['day_of_posting'])

NameError: name 'pd' is not defined

# Yes !!! we got the problem , there was a string which was barring us from converting the day_of_posting column into numeric column that string was "TODAY" so we will convert that today to 0 number of days

In [ ]:
naukri_data['day_of_posting'] = naukri_data['day_of_posting'].replace(["TODAY"],"0")
naukri_data.head(24527)

In [51]:
naukri_data[naukri_data['day_of_posting']== "TODAY" ].head(50)

Empty DataFrame
Columns: [job_post, company, company_rating, company_review, exp_required, salary_offered, job_location, job_description, required_skills, Posted_as_on_22_5_2022, max_exp_years, day_of_posting]
Index: []

In [33]:
naukri_data['day_of_posting'] = naukri_data['day_of_posting'].str.strip()
naukri_data.head(253)

,job_post,company,company_rating,company_review,exp_required,salary_offered,job_location,job_description,required_skills,Posted_as_on_22_5_2022,max_exp_years,day_of_posting
0,Information Technology Executive,Marriott,4.2,(2907 Reviews),0-3 Yrs,Not disclosed,Bhopal,POSITION SUMMARY Troubleshoot and resolve tech...,Supervisor\nAdministration\nTactical planning\...,5 DAYS AGO,3,5
1,Associate Director-Information Technology(SAP),Unacademy,3.4,(544 Reviews),5-15 Yrs,Not disclosed,"Noida, Greater Noida",Support / manage timely delivery of custom dev...,Relationship management\nSAP MM\nPharma\nAnaly...,3 DAYS AGO,15,3
2,Lead - Information Technology,EchoIndia,4.0,(20 Reviews),11-13 Yrs,Not disclosed,Delhi / NCR,Experience in designing modern REST APIs that ...,Spring\nDocker\nSystem Design\nPaaS\nMicroserv...,1 DAY AGO,13,1
3,Information Technology - Project Manager,Tata International,4.1,(287 Reviews),4-8 Yrs,Not disclosed,Mumbai (All Areas),Should be able to manage a project using vario...,project management\nit projects\ninformation t...,2 DAYS AGO,8,2
4,Information Technology Trainee,Stefanini,3.8,(75 Reviews),2-7 Yrs,Not disclosed,Noida,The resource will be expected to cross skill\t...,POP\nTraining\nBasic\nNetworking\nIntern\nIT i...,4 DAYS AGO,7,4
...,...,...,...,...,...,...,...,...,...,...,...,...
248,Rocket Flyer Technology - Software Development...,Rocket Flyer Technology,4.5,(3 Reviews),1-5 Yrs,Not disclosed,Gurgaon/Gurugram,Requirements : - BE / BTech (CS)/ MCA from goo...,Java\nMongo\nJ2EE\nMySQL\nNOSQL\nMemCache\nNgi...,30 DAYS AGO,5,30
249,Rocket Flyer Technology - Software Development...,Rocket Flyer Technology,4.5,(3 Reviews),2-6 Yrs,Not disclosed,Gurgaon/Gurugram,Good understanding of React Component architec...,Redux\nOOP\nReact Native\nobject - oriented pr...,30 DAYS AGO,6,30
250,Rocket Flyer Technology - Software Development...,Rocket Flyer Technology,4.5,(3 Reviews),5-8 Yrs,Not disclosed,"Gurgaon/Gurugram, Others",The following skills are required : - In-Depth...,OpenCV\nVideoAI\nPython\nTensorflow\nLinux\nKe...,30 DAYS AGO,8,30
251,SAP QM Quality Management Software Configurati...,Accenture,4.1,(26528 Reviews),4-6 Yrs,Not disclosed,Gurgaon/Gurugram,Educational Qualification : Preferred MBA Work...,Configuration Management\nConsulting\nBusiness...,30+ DAYS AGO,6,30+
252,"Sr Software Engineer,PAN INDIA",Allscripts India pvt. ltd.,4.3,(395 Reviews),6-10 Yrs,Not disclosed,Remote,"Bachelors degree in Computer Science, Informat...",SSIS\nAgile methodologies\nGoogle Cloud Techno...,30+ DAYS AGO,10,30+

# Now we will remove all the data posted a month befor the given date is that 22 May 2022 so that we could properly take out insights from the data of a whole month

In [34]:
naukri_data.drop(naukri_data[naukri_data['day_of_posting'] == "30+"].index, inplace = True)
naukri_data.head(253)

,job_post,company,company_rating,company_review,exp_required,salary_offered,job_location,job_description,required_skills,Posted_as_on_22_5_2022,max_exp_years,day_of_posting
0,Information Technology Executive,Marriott,4.2,(2907 Reviews),0-3 Yrs,Not disclosed,Bhopal,POSITION SUMMARY Troubleshoot and resolve tech...,Supervisor\nAdministration\nTactical planning\...,5 DAYS AGO,3,5
1,Associate Director-Information Technology(SAP),Unacademy,3.4,(544 Reviews),5-15 Yrs,Not disclosed,"Noida, Greater Noida",Support / manage timely delivery of custom dev...,Relationship management\nSAP MM\nPharma\nAnaly...,3 DAYS AGO,15,3
2,Lead - Information Technology,EchoIndia,4.0,(20 Reviews),11-13 Yrs,Not disclosed,Delhi / NCR,Experience in designing modern REST APIs that ...,Spring\nDocker\nSystem Design\nPaaS\nMicroserv...,1 DAY AGO,13,1
3,Information Technology - Project Manager,Tata International,4.1,(287 Reviews),4-8 Yrs,Not disclosed,Mumbai (All Areas),Should be able to manage a project using vario...,project management\nit projects\ninformation t...,2 DAYS AGO,8,2
4,Information Technology Trainee,Stefanini,3.8,(75 Reviews),2-7 Yrs,Not disclosed,Noida,The resource will be expected to cross skill\t...,POP\nTraining\nBasic\nNetworking\nIntern\nIT i...,4 DAYS AGO,7,4
...,...,...,...,...,...,...,...,...,...,...,...,...
558,Software Test Engineer - B.Tech/MCA Freshers V...,QualiTlabs ( www.Qualitlabs.com ),5.0,(4 Reviews),0-1 Yrs,"3,00,000 PA.",Hyderabad/Secunderabad(Gachibowli),"Send your resume to jobs@qualitlabs.com, or ap...",Core Java\nJava\nCommunication Skills\nC\nCodi...,1 DAY AGO,1,1
559,Associate Manager - Software Development,Sutherland Global Services Inc,3.9,(4496 Reviews),5-10 Yrs,Not disclosed,Hyderabad/Secunderabad,Experience end-to-end machine learning pipelin...,regression analysis\nAzure Machine Learning Se...,22 DAYS AGO,10,22
560,Software Test Engineer,Web Access (I) Pvt. Ltd.,4.0,(11 Reviews),0-2 Yrs,Not disclosed,Mumbai (All Areas),Job DescriptionWe are looking for Software Tes...,Software Testing\nManual Testing\nAutomation T...,1 DAY AGO,2,1
561,Scrum Master Software Engineer,Zen Technologies Limited,3.7,(64 Reviews),0-3 Yrs,"3,00,000 - 5,00,000 PA.",Hyderabad/Secunderabad(Kondapur),Good client interfacing skills and leading the...,communication\nJIRA\nIT Skills\nProject Manage...,16 DAYS AGO,3,16
562,Freshers Software engineer .,Inspirisys Solutions Limited,3.9,(154 Reviews),0-0 Yrs,Not disclosed,Kolkata,Title : Freshers Software engineer Experience ...,CORE Java\nSQL,18 DAYS AGO,0,18

In [43]:
naukri_data['day_of_posting'] = naukri_data['day_of_posting'].replace(["TODAY"],"0")
naukri_data.head(24527)

,job_post,company,company_rating,company_review,exp_required,salary_offered,job_location,job_description,required_skills,Posted_as_on_22_5_2022,max_exp_years,day_of_posting
0,Information Technology Executive,Marriott,4.2,(2907 Reviews),0-3 Yrs,Not disclosed,Bhopal,POSITION SUMMARY Troubleshoot and resolve tech...,Supervisor\nAdministration\nTactical planning\...,5 DAYS AGO,3,5
1,Associate Director-Information Technology(SAP),Unacademy,3.4,(544 Reviews),5-15 Yrs,Not disclosed,"Noida, Greater Noida",Support / manage timely delivery of custom dev...,Relationship management\nSAP MM\nPharma\nAnaly...,3 DAYS AGO,15,3
2,Lead - Information Technology,EchoIndia,4.0,(20 Reviews),11-13 Yrs,Not disclosed,Delhi / NCR,Experience in designing modern REST APIs that ...,Spring\nDocker\nSystem Design\nPaaS\nMicroserv...,1 DAY AGO,13,1
3,Information Technology - Project Manager,Tata International,4.1,(287 Reviews),4-8 Yrs,Not disclosed,Mumbai (All Areas),Should be able to manage a project using vario...,project management\nit projects\ninformation t...,2 DAYS AGO,8,2
4,Information Technology Trainee,Stefanini,3.8,(75 Reviews),2-7 Yrs,Not disclosed,Noida,The resource will be expected to cross skill\t...,POP\nTraining\nBasic\nNetworking\nIntern\nIT i...,4 DAYS AGO,7,4
...,...,...,...,...,...,...,...,...,...,...,...,...
32733,TIBCO Spotfire,Birlasoft,3.8,(1133 Reviews),4-9 Yrs,Not disclosed,Bangalore/Bengaluru,"JD : Tibco Spotfire or, Tableau Reporting Deve...",TIBCO\ndata analysis\ncommunication\nPython\nT...,26 DAYS AGO,9,26
32734,Sr Consultant,Birlasoft,3.8,(1133 Reviews),5-10 Yrs,Not disclosed,Pune,SAP BI/BW DeveloperKey SkillsSAP BW 7.5 on HAN...,SAP BI/BW\nSAP BEx\nHANA\nAgile\nMS SQL\nSAP B...,26 DAYS AGO,10,26
32735,Package Consultant: SAP SCM GTS,IBM,4.2,(13370 Reviews),6-10 Yrs,Not disclosed,Pune,Experience in performing project management fu...,Data analysis\nProject management\nScheduling\...,27 DAYS AGO,10,27
32736,Associate Manager-Marketing Operations,Accenture,4.1,(26627 Reviews),10-14 Yrs,Not disclosed,Mumbai,"Qualifications: BTech, Any Graduation Skill re...",Data analysis\nDirect marketing\nEmail marketi...,27 DAYS AGO,14,27
32737,Package Consultant: SAP SCM GTS,IBM,4.2,(13370 Reviews),6-10 Yrs,Not disclosed,Pune,Experience in performing project management fu...,Data analysis\nProject management\nScheduling\...,27 DAYS AGO,10,27

# Now we will substract the number of days from the posted date to get exact date on which Job was posted on Naukri.com

In [53]:
naukri_data['date_of_posting'] = pd.to_datetime('2022-05-22') - pd.to_timedelta(naukri_data['day_of_posting'], unit='d')
naukri_data

,job_post,company,company_rating,company_review,exp_required,salary_offered,job_location,job_description,required_skills,Posted_as_on_22_5_2022,max_exp_years,day_of_posting,date_of_posting
0,Information Technology Executive,Marriott,4.2,(2907 Reviews),0-3 Yrs,Not disclosed,Bhopal,POSITION SUMMARY Troubleshoot and resolve tech...,Supervisor\nAdministration\nTactical planning\...,5 DAYS AGO,3,5.0,2022-05-17
1,Associate Director-Information Technology(SAP),Unacademy,3.4,(544 Reviews),5-15 Yrs,Not disclosed,"Noida, Greater Noida",Support / manage timely delivery of custom dev...,Relationship management\nSAP MM\nPharma\nAnaly...,3 DAYS AGO,15,3.0,2022-05-19
2,Lead - Information Technology,EchoIndia,4.0,(20 Reviews),11-13 Yrs,Not disclosed,Delhi / NCR,Experience in designing modern REST APIs that ...,Spring\nDocker\nSystem Design\nPaaS\nMicroserv...,1 DAY AGO,13,1.0,2022-05-21
3,Information Technology - Project Manager,Tata International,4.1,(287 Reviews),4-8 Yrs,Not disclosed,Mumbai (All Areas),Should be able to manage a project using vario...,project management\nit projects\ninformation t...,2 DAYS AGO,8,2.0,2022-05-20
4,Information Technology Trainee,Stefanini,3.8,(75 Reviews),2-7 Yrs,Not disclosed,Noida,The resource will be expected to cross skill\t...,POP\nTraining\nBasic\nNetworking\nIntern\nIT i...,4 DAYS AGO,7,4.0,2022-05-18
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32733,TIBCO Spotfire,Birlasoft,3.8,(1133 Reviews),4-9 Yrs,Not disclosed,Bangalore/Bengaluru,"JD : Tibco Spotfire or, Tableau Reporting Deve...",TIBCO\ndata analysis\ncommunication\nPython\nT...,26 DAYS AGO,9,26.0,2022-04-26
32734,Sr Consultant,Birlasoft,3.8,(1133 Reviews),5-10 Yrs,Not disclosed,Pune,SAP BI/BW DeveloperKey SkillsSAP BW 7.5 on HAN...,SAP BI/BW\nSAP BEx\nHANA\nAgile\nMS SQL\nSAP B...,26 DAYS AGO,10,26.0,2022-04-26
32735,Package Consultant: SAP SCM GTS,IBM,4.2,(13370 Reviews),6-10 Yrs,Not disclosed,Pune,Experience in performing project management fu...,Data analysis\nProject management\nScheduling\...,27 DAYS AGO,10,27.0,2022-04-25
32736,Associate Manager-Marketing Operations,Accenture,4.1,(26627 Reviews),10-14 Yrs,Not disclosed,Mumbai,"Qualifications: BTech, Any Graduation Skill re...",Data analysis\nDirect marketing\nEmail marketi...,27 DAYS AGO,14,27.0,2022-04-25
32737,Package Consultant: SAP SCM GTS,IBM,4.2,(13370 Reviews),6-10 Yrs,Not disclosed,Pune,Experience in performing project management fu...,Data analysis\nProject management\nScheduling\...,27 DAYS AGO,10,27.0,2022-04-25

# Now we will remove the  "Day of Posting"  Column as we have nothing to do with it

In [54]:
naukri_data.drop(['day_of_posting'], axis = 1, inplace = True)

In [55]:
naukri_data

,job_post,company,company_rating,company_review,exp_required,salary_offered,job_location,job_description,required_skills,Posted_as_on_22_5_2022,max_exp_years,date_of_posting
0,Information Technology Executive,Marriott,4.2,(2907 Reviews),0-3 Yrs,Not disclosed,Bhopal,POSITION SUMMARY Troubleshoot and resolve tech...,Supervisor\nAdministration\nTactical planning\...,5 DAYS AGO,3,2022-05-17
1,Associate Director-Information Technology(SAP),Unacademy,3.4,(544 Reviews),5-15 Yrs,Not disclosed,"Noida, Greater Noida",Support / manage timely delivery of custom dev...,Relationship management\nSAP MM\nPharma\nAnaly...,3 DAYS AGO,15,2022-05-19
2,Lead - Information Technology,EchoIndia,4.0,(20 Reviews),11-13 Yrs,Not disclosed,Delhi / NCR,Experience in designing modern REST APIs that ...,Spring\nDocker\nSystem Design\nPaaS\nMicroserv...,1 DAY AGO,13,2022-05-21
3,Information Technology - Project Manager,Tata International,4.1,(287 Reviews),4-8 Yrs,Not disclosed,Mumbai (All Areas),Should be able to manage a project using vario...,project management\nit projects\ninformation t...,2 DAYS AGO,8,2022-05-20
4,Information Technology Trainee,Stefanini,3.8,(75 Reviews),2-7 Yrs,Not disclosed,Noida,The resource will be expected to cross skill\t...,POP\nTraining\nBasic\nNetworking\nIntern\nIT i...,4 DAYS AGO,7,2022-05-18
...,...,...,...,...,...,...,...,...,...,...,...,...
32733,TIBCO Spotfire,Birlasoft,3.8,(1133 Reviews),4-9 Yrs,Not disclosed,Bangalore/Bengaluru,"JD : Tibco Spotfire or, Tableau Reporting Deve...",TIBCO\ndata analysis\ncommunication\nPython\nT...,26 DAYS AGO,9,2022-04-26
32734,Sr Consultant,Birlasoft,3.8,(1133 Reviews),5-10 Yrs,Not disclosed,Pune,SAP BI/BW DeveloperKey SkillsSAP BW 7.5 on HAN...,SAP BI/BW\nSAP BEx\nHANA\nAgile\nMS SQL\nSAP B...,26 DAYS AGO,10,2022-04-26
32735,Package Consultant: SAP SCM GTS,IBM,4.2,(13370 Reviews),6-10 Yrs,Not disclosed,Pune,Experience in performing project management fu...,Data analysis\nProject management\nScheduling\...,27 DAYS AGO,10,2022-04-25
32736,Associate Manager-Marketing Operations,Accenture,4.1,(26627 Reviews),10-14 Yrs,Not disclosed,Mumbai,"Qualifications: BTech, Any Graduation Skill re...",Data analysis\nDirect marketing\nEmail marketi...,27 DAYS AGO,14,2022-04-25
32737,Package Consultant: SAP SCM GTS,IBM,4.2,(13370 Reviews),6-10 Yrs,Not disclosed,Pune,Experience in performing project management fu...,Data analysis\nProject management\nScheduling\...,27 DAYS AGO,10,2022-04-25

In [56]:
naukri_data.drop(['Posted_as_on_22_5_2022'], axis = 1, inplace = True)
naukri_data

,job_post,company,company_rating,company_review,exp_required,salary_offered,job_location,job_description,required_skills,max_exp_years,date_of_posting
0,Information Technology Executive,Marriott,4.2,(2907 Reviews),0-3 Yrs,Not disclosed,Bhopal,POSITION SUMMARY Troubleshoot and resolve tech...,Supervisor\nAdministration\nTactical planning\...,3,2022-05-17
1,Associate Director-Information Technology(SAP),Unacademy,3.4,(544 Reviews),5-15 Yrs,Not disclosed,"Noida, Greater Noida",Support / manage timely delivery of custom dev...,Relationship management\nSAP MM\nPharma\nAnaly...,15,2022-05-19
2,Lead - Information Technology,EchoIndia,4.0,(20 Reviews),11-13 Yrs,Not disclosed,Delhi / NCR,Experience in designing modern REST APIs that ...,Spring\nDocker\nSystem Design\nPaaS\nMicroserv...,13,2022-05-21
3,Information Technology - Project Manager,Tata International,4.1,(287 Reviews),4-8 Yrs,Not disclosed,Mumbai (All Areas),Should be able to manage a project using vario...,project management\nit projects\ninformation t...,8,2022-05-20
4,Information Technology Trainee,Stefanini,3.8,(75 Reviews),2-7 Yrs,Not disclosed,Noida,The resource will be expected to cross skill\t...,POP\nTraining\nBasic\nNetworking\nIntern\nIT i...,7,2022-05-18
...,...,...,...,...,...,...,...,...,...,...,...
32733,TIBCO Spotfire,Birlasoft,3.8,(1133 Reviews),4-9 Yrs,Not disclosed,Bangalore/Bengaluru,"JD : Tibco Spotfire or, Tableau Reporting Deve...",TIBCO\ndata analysis\ncommunication\nPython\nT...,9,2022-04-26
32734,Sr Consultant,Birlasoft,3.8,(1133 Reviews),5-10 Yrs,Not disclosed,Pune,SAP BI/BW DeveloperKey SkillsSAP BW 7.5 on HAN...,SAP BI/BW\nSAP BEx\nHANA\nAgile\nMS SQL\nSAP B...,10,2022-04-26
32735,Package Consultant: SAP SCM GTS,IBM,4.2,(13370 Reviews),6-10 Yrs,Not disclosed,Pune,Experience in performing project management fu...,Data analysis\nProject management\nScheduling\...,10,2022-04-25
32736,Associate Manager-Marketing Operations,Accenture,4.1,(26627 Reviews),10-14 Yrs,Not disclosed,Mumbai,"Qualifications: BTech, Any Graduation Skill re...",Data analysis\nDirect marketing\nEmail marketi...,14,2022-04-25
32737,Package Consultant: SAP SCM GTS,IBM,4.2,(13370 Reviews),6-10 Yrs,Not disclosed,Pune,Experience in performing project management fu...,Data analysis\nProject management\nScheduling\...,10,2022-04-25

# Now we will extract minimum numbers of years of experience a candidate must have to apply for this Job

In [57]:
naukri_data['min_exp_years'] = naukri_data['exp_required'].str[:2]
naukri_data

,job_post,company,company_rating,company_review,exp_required,salary_offered,job_location,job_description,required_skills,max_exp_years,date_of_posting,min_exp_years
0,Information Technology Executive,Marriott,4.2,(2907 Reviews),0-3 Yrs,Not disclosed,Bhopal,POSITION SUMMARY Troubleshoot and resolve tech...,Supervisor\nAdministration\nTactical planning\...,3,2022-05-17,0-
1,Associate Director-Information Technology(SAP),Unacademy,3.4,(544 Reviews),5-15 Yrs,Not disclosed,"Noida, Greater Noida",Support / manage timely delivery of custom dev...,Relationship management\nSAP MM\nPharma\nAnaly...,15,2022-05-19,5-
2,Lead - Information Technology,EchoIndia,4.0,(20 Reviews),11-13 Yrs,Not disclosed,Delhi / NCR,Experience in designing modern REST APIs that ...,Spring\nDocker\nSystem Design\nPaaS\nMicroserv...,13,2022-05-21,11
3,Information Technology - Project Manager,Tata International,4.1,(287 Reviews),4-8 Yrs,Not disclosed,Mumbai (All Areas),Should be able to manage a project using vario...,project management\nit projects\ninformation t...,8,2022-05-20,4-
4,Information Technology Trainee,Stefanini,3.8,(75 Reviews),2-7 Yrs,Not disclosed,Noida,The resource will be expected to cross skill\t...,POP\nTraining\nBasic\nNetworking\nIntern\nIT i...,7,2022-05-18,2-
...,...,...,...,...,...,...,...,...,...,...,...,...
32733,TIBCO Spotfire,Birlasoft,3.8,(1133 Reviews),4-9 Yrs,Not disclosed,Bangalore/Bengaluru,"JD : Tibco Spotfire or, Tableau Reporting Deve...",TIBCO\ndata analysis\ncommunication\nPython\nT...,9,2022-04-26,4-
32734,Sr Consultant,Birlasoft,3.8,(1133 Reviews),5-10 Yrs,Not disclosed,Pune,SAP BI/BW DeveloperKey SkillsSAP BW 7.5 on HAN...,SAP BI/BW\nSAP BEx\nHANA\nAgile\nMS SQL\nSAP B...,10,2022-04-26,5-
32735,Package Consultant: SAP SCM GTS,IBM,4.2,(13370 Reviews),6-10 Yrs,Not disclosed,Pune,Experience in performing project management fu...,Data analysis\nProject management\nScheduling\...,10,2022-04-25,6-
32736,Associate Manager-Marketing Operations,Accenture,4.1,(26627 Reviews),10-14 Yrs,Not disclosed,Mumbai,"Qualifications: BTech, Any Graduation Skill re...",Data analysis\nDirect marketing\nEmail marketi...,14,2022-04-25,10
32737,Package Consultant: SAP SCM GTS,IBM,4.2,(13370 Reviews),6-10 Yrs,Not disclosed,Pune,Experience in performing project management fu...,Data analysis\nProject management\nScheduling\...,10,2022-04-25,6-


# Then cleaning it

In [58]:
naukri_data['min_exp_years'] = naukri_data['min_exp_years'].map(lambda x: x.lstrip('-').rstrip('-'))
naukri_data

,job_post,company,company_rating,company_review,exp_required,salary_offered,job_location,job_description,required_skills,max_exp_years,date_of_posting,min_exp_years
0,Information Technology Executive,Marriott,4.2,(2907 Reviews),0-3 Yrs,Not disclosed,Bhopal,POSITION SUMMARY Troubleshoot and resolve tech...,Supervisor\nAdministration\nTactical planning\...,3,2022-05-17,0
1,Associate Director-Information Technology(SAP),Unacademy,3.4,(544 Reviews),5-15 Yrs,Not disclosed,"Noida, Greater Noida",Support / manage timely delivery of custom dev...,Relationship management\nSAP MM\nPharma\nAnaly...,15,2022-05-19,5
2,Lead - Information Technology,EchoIndia,4.0,(20 Reviews),11-13 Yrs,Not disclosed,Delhi / NCR,Experience in designing modern REST APIs that ...,Spring\nDocker\nSystem Design\nPaaS\nMicroserv...,13,2022-05-21,11
3,Information Technology - Project Manager,Tata International,4.1,(287 Reviews),4-8 Yrs,Not disclosed,Mumbai (All Areas),Should be able to manage a project using vario...,project management\nit projects\ninformation t...,8,2022-05-20,4
4,Information Technology Trainee,Stefanini,3.8,(75 Reviews),2-7 Yrs,Not disclosed,Noida,The resource will be expected to cross skill\t...,POP\nTraining\nBasic\nNetworking\nIntern\nIT i...,7,2022-05-18,2
...,...,...,...,...,...,...,...,...,...,...,...,...
32733,TIBCO Spotfire,Birlasoft,3.8,(1133 Reviews),4-9 Yrs,Not disclosed,Bangalore/Bengaluru,"JD : Tibco Spotfire or, Tableau Reporting Deve...",TIBCO\ndata analysis\ncommunication\nPython\nT...,9,2022-04-26,4
32734,Sr Consultant,Birlasoft,3.8,(1133 Reviews),5-10 Yrs,Not disclosed,Pune,SAP BI/BW DeveloperKey SkillsSAP BW 7.5 on HAN...,SAP BI/BW\nSAP BEx\nHANA\nAgile\nMS SQL\nSAP B...,10,2022-04-26,5
32735,Package Consultant: SAP SCM GTS,IBM,4.2,(13370 Reviews),6-10 Yrs,Not disclosed,Pune,Experience in performing project management fu...,Data analysis\nProject management\nScheduling\...,10,2022-04-25,6
32736,Associate Manager-Marketing Operations,Accenture,4.1,(26627 Reviews),10-14 Yrs,Not disclosed,Mumbai,"Qualifications: BTech, Any Graduation Skill re...",Data analysis\nDirect marketing\nEmail marketi...,14,2022-04-25,10
32737,Package Consultant: SAP SCM GTS,IBM,4.2,(13370 Reviews),6-10 Yrs,Not disclosed,Pune,Experience in performing project management fu...,Data analysis\nProject management\nScheduling\...,10,2022-04-25,6

In [59]:
naukri_data.drop(['exp_required'], axis = 1, inplace = True)
naukri_data

,job_post,company,company_rating,company_review,salary_offered,job_location,job_description,required_skills,max_exp_years,date_of_posting,min_exp_years
0,Information Technology Executive,Marriott,4.2,(2907 Reviews),Not disclosed,Bhopal,POSITION SUMMARY Troubleshoot and resolve tech...,Supervisor\nAdministration\nTactical planning\...,3,2022-05-17,0
1,Associate Director-Information Technology(SAP),Unacademy,3.4,(544 Reviews),Not disclosed,"Noida, Greater Noida",Support / manage timely delivery of custom dev...,Relationship management\nSAP MM\nPharma\nAnaly...,15,2022-05-19,5
2,Lead - Information Technology,EchoIndia,4.0,(20 Reviews),Not disclosed,Delhi / NCR,Experience in designing modern REST APIs that ...,Spring\nDocker\nSystem Design\nPaaS\nMicroserv...,13,2022-05-21,11
3,Information Technology - Project Manager,Tata International,4.1,(287 Reviews),Not disclosed,Mumbai (All Areas),Should be able to manage a project using vario...,project management\nit projects\ninformation t...,8,2022-05-20,4
4,Information Technology Trainee,Stefanini,3.8,(75 Reviews),Not disclosed,Noida,The resource will be expected to cross skill\t...,POP\nTraining\nBasic\nNetworking\nIntern\nIT i...,7,2022-05-18,2
...,...,...,...,...,...,...,...,...,...,...,...
32733,TIBCO Spotfire,Birlasoft,3.8,(1133 Reviews),Not disclosed,Bangalore/Bengaluru,"JD : Tibco Spotfire or, Tableau Reporting Deve...",TIBCO\ndata analysis\ncommunication\nPython\nT...,9,2022-04-26,4
32734,Sr Consultant,Birlasoft,3.8,(1133 Reviews),Not disclosed,Pune,SAP BI/BW DeveloperKey SkillsSAP BW 7.5 on HAN...,SAP BI/BW\nSAP BEx\nHANA\nAgile\nMS SQL\nSAP B...,10,2022-04-26,5
32735,Package Consultant: SAP SCM GTS,IBM,4.2,(13370 Reviews),Not disclosed,Pune,Experience in performing project management fu...,Data analysis\nProject management\nScheduling\...,10,2022-04-25,6
32736,Associate Manager-Marketing Operations,Accenture,4.1,(26627 Reviews),Not disclosed,Mumbai,"Qualifications: BTech, Any Graduation Skill re...",Data analysis\nDirect marketing\nEmail marketi...,14,2022-04-25,10
32737,Package Consultant: SAP SCM GTS,IBM,4.2,(13370 Reviews),Not disclosed,Pune,Experience in performing project management fu...,Data analysis\nProject management\nScheduling\...,10,2022-04-25,6

# As we know reviews make a huge weightage in any job in demand so we will extract number of reviews from the company_review by cleaning all non numeric characters from the column so that we could do furthur analysis on the data

In [60]:
new2 = naukri_data["company_review"].str.split(" ", n = 1, expand = True)
naukri_data["companyreview"]= new2[0]
naukri_data

,job_post,company,company_rating,company_review,salary_offered,job_location,job_description,required_skills,max_exp_years,date_of_posting,min_exp_years,companyreview
0,Information Technology Executive,Marriott,4.2,(2907 Reviews),Not disclosed,Bhopal,POSITION SUMMARY Troubleshoot and resolve tech...,Supervisor\nAdministration\nTactical planning\...,3,2022-05-17,0,(2907
1,Associate Director-Information Technology(SAP),Unacademy,3.4,(544 Reviews),Not disclosed,"Noida, Greater Noida",Support / manage timely delivery of custom dev...,Relationship management\nSAP MM\nPharma\nAnaly...,15,2022-05-19,5,(544
2,Lead - Information Technology,EchoIndia,4.0,(20 Reviews),Not disclosed,Delhi / NCR,Experience in designing modern REST APIs that ...,Spring\nDocker\nSystem Design\nPaaS\nMicroserv...,13,2022-05-21,11,(20
3,Information Technology - Project Manager,Tata International,4.1,(287 Reviews),Not disclosed,Mumbai (All Areas),Should be able to manage a project using vario...,project management\nit projects\ninformation t...,8,2022-05-20,4,(287
4,Information Technology Trainee,Stefanini,3.8,(75 Reviews),Not disclosed,Noida,The resource will be expected to cross skill\t...,POP\nTraining\nBasic\nNetworking\nIntern\nIT i...,7,2022-05-18,2,(75
...,...,...,...,...,...,...,...,...,...,...,...,...
32733,TIBCO Spotfire,Birlasoft,3.8,(1133 Reviews),Not disclosed,Bangalore/Bengaluru,"JD : Tibco Spotfire or, Tableau Reporting Deve...",TIBCO\ndata analysis\ncommunication\nPython\nT...,9,2022-04-26,4,(1133
32734,Sr Consultant,Birlasoft,3.8,(1133 Reviews),Not disclosed,Pune,SAP BI/BW DeveloperKey SkillsSAP BW 7.5 on HAN...,SAP BI/BW\nSAP BEx\nHANA\nAgile\nMS SQL\nSAP B...,10,2022-04-26,5,(1133
32735,Package Consultant: SAP SCM GTS,IBM,4.2,(13370 Reviews),Not disclosed,Pune,Experience in performing project management fu...,Data analysis\nProject management\nScheduling\...,10,2022-04-25,6,(13370
32736,Associate Manager-Marketing Operations,Accenture,4.1,(26627 Reviews),Not disclosed,Mumbai,"Qualifications: BTech, Any Graduation Skill re...",Data analysis\nDirect marketing\nEmail marketi...,14,2022-04-25,10,(26627
32737,Package Consultant: SAP SCM GTS,IBM,4.2,(13370 Reviews),Not disclosed,Pune,Experience in performing project management fu...,Data analysis\nProject management\nScheduling\...,10,2022-04-25,6,(13370

In [61]:
naukri_data['companyreview3'] = naukri_data['companyreview'].map(lambda x: x.lstrip('('))

naukri_data

,job_post,company,company_rating,company_review,salary_offered,job_location,job_description,required_skills,max_exp_years,date_of_posting,min_exp_years,companyreview,companyreview3
0,Information Technology Executive,Marriott,4.2,(2907 Reviews),Not disclosed,Bhopal,POSITION SUMMARY Troubleshoot and resolve tech...,Supervisor\nAdministration\nTactical planning\...,3,2022-05-17,0,(2907,2907
1,Associate Director-Information Technology(SAP),Unacademy,3.4,(544 Reviews),Not disclosed,"Noida, Greater Noida",Support / manage timely delivery of custom dev...,Relationship management\nSAP MM\nPharma\nAnaly...,15,2022-05-19,5,(544,544
2,Lead - Information Technology,EchoIndia,4.0,(20 Reviews),Not disclosed,Delhi / NCR,Experience in designing modern REST APIs that ...,Spring\nDocker\nSystem Design\nPaaS\nMicroserv...,13,2022-05-21,11,(20,20
3,Information Technology - Project Manager,Tata International,4.1,(287 Reviews),Not disclosed,Mumbai (All Areas),Should be able to manage a project using vario...,project management\nit projects\ninformation t...,8,2022-05-20,4,(287,287
4,Information Technology Trainee,Stefanini,3.8,(75 Reviews),Not disclosed,Noida,The resource will be expected to cross skill\t...,POP\nTraining\nBasic\nNetworking\nIntern\nIT i...,7,2022-05-18,2,(75,75
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32733,TIBCO Spotfire,Birlasoft,3.8,(1133 Reviews),Not disclosed,Bangalore/Bengaluru,"JD : Tibco Spotfire or, Tableau Reporting Deve...",TIBCO\ndata analysis\ncommunication\nPython\nT...,9,2022-04-26,4,(1133,1133
32734,Sr Consultant,Birlasoft,3.8,(1133 Reviews),Not disclosed,Pune,SAP BI/BW DeveloperKey SkillsSAP BW 7.5 on HAN...,SAP BI/BW\nSAP BEx\nHANA\nAgile\nMS SQL\nSAP B...,10,2022-04-26,5,(1133,1133
32735,Package Consultant: SAP SCM GTS,IBM,4.2,(13370 Reviews),Not disclosed,Pune,Experience in performing project management fu...,Data analysis\nProject management\nScheduling\...,10,2022-04-25,6,(13370,13370
32736,Associate Manager-Marketing Operations,Accenture,4.1,(26627 Reviews),Not disclosed,Mumbai,"Qualifications: BTech, Any Graduation Skill re...",Data analysis\nDirect marketing\nEmail marketi...,14,2022-04-25,10,(26627,26627
32737,Package Consultant: SAP SCM GTS,IBM,4.2,(13370 Reviews),Not disclosed,Pune,Experience in performing project management fu...,Data analysis\nProject management\nScheduling\...,10,2022-04-25,6,(13370,13370

In [62]:
naukri_data.drop(['company_review','companyreview'], axis = 1, inplace = True)
naukri_data

,job_post,company,company_rating,salary_offered,job_location,job_description,required_skills,max_exp_years,date_of_posting,min_exp_years,companyreview3
0,Information Technology Executive,Marriott,4.2,Not disclosed,Bhopal,POSITION SUMMARY Troubleshoot and resolve tech...,Supervisor\nAdministration\nTactical planning\...,3,2022-05-17,0,2907
1,Associate Director-Information Technology(SAP),Unacademy,3.4,Not disclosed,"Noida, Greater Noida",Support / manage timely delivery of custom dev...,Relationship management\nSAP MM\nPharma\nAnaly...,15,2022-05-19,5,544
2,Lead - Information Technology,EchoIndia,4.0,Not disclosed,Delhi / NCR,Experience in designing modern REST APIs that ...,Spring\nDocker\nSystem Design\nPaaS\nMicroserv...,13,2022-05-21,11,20
3,Information Technology - Project Manager,Tata International,4.1,Not disclosed,Mumbai (All Areas),Should be able to manage a project using vario...,project management\nit projects\ninformation t...,8,2022-05-20,4,287
4,Information Technology Trainee,Stefanini,3.8,Not disclosed,Noida,The resource will be expected to cross skill\t...,POP\nTraining\nBasic\nNetworking\nIntern\nIT i...,7,2022-05-18,2,75
...,...,...,...,...,...,...,...,...,...,...,...
32733,TIBCO Spotfire,Birlasoft,3.8,Not disclosed,Bangalore/Bengaluru,"JD : Tibco Spotfire or, Tableau Reporting Deve...",TIBCO\ndata analysis\ncommunication\nPython\nT...,9,2022-04-26,4,1133
32734,Sr Consultant,Birlasoft,3.8,Not disclosed,Pune,SAP BI/BW DeveloperKey SkillsSAP BW 7.5 on HAN...,SAP BI/BW\nSAP BEx\nHANA\nAgile\nMS SQL\nSAP B...,10,2022-04-26,5,1133
32735,Package Consultant: SAP SCM GTS,IBM,4.2,Not disclosed,Pune,Experience in performing project management fu...,Data analysis\nProject management\nScheduling\...,10,2022-04-25,6,13370
32736,Associate Manager-Marketing Operations,Accenture,4.1,Not disclosed,Mumbai,"Qualifications: BTech, Any Graduation Skill re...",Data analysis\nDirect marketing\nEmail marketi...,14,2022-04-25,10,26627
32737,Package Consultant: SAP SCM GTS,IBM,4.2,Not disclosed,Pune,Experience in performing project management fu...,Data analysis\nProject management\nScheduling\...,10,2022-04-25,6,13370

In [63]:
naukri_data.rename(columns = {'companyreview3':'company_review'}, inplace = True)
naukri_data

,job_post,company,company_rating,salary_offered,job_location,job_description,required_skills,max_exp_years,date_of_posting,min_exp_years,company_review
0,Information Technology Executive,Marriott,4.2,Not disclosed,Bhopal,POSITION SUMMARY Troubleshoot and resolve tech...,Supervisor\nAdministration\nTactical planning\...,3,2022-05-17,0,2907
1,Associate Director-Information Technology(SAP),Unacademy,3.4,Not disclosed,"Noida, Greater Noida",Support / manage timely delivery of custom dev...,Relationship management\nSAP MM\nPharma\nAnaly...,15,2022-05-19,5,544
2,Lead - Information Technology,EchoIndia,4.0,Not disclosed,Delhi / NCR,Experience in designing modern REST APIs that ...,Spring\nDocker\nSystem Design\nPaaS\nMicroserv...,13,2022-05-21,11,20
3,Information Technology - Project Manager,Tata International,4.1,Not disclosed,Mumbai (All Areas),Should be able to manage a project using vario...,project management\nit projects\ninformation t...,8,2022-05-20,4,287
4,Information Technology Trainee,Stefanini,3.8,Not disclosed,Noida,The resource will be expected to cross skill\t...,POP\nTraining\nBasic\nNetworking\nIntern\nIT i...,7,2022-05-18,2,75
...,...,...,...,...,...,...,...,...,...,...,...
32733,TIBCO Spotfire,Birlasoft,3.8,Not disclosed,Bangalore/Bengaluru,"JD : Tibco Spotfire or, Tableau Reporting Deve...",TIBCO\ndata analysis\ncommunication\nPython\nT...,9,2022-04-26,4,1133
32734,Sr Consultant,Birlasoft,3.8,Not disclosed,Pune,SAP BI/BW DeveloperKey SkillsSAP BW 7.5 on HAN...,SAP BI/BW\nSAP BEx\nHANA\nAgile\nMS SQL\nSAP B...,10,2022-04-26,5,1133
32735,Package Consultant: SAP SCM GTS,IBM,4.2,Not disclosed,Pune,Experience in performing project management fu...,Data analysis\nProject management\nScheduling\...,10,2022-04-25,6,13370
32736,Associate Manager-Marketing Operations,Accenture,4.1,Not disclosed,Mumbai,"Qualifications: BTech, Any Graduation Skill re...",Data analysis\nDirect marketing\nEmail marketi...,14,2022-04-25,10,26627
32737,Package Consultant: SAP SCM GTS,IBM,4.2,Not disclosed,Pune,Experience in performing project management fu...,Data analysis\nProject management\nScheduling\...,10,2022-04-25,6,13370

In [64]:
naukri_data['required_skills'] = naukri_data['required_skills'].replace(r'\n',' , ', regex=True) 
naukri_data

,job_post,company,company_rating,salary_offered,job_location,job_description,required_skills,max_exp_years,date_of_posting,min_exp_years,company_review
0,Information Technology Executive,Marriott,4.2,Not disclosed,Bhopal,POSITION SUMMARY Troubleshoot and resolve tech...,"Supervisor , Administration , Tactical plannin...",3,2022-05-17,0,2907
1,Associate Director-Information Technology(SAP),Unacademy,3.4,Not disclosed,"Noida, Greater Noida",Support / manage timely delivery of custom dev...,"Relationship management , SAP MM , Pharma , An...",15,2022-05-19,5,544
2,Lead - Information Technology,EchoIndia,4.0,Not disclosed,Delhi / NCR,Experience in designing modern REST APIs that ...,"Spring , Docker , System Design , PaaS , Micro...",13,2022-05-21,11,20
3,Information Technology - Project Manager,Tata International,4.1,Not disclosed,Mumbai (All Areas),Should be able to manage a project using vario...,"project management , it projects , information...",8,2022-05-20,4,287
4,Information Technology Trainee,Stefanini,3.8,Not disclosed,Noida,The resource will be expected to cross skill\t...,"POP , Training , Basic , Networking , Intern ,...",7,2022-05-18,2,75
...,...,...,...,...,...,...,...,...,...,...,...
32733,TIBCO Spotfire,Birlasoft,3.8,Not disclosed,Bangalore/Bengaluru,"JD : Tibco Spotfire or, Tableau Reporting Deve...","TIBCO , data analysis , communication , Python...",9,2022-04-26,4,1133
32734,Sr Consultant,Birlasoft,3.8,Not disclosed,Pune,SAP BI/BW DeveloperKey SkillsSAP BW 7.5 on HAN...,"SAP BI/BW , SAP BEx , HANA , Agile , MS SQL , ...",10,2022-04-26,5,1133
32735,Package Consultant: SAP SCM GTS,IBM,4.2,Not disclosed,Pune,Experience in performing project management fu...,"Data analysis , Project management , Schedulin...",10,2022-04-25,6,13370
32736,Associate Manager-Marketing Operations,Accenture,4.1,Not disclosed,Mumbai,"Qualifications: BTech, Any Graduation Skill re...","Data analysis , Direct marketing , Email marke...",14,2022-04-25,10,26627
32737,Package Consultant: SAP SCM GTS,IBM,4.2,Not disclosed,Pune,Experience in performing project management fu...,"Data analysis , Project management , Schedulin...",10,2022-04-25,6,13370

# Finally   verifying the data randomly to reduce teh margin of error as far as we could

In [65]:
naukri_data.iloc[917]

job_post           Sr. Software Engr / Tech Lead . - Full stack -...
company                               PrismHR ( US Based IT Company)
company_rating                                                   4.0
salary_offered                             10,00,000 - 18,00,000 PA.
job_location       Noida(Noida-Greater Noida Expressway), Greater...
job_description    PrismHR is a US Based fast-growing IT company ...
required_skills    SQL Server , JQuery , ASP.Net , IT Skills , c#...
max_exp_years                                                     9
date_of_posting                                  2022-05-22 00:00:00
min_exp_years                                                      5
company_review                                                    16
Name: 1842, dtype: object

In [67]:
naukri_data.iloc[1546]

job_post                                   Devops Engineer (DM-3343)
company                                  Oodles Technologies Pvt Ltd
company_rating                                                   3.0
salary_offered                                         Not disclosed
job_location                                        Gurgaon/Gurugram
job_description    Experience with Github is a mustLinux Systems ...
required_skills    Jenkins , Docker , Linux , AWS , Devops , Ansi...
max_exp_years                                                     1
date_of_posting                                  2022-05-19 00:00:00
min_exp_years                                                      0
company_review                                                   116
Name: 2946, dtype: object

In [68]:
naukri_data.iloc[321]

job_post           Software Engineer || Python || Python Scriptin...
company                                              Innodata Isogen
company_rating                                                   3.9
salary_offered                                         Not disclosed
job_location                                                   Noida
job_description    We are looking for a passionate, highly talent...
required_skills    SQL Server , Python , Scripting , IT Skills , ...
max_exp_years                                                     5
date_of_posting                                  2022-05-20 00:00:00
min_exp_years                                                      2
company_review                                                   328
Name: 755, dtype: object

# As our data cleaning has been reached to 5 star level so we will use this data for analysis. The data has still some shortcomings but at least it is sufficient for us to analyze the data

In [69]:
naukri_data.to_csv('cleaned_noukri_data2.csv')

Links-----



https://stackoverflow.com
https://corporatefinanceinstitute.com
https://towardsdatascience.com
https://www.geeksforgeeks.org
https://www.projectpro.io
https://pandas.pydata.org
https://jamesrledoux.com
https://blog.rtwilson.com
https://www.geeksforgeeks.org
https://www.codegrepper.com
https://www.stackvidhya.com
https://www.adamsmith.haus