# Week 12 Assignment

In [1]:
# import libs
import re
import pandas as pd

# Json
```json
[
  {
    "title": "Python Crash Course, 2nd Edition",
    "authors": ["Eric Matthes"],
    "price": 39.95,
    "discount_price": 23.99,
    "publish_date": "May 21, 2019"
  },
  {
    "title": "Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow",
    "authors": ["Aurélien Géron"],
    "price": 63.99,
    "discount_price": 37.49,
    "publish_date": "Sep 5, 2019"
  },
  {
    "title": "Software Engineering at Google",
    "authors": ["Titus Winters", "Tom Manshreck", "Hyrum Wright"],
    "price": 50.99,
    "discount_price": 34.25,
    "publish_date": "Feb 28, 2020"
  }
]
```

In [2]:
# load json file, transfer to pandas data frame
json_df = pd.read_json("https://raw.githubusercontent.com/Yuehao-Wang/AIM-5001/master/data/W12_Json.json")
json_df

,title,authors,price,discount_price,publish_date
0,"Python Crash Course, 2nd Edition",[Eric Matthes],39.95,23.99,"May 21, 2019"
1,"Hands-On Machine Learning with Scikit-Learn, K...",[Aurélien Géron],63.99,37.49,"Sep 5, 2019"
2,Software Engineering at Google,"[Titus Winters, Tom Manshreck, Hyrum Wright]",50.99,34.25,"Feb 28, 2020"

In the dataframe, there is a list of [Titus Winters, Tom Manshreck, Hyrum Wright]. I will convert list to string.

For example:

[Titus Winters, Tom Manshreck, Hyrum Wright]  

convert to

Titus Winters, Tom Manshreck, Hyrum Wright

In [3]:
# True if x % 2 == 0 else False
def convert_lst_to_str(s):
    if isinstance(s, list):
        return ', '.join(s)
    else:
        return s

json_df['authors'] = json_df['authors'].apply(lambda x: convert_lst_to_str(x))
json_df

,title,authors,price,discount_price,publish_date
0,"Python Crash Course, 2nd Edition",Eric Matthes,39.95,23.99,"May 21, 2019"
1,"Hands-On Machine Learning with Scikit-Learn, K...",Aurélien Géron,63.99,37.49,"Sep 5, 2019"
2,Software Engineering at Google,"Titus Winters, Tom Manshreck, Hyrum Wright",50.99,34.25,"Feb 28, 2020"

# Html
```HTML
<table>
<thead>
<tr>
<td>title</td>
<td>authors</td>
<td>price</td>
<td>discount_price</td>
<td>publish_date</td>
</tr>
</thead>
<tbody>
<tr>
<td>Python Crash Course, 2nd Edition</td>
<td>Eric Matthes</td>
<td>39.95</td>
<td>23.99</td>
<td>May 21, 2019</td>
</tr>
<tr>
<td>Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow</td>
<td>Aurélien Géron</td>
<td>63.99</td>
<td>37.49</td>
<td>Sep 5, 2019</td>
</tr>
<tr>
<td>Software Engineering at Google</td>
<td>Titus Winters, Tom Manshreck, Hyrum Wright</td>
<td>50.99</td>
<td>34.25</td>
<td>Feb 28, 2020</td>
</tr>
</tbody>
</table>
```

In [4]:
# load html file, transfer to pandas data frame
html_tables = pd.read_html("https://raw.githubusercontent.com/Yuehao-Wang/AIM-5001/master/data/W12_HTML.html")
html_tables

[                                               title  \
 0                   Python Crash Course, 2nd Edition
 1  Hands-On Machine Learning with Scikit-Learn, K...
 2                     Software Engineering at Google

                                       authors  price  discount_price  \
 0                                Eric Matthes  39.95           23.99
 1                            AurÃ©lien GÃ©ron  63.99           37.49
 2  Titus Winters, Tom Manshreck, Hyrum Wright  50.99           34.25

    publish_date
 0  May 21, 2019
 1   Sep 5, 2019
 2  Feb 28, 2020  ]

In [5]:
# get the 1st table
html_df = html_tables[0]
html_df

,title,authors,price,discount_price,publish_date
0,"Python Crash Course, 2nd Edition",Eric Matthes,39.95,23.99,"May 21, 2019"
1,"Hands-On Machine Learning with Scikit-Learn, K...",AurÃ©lien GÃ©ron,63.99,37.49,"Sep 5, 2019"
2,Software Engineering at Google,"Titus Winters, Tom Manshreck, Hyrum Wright",50.99,34.25,"Feb 28, 2020"

# XML

In [6]:
# import urllib.request
import urllib.request

# load the objectify() function from the lxml library
from lxml import objectify

## XML method 1

Mutiple authors has been written in a element.

```XML
<?xml version="1.0" encoding="UTF-8" ?>
<books>
	<book>
		<title>Python Crash Course, 2nd Edition</title>
		<authors>Eric Matthes</authors>
		<price>39.95</price>
		<discount_price>23.99</discount_price>
		<publish_date>May 21, 2019</publish_date>
	</book>
	<book>
		<title>Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow</title>
		<authors>Aurélien Géron</authors>
		<price>63.99</price>
		<discount_price>37.49</discount_price>
		<publish_date>Sep 5, 2019</publish_date>
	</book>
	<book>
		<title>Software Engineering at Google</title>
		<authors>Titus Winters, Tom Manshreck, Hyrum Wright</authors>
		<price>50.99</price>
		<discount_price>34.25</discount_price>
		<publish_date>Feb 28, 2020</publish_date>
	</book>
</books>  
```

In [7]:
# open the web page containing the data set: be sure to capture the 
# header info separately from the path
path, headers = urllib.request.urlretrieve('https://raw.githubusercontent.com/Yuehao-Wang/AIM-5001/master/data/W12_XML.xml')

# objectify() is then used to parse the web page
parsed = objectify.parse(open(path))

# now get a reference to the root node of the XML file
root = parsed.getroot()

In [8]:
# define an empty list that will be used to store the parsed data
data = []

# root.book is a generator that we use to extract each <book>
# element from the XML data
for elt in root.book:
     # for each record, create a dict of tag names (e.g., 'title')
    el_data = {}
    for child in elt.getchildren():
        el_data[child.tag] = child.pyval
        
    data.append(el_data)

In [9]:
# now check the results
perf = pd.DataFrame(data)
perf.head()

,title,authors,price,discount_price,publish_date
0,"Python Crash Course, 2nd Edition",Eric Matthes,39.95,23.99,"May 21, 2019"
1,"Hands-On Machine Learning with Scikit-Learn, K...",AurÃ©lien GÃ©ron,63.99,37.49,"Sep 5, 2019"
2,Software Engineering at Google,"Titus Winters, Tom Manshreck, Hyrum Wright",50.99,34.25,"Feb 28, 2020"

## XML method 2

Mutiple authors has been written in a list sub elements.

```XML
<?xml version="1.0" encoding="UTF-8" ?>
<books>
	<book>
		<title>Python Crash Course, 2nd Edition</title>
		<authors>
			<author>Eric Matthes</author>
		</authors>
		<price>39.95</price>
		<discount_price>23.99</discount_price>
		<publish_date>May 21, 2019</publish_date>
	</book>
	<book>
		<title>Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow</title>
		<authors>
			<author>Aurélien Géron</author>
		</authors>
		<price>63.99</price>
		<discount_price>37.49</discount_price>
		<publish_date>Sep 5, 2019</publish_date>
	</book>
	<book>
		<title>Software Engineering at Google</title>
		<authors>
			<author>Titus Winters</author>
			<author>Tom Manshreck</author>
			<author>Hyrum Wright</author>
		</authors>
		<price>50.99</price>
		<discount_price>34.25</discount_price>
		<publish_date>Feb 28, 2020</publish_date>
	</book>
</books>  
```

In [10]:
# open the web page containing the data set: be sure to capture the 
# header info separately from the path
path, headers = urllib.request.urlretrieve('https://raw.githubusercontent.com/Yuehao-Wang/AIM-5001/master/data/W12_XML2')

# objectify() is then used to parse the web page
parsed = objectify.parse(open(path))

# now get a reference to the root node of the XML file
root = parsed.getroot()

In [11]:
# define an empty list that will be used to store the parsed data
data = []

# root.book is a generator that we use to extract each <book>
# element from the XML data
for elt in root.book:
     # for each record, create a dict of tag names (e.g., 'title')
    el_data = {}
    for child in elt.getchildren():
        
        if child.tag != 'authors':
            el_data[child.tag] = child.pyval
        else:
            # to read list of author, and put into authors
            authors = []
            for child in elt.authors.getchildren():
                authors.append( child.pyval )
            el_data['authors'] = ', '.join(authors)
                
    data.append(el_data)

# now check the results
perf = pd.DataFrame(data)
perf.head()

,title,authors,price,discount_price,publish_date
0,"Python Crash Course, 2nd Edition",Eric Matthes,39.95,23.99,"May 21, 2019"
1,"Hands-On Machine Learning with Scikit-Learn, K...",AurÃ©lien GÃ©ron,63.99,37.49,"Sep 5, 2019"
2,Software Engineering at Google,"Titus Winters, Tom Manshreck, Hyrum Wright",50.99,34.25,"Feb 28, 2020"

# New York Times API

In [12]:
# import requests
import requests

#### New York Times Movie Reviewers API

https://api.nytimes.com/svc/movies/v2/critics/{reviewer}.json

Path Parameters
reviewer (required)	
string

Reviewer name or "all" for all reviewers, "full-time" for full-time reviewers, or "part-time" for part-time reviewers.

In [13]:
def my_nyt_movie_reviews(s = 'all'):
    """
    Query new york times movie reviewers

    Args:
      s: aLL, full-time, part-time.


    Returns:
      json

    Raises:
      none

    Sample:
    >>> s = 'all'
    >>> my_nyt_movie_reviews(s)
    {'A0': 'a', 'A1': 'b'}
    
    >>> lst = ['a', 'b', 'c']
    >>> makedict(lst, 10)
    {'A0': 'a', 'A1': 'b', 'A2': 'c'}

    >>> lst = []
    >>> makedict(lst, 3)
    {'status': 'OK',
     'copyright': '...'
     ...
    }
    """
    
    # my new york times developer key
    nyt_key = "FjuDAqGEpWJae33FcbQBfwWG8KRswWo6"

    # url, Movie Reviews API
    # I choose all.json. Then I add my developer key
    url = 'https://api.nytimes.com/svc/movies/v2/critics/' + s + '.json?api-key=' + nyt_key

    # sent a request
    r = requests.get(url)

    # get response and get a json data
    json_data = r.json()
    
    return json_data

# show
json_data = my_nyt_movie_reviews('all')

json_data

{'status': 'OK',
 'copyright': 'Copyright (c) 2020 The New York Times Company. All Rights Reserved.',
 'num_results': 82,
 'results': [{'display_name': 'A. O. Scott',
   'sort_name': 'A. O. Scott',
   'status': 'full-time',
   'bio': 'A. O. Scott joined The New York Times as a film critic in January 2000, and was named a chief critic in 2004. Previously, Mr. Scott had been the lead Sunday book reviewer for Newsday and a frequent contributor to Slate, The New York Review of Books, and many other publications. \n<br/><br/>\nIn the 1990s he served on the editorial staffs of Lingua Franca and The New York Review of Books. He also edited "A Bolt from the Blue and Other Essays," a collection by Mary McCarthy, which was published by The New York Review of Books in 2002. \n<br/><br/>\nMr. Scott was a finalist for the Pulitzer Prize in Criticism in 2010, the same year he served as co-host (with Michael Phillips of the Chicago Tribune) on the last season of "At the Movies," the syndicated film-reviewing program started by Roger Ebert and Gene Siskel.\n<br/><br/>\nA frequent presence on radio and television, Mr. Scott is Distinguished Professor of Film Criticism at Wesleyan University and the author of Better Living Through Criticism, forthcoming in 2016 from The Penguin Press. A collection of his film writing will be published by Penguin in 2017. \n<br/><br/>\nHe lives in Brooklyn with his family.',
   'seo_name': 'A-O-Scott',
   'multimedia': {'resource': {'type': 'image',
     'src': 'http://static01.nyt.com/images/2015/10/07/topics/ao-scott/ao-scott-articleInline.jpg',
     'height': 163,
     'width': 220,
     'credit': 'Earl Wilson/<br/>The New York Times'}}},
  {'display_name': 'Manohla Dargis',
   'sort_name': 'Manohla Dargis',
   'status': 'full-time',
   'bio': 'Manohla Dargis is the co-chief film critic for The Times, where she started in 2004. She has also written for The Los Angeles Times, where she was a chief film critic, and for the LA Weekly, where she was both a film critic and the film editor. She lives in Los Angeles.',
   'seo_name': 'Manohla-Dargis',
   'multimedia': None},
  {'display_name': 'Stephen Holden',
   'sort_name': 'Stephen Holden',
   'status': 'full-time',
   'bio': 'Stephen Holden is a film and music critic for The Times; he joined the culture staff in 1988. Prior to that, he was a pop music critic and journalist for Rolling Stone, The Village Voice, and numerous other magazines and anthologies. Drawing on his experiences as a journalist and record executive, he wrote a satirical novel about the record business, "Triple Platinum,"  that was published in 1980 by Dell Books. In 1986, he won a Grammy with six other writers for Best Album Notes for "The Voice: The Columbia Years, a Frank Sinatra Anthology." Born July 18, 1941, Mr. Holden graduated from Yale University in 1963 with a Bachelor of Arts degree in English and was elected Class Poet.',
   'seo_name': 'Stephen-Holden',
   'multimedia': {'resource': {'type': 'image',
     'src': 'http://nytimes.com/images/2007/01/05/movies/sholden.163.jpg',
     'height': 163,
     'width': 220,
     'credit': 'Brent Murray/<br>NYTimes.com'}}},
  {'display_name': 'Renata Adler',
   'sort_name': 'Adler, Renata',
   'status': 'part-time',
   'bio': '',
   'seo_name': 'Renata-Adler',
   'multimedia': None},
  {'display_name': 'Mordaunt Hall',
   'sort_name': 'Hall, Mordaunt ',
   'status': 'part-time',
   'bio': '',
   'seo_name': 'Mordaunt-Hall',
   'multimedia': None},
  {'display_name': 'Thomas M. Pryor',
   'sort_name': 'Pryor, Thomas M.',
   'status': 'part-time',
   'bio': '',
   'seo_name': 'Thomas-M-Pryor',
   'multimedia': None},
  {'display_name': 'Eugene Archer',
   'sort_name': 'Archer, Eugene',
   'status': 'part-time',
   'bio': '',
   'seo_name': 'Eugene-Archer',
   'multimedia': None},
  {'display_name': 'Donal J. Henahan',
   'sort_name': 'Henahan, Donal J.',
   'status': 'part-time',
   'bio': '',
   'seo_name': 'Donal-J-Henahan',
   'multimedia': None},
  {'display_name': 'Nora Sayre',
   'sort_name': 'Sayre, Nora',
   'status': 'part-time',
   'bio': '',
   'seo_name': 'Nora-Sayre',
   'multimedia': None},
  {'display_name': 'D. J. R. Bruckner',
   'sort_name': 'Bruckner, D. J. R. ',
   'status': 'part-time',
   'bio': '',
   'seo_name': 'D-J-R-Bruckner',
   'multimedia': None},
  {'display_name': 'Caryn James',
   'sort_name': 'James, Caryn',
   'status': 'part-time',
   'bio': '',
   'seo_name': 'Caryn-James',
   'multimedia': None},
  {'display_name': 'Harold C. Schonberg',
   'sort_name': 'Schonberg, Harold C.',
   'status': 'part-time',
   'bio': '',
   'seo_name': 'Harold-C-Schonberg',
   'multimedia': None},
  {'display_name': 'Tom Buckley',
   'sort_name': 'Buckley, Tom ',
   'status': 'part-time',
   'bio': '',
   'seo_name': 'Tom-Buckley',
   'multimedia': None},
  {'display_name': 'Stanley Kauffman',
   'sort_name': 'Kauffman, Stanley',
   'status': 'part-time',
   'bio': '',
   'seo_name': 'Stanley-Kauffman',
   'multimedia': None},
  {'display_name': 'Andre Sennwald',
   'sort_name': 'Sennwald, Andre',
   'status': 'part-time',
   'bio': '',
   'seo_name': 'Andre-Sennwald',
   'multimedia': None},
  {'display_name': 'Vincent Canby',
   'sort_name': 'Canby, Vincent',
   'status': 'part-time',
   'bio': '',
   'seo_name': 'Vincent-Canby',
   'multimedia': None},
  {'display_name': 'Dave Kehr',
   'sort_name': 'Kehr, Dave',
   'status': 'part-time',
   'bio': '',
   'seo_name': 'Dave-Kehr',
   'multimedia': None},
  {'display_name': 'Dana Stevens',
   'sort_name': 'Stevens, Dana',
   'status': 'part-time',
   'bio': '',
   'seo_name': 'Dana-Stevens',
   'multimedia': None},
  {'display_name': 'B. R. Crisler',
   'sort_name': 'Crisler, B. R.',
   'status': 'part-time',
   'bio': '',
   'seo_name': 'B-R-Crisler',
   'multimedia': None},
  {'display_name': 'Hilton Kramer',
   'sort_name': 'Kramer, Hilton',
   'status': 'part-time',
   'bio': '',
   'seo_name': 'Hilton-Kramer',
   'multimedia': None},
  {'display_name': 'Michael Stern',
   'sort_name': 'Stern, Michael',
   'status': 'part-time',
   'bio': '',
   'seo_name': 'Michael-Stern',
   'multimedia': None},
  {'display_name': 'Bosley Crowther',
   'sort_name': 'Crowther, Bosley',
   'status': 'part-time',
   'bio': '',
   'seo_name': 'Bosley-Crowther',
   'multimedia': None},
  {'display_name': 'Ned Martel',
   'sort_name': 'Martel, Ned',
   'status': 'part-time',
   'bio': '',
   'seo_name': 'Ned-Martel',
   'multimedia': None},
  {'display_name': 'Theodore Strauss',
   'sort_name': 'Strauss, Theodore',
   'status': 'part-time',
   'bio': '',
   'seo_name': 'Theodore-Strauss',
   'multimedia': None},
  {'display_name': 'Richard Eder',
   'sort_name': 'Eder, Richard',
   'status': 'part-time',
   'bio': '',
   'seo_name': 'Richard-Eder',
   'multimedia': None},
  {'display_name': 'Janet Maslin',
   'sort_name': 'Maslin, Janet',
   'status': 'part-time',
   'bio': '',
   'seo_name': 'Janet-Maslin',
   'multimedia': None},
  {'display_name': 'Howard Thompson',
   'sort_name': 'Thompson, Howard',
   'status': 'part-time',
   'bio': '',
   'seo_name': 'Howard-Thompson',
   'multimedia': None},
  {'display_name': 'Anita Gates',
   'sort_name': 'Gates, Anita',
   'status': 'part-time',
   'bio': '',
   'seo_name': 'Anita-Gates',
   'multimedia': None},
  {'display_name': 'John T. McManus',
   'sort_name': 'McManus, John T.',
   'status': 'part-time',
   'bio': '',
   'seo_name': 'John-T-McManus',
   'multimedia': None},
  {'display_name': 'Lawrence Van Gelder',
   'sort_name': 'Van Gelder, Lawrence',
   'status': 'part-time',
   'bio': '',
   'seo_name': 'Lawrence-Van-Gelder',
   'multimedia': None},
  {'display_name': 'Walter Goodman',
   'sort_name': 'Goodman, Walter',
   'status': 'part-time',
   'bio': '',
   'seo_name': 'Walter-Goodman',
   'multimedia': None},
  {'display_name': 'Elvis Mitchell',
   'sort_name': 'Mitchell, Elvis',
   'status': 'part-time',
   'bio': '',
   'seo_name': 'Elvis-Mitchell',
   'multimedia': None},
  {'display_name': 'A. H. Weiler',
   'sort_name': 'Weiler, A. H.',
   'status': 'part-time',
   'bio': '',
   'seo_name': 'A-H-Weiler',
   'multimedia': None},
  {'display_name': 'Roger Greenspun',
   'sort_name': 'Greenspun, Roger',
   'status': 'part-time',
   'bio': '',
   'seo_name': 'Roger-Greenspun',
   'multimedia': None},
  {'display_name': 'Frank S. Nugent',
   'sort_name': 'Nugent, Frank S.',
   'status': 'part-time',
   'bio': '',
   'seo_name': 'Frank-S-Nugent',
   'multimedia': None},
  {'display_name': 'Matt Zoller Seitz',
   'sort_name': 'Seitz, Matt Zoller',
   'status': 'part-time',
   'bio': '',
   'seo_name': 'Matt-Zoller-Seitz',
   'multimedia': None},
  {'display_name': 'Neil Genzlinger',
   'sort_name': 'Genzlinger, Neil',
   'status': 'part-time',
   'bio': '',
   'seo_name': 'Neil-Genzlinger',
   'multimedia': None},
  {'display_name': 'Andy Webster',
   'sort_name': 'Webster, Andy',
   'status': 'part-time',
   'bio': '',
   'seo_name': 'Andy-Webster',
   'multimedia': None},
  {'display_name': 'Jeannette Catsoulis',
   'sort_name': 'Catsoulis, Jeannette',
   'status': 'part-time',
   'bio': '',
   'seo_name': 'Jeannette-Catsoulis',
   'multimedia': None},
  {'display_name': 'Nathan Lee',
   'sort_name': 'Lee, Nathan',
   'status': 'part-time',
   'bio': '',
   'seo_name': 'Nathan-Lee',
   'multimedia': None},
  {'display_name': 'Kevin Cahillane',
   'sort_name': 'Cahillane, Kevin',
   'status': None,
   'bio': '',
   'seo_name': 'Kevin-Cahillane',
   'multimedia': None},
  {'display_name': 'Laura Kern',
   'sort_name': 'Kern, Laura',
   'status': 'part-time',
   'bio': '',
   'seo_name': 'Laura-Kern',
   'multimedia': None},
  {'display_name': 'Anna Kisselgoff',
   'sort_name': 'Kisselgoff, Anna',
   'status': None,
   'bio': None,
   'seo_name': 'Anna-Kisselgoff',
   'multimedia': None},
  {'display_name': 'C. Hooper Trask',
   'sort_name': 'Trask, C. Hooper',
   'status': None,
   'bio': None,
   'seo_name': 'C-Hooper-Trask',
   'multimedia': None},
  {'display_name': 'Ernest Marshall',
   'sort_name': 'Marshall, Ernest',
   'status': None,
   'bio': None,
   'seo_name': 'Ernest-Marshall',
   'multimedia': None},
  {'display_name': 'Herbert L. Matthews',
   'sort_name': 'Matthews, Herbert L.',
   'status': None,
   'bio': None,
   'seo_name': 'Herbert-L-Matthews',
   'multimedia': None},
  {'display_name': 'Herbert Mitgang',
   'sort_name': 'Mitgang, Herbert',
   'status': None,
   'bio': None,
   'seo_name': 'Herbert-Mitgang',
   'multimedia': None},
  {'display_name': 'Jennifer Dunning',
   'sort_name': 'Dunning, Jennifer',
   'status': None,
   'bio': None,
   'seo_name': 'Jennifer-Dunning',
   'multimedia': None},
  {'display_name': 'John Corry',
   'sort_name': 'Corry, John',
   'status': None,
   'bio': None,
   'seo_name': 'John-Corry',
   'multimedia': None},
  {'display_name': 'Jon Pareles',
   'sort_name': 'Pareles, John',
   'status': None,
   'bio': None,
   'seo_name': 'Jon-Pareles',
   'multimedia': None},
  {'display_name': 'Nina Darnton',
   'sort_name': 'Darnton, Nina',
   'status': None,
   'bio': None,
   'seo_name': 'Nina-Darnton',
   'multimedia': None},
  {'display_name': 'Patricia S. McCormick',
   'sort_name': 'McCormick, Patricia S.',
   'status': None,
   'bio': None,
   'seo_name': 'Patricia-S-McCormick',
   'multimedia': None},
  {'display_name': 'Peter M. Nichols',
   'sort_name': 'Nichols, Peter M.',
   'status': None,
   'bio': None,
   'seo_name': 'Peter-M-Nichols',
   'multimedia': None},
  {'display_name': 'Richard Bernstein',
   'sort_name': 'Bernstein, Richard',
   'status': None,
   'bio': None,
   'seo_name': 'Richard-Bernstein',
   'multimedia': None},
  {'display_name': 'Richard F. Shepard',
   'sort_name': 'Shepard, Richard F.',
   'status': None,
   'bio': None,
   'seo_name': 'Richard-F-Shepard',
   'multimedia': None},
  {'display_name': 'Richard W. Nason',
   'sort_name': 'Nason, Richard W.',
   'status': None,
   'bio': None,
   'seo_name': 'Richard-W-Nason',
   'multimedia': None},
  {'display_name': 'Robert Alden',
   'sort_name': 'Alden, Robert',
   'status': None,
   'bio': None,
   'seo_name': 'Robert-Alden',
   'multimedia': None},
  {'display_name': 'Charles Morgan',
   'sort_name': 'Morgan, Charles',
   'status': None,
   'bio': None,
   'seo_name': 'Charles-Morgan',
   'multimedia': None},
  {'display_name': 'Dan Sullivan',
   'sort_name': 'Sullivan, Dan',
   'status': None,
   'bio': None,
   'seo_name': 'Dan-Sullivan',
   'multimedia': None},
  {'display_name': 'Harry Gilroy',
   'sort_name': 'Gilroy, Harry',
   'status': None,
   'bio': None,
   'seo_name': 'Harry-Gilroy',
   'multimedia': None},
  {'display_name': 'Julie Salamon',
   'sort_name': 'Salamon, Julie',
   'status': None,
   'bio': None,
   'seo_name': 'Julie-Salamon',
   'multimedia': None},
  {'display_name': 'Morris Gilbert',
   'sort_name': 'Gilbert, Morris',
   'status': None,
   'bio': None,
   'seo_name': 'Morris-Gilbert',
   'multimedia': None},
  {'display_name': 'W. L. Middleton',
   'sort_name': 'Middleton, W. L.',
   'status': None,
   'bio': None,
   'seo_name': 'W-L-Middleton',
   'multimedia': None},
  {'display_name': 'Harry T. Smith',
   'sort_name': 'Smith, Harry T.',
   'status': None,
   'bio': None,
   'seo_name': 'Harry-T-Smith',
   'multimedia': None},
  {'display_name': 'David DeWitt',
   'sort_name': 'DeWitt, David',
   'status': 'part-time',
   'bio': None,
   'seo_name': 'David-DeWitt',
   'multimedia': None},
  {'display_name': 'Ben Brantley',
   'sort_name': 'Brantley, Ben',
   'status': 'part-time',
   'bio': None,
   'seo_name': 'Ben-Brantley',
   'multimedia': None},
  {'display_name': 'Carina Chocano',
   'sort_name': 'Chocano, Carina',
   'status': 'part-time',
   'bio': None,
   'seo_name': 'Carina-Chocano',
   'multimedia': None},
  {'display_name': 'Daniel M. Gold',
   'sort_name': 'Gold, Daniel M.',
   'status': 'part-time',
   'bio': None,
   'seo_name': 'Daniel-M-Gold',
   'multimedia': None},
  {'display_name': 'Felicity Barringer',
   'sort_name': 'Barringer, Felicity',
   'status': 'part-time',
   'bio': None,
   'seo_name': 'Felicity-Barringer',
   'multimedia': None},
  {'display_name': 'Holcomb B. Noble',
   'sort_name': 'Noble, Holcomb B.',
   'status': 'part-time',
   'bio': None,
   'seo_name': 'Holcomb-B-Noble',
   'multimedia': None},
  {'display_name': 'Jack Gould',
   'sort_name': 'Gould, Jack',
   'status': 'part-time',
   'bio': None,
   'seo_name': 'Jack-Gould',
   'multimedia': None},
  {'display_name': 'Mike Hale',
   'sort_name': 'Hale, Mike',
   'status': 'part-time',
   'bio': None,
   'seo_name': 'Mike-Hale',
   'multimedia': None},
  {'display_name': 'Paul Brunick',
   'sort_name': 'Brunick, Pual',
   'status': 'part-time',
   'bio': None,
   'seo_name': 'Paul-Brunick',
   'multimedia': None},
  {'display_name': 'Peter Kihss',
   'sort_name': 'Kihss, Peter',
   'status': 'part-time',
   'bio': None,
   'seo_name': 'Peter-Kihss',
   'multimedia': None},
  {'display_name': 'Rachel Saltz',
   'sort_name': 'Saltz, Rachel',
   'status': 'part-time',
   'bio': None,
   'seo_name': 'Rachel-Saltz',
   'multimedia': None},
  {'display_name': "Suzanne O'Connor",
   'sort_name': "O'Connor, Suzanne",
   'status': 'part-time',
   'bio': None,
   'seo_name': 'Suzanne-OConnor',
   'multimedia': None},
  {'display_name': 'Victor Navasky',
   'sort_name': 'Navasky, Victor',
   'status': 'part-time',
   'bio': None,
   'seo_name': 'Victor-Navasky',
   'multimedia': None},
  {'display_name': 'Wayne King',
   'sort_name': 'King, Wayne',
   'status': 'part-time',
   'bio': None,
   'seo_name': 'Wayne-King',
   'multimedia': None},
  {'display_name': 'Nicolas Rapold',
   'sort_name': 'Rapold, Nicolas',
   'status': 'part-time',
   'bio': None,
   'seo_name': 'Nicolas-Rapold',
   'multimedia': None},
  {'display_name': 'Miriam Bale',
   'sort_name': 'Bale, Miriam',
   'status': 'part-time',
   'bio': None,
   'seo_name': 'Miriam-Bale',
   'multimedia': None},
  {'display_name': 'Nicole Herrington',
   'sort_name': 'Herrington, Nicole',
   'status': 'part-time',
   'bio': None,
   'seo_name': 'Nicole-Herrington',
   'multimedia': None},
  {'display_name': 'Ben Kenigsberg',
   'sort_name': 'Kenigsberg, Ben',
   'status': 'part-time',
   'bio': None,
   'seo_name': 'Ben-Kenigsberg',
   'multimedia': None}]}

In [14]:
# choose list of results
json_data['results']

[{'display_name': 'A. O. Scott',
  'sort_name': 'A. O. Scott',
  'status': 'full-time',
  'bio': 'A. O. Scott joined The New York Times as a film critic in January 2000, and was named a chief critic in 2004. Previously, Mr. Scott had been the lead Sunday book reviewer for Newsday and a frequent contributor to Slate, The New York Review of Books, and many other publications. \n<br/><br/>\nIn the 1990s he served on the editorial staffs of Lingua Franca and The New York Review of Books. He also edited "A Bolt from the Blue and Other Essays," a collection by Mary McCarthy, which was published by The New York Review of Books in 2002. \n<br/><br/>\nMr. Scott was a finalist for the Pulitzer Prize in Criticism in 2010, the same year he served as co-host (with Michael Phillips of the Chicago Tribune) on the last season of "At the Movies," the syndicated film-reviewing program started by Roger Ebert and Gene Siskel.\n<br/><br/>\nA frequent presence on radio and television, Mr. Scott is Distinguished Professor of Film Criticism at Wesleyan University and the author of Better Living Through Criticism, forthcoming in 2016 from The Penguin Press. A collection of his film writing will be published by Penguin in 2017. \n<br/><br/>\nHe lives in Brooklyn with his family.',
  'seo_name': 'A-O-Scott',
  'multimedia': {'resource': {'type': 'image',
    'src': 'http://static01.nyt.com/images/2015/10/07/topics/ao-scott/ao-scott-articleInline.jpg',
    'height': 163,
    'width': 220,
    'credit': 'Earl Wilson/<br/>The New York Times'}}},
 {'display_name': 'Manohla Dargis',
  'sort_name': 'Manohla Dargis',
  'status': 'full-time',
  'bio': 'Manohla Dargis is the co-chief film critic for The Times, where she started in 2004. She has also written for The Los Angeles Times, where she was a chief film critic, and for the LA Weekly, where she was both a film critic and the film editor. She lives in Los Angeles.',
  'seo_name': 'Manohla-Dargis',
  'multimedia': None},
 {'display_name': 'Stephen Holden',
  'sort_name': 'Stephen Holden',
  'status': 'full-time',
  'bio': 'Stephen Holden is a film and music critic for The Times; he joined the culture staff in 1988. Prior to that, he was a pop music critic and journalist for Rolling Stone, The Village Voice, and numerous other magazines and anthologies. Drawing on his experiences as a journalist and record executive, he wrote a satirical novel about the record business, "Triple Platinum,"  that was published in 1980 by Dell Books. In 1986, he won a Grammy with six other writers for Best Album Notes for "The Voice: The Columbia Years, a Frank Sinatra Anthology." Born July 18, 1941, Mr. Holden graduated from Yale University in 1963 with a Bachelor of Arts degree in English and was elected Class Poet.',
  'seo_name': 'Stephen-Holden',
  'multimedia': {'resource': {'type': 'image',
    'src': 'http://nytimes.com/images/2007/01/05/movies/sholden.163.jpg',
    'height': 163,
    'width': 220,
    'credit': 'Brent Murray/<br>NYTimes.com'}}},
 {'display_name': 'Renata Adler',
  'sort_name': 'Adler, Renata',
  'status': 'part-time',
  'bio': '',
  'seo_name': 'Renata-Adler',
  'multimedia': None},
 {'display_name': 'Mordaunt Hall',
  'sort_name': 'Hall, Mordaunt ',
  'status': 'part-time',
  'bio': '',
  'seo_name': 'Mordaunt-Hall',
  'multimedia': None},
 {'display_name': 'Thomas M. Pryor',
  'sort_name': 'Pryor, Thomas M.',
  'status': 'part-time',
  'bio': '',
  'seo_name': 'Thomas-M-Pryor',
  'multimedia': None},
 {'display_name': 'Eugene Archer',
  'sort_name': 'Archer, Eugene',
  'status': 'part-time',
  'bio': '',
  'seo_name': 'Eugene-Archer',
  'multimedia': None},
 {'display_name': 'Donal J. Henahan',
  'sort_name': 'Henahan, Donal J.',
  'status': 'part-time',
  'bio': '',
  'seo_name': 'Donal-J-Henahan',
  'multimedia': None},
 {'display_name': 'Nora Sayre',
  'sort_name': 'Sayre, Nora',
  'status': 'part-time',
  'bio': '',
  'seo_name': 'Nora-Sayre',
  'multimedia': None},
 {'display_name': 'D. J. R. Bruckner',
  'sort_name': 'Bruckner, D. J. R. ',
  'status': 'part-time',
  'bio': '',
  'seo_name': 'D-J-R-Bruckner',
  'multimedia': None},
 {'display_name': 'Caryn James',
  'sort_name': 'James, Caryn',
  'status': 'part-time',
  'bio': '',
  'seo_name': 'Caryn-James',
  'multimedia': None},
 {'display_name': 'Harold C. Schonberg',
  'sort_name': 'Schonberg, Harold C.',
  'status': 'part-time',
  'bio': '',
  'seo_name': 'Harold-C-Schonberg',
  'multimedia': None},
 {'display_name': 'Tom Buckley',
  'sort_name': 'Buckley, Tom ',
  'status': 'part-time',
  'bio': '',
  'seo_name': 'Tom-Buckley',
  'multimedia': None},
 {'display_name': 'Stanley Kauffman',
  'sort_name': 'Kauffman, Stanley',
  'status': 'part-time',
  'bio': '',
  'seo_name': 'Stanley-Kauffman',
  'multimedia': None},
 {'display_name': 'Andre Sennwald',
  'sort_name': 'Sennwald, Andre',
  'status': 'part-time',
  'bio': '',
  'seo_name': 'Andre-Sennwald',
  'multimedia': None},
 {'display_name': 'Vincent Canby',
  'sort_name': 'Canby, Vincent',
  'status': 'part-time',
  'bio': '',
  'seo_name': 'Vincent-Canby',
  'multimedia': None},
 {'display_name': 'Dave Kehr',
  'sort_name': 'Kehr, Dave',
  'status': 'part-time',
  'bio': '',
  'seo_name': 'Dave-Kehr',
  'multimedia': None},
 {'display_name': 'Dana Stevens',
  'sort_name': 'Stevens, Dana',
  'status': 'part-time',
  'bio': '',
  'seo_name': 'Dana-Stevens',
  'multimedia': None},
 {'display_name': 'B. R. Crisler',
  'sort_name': 'Crisler, B. R.',
  'status': 'part-time',
  'bio': '',
  'seo_name': 'B-R-Crisler',
  'multimedia': None},
 {'display_name': 'Hilton Kramer',
  'sort_name': 'Kramer, Hilton',
  'status': 'part-time',
  'bio': '',
  'seo_name': 'Hilton-Kramer',
  'multimedia': None},
 {'display_name': 'Michael Stern',
  'sort_name': 'Stern, Michael',
  'status': 'part-time',
  'bio': '',
  'seo_name': 'Michael-Stern',
  'multimedia': None},
 {'display_name': 'Bosley Crowther',
  'sort_name': 'Crowther, Bosley',
  'status': 'part-time',
  'bio': '',
  'seo_name': 'Bosley-Crowther',
  'multimedia': None},
 {'display_name': 'Ned Martel',
  'sort_name': 'Martel, Ned',
  'status': 'part-time',
  'bio': '',
  'seo_name': 'Ned-Martel',
  'multimedia': None},
 {'display_name': 'Theodore Strauss',
  'sort_name': 'Strauss, Theodore',
  'status': 'part-time',
  'bio': '',
  'seo_name': 'Theodore-Strauss',
  'multimedia': None},
 {'display_name': 'Richard Eder',
  'sort_name': 'Eder, Richard',
  'status': 'part-time',
  'bio': '',
  'seo_name': 'Richard-Eder',
  'multimedia': None},
 {'display_name': 'Janet Maslin',
  'sort_name': 'Maslin, Janet',
  'status': 'part-time',
  'bio': '',
  'seo_name': 'Janet-Maslin',
  'multimedia': None},
 {'display_name': 'Howard Thompson',
  'sort_name': 'Thompson, Howard',
  'status': 'part-time',
  'bio': '',
  'seo_name': 'Howard-Thompson',
  'multimedia': None},
 {'display_name': 'Anita Gates',
  'sort_name': 'Gates, Anita',
  'status': 'part-time',
  'bio': '',
  'seo_name': 'Anita-Gates',
  'multimedia': None},
 {'display_name': 'John T. McManus',
  'sort_name': 'McManus, John T.',
  'status': 'part-time',
  'bio': '',
  'seo_name': 'John-T-McManus',
  'multimedia': None},
 {'display_name': 'Lawrence Van Gelder',
  'sort_name': 'Van Gelder, Lawrence',
  'status': 'part-time',
  'bio': '',
  'seo_name': 'Lawrence-Van-Gelder',
  'multimedia': None},
 {'display_name': 'Walter Goodman',
  'sort_name': 'Goodman, Walter',
  'status': 'part-time',
  'bio': '',
  'seo_name': 'Walter-Goodman',
  'multimedia': None},
 {'display_name': 'Elvis Mitchell',
  'sort_name': 'Mitchell, Elvis',
  'status': 'part-time',
  'bio': '',
  'seo_name': 'Elvis-Mitchell',
  'multimedia': None},
 {'display_name': 'A. H. Weiler',
  'sort_name': 'Weiler, A. H.',
  'status': 'part-time',
  'bio': '',
  'seo_name': 'A-H-Weiler',
  'multimedia': None},
 {'display_name': 'Roger Greenspun',
  'sort_name': 'Greenspun, Roger',
  'status': 'part-time',
  'bio': '',
  'seo_name': 'Roger-Greenspun',
  'multimedia': None},
 {'display_name': 'Frank S. Nugent',
  'sort_name': 'Nugent, Frank S.',
  'status': 'part-time',
  'bio': '',
  'seo_name': 'Frank-S-Nugent',
  'multimedia': None},
 {'display_name': 'Matt Zoller Seitz',
  'sort_name': 'Seitz, Matt Zoller',
  'status': 'part-time',
  'bio': '',
  'seo_name': 'Matt-Zoller-Seitz',
  'multimedia': None},
 {'display_name': 'Neil Genzlinger',
  'sort_name': 'Genzlinger, Neil',
  'status': 'part-time',
  'bio': '',
  'seo_name': 'Neil-Genzlinger',
  'multimedia': None},
 {'display_name': 'Andy Webster',
  'sort_name': 'Webster, Andy',
  'status': 'part-time',
  'bio': '',
  'seo_name': 'Andy-Webster',
  'multimedia': None},
 {'display_name': 'Jeannette Catsoulis',
  'sort_name': 'Catsoulis, Jeannette',
  'status': 'part-time',
  'bio': '',
  'seo_name': 'Jeannette-Catsoulis',
  'multimedia': None},
 {'display_name': 'Nathan Lee',
  'sort_name': 'Lee, Nathan',
  'status': 'part-time',
  'bio': '',
  'seo_name': 'Nathan-Lee',
  'multimedia': None},
 {'display_name': 'Kevin Cahillane',
  'sort_name': 'Cahillane, Kevin',
  'status': None,
  'bio': '',
  'seo_name': 'Kevin-Cahillane',
  'multimedia': None},
 {'display_name': 'Laura Kern',
  'sort_name': 'Kern, Laura',
  'status': 'part-time',
  'bio': '',
  'seo_name': 'Laura-Kern',
  'multimedia': None},
 {'display_name': 'Anna Kisselgoff',
  'sort_name': 'Kisselgoff, Anna',
  'status': None,
  'bio': None,
  'seo_name': 'Anna-Kisselgoff',
  'multimedia': None},
 {'display_name': 'C. Hooper Trask',
  'sort_name': 'Trask, C. Hooper',
  'status': None,
  'bio': None,
  'seo_name': 'C-Hooper-Trask',
  'multimedia': None},
 {'display_name': 'Ernest Marshall',
  'sort_name': 'Marshall, Ernest',
  'status': None,
  'bio': None,
  'seo_name': 'Ernest-Marshall',
  'multimedia': None},
 {'display_name': 'Herbert L. Matthews',
  'sort_name': 'Matthews, Herbert L.',
  'status': None,
  'bio': None,
  'seo_name': 'Herbert-L-Matthews',
  'multimedia': None},
 {'display_name': 'Herbert Mitgang',
  'sort_name': 'Mitgang, Herbert',
  'status': None,
  'bio': None,
  'seo_name': 'Herbert-Mitgang',
  'multimedia': None},
 {'display_name': 'Jennifer Dunning',
  'sort_name': 'Dunning, Jennifer',
  'status': None,
  'bio': None,
  'seo_name': 'Jennifer-Dunning',
  'multimedia': None},
 {'display_name': 'John Corry',
  'sort_name': 'Corry, John',
  'status': None,
  'bio': None,
  'seo_name': 'John-Corry',
  'multimedia': None},
 {'display_name': 'Jon Pareles',
  'sort_name': 'Pareles, John',
  'status': None,
  'bio': None,
  'seo_name': 'Jon-Pareles',
  'multimedia': None},
 {'display_name': 'Nina Darnton',
  'sort_name': 'Darnton, Nina',
  'status': None,
  'bio': None,
  'seo_name': 'Nina-Darnton',
  'multimedia': None},
 {'display_name': 'Patricia S. McCormick',
  'sort_name': 'McCormick, Patricia S.',
  'status': None,
  'bio': None,
  'seo_name': 'Patricia-S-McCormick',
  'multimedia': None},
 {'display_name': 'Peter M. Nichols',
  'sort_name': 'Nichols, Peter M.',
  'status': None,
  'bio': None,
  'seo_name': 'Peter-M-Nichols',
  'multimedia': None},
 {'display_name': 'Richard Bernstein',
  'sort_name': 'Bernstein, Richard',
  'status': None,
  'bio': None,
  'seo_name': 'Richard-Bernstein',
  'multimedia': None},
 {'display_name': 'Richard F. Shepard',
  'sort_name': 'Shepard, Richard F.',
  'status': None,
  'bio': None,
  'seo_name': 'Richard-F-Shepard',
  'multimedia': None},
 {'display_name': 'Richard W. Nason',
  'sort_name': 'Nason, Richard W.',
  'status': None,
  'bio': None,
  'seo_name': 'Richard-W-Nason',
  'multimedia': None},
 {'display_name': 'Robert Alden',
  'sort_name': 'Alden, Robert',
  'status': None,
  'bio': None,
  'seo_name': 'Robert-Alden',
  'multimedia': None},
 {'display_name': 'Charles Morgan',
  'sort_name': 'Morgan, Charles',
  'status': None,
  'bio': None,
  'seo_name': 'Charles-Morgan',
  'multimedia': None},
 {'display_name': 'Dan Sullivan',
  'sort_name': 'Sullivan, Dan',
  'status': None,
  'bio': None,
  'seo_name': 'Dan-Sullivan',
  'multimedia': None},
 {'display_name': 'Harry Gilroy',
  'sort_name': 'Gilroy, Harry',
  'status': None,
  'bio': None,
  'seo_name': 'Harry-Gilroy',
  'multimedia': None},
 {'display_name': 'Julie Salamon',
  'sort_name': 'Salamon, Julie',
  'status': None,
  'bio': None,
  'seo_name': 'Julie-Salamon',
  'multimedia': None},
 {'display_name': 'Morris Gilbert',
  'sort_name': 'Gilbert, Morris',
  'status': None,
  'bio': None,
  'seo_name': 'Morris-Gilbert',
  'multimedia': None},
 {'display_name': 'W. L. Middleton',
  'sort_name': 'Middleton, W. L.',
  'status': None,
  'bio': None,
  'seo_name': 'W-L-Middleton',
  'multimedia': None},
 {'display_name': 'Harry T. Smith',
  'sort_name': 'Smith, Harry T.',
  'status': None,
  'bio': None,
  'seo_name': 'Harry-T-Smith',
  'multimedia': None},
 {'display_name': 'David DeWitt',
  'sort_name': 'DeWitt, David',
  'status': 'part-time',
  'bio': None,
  'seo_name': 'David-DeWitt',
  'multimedia': None},
 {'display_name': 'Ben Brantley',
  'sort_name': 'Brantley, Ben',
  'status': 'part-time',
  'bio': None,
  'seo_name': 'Ben-Brantley',
  'multimedia': None},
 {'display_name': 'Carina Chocano',
  'sort_name': 'Chocano, Carina',
  'status': 'part-time',
  'bio': None,
  'seo_name': 'Carina-Chocano',
  'multimedia': None},
 {'display_name': 'Daniel M. Gold',
  'sort_name': 'Gold, Daniel M.',
  'status': 'part-time',
  'bio': None,
  'seo_name': 'Daniel-M-Gold',
  'multimedia': None},
 {'display_name': 'Felicity Barringer',
  'sort_name': 'Barringer, Felicity',
  'status': 'part-time',
  'bio': None,
  'seo_name': 'Felicity-Barringer',
  'multimedia': None},
 {'display_name': 'Holcomb B. Noble',
  'sort_name': 'Noble, Holcomb B.',
  'status': 'part-time',
  'bio': None,
  'seo_name': 'Holcomb-B-Noble',
  'multimedia': None},
 {'display_name': 'Jack Gould',
  'sort_name': 'Gould, Jack',
  'status': 'part-time',
  'bio': None,
  'seo_name': 'Jack-Gould',
  'multimedia': None},
 {'display_name': 'Mike Hale',
  'sort_name': 'Hale, Mike',
  'status': 'part-time',
  'bio': None,
  'seo_name': 'Mike-Hale',
  'multimedia': None},
 {'display_name': 'Paul Brunick',
  'sort_name': 'Brunick, Pual',
  'status': 'part-time',
  'bio': None,
  'seo_name': 'Paul-Brunick',
  'multimedia': None},
 {'display_name': 'Peter Kihss',
  'sort_name': 'Kihss, Peter',
  'status': 'part-time',
  'bio': None,
  'seo_name': 'Peter-Kihss',
  'multimedia': None},
 {'display_name': 'Rachel Saltz',
  'sort_name': 'Saltz, Rachel',
  'status': 'part-time',
  'bio': None,
  'seo_name': 'Rachel-Saltz',
  'multimedia': None},
 {'display_name': "Suzanne O'Connor",
  'sort_name': "O'Connor, Suzanne",
  'status': 'part-time',
  'bio': None,
  'seo_name': 'Suzanne-OConnor',
  'multimedia': None},
 {'display_name': 'Victor Navasky',
  'sort_name': 'Navasky, Victor',
  'status': 'part-time',
  'bio': None,
  'seo_name': 'Victor-Navasky',
  'multimedia': None},
 {'display_name': 'Wayne King',
  'sort_name': 'King, Wayne',
  'status': 'part-time',
  'bio': None,
  'seo_name': 'Wayne-King',
  'multimedia': None},
 {'display_name': 'Nicolas Rapold',
  'sort_name': 'Rapold, Nicolas',
  'status': 'part-time',
  'bio': None,
  'seo_name': 'Nicolas-Rapold',
  'multimedia': None},
 {'display_name': 'Miriam Bale',
  'sort_name': 'Bale, Miriam',
  'status': 'part-time',
  'bio': None,
  'seo_name': 'Miriam-Bale',
  'multimedia': None},
 {'display_name': 'Nicole Herrington',
  'sort_name': 'Herrington, Nicole',
  'status': 'part-time',
  'bio': None,
  'seo_name': 'Nicole-Herrington',
  'multimedia': None},
 {'display_name': 'Ben Kenigsberg',
  'sort_name': 'Kenigsberg, Ben',
  'status': 'part-time',
  'bio': None,
  'seo_name': 'Ben-Kenigsberg',
  'multimedia': None}]

In [15]:
# Transfer to pandas dataframe, and choose 4 columns
issues = pd.DataFrame(json_data['results'], columns=['display_name', 'sort_name',
                                     'status', 'seo_name'])
issues

         display_name           sort_name     status           seo_name
0         A. O. Scott         A. O. Scott  full-time          A-O-Scott
1      Manohla Dargis      Manohla Dargis  full-time     Manohla-Dargis
2      Stephen Holden      Stephen Holden  full-time     Stephen-Holden
3        Renata Adler       Adler, Renata  part-time       Renata-Adler
4       Mordaunt Hall     Hall, Mordaunt   part-time      Mordaunt-Hall
..                ...                 ...        ...                ...
77         Wayne King         King, Wayne  part-time         Wayne-King
78     Nicolas Rapold     Rapold, Nicolas  part-time     Nicolas-Rapold
79        Miriam Bale        Bale, Miriam  part-time        Miriam-Bale
80  Nicole Herrington  Herrington, Nicole  part-time  Nicole-Herrington
81     Ben Kenigsberg     Kenigsberg, Ben  part-time     Ben-Kenigsberg

[82 rows x 4 columns]