In [3]:
import pandas as pd

df1 = pd.read_csv('new各鄉鎮市區人口密度.csv')
display(df1)
df1.style

     統計年     區域別   年底人口數     土地面積   人口密度
0    106  新北市板橋區  551480  23.1373  23835
1    106  新北市三重區  387484  16.3170  23747
2    106  新北市中和區  413590  20.1440  20532
3    106  新北市永和區  222585   5.7138  38956
4    106  新北市新莊區  416524  19.7383  21102
..   ...     ...     ...      ...    ...
365  106  連江縣北竿鄉    2360   9.9000    238
366  106  連江縣莒光鄉    1624   4.7000    346
367  106  連江縣東引鄉    1352   3.8000    356
368  106    東沙群島       0   2.3800      0
369  106    南沙群島       0   0.5045      0

[370 rows x 5 columns]

ImportError: Missing optional dependency 'Jinja2'. DataFrame.style requires jinja2. Use pip or conda to install Jinja2.

In [ ]:
import pandas as pd
# \表示接續下一行是同一串
df1 = pd.read_csv('new各鄉鎮市區人口密度.csv')
display(df1)
def format1(value:int):
    return f"第{value}號"
df1.style\
.format(precision=2,thousands=',',decimal='.')\
.format_index(format1)

In [ ]:
#匿名的function
df1 = pd.read_csv('new各鄉鎮市區人口密度.csv')
display(df1)
# (def format1(value:int):
    #return f"第{value}號")有lambda這些就可以不用寫
df1.style\
.format(precision=2,thousands=',',decimal='.')\
.format_index(lambda value:f'第{value}號')

In [6]:
type(df1.style)

pandas.io.formats.style.Styler

In [15]:
import numpy as np
weather_df = pd.DataFrame(np.random.rand(10,2)*5,
                        index=pd.date_range(start="2021-01-01", periods=10),
                        columns=["Tokyo", "Taipei"])
weather_df

               Tokyo    Taipei
2021-01-01  3.285547  2.066443
2021-01-02  4.292455  3.135764
2021-01-03  3.228306  4.890695
2021-01-04  4.634866  3.842416
2021-01-05  2.352441  0.474647
2021-01-06  3.675383  0.934894
2021-01-07  3.876480  1.362274
2021-01-08  1.839015  4.125858
2021-01-09  1.360098  1.644301
2021-01-10  4.296175  3.236132

In [20]:
#cmap跟matplotlib有關係 colormap reference
weather_df.style\
.set_caption('Weather Conditions')\
.format_index(lambda v:v.strftime("%A"))\
.background_gradient(vmin=1,vmax=5,cmap='RdGy')

In [17]:
weather_df.index

DatetimeIndex(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
               '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
               '2021-01-09', '2021-01-10'],
              dtype='datetime64[ns]', freq='D')