In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
train_df = pd.read_excel('/content/Flight_Price_Prediction_Data_Train.xlsx')

In [7]:
train_df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [5]:
test_df = pd.read_excel('/content/Flight_Price_Prediction_Test_set.xlsx')

In [8]:
test_df.head() #doesn't have price

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info
0,Jet Airways,6/06/2019,Delhi,Cochin,DEL → BOM → COK,17:30,04:25 07 Jun,10h 55m,1 stop,No info
1,IndiGo,12/05/2019,Kolkata,Banglore,CCU → MAA → BLR,06:20,10:20,4h,1 stop,No info
2,Jet Airways,21/05/2019,Delhi,Cochin,DEL → BOM → COK,19:15,19:00 22 May,23h 45m,1 stop,In-flight meal not included
3,Multiple carriers,21/05/2019,Delhi,Cochin,DEL → BOM → COK,08:00,21:00,13h,1 stop,No info
4,Air Asia,24/06/2019,Banglore,Delhi,BLR → DEL,23:55,02:45 25 Jun,2h 50m,non-stop,No info

In [139]:
final_df = pd.concat([train_df, test_df], ignore_index =True)
final_df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882.0
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0

In [140]:
final_df.shape

(13354, 11)

In [141]:
final_df.tail()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
13349,Air India,6/06/2019,Kolkata,Banglore,CCU → DEL → BLR,20:30,20:25 07 Jun,23h 55m,1 stop,No info,NaN
13350,IndiGo,27/03/2019,Kolkata,Banglore,CCU → BLR,14:20,16:55,2h 35m,non-stop,No info,NaN
13351,Jet Airways,6/03/2019,Delhi,Cochin,DEL → BOM → COK,21:50,04:25 07 Mar,6h 35m,1 stop,No info,NaN
13352,Air India,6/03/2019,Delhi,Cochin,DEL → BOM → COK,04:00,19:15,15h 15m,1 stop,No info,NaN
13353,Multiple carriers,15/06/2019,Delhi,Cochin,DEL → BOM → COK,04:55,19:15,14h 20m,1 stop,No info,NaN

In [142]:
final_df.isna().sum()

Airline               0
Date_of_Journey       0
Source                0
Destination           0
Route                 1
Dep_Time              0
Arrival_Time          0
Duration              0
Total_Stops           1
Additional_Info       0
Price              2671
dtype: int64

In [143]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13354 entries, 0 to 13353
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Date_of_Journey  13354 non-null  object
 2   Source           13354 non-null  object
 3   Destination      13354 non-null  object
 4   Route            13353 non-null  object
 5   Dep_Time         13354 non-null  object
 6   Arrival_Time     13354 non-null  object
 7   Duration         13354 non-null  object
 8   Total_Stops      13353 non-null  object
 9   Additional_Info  13354 non-null  object
 10  Price            10683 non-null  float64
dtypes: float64(1), object(10)
memory usage: 1.1+ MB

#Feature Engineering

In [144]:
final_df['Date_of_Journey'].str.split('/')

0        [24, 03, 2019]
1         [1, 05, 2019]
2         [9, 06, 2019]
3        [12, 05, 2019]
4        [01, 03, 2019]
              ...
13349     [6, 06, 2019]
13350    [27, 03, 2019]
13351     [6, 03, 2019]
13352     [6, 03, 2019]
13353    [15, 06, 2019]
Name: Date_of_Journey, Length: 13354, dtype: object

In [145]:
#we'll have to convert string date of jouney to datetime and generate date, month and year fields
final_df['Date']=final_df['Date_of_Journey'].str.split('/').str[0]
final_df['Month']=final_df['Date_of_Journey'].str.split('/').str[1]
final_df['Year']=final_df['Date_of_Journey'].str.split('/').str[2]

In [146]:
final_df['Date']=final_df['Date'].astype(int)
final_df['Month']=final_df['Month'].astype(int)
final_df['Year']=final_df['Year'].astype(int)

In [147]:
final_df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0,24,3,2019
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0,1,5,2019
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882.0,9,6,2019
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0,12,5,2019
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0,1,3,2019

In [148]:
final_df.drop(columns = ['Date_of_Journey'], inplace = True)

In [149]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13354 entries, 0 to 13353
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Source           13354 non-null  object
 2   Destination      13354 non-null  object
 3   Route            13353 non-null  object
 4   Dep_Time         13354 non-null  object
 5   Arrival_Time     13354 non-null  object
 6   Duration         13354 non-null  object
 7   Total_Stops      13353 non-null  object
 8   Additional_Info  13354 non-null  object
 9   Price            10683 non-null  float64
 10  Date             13354 non-null  int64
 11  Month            13354 non-null  int64
 12  Year             13354 non-null  int64
dtypes: float64(1), int64(3), object(9)
memory usage: 1.3+ MB

In [150]:
#Arrival time

final_df["Arrival_Time"] =  final_df["Arrival_Time"].str.split(' ').str[0]

In [151]:
final_df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10,2h 50m,non-stop,No info,3897.0,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0,1,5,2019
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25,19h,2 stops,No info,13882.0,9,6,2019
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0,12,5,2019
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0,1,3,2019

In [152]:
final_df["Arrival_Hour"] =  final_df["Arrival_Time"].str.split(':').str[0]
final_df['Arrival_Minutes']  = final_df["Arrival_Time"].str.split(':').str[1]

In [153]:
final_df["Arrival_Hour"] = final_df["Arrival_Hour"].astype(int)
final_df['Arrival_Minutes'] = final_df['Arrival_Minutes'].astype(int)

In [154]:
final_df.drop(columns  = ['Arrival_Time'], inplace = True)

In [155]:
final_df.head(1)

,Airline,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minutes
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,2h 50m,non-stop,No info,3897.0,24,3,2019,1,10

In [156]:
#departure time
final_df["Dep_Hour"] =  final_df["Dep_Time"].str.split(':').str[0]
final_df['Dep_Minutes']  = final_df["Dep_Time"].str.split(':').str[1]

In [157]:
final_df["Dep_Hour"] = final_df["Dep_Hour"].astype(int)
final_df['Dep_Minutes'] = final_df['Dep_Minutes'].astype(int)

In [158]:
final_df.drop(columns  = ['Dep_Time'], inplace = True)

In [159]:
final_df.head(1)

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minutes,Dep_Hour,Dep_Minutes
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897.0,24,3,2019,1,10,22,20

In [160]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13354 entries, 0 to 13353
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Source           13354 non-null  object
 2   Destination      13354 non-null  object
 3   Route            13353 non-null  object
 4   Duration         13354 non-null  object
 5   Total_Stops      13353 non-null  object
 6   Additional_Info  13354 non-null  object
 7   Price            10683 non-null  float64
 8   Date             13354 non-null  int64
 9   Month            13354 non-null  int64
 10  Year             13354 non-null  int64
 11  Arrival_Hour     13354 non-null  int64
 12  Arrival_Minutes  13354 non-null  int64
 13  Dep_Hour         13354 non-null  int64
 14  Dep_Minutes      13354 non-null  int64
dtypes: float64(1), int64(7), object(7)
memory usage: 1.5+ MB

In [161]:
final_df['Total_Stops'].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops'],
      dtype=object)

In [162]:
final_df['Total_Stops'].isna().sum()

1

In [163]:
final_df[final_df['Total_Stops'].isna()]

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minutes,Dep_Hour,Dep_Minutes
9039,Air India,Delhi,Cochin,NaN,23h 40m,NaN,No info,7480.0,6,5,2019,9,25,9,45

In [164]:
#either delete this record or lets just assume that maybe 1 stop will be there on the basis of GK
#let us now map the no. of stops in string format to ints

final_df['Total_Stops'] = final_df['Total_Stops'].map({'non-stop': 0, '2 stops':2, '1 stop':1, '3 stops':3 , '4 stops': 4, 'NaN': 1})

In [165]:
#we need only one either route or no. of stops
#so let us now drop route
final_df.drop(columns = ['Route'], inplace = True)

In [166]:
final_df.head()

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minutes,Dep_Hour,Dep_Minutes
0,IndiGo,Banglore,New Delhi,2h 50m,0.0,No info,3897.0,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,7h 25m,2.0,No info,7662.0,1,5,2019,13,15,5,50
2,Jet Airways,Delhi,Cochin,19h,2.0,No info,13882.0,9,6,2019,4,25,9,25
3,IndiGo,Kolkata,Banglore,5h 25m,1.0,No info,6218.0,12,5,2019,23,30,18,5
4,IndiGo,Banglore,New Delhi,4h 45m,1.0,No info,13302.0,1,3,2019,21,35,16,50

In [167]:
final_df['Additional_Info'].unique()

array(['No info', 'In-flight meal not included',
       'No check-in baggage included', '1 Short layover', 'No Info',
       '1 Long layover', 'Change airports', 'Business class',
       'Red-eye flight', '2 Long layover'], dtype=object)

In [168]:
#we can probably just encode additional info

#now let us deal with Duration convert it entirely into minutes

final_df['Duration_Hour'] = final_df['Duration'].str.split(' ').str[0].str.split('h').str[0]

In [169]:
final_df.head()

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minutes,Dep_Hour,Dep_Minutes,Duration_Hour
0,IndiGo,Banglore,New Delhi,2h 50m,0.0,No info,3897.0,24,3,2019,1,10,22,20,2
1,Air India,Kolkata,Banglore,7h 25m,2.0,No info,7662.0,1,5,2019,13,15,5,50,7
2,Jet Airways,Delhi,Cochin,19h,2.0,No info,13882.0,9,6,2019,4,25,9,25,19
3,IndiGo,Kolkata,Banglore,5h 25m,1.0,No info,6218.0,12,5,2019,23,30,18,5,5
4,IndiGo,Banglore,New Delhi,4h 45m,1.0,No info,13302.0,1,3,2019,21,35,16,50,4

In [170]:
final_df['Duration_Hour'] = final_df['Duration_Hour'].astype(int)

ValueError: invalid literal for int() with base 10: '5m'

In [171]:
final_df[(final_df['Duration']=='5m')] #now this clearly seems impossible so let us just drop these two records

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minutes,Dep_Hour,Dep_Minutes,Duration_Hour
6474,Air India,Mumbai,Hyderabad,5m,2.0,No info,17327.0,6,3,2019,16,55,16,50,5m
13343,Air India,Mumbai,Hyderabad,5m,2.0,No info,NaN,12,3,2019,16,55,16,50,5m

In [172]:
final_df.drop([6474, 13343], inplace = True)

In [173]:
final_df['Duration_Hour'] = final_df['Duration_Hour'].astype(int)

In [174]:
final_df.head(1)

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minutes,Dep_Hour,Dep_Minutes,Duration_Hour
0,IndiGo,Banglore,New Delhi,2h 50m,0.0,No info,3897.0,24,3,2019,1,10,22,20,2

In [175]:
final_df['Duration_Minutes'] =final_df['Duration'].str.split(' ').str[1].str.split('m').str[0]

In [176]:
final_df['Duration_Minutes'].isna().sum()

1284

In [177]:
final_df['Duration_Minutes'] = final_df['Duration_Minutes'].fillna('0')

In [178]:
final_df['Duration_Minutes'] = final_df['Duration_Minutes'].astype(int)

In [179]:
final_df['Duration'] = final_df['Duration_Hour']*60 + final_df['Duration_Minutes']

In [180]:
final_df.head()

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minutes,Dep_Hour,Dep_Minutes,Duration_Hour,Duration_Minutes
0,IndiGo,Banglore,New Delhi,170,0.0,No info,3897.0,24,3,2019,1,10,22,20,2,50
1,Air India,Kolkata,Banglore,445,2.0,No info,7662.0,1,5,2019,13,15,5,50,7,25
2,Jet Airways,Delhi,Cochin,1140,2.0,No info,13882.0,9,6,2019,4,25,9,25,19,0
3,IndiGo,Kolkata,Banglore,325,1.0,No info,6218.0,12,5,2019,23,30,18,5,5,25
4,IndiGo,Banglore,New Delhi,285,1.0,No info,13302.0,1,3,2019,21,35,16,50,4,45

In [181]:
final_df.drop(columns = ['Duration_Hour', 'Duration_Minutes'], inplace = True)

In [182]:
final_df.head(1)

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minutes,Dep_Hour,Dep_Minutes
0,IndiGo,Banglore,New Delhi,170,0.0,No info,3897.0,24,3,2019,1,10,22,20

In [ ]:
#categorical features
# we can use labelencoding

In [185]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(handle_unknown="ignore")

In [204]:
df_Airline = ohe.fit_transform(final_df['Airline'].values.reshape(-1, 1)).toarray()
df_Source = ohe.fit_transform(final_df['Source'].values.reshape(-1, 1)).toarray()
df_Destination = ohe.fit_transform(final_df['Destination'].values.reshape(-1, 1)).toarray()
df_Additional_Info = ohe.fit_transform(final_df['Additional_Info'].values.reshape(-1, 1)).toarray()

In [206]:
dfOneHot_Airline = pd.DataFrame(df_Airline, columns=["Airline_" + str(int(i)) for i in range(df_Airline.shape[1])])
dfOneHot_Source = pd.DataFrame(df_Source, columns=["Source_" + str(int(i)) for i in range(df_Source.shape[1])])
dfOneHot_Destination = pd.DataFrame(df_Destination, columns=["Destination_" + str(int(i)) for i in range(df_Destination.shape[1])])
dfOneHot_Additional_Info= pd.DataFrame(df_Additional_Info, columns=["Additional_Info_" + str(int(i)) for i in range(df_Additional_Info.shape[1])])

In [207]:
final_df = pd.concat([final_df, dfOneHot_Airline], axis=1)
final_df = pd.concat([final_df, dfOneHot_Source], axis=1)
final_df = pd.concat([final_df, dfOneHot_Destination], axis=1)
final_df = pd.concat([final_df, dfOneHot_Additional_Info], axis=1)

In [208]:
final_df.drop(['Airline'], axis=1, inplace = True)
final_df.drop(['Source'], axis=1, inplace = True)
final_df.drop(['Destination'], axis=1, inplace = True)
final_df.drop(['Additional_Info'], axis=1, inplace = True)

In [213]:
pd.set_option('display.max_columns', None)

In [214]:
final_df.head()

,Duration,Total_Stops,Price,Date,Month,Year,Arrival_Hour,Arrival_Minutes,Dep_Hour,Dep_Minutes,Airline_0,Airline_1,Airline_2,Airline_3,Airline_4,Airline_5,Airline_6,Airline_7,Airline_8,Airline_9,Airline_10,Airline_11,Source_0,Source_1,Source_2,Source_3,Source_4,Source_5,Destination_0,Destination_1,Destination_2,Destination_3,Destination_4,Destination_5,Destination_6,Additional_Info_0,Additional_Info_1,Additional_Info_2,Additional_Info_3,Additional_Info_4,Additional_Info_5,Additional_Info_6,Additional_Info_7,Additional_Info_8,Additional_Info_9,Additional_Info_10
0,170.0,0.0,3897.0,24.0,3.0,2019.0,1.0,10.0,22.0,20.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,445.0,2.0,7662.0,1.0,5.0,2019.0,13.0,15.0,5.0,50.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,1140.0,2.0,13882.0,9.0,6.0,2019.0,4.0,25.0,9.0,25.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,325.0,1.0,6218.0,12.0,5.0,2019.0,23.0,30.0,18.0,5.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,285.0,1.0,13302.0,1.0,3.0,2019.0,21.0,35.0,16.0,50.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [215]:
final_df.shape

(13354, 46)

In [ ]:
#we can split the data back into train and test