# Exploration: Mining Data

This notebook reflects an exploration into several mining data sources: 
1. USGS - US Monitored Active Mines and Mineral Plants
    - Original Data is a shape file. 
    - Source: https://mrdata.usgs.gov/mineplant/
    - Expect data to contain a wide variety of mine and mineral types
    - Likely categorical data only. This data acts as 
2. Uranium Mine Data 
    - Original data is shape file.
    - Source: Spladder

In [25]:
#Libraries: 
#Basic py: 
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from PIL import Image
import os

pd.options.display.max_columns = 50

## Import the Data

In [32]:
path = './Mining/'
data_dict = {}

#Let's store this data in a dictionary: 
for files in os.listdir(path):
    if (files.split('.')[1] == 'txt'):
        data_dict[files.split('.')[0] + '_df'] =pd.read_csv(path +
                                                    files, sep=",", header=0) 
#Save the dataframes
uran_bound_df = data_dict['Uranium_Boundaries_List_df']
uran_pprod_df = data_dict['Uranium_Past_Producers_df']
uran_perm_df = data_dict['Utah_Uranium_Permits_df']
asb_df = data_dict['Asbestos_fUS49_UT_df']

In [43]:
uran_pprod_df = uran_pprod_df.replace(r'^\s*$', np.nan, regex=True)
print(uran_pprod_df.isna().sum().sort_values().to_string())

FID              0
STATUS           0
UTM_Z            0
UTM_E            0
UTM_N            0
Q2_SCALE         0
REF              0
PROD            26
COMMOD          26
COUNTY          26
STATE           26
COUNTRY         26
ZID             26
REC_NO          26
REC_TYPE        26
REP_DATE        27
MERIDIAN        32
REP             34
SITE_NAME       37
RANGE           39
TOWNSHIP        39
FIL_LINK        84
SECTION        101
REP_AFF        112
RF1            214
ACC            260
DIST           265
POSITION       367
HR_TYPE        460
HR_AGE         477
LONG           478
LAT            478
PHYS           479
DRAIN          480
ELEV           483
NAT_DISC       496
DEP_NUM        497
DEP_TYPE       504
FORM_NAME      518
FORM_AGE       524
LOCATION       525
LAND_ST        528
DESC_WORK      530
DEP_SIZE       538
TECT_SET       549
MAJOR          575
DEP_FORM       577
ORE_MAT        590
QUAD2          610
DEP_T_U        611
M_T_U          639
MAX_THICK      640
LEN_WK         648
L_WK_U         650
STRIKE         669
DIP            674
DEPTH_BOT      676
DEP_B_U        676
ORE_CNTL       691
RF2            693
DEPTH_WK       696
D_WK_U         697
QUAD1          698
RF4            699
MAX_LEN        712
CP_ITEM        713
M_L_U          715
CP_AMT         717
CP_U           717
CP_YEAR        719
MAX_WID        725
M_W_U          730
DEPTH_TOP      743
RPR_SOURCE     768
OWNER          796
CONC           804
DESC_WORK_     809
RPR_ITEM       827
RPR_ACC        830
P_SOURCE       854
RPR_YEAR       873
RF3            876
ALTER_         919
SYN            923
RPR_GRADE      929
REG_STRUCT     941
NON_ORE_MI     970
Q1_SCALE       974
OPER           978
AP_AMT         981
AP_ITEM        981
AP_U           983
AP_YEAR        989
LOCAL_STRU     999
DEP_DESC_C    1006
MINOR         1036
AP_GRADE      1045
MIN_AGE       1048
YR_DISC       1055
GEN_ANAL      1072
CP_GRADE      1080
RPR_COM       1104
OCCUR         1105
CP_ACC        1106
EXPL_COM      1106
OV_LEN_WK     1109
O_L_U         1109
O_W_U         1111
OV_WID_WK     1111
OV_AREA_WK    1115
P_COM         1117
O_A_U         1119
GEOL_COM      1125
R_ACC         1129
R_ITEM        1129
POTEN         1131
R_YEAR        1134
R_GRADE       1138
PR_ITEM       1138
PR_ACC        1138
PR_SOURCE     1140
R_AMT         1141
R_U           1141
PR_YEAR       1143
DISC          1148
R_SOURCE      1150
PR_GRADE      1153
AP_ACC        1158
YR_1ST_PRO    1159
PLUNGE        1166
PLUNGE_DIR    1167
PR_U          1175
PR_AMT        1175
GEN_COM       1176
IG_UNIT_NA    1184
IG_UNIT_AG    1184
IG_AGE        1186
COM_INFO      1194
IG_TYPE       1198
INFO_SRC      1201
R_COM         1204
RPR_U         1204
RPR_AMT       1204
PR_COM        1206
SECT_FRACT    1207
NP_MAIN       1210
NP_MINOR      1212
COM_SUB       1213
YR_LAST_PR    1215
FORM2_AGE     1216
IG2_UNIT_A    1216
IG2_UNIT_N    1216
FORM2_NAME    1216

In [44]:
uran_pprod_df[['FID','CP_YEAR','TOWNSHIP','SITE_NAME','LAT','LONG']]

,FID,CP_YEAR,TOWNSHIP,SITE_NAME,LAT,LONG
0,0,PRE-1956; .1,013S,YELLOW BIRD CLAIM,39-42-20N,113-35-03W
1,1,NaN,040S,BULLOCH CLAIM,37-20-30N,112-51-30W
2,2,NaN,043S,SKYLINE ROAD,37-01-07N,110-15-36W
3,3,NaN,043S,TOM HOLLIDAY PROSPECT,37-01-07N,110-15-36W
4,4,NaN,043S,MONUMENT 3,37-01-05N,110-19-13W
...,...,...,...,...,...,...
1211,1211,NaN,NaN,NaN,NaN,NaN
1212,1212,NaN,NaN,NaN,NaN,NaN
1213,1213,NaN,NaN,NaN,NaN,NaN
1214,1214,NaN,NaN,NaN,NaN,NaN
1215,1215,NaN,NaN,NaN,NaN,NaN

In [46]:
uran_pprod_df.shape

(1216, 153)

In [54]:
uran_pprod_years = uran_pprod_df[uran_pprod_df.loc[:,'CP_YEAR'].notna()]
uran_pprod_township = uran_pprod_df[uran_pprod_df.loc[:,'TOWNSHIP'].notna()]
print(uran_pprod_years.shape)
print(uran_pprod_township.shape)

(497, 153)
(1177, 153)

In [63]:
uran_pprod_years.loc[:,'TOWNSHIP'].value_counts()

024S       76
023S       51
035S       50
032S       42
031S       32
037S       29
033S       23
022S       23
021S       20
025S       20
034S       19
036S       19
026S       14
030S       12
027S       12
020S        7
029S        7
028S        4
013S        3
039S        3
040S        3
043S        3
009S        2
038S        2
018S        2
031S 03     1
029S 02     1
033S 03     1
024S 02     1
041S        1
/24S        1
026S 02     1
035S 03     1
032S 03     1
032E        1
042S        1
006S;       1
Name: TOWNSHIP, dtype: int64

## Conclusion: This Data needs quite a bit of cleaning. The export is not perfect by any means

In [66]:
asb_df

,FID,rec_id,state,county,site_name,devel,latitude,longitude,oremin,assocmin,hostrock,source
0,0,393,UT,Beaver,Big Pass group,occurrence,38.303799,-112.8216,"short-fiber chrysotile (asbestos)"""", fibrous t...","garnet, epidote, wollastonite, fluorite, pyrit...",calcite-wollastonite marble,ofr20081095
1,1,394,UT,Beaver,King David mine,occurrence,38.451599,-113.2778,"asbestos""""""""","alunite, marble [calc-silicate minerals], arge...",marble,ofr20081095
2,2,395,UT,Millard,Tremolite no. 1 mine,past producer,38.581501,-112.8409,mass-fiber tremolite asbestos,"calcite, """"potash"""", malachite, chalcopyrite, ...",marble (dolomitic),ofr20081095
3,3,396,UT,Duchesne,unnamed occurrences in Avintaquin Canyon,occurrence,39.979999,-110.8600,asbestiform magnesioarfvedsonite,"dolomite, quartz, hornblende, plagioclase","dolomitic marlstone (""""""""oil shale"""""""")",ofr20081095
4,4,397,UT,Salt Lake,Bingham stock,occurrence,40.516998,-112.1570,"asbestos"""", finely fibrous actinolite","numerous minerals reported--see Hunt (1924), L...",dolomitic copper skarn,ofr20081095
5,5,398,UT,Davis,occurrences in Bair Canyon,occurrence,41.041000,-111.8590,"slip-fiber tremolite asbestos, fibrous actinolite","microcline feldspar, quartz, actinolite, mica,...",pegmatite sill,ofr20081095
6,6,399,UT,Box Elder,Pack Rat tremolite prospect,past prospect,41.199402,-113.3375,tremolite asbestos,dolomite,dolomitic marble,ofr20081095

In [1]:
#This is a test for github
yikes = np.array(1)

NameError: name 'np' is not defined