In [1]:
import requests
import re
import pickle

In [10]:
#용량이 클 시 해당 파일만 선택 개방
with open("./kbo.pkl", "rb") as f:
    kbo = pickle.load(f)

In [2]:
from bs4 import BeautifulSoup

In [33]:
kbo

['52895',
 '51868',
 '72523',
 '71837',
 '51867',
 '77829',
 '50817',
 '69810',
 '52844',
 '62864',
 '66803',
 '76430',
 '50848',
 '76802',
 '64499',
 '68830',
 '65411',
 '50816',
 '52803',
 '79847',
 '65343',
 '73211',
 '52833',
 '52806',
 '52808',
 '62869',
 '64893',
 '52864',
 '67893',
 '50812',
 '51860',
 '51805',
 '60841',
 '69839',
 '64896',
 '69803',
 '61895',
 '52804',
 '65897',
 '62937',
 '52873',
 '66864',
 '50859',
 '61743',
 '60558',
 '64890',
 '68801',
 '52867',
 '50819',
 '64861',
 '52868',
 '76812',
 '67807',
 '60768',
 '65869',
 '63440',
 '68804',
 '52807',
 '52802',
 '51804',
 '51895',
 '68869',
 '52809',
 '50820',
 '69805',
 '66858',
 '65058',
 '51897',
 '68848',
 '51809',
 '64768',
 '51865',
 '69802',
 '68856',
 '68805',
 '69893',
 '52805',
 '75847',
 '76267',
 '68868',
 '50854',
 '62884',
 '51817',
 '52827',
 '51863',
 '66802',
 '69813',
 '68092',
 '62895',
 '64906',
 '50395',
 '50393',
 '50360',
 '52398',
 '52303',
 '66018',
 '67828',
 '51301',
 '68346',
 '51303',
 '65898',
 '69367',
 '67391',
 '62332',
 '65392',
 '69306',
 '63920',
 '51393',
 '64984',
 '62360',
 '51304',
 '67304',
 '51344',
 '52394',
 '52306',
 '60336',
 '50397',
 '52305',
 '66305',
 '52302',
 '69328',
 '65348',
 '50357',
 '64657',
 '52348',
 '68302',
 '52392',
 '68305',
 '65357',
 '52391',
 '50312',
 '68341',
 '52308',
 '51305',
 '67365',
 '61268',
 '68330',
 '52304',
 '67360',
 '69343',
 '52395',
 '69399',
 '69366',
 '52397',
 '67363',
 '52301',
 '67603',
 '64051',
 '74163',
 '51307',
 '67341',
 '50354',
 '51302',
 '79456',
 '64346',
 '64340',
 '51359',
 '65586',
 '51306',
 '50394',
 '78148',
 '63342',
 '69360',
 '69332',
 '52396',
 '52330',
 '66354',
 '65320',
 '52366',
 '64350',
 '62363',
 '52125',
 '69158',
 '51143',
 '67119',
 '69100',
 '66112',
 '60337',
 '51109',
 '50116',
 '77564',
 '52105',
 '69105',
 '67169',
 '68130',
 '51106',
 '50157',
 '68109',
 '66162',
 '52140',
 '51104',
 '75867',
 '67122',
 '76290',
 '51103',
 '66113',
 '52112',
 '63103',
 '69102',
 '68119',
 '52121',
 '72133',
 '64100',
 '62415',
 '63145',
 '65109',
 '78168',
 '68159',
 '50109',
 '67143',
 '50150',
 '51111',
 '73801',
 '68110',
 '65207',
 '65115',
 '52123',
 '52124',
 '67116',
 '79109',
 '61102',
 '50106',
 '68157',
 '66109',
 '50126',
 '65117',
 '60566',
 '51100',
 '61145',
 '68106',
 '69134',
 '52154',
 '69108',
 '52168',
 '67164',
 '61186',
 '78135',
 '61891',
 '69113',
 '64155',
 '61101',
 '67123',
 '69159',
 '79150',
 '51163',
 '68107',
 '52149',
 '76650',
 '76455',
 '79192',
 '65241',
 '79140',
 '65157',
 '62146',
 '52163',
 '52103',
 '68100',
 '69103',
 '52145',
 '64101',
 '69111',
 '63248',
 '77243',
 '52119',
 '66108',
 '68050',
 '68069',
 '69055',
 '64001',
 '51003',
 '52003',
 '51006',
 '65044',
 '68043',
 '65048',
 '64004',
 '52002',
 '64014',
 '50093',
 '66462',
 '51097',
 '65062',
 '62558',
 '66064',
 '65040',
 '66956',
 '50040',
 '52025',
 '67063',
 '50007',
 '64007',
 '73113',
 '75125',
 '60559',
 '68068',
 '52060',
 '68097',
 '68003',
 '64166',
 '65516',
 '68096',
 '52043',
 '50094',
 '50030',
 '64012',
 '52004',
 '51057',
 '68067',
 '62556',
 '64006',
 '64017',
 '52005',
 '73738',
 '67006',
 '52001',
 '64041',
 '52009',
 '68002',
 '65056',
 '50008',
 '64504',
 '52006',
 '51013',
 '68093',
 '50092',
 '52063',
 '69068',
 '66702',
 '67048',
 '69035',
 '67066',
 '65057',
 '68896',
 '66056',
 '78548',
 '64115',
 '69047',
 '75340',
 '51009',
 '52007',
 '65096',
 '68089',
 '67045',
 '64868',
 '64047',
 '65060',
 '69093',
 '51060',
 '50054',
 '52008',
 '51007',
 '69032',
 '78517',
 '67095',
 '50096',
 '52065',
 '51058',
 '67005',
 '76313',
 '61700',
 '52659',
 '67604',
 '63628',
 '61353',
 '51640',
 '66614',
 '69620',
 '52605',
 '69745',
 '69627',
 '67610',
 '78603',
 '51604',
 '68616',
 '50613',
 '68659',
 '64580',
 '63894',
 '52661',
 '69628',
 '69516',
 '66630',
 '65653',
 '62947',
 '69630',
 '78629',
 '66660',
 '52637',
 '52645',
 '66615',
 '62234',
 '51645',
 '79365',
 '50657',
 '52634',
 '69633',
 '67609',
 '63638',
 '67646',
 '64646',
 '52650',
 '66663',
 '52630',
 '52649',
 '67606',
 '52642',
 '66662',
 '77637',
 '69636',
 '68614',
 '52629',
 '67640',
 '52667',
 '52631',
 '68619',
 '52647',
 '51668',
 '51605',
 '63260',
 '51648',
 '50608',
 '67644',
 '51602',
 '65665',
 '62463',
 '64560',
 '69623',
 '62754',
 '66833',
 '51665',
 '50641',
 '69645',
 '63950',
 '66609',
 '50662',
 '50650',
 '62893',
 '65464',
 '52639',
 '72443',
 '52606',
 '52628',
 '63722',
 '61666',
 '78247',
 '65610',
 '52641',
 '61295',
 '50905',
 '65933',
 '65412',
 '63963',
 '60339',
 '65462',
 '52995',
 '67900',
 '68928',
 '68900',
 '60288',
 '68908',
 '51903',
 '51907',
 '51904',
 '51901',
 '67954',
 '50992',
 '67956',
 '50902',
 '50955',
 '69996',
 '62931',
 '52950',
 '66965',
 '69940',
 '65949',
 '52904',
 '79215',
 '64944',
 '52994',
 '62907',
 '74465',
 '52980',
 '66928',
 '66068',
 '52906',
 '69995',
 '77532',
 '63914',
 '69962',
 '68902',
 '61411',
 '50901',
 '76232',
 '52909',
 '68904',
 '51991',
 '51996',
 '76118',
 '63905',
 '76849',
 '62929',
 '51948',
 '77211',
 '65964',
 '68901',
 '67993',
 '60263',
 '52901',
 '52992',
 '52907',
 '52905',
 '63959',
 '52902',
 '78361',
 '69969',
 '50995',
 '76720',
 '61869',
 '63450',
 '52903',
 '52908',
 '67905',
 '68909',
 '65905',
 '69984',
 '66963',
 '51967',
 '69991',
 '68639',
 '50911',
 '51994',
 '62655',
 '52416',
 '74540',
 '64610',
 '68407',
 '62404',
 '64498',
 '61365',
 '66838',
 '51403',
 '64793',
 '52402',
 '79402',
 '52460',
 '68416',
 '67449',
 '63435',
 '51409',
 '66492',
 '52430',
 '68403',
 '65132',
 '52424',
 '50458',
 '78122',
 '68454',
 '61404',
 '51417',
 '64407',
 '62920',
 '67419',
 '65844',
 '69418',
 '61396',
 '50411',
 '77446',
 '50404',
 '68468',
 '64469',
 '52457',
 '52440',
 '66406',
 '68415',
 '69430',
 '78756',
 '75421',
 '75334',
 '73117',
 '69446',
 '68463',
 '52407',
 '51411',
 '69428',
 '63960',
 '66409',
 '64464',
 '50464',
 '51454',
 '60146',
 '75566',
 '63492',
 '52415',
 '51460',
 '68466',
 '69416',
 '66493',
 '52417',
 '77927',
 '50414',
 '52405',
 '51468',
 '52400',
 '61197',
 '66451',
 '68501',
 '51463',
 '50449',
 '51462',
 '51408',
 '65496',
 '50441',
 '65515',
 '69585',
 '79358',
 '65514',
 '52562',
 '69517',
 '63543',
 '65522',
 '50517',
 '78536',
 '68585',
 '68589',
 '52576',
 '52504',
 '50573',
 '69500',
 '67504',
 '52564',
 '52514',
 '52569',
 '52566',
 '62528',
 '64596',
 '65506',
 '66749',
 '51516',
 '51586',
 '67539',
 '51551',
 '67454',
 '52547',
 '65643',
 '52583',
 '66556',
 '64021',
 '62802',
 '50563',
 '69594',
 '63512',
 '52528',
 '64501',
 '69539',
 '51594',
 '50558',
 '52557',
 '69508',
 '50590',
 '64022',
 '79608',
 '52565',
 '52591',
 '67588',
 '50036',
 '71564',
 '52530',
 '68529',
 '64565',
 '62294',
 '69453',
 '68504',
 '68507',
 '78513',
 '51580',
 '68518',
 '68556',
 '51546',
 '60523',
 '65067',
 '52516',
 '64717',
 '79545',
 '52558',
 '68036',
 '63895',
 '64718',
 '50556',
 '68362',
 '52526',
 '52560',
 '68525',
 '52568',
 '50500',
 '52210',
 '52207',
 '63123',
 '51297',
 '62925',
 '51269',
 '68220',
 '68204',
 '50203',
 '77263',
 '69238',
 '51294',
 '51230',
 '52267',
 '67246',
 '69210',
 '65269',
 '50294',
 '52211',
 '63257',
 '74206',
 '78224',
 '60181',
 '69207',
 '68269',
 '69104',
 '67259',
 '51257',
 '64468',
 '51298',
 '62244',
 '63292',
 '68249',
 '50205',
 '67202',
 '65639',
 '67266',
 '52257',
 '66203',
 '69203',
 '52234',
 '52294',
 '64086',
 '66202',
 '50202',
 '64011',
 '51203',
 '64153',
 '50293',
 '51200',
 '50208',
 '77248',
 '66160',
 '62242',
 '65064',
 '52202',
 '69205',
 '52209',
 '52204',
 '64805',
 '66291',
 '52295',
 '67207',
 '76329',
 '62951',
 '52205',
 '78352',
 '51295',
 '51204',
 '63202',
 '74513',
 '68205',
 '69204',
 '69211',
 '52299',
 '79231',
 '52203',
 '64202',
 '68242',
 '50211',
 '66209',
 '50296',
 '52208',
 '50298',
 '51264',
 '64213',
 '67263',
 '52206',
 '69209',
 '79240',
 '68260',
 '61643',
 '66233',
 '66207',
 '66710',
 '50705',
 '52769',
 '69702',
 '52703',
 '51713',
 '51715',
 '67711',
 '68707',
 '65764',
 '65769',
 '50710',
 '66715',
 '66741',
 '63765',
 '52706',
 '66704',
 '67768',
 '69518',
 '50720',
 '52717',
 '63704',
 '69737',
 '52707',
 '64029',
 '52701',
 '51705',
 '52711',
 '66707',
 '67703',
 '69762',
 '50709',
 '52731',
 '78643',
 '69727',
 '61156',
 '51767',
 '60140',
 '68625',
 '50758',
 '52716',
 '51707',
 '52702',
 '51202',
 '67760',
 '69766',
 '52765',
 '52705',
 '63464',
 '69213',
 '63961',
 '65703',
 '65616',
 '52704',
 '64266',
 '52714',
 '68706',
 '68797',
 '68700',
 '52715',
 '51708',
 '51702',
 '66657',
 '63749',
 '60343',
 '50704',
 '62611',
 '51762',
 '79764',
 '77318',
 '63700',
 '51706',
 '66706',
 '52722',
 '51764',
 '74857',
 '68743',
 '69767',
 '51796',
 '51701',
 '65707',
 '50708',
 '78288',
 '52733',
 '51722',
 '50815',
 '52712',
 '52720',
 '62700',
 '52710',
 '50726',
 '69706',
 '52764',
 '64760']

In [6]:
url = "https://www.koreabaseball.com/Futures/Player/HitterDetail.aspx?playerId={}"

In [11]:
r = requests.get(url.format(kbo[0]))

In [12]:
bs = BeautifulSoup(r.text, 'lxml')

In [15]:
for x in bs.find("div", {'class' :'player_basic'}).findAll("li"):
    key, value = x.text.split(":")
    tmp_dict[key.strip()] = value.strip()

In [30]:
from bs4 import BeautifulSoup
url = "https://www.koreabaseball.com/Futures/Player/HitterDetail.aspx?playerId={}"
r = requests.get(url.format(kbo[0]))
bs = BeautifulSoup(r.text, 'lxml')
tmp_dict = dict()
for x in bs.find("div", {'class' :'player_basic'}).findAll("li"):
    key, value = x.text.split(":")
    tmp_dict[key.strip()] = value.strip()

In [31]:
team

'SSG 랜더스'

In [32]:
tmp_dict

{'선수명': '강매성',
 '등번호': 'No.95',
 '생년월일': '2003년 06월 08일',
 '포지션': '투수(우투우타)',
 '신장/체중': '187cm/94kg',
 '경력': '상탄초(일산동구리틀)-개군중-공주고',
 '입단 계약금': '5000만원',
 '연봉': '3000만원',
 '지명순위': '22 SSG 2차 6라운드 52순위',
 '입단년도': ''}

In [ ]:
import tqdm

In [36]:
import tqdm
total = []
for player_id in tqdm.tqdm(kbo):
    r = requests.get(url.format(player_id))
    bs = BeautifulSoup(r.text, 'lxml')
    tmp_dict = dict()
    for x in bs.find("div", {'class' :'player_basic'}).findAll("li"):
        key, value = x.text.split(":")
        tmp_dict[key.strip()] = value.strip()
    tmp_dict['team'] = bs.find("h4", id="h4Team").text     
    total.append(tmp_dict)

100%|████████████████████████████████████████████████████████████████████████████████| 882/882 [01:29<00:00,  9.82it/s]

In [66]:
import pandas as pd
pd.DataFrame(total)

,선수명,등번호,생년월일,포지션,신장/체중,경력,입단 계약금,연봉,지명순위,입단년도,team
0,강매성,No.95,2003년 06월 08일,투수(우투우타),187cm/94kg,상탄초(일산동구리틀)-개군중-공주고,5000만원,3000만원,22 SSG 2차 6라운드 52순위,,SSG 랜더스
1,고명준,No.6,2002년 07월 08일,내야수(우투우타),185cm/94kg,서원초-세광중-세광고-SK,9000만원,3000만원,21 SK 2차 2라운드 18순위,21SK,SSG 랜더스
2,고효준,No.65,1983년 02월 08일,투수(좌투좌타),179cm/81kg,서원초-세광중-세광고-롯데-SK-KIA-롯데-LG,11000만원,4000만원,02 롯데 2차 1라운드 6순위,02롯데,SSG 랜더스
3,김강민,No.0,1982년 09월 13일,외야수(우투우타),182cm/87kg,본리초-대구중-경북고-SK,11000만원,16000만원,01 SK 2차 2라운드 18순위,01SK,SSG 랜더스
4,김건우,No.59,2002년 07월 12일,투수(좌투좌타),185cm/88kg,가현초(인천서구리틀)-동산중-제물포고-SK,20000만원,3100만원,21 SK 1차,21SK,SSG 랜더스
...,...,...,...,...,...,...,...,...,...,...,...
877,한경빈,No.110,1998년 12월 11일,내야수(우투좌타),178cm/77kg,인천서림초-상인천중-동산고-인천재능대,,3000만원,22 한화 육성선수,,한화 이글스
878,한승주,No.59,2001년 03월 17일,투수(우투우타),184cm/82kg,부산수영초-대천중-부산고,11000만원,3000만원,20 한화 2차 2라운드 18순위,20한화,한화 이글스
879,허관회,No.26,1999년 02월 12일,포수(우투우타),176cm/83kg,경동초(의정부리틀)-건대부중-경기고,3000만원,3370만원,19 한화 2차 9라운드 83순위,20한화,한화 이글스
880,허인서,No.64,2003년 07월 11일,포수(우투우타),182cm/93kg,순천북초-여수중-효천고,11000만원,3000만원,22 한화 2차 2라운드 11순위,22한화,한화 이글스
881,황영국,No.4,1995년 12월 26일,투수(좌투좌타),185cm/83kg,청주우암초-청주중-청주고-한화-경찰,20000만원,3400만원,14 한화 1차,14한화,한화 이글스

In [67]:
total

In [41]:
df.to_excel("kbo.xlsx")

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 882 entries, 0 to 881
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   선수명     882 non-null    object
 1   등번호     882 non-null    object
 2   생년월일    882 non-null    object
 3   포지션     882 non-null    object
 4   신장/체중   882 non-null    object
 5   경력      882 non-null    object
 6   입단 계약금  882 non-null    object
 7   연봉      868 non-null    object
 8   지명순위    882 non-null    object
 9   입단년도    882 non-null    object
 10  team    882 non-null    object
dtypes: object(11)
memory usage: 75.9+ KB

In [51]:
import matplotlib.pyplot as plt
ans = df['team'].value_counts().sort_index()

In [52]:
ans

KIA 타이거즈    85
KT 위즈       93
LG 트윈스      93
NC 다이노스     85
SSG 랜더스     88
고양 히어로즈     16
두산 베어스      94
롯데 자이언츠     79
삼성 라이온즈     78
상무          14
키움 히어로즈     64
한화 이글스      93
Name: team, dtype: int64

In [68]:
height, weight = x['신장/체중'].split("/")

TypeError: list indices must be integers or slices, not str

In [60]:
def calc(h, w):
    return int(w.replace("kg", "")) / (int(h.replace('cm','')) / 100 ** 2)(height, weight)

In [61]:
calc(weight, height)

NameError: name 'weight' is not defined

In [ ]:
for x in total:
    height, weight = x['신장/체중'].split("/")
    x['BMI']  = calc(height, weight)

In [ ]:
sorted({x['선수명'] : x['BMI'] for x in total}.items(), key=lambda x : x[1])

In [84]:
hana = "https://www.kebhana.com/cms/rate/wpfxd651_0li_01.do"

In [85]:
hana_payload = {"ajax"  : "true",
           "curCd"  : "",
           "tmpInqStrDt"  : "2023-01-12",
           "pbldDvCd"  : "0",
           "pbldSqn"  : "",
           "hid_key_data"  : "",
           "inqStrDt"  : "20230112",
           "inqKindCd"  : "1",
           "hid_enc_data"  : "",
           "requestTarget"  : "searchContentDiv",
}

In [86]:
r = requests.post(hana, data=hana_payload)

In [80]:
for idx, x enumerate(BeautifulSoup(r.text, 'lxml').findAll("tr")[3].findAll("td")):
    print(idx, x.text)

SyntaxError: invalid syntax (4104571769.py, line 1)

In [90]:
def tmp(date_):
    pass

In [95]:
def exchange(date_):
    hana_payload['tmpInqStrDt'] = date_ 
    hana_payload['inqStrDt'] = date_.replace("-", "")
    r = requests.post(hana, data = hana_payload)
    return BeautifulSoup(r.text, 'lxml').findAll("tr")[3].findAll("td")[9].text

In [96]:
from datetime import date, datetime, timedelta
date_dict = dict()
for x in range(3):
    key = (date(2022,1,1) + timedelta(days=x)).strftime("%Y-%m-%d")
    val = exchange((date(2022,1,1) + timedelta(days=x)).strftime("%Y-%m-%d"))
    date_dict[key] = val

IndexError: list index out of range

In [97]:
import random

In [99]:
no_sw_win = list()
sw_win = list()

In [100]:
prize = random.sample(doors, 1)
print(pick)

NameError: name 'doors' is not defined

In [ ]:
if __name__ =="__main__":
    start = time.time()
    print(f"start -> {start}")
          
    with open
          
    pool = pool(processes=4)
    
          result = pool.map(crawling_kbo, kbo):
          
          with open(./kbo-result.pkl):
              pickle.duup
          print(f"time -->)

In [ ]:
float(exchange:

In [ ]:
if x ['연봉'].find("달러") > -1:
    int(x['연봉(만원)'])

In [101]:
if x['연봉'].find("달러") == 1:

TypeError: 'int' object is not subscriptable

In [ ]:
kbo_result

In [102]:
print("{:,}원".format(sum([x['연봉(만원)'] for x in kbo_result]) / len(kbo_result)))

NameError: name 'kbo_result' is not defined

In [ ]:
for x in kbo_result:
    x['나이'] = 2023 - int(x['생년월일'].split("년")[0])

In [ ]:
sorted({x['선수명'] : x['나이'] for x in kbo_result}.items(), key=lambda x : x[1])