In [3]:
import sys

sys.path.append('../')
import mustaching as ms


%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

# Load transactions

In [26]:
# Invent some sample transactions.
transactions = ms.create_transactions('2020-01-01', '2020-12-31')

# Alternatively, upload your own transactions as say 'my_transactions.csv' 
#transactions = ms.read_transactions('my_transactions.csv')

transactions.head(10)

                 date  amount description       comment     category
0 2020-01-01 00:00:00      61     0x66736  0xfa3d4004d8  programming
1 2020-01-01 12:00:00      79     0x55ce2  0xf853bc66f1  programming
2 2020-01-02 00:00:00      14     0xee9a3  0x38bc13c668        reiki
3 2020-01-02 12:00:00      76     0x346de  0x6f1942aa09  programming
4 2020-01-03 00:00:00      36     0xb3df1  0x8a936a1843  programming
5 2020-01-03 12:00:00      42     0x2b6bd  0x545c0e9945        reiki
6 2020-01-04 00:00:00     -65       0x5bb  0x8aa462342b      shelter
7 2020-01-04 12:00:00      62     0xc7581  0x99146ccd75    investing
8 2020-01-05 00:00:00      85     0xf3334  0x9f85d84001  programming
9 2020-01-05 12:00:00      84     0x7b335  0x346ec6bc74    investing

In [27]:
import io

ms.read_transactions(io.StringIO(transactions.to_csv(index=False)))

                   date  amount description      category       comment
0   2020-01-01 00:00:00    61.0     0x66736   programming  0xfa3d4004d8
1   2020-01-01 12:00:00    79.0     0x55ce2   programming  0xf853bc66f1
2   2020-01-02 00:00:00    14.0     0xee9a3         reiki  0x38bc13c668
3   2020-01-02 12:00:00    76.0     0x346de   programming  0x6f1942aa09
4   2020-01-03 00:00:00    36.0     0xb3df1   programming  0x8a936a1843
..                  ...     ...         ...           ...           ...
726 2020-12-29 00:00:00   -23.0     0xdf05d     transport  0xb482ea9eaf
727 2020-12-29 12:00:00    32.0     0x12d0e     investing  0x440177a330
728 2020-12-30 00:00:00    86.0     0x33cfd   programming  0xa72ad6bcd5
729 2020-12-30 12:00:00   -29.0     0x5003a       shelter  0x4c4e261e73
730 2020-12-31 00:00:00     0.0     0x4686d  soil testing  0x2473651aa2

[731 rows x 5 columns]

# Summarize transactions and plot

In [28]:
# Summarize over entire period by category
s1 = ms.summarize(transactions, by_category=True)
s1

,date,category,income,expense,balance,savings_pc_for_period,spending_pc_for_period,spending_pc_for_period_and_category,income_pc_for_period_and_category,expense_pc_for_period_and_category,daily_avg,weekly_avg,monthly_avg,yearly_avg
0,2020-01-01,food,0,1595,9010,44.03,55.97,7.79,0.00,13.93,-4.36,-30.51,-132.55,-1590.64
1,2020-01-01,healthcare,0,2203,9010,44.03,55.97,10.77,0.00,19.24,-6.02,-42.13,-183.08,-2196.98
2,2020-01-01,investing,4721,0,9010,44.03,55.97,0.00,23.07,0.00,12.90,90.29,392.34,4708.10
3,2020-01-01,programming,11017,0,9010,44.03,55.97,0.00,53.84,0.00,30.10,210.71,915.57,10986.90
4,2020-01-01,reiki,4725,0,9010,44.03,55.97,0.00,23.09,0.00,12.91,90.37,392.67,4712.09
5,2020-01-01,shelter,0,3724,9010,44.03,55.97,18.20,0.00,32.52,-10.17,-71.22,-309.49,-3713.83
6,2020-01-01,soil testing,0,2164,9010,44.03,55.97,10.58,0.00,18.89,-5.91,-41.39,-179.84,-2158.09
7,2020-01-01,transport,0,1767,9010,44.03,55.97,8.64,0.00,15.43,-4.83,-33.80,-146.85,-1762.17

In [29]:
ms.plot(s1)

In [30]:
# Summarize by month start
s2 = ms.summarize(transactions, freq='QS', by_category=True)
s2

,date,category,income,expense,balance,savings_pc_for_period,spending_pc_for_period,spending_pc_for_period_and_category,income_pc_for_period_and_category,expense_pc_for_period_and_category
0,2020-01-01,food,0,333,2759,51.00,49.00,6.16,0.00,12.56
1,2020-01-01,healthcare,0,434,2759,51.00,49.00,8.02,0.00,16.37
2,2020-01-01,investing,1481,0,2759,51.00,49.00,0.00,27.38,0.00
3,2020-01-01,programming,2953,0,2759,51.00,49.00,0.00,54.58,0.00
4,2020-01-01,reiki,976,0,2759,51.00,49.00,0.00,18.04,0.00
5,2020-01-01,shelter,0,1043,2759,51.00,49.00,19.28,0.00,39.34
6,2020-01-01,soil testing,0,619,2759,51.00,49.00,11.44,0.00,23.35
7,2020-01-01,transport,0,222,2759,51.00,49.00,4.10,0.00,8.37
8,2020-04-01,food,0,568,4928,42.16,57.84,11.04,0.00,19.09
9,2020-04-01,healthcare,0,727,4928,42.16,57.84,14.13,0.00,24.43
10,2020-04-01,investing,1317,0,4928,42.16,57.84,0.00,25.60,0.00
11,2020-04-01,programming,2573,0,4928,42.16,57.84,0.00,50.01,0.00
12,2020-04-01,reiki,1255,0,4928,42.16,57.84,0.00,24.39,0.00
13,2020-04-01,shelter,0,864,4928,42.16,57.84,16.79,0.00,29.03
14,2020-04-01,soil testing,0,435,4928,42.16,57.84,8.45,0.00,14.62
15,2020-04-01,transport,0,382,4928,42.16,57.84,7.42,0.00,12.84
16,2020-07-01,food,0,325,6714,37.59,62.41,6.84,0.00,10.96
17,2020-07-01,healthcare,0,540,6714,37.59,62.41,11.37,0.00,18.21
18,2020-07-01,investing,797,0,6714,37.59,62.41,0.00,16.78,0.00
19,2020-07-01,programming,2537,0,6714,37.59,62.41,0.00,53.40,0.00
20,2020-07-01,reiki,1417,0,6714,37.59,62.41,0.00,29.83,0.00
21,2020-07-01,shelter,0,829,6714,37.59,62.41,17.45,0.00,27.96
22,2020-07-01,soil testing,0,484,6714,37.59,62.41,10.19,0.00,16.32
23,2020-07-01,transport,0,787,6714,37.59,62.41,16.56,0.00,26.54
24,2020-10-01,food,0,369,9010,44.52,55.48,7.16,0.00,12.90
25,2020-10-01,healthcare,0,502,9010,44.52,55.48,9.73,0.00,17.55
26,2020-10-01,investing,1126,0,9010,44.52,55.48,0.00,21.83,0.00
27,2020-10-01,programming,2954,0,9010,44.52,55.48,0.00,57.28,0.00
28,2020-10-01,reiki,1077,0,9010,44.52,55.48,0.00,20.88,0.00
29,2020-10-01,shelter,0,988,9010,44.52,55.48,19.16,0.00,34.53
30,2020-10-01,soil testing,0,626,9010,44.52,55.48,12.14,0.00,21.88
31,2020-10-01,transport,0,376,9010,44.52,55.48,7.29,0.00,13.14

In [31]:
ms.plot(s2)

In [16]:
# Summarize by quarter start and by category
s3 = ms.summarize(transactions, freq='QS', by_category=True)
s3

,date,category,income,expense,balance,savings_pc_for_period,spending_pc_for_period,spending_pc_for_period_and_category,income_pc_for_period_and_category,expense_pc_for_period_and_category
0,2017-01-01,food,0,496,1844,36.74,63.26,9.88,0.00,15.62
1,2017-01-01,healthcare,0,410,1844,36.74,63.26,8.17,0.00,12.91
2,2017-01-01,investing,1336,0,1844,36.74,63.26,0.00,26.62,0.00
3,2017-01-01,programming,2292,0,1844,36.74,63.26,0.00,45.67,0.00
4,2017-01-01,reiki,1391,0,1844,36.74,63.26,0.00,27.71,0.00
5,2017-01-01,shelter,0,1236,1844,36.74,63.26,24.63,0.00,38.93
6,2017-01-01,soil testing,0,498,1844,36.74,63.26,9.92,0.00,15.69
7,2017-01-01,transport,0,535,1844,36.74,63.26,10.66,0.00,16.85
8,2017-04-01,food,0,476,4331,48.47,51.53,9.28,0.00,18.00
9,2017-04-01,healthcare,0,513,4331,48.47,51.53,10.00,0.00,19.40
10,2017-04-01,investing,1269,0,4331,48.47,51.53,0.00,24.73,0.00
11,2017-04-01,programming,2698,0,4331,48.47,51.53,0.00,52.58,0.00
12,2017-04-01,reiki,1164,0,4331,48.47,51.53,0.00,22.69,0.00
13,2017-04-01,shelter,0,852,4331,48.47,51.53,16.60,0.00,32.22
14,2017-04-01,soil testing,0,419,4331,48.47,51.53,8.17,0.00,15.85
15,2017-04-01,transport,0,384,4331,48.47,51.53,7.48,0.00,14.52
16,2017-07-01,food,0,553,7577,54.69,45.31,9.32,0.00,20.57
17,2017-07-01,healthcare,0,301,7577,54.69,45.31,5.07,0.00,11.19
18,2017-07-01,investing,1263,0,7577,54.69,45.31,0.00,21.28,0.00
19,2017-07-01,programming,2856,0,7577,54.69,45.31,0.00,48.12,0.00
20,2017-07-01,reiki,1816,0,7577,54.69,45.31,0.00,30.60,0.00
21,2017-07-01,shelter,0,1033,7577,54.69,45.31,17.41,0.00,38.42
22,2017-07-01,soil testing,0,367,7577,54.69,45.31,6.18,0.00,13.65
23,2017-07-01,transport,0,435,7577,54.69,45.31,7.33,0.00,16.18
24,2017-10-01,food,0,308,10216,52.52,47.48,6.13,0.00,12.91
25,2017-10-01,healthcare,0,397,10216,52.52,47.48,7.90,0.00,16.64
26,2017-10-01,investing,1259,0,10216,52.52,47.48,0.00,25.05,0.00
27,2017-10-01,programming,2832,0,10216,52.52,47.48,0.00,56.36,0.00
28,2017-10-01,reiki,934,0,10216,52.52,47.48,0.00,18.59,0.00
29,2017-10-01,shelter,0,751,10216,52.52,47.48,14.95,0.00,31.48
30,2017-10-01,soil testing,0,379,10216,52.52,47.48,7.54,0.00,15.88
31,2017-10-01,transport,0,551,10216,52.52,47.48,10.97,0.00,23.09

In [17]:
ms.plot(s3)