# Basic Python script to collate quizes from sites using web scraping methods

In [1]:
#importing necessary packages 
import requests
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.options import Options
import time

In [43]:
#scraping quize from javapoint 
# Making a GET request
r = requests.get('https://www.javatpoint.com/python-mcq')

# Parsing the HTML
soup = BeautifulSoup(r.content, 'html.parser')

In [75]:
# parsing the html tags from various classes
for m,tag in enumerate(soup.find_all('div',{'class':'testanswer'})):
    answer = tag.find_all('p')
    
question = soup.find_all('p', class_='pq')
options = soup.find_all('ol',class_ = 'pointsa')

ques = []#creating empty list
op = []
ans = []
#appending texts into list
for q in question:
    ques.append(q.text)
    #print(ques)
for o in options:
    op.append(o.text)
    #print(op)
#for item in answer:
    #an.append(item.text)

In [117]:
#for n,tag1 in enumerate(soup.find_all('ol',{'class':'pointsa'})):
    #options = tag.find_all('li')
    
o = []
for n,tag1 in enumerate(soup.find_all('ol',{'class':'pointsa'})):
    op = [x for x in tag1.find_all('li')]
    
    
    for item in op:
        o.append(item.text)

In [98]:

answ = []
for m,tag in enumerate(soup.find_all('div',{'class':'testanswer'})):
    answer = [x for x in tag.find('p')]
    
    
    for item in answer:
        answ.append(item.text)

In [219]:
answ

[' (d) None of these above',
 ' (b) Guido van Rossum',
 ' (d) 1989',
 ' (b) C',
 ' (a) .py',
 ' (a) 2008',
 ' (c) Indentation',
 ' (c) #',
 ' (b) Objects are real-world entities while classes are not real',
 ' (b) id(name1) and id(name2) will have same value',
 ' (b) Function',
 ' (d) None of these',
 ' (c) It indicates a private variable of a class',
 ' (a) val',
 ' (b) Unlimited length',
 ' (b) x y z p = 5000 6000 7000 8000',
 ' (c) try',
 ' (b) a**b',
 ' (a) Parentheses, Exponential, Multiplication, Division, Addition, Subtraction',
 ' (b) Division and Multiplication',
 ' (d) Parentheses',
 ' (b) print()',
 ' (d) 5',
 ' (c) (x**y) % z',
 ' (a) False',
 ' (a) error',
 " (a) Infile = open(''c:\\\\scores.txt'', ''r'')",
 " (a) ['XX', 'YY']",
 ' (d) 6.0',
 ' (b) True',
 ' (b) abc',
 ' (c) point',
 ' (d) string.ascii_lowercase+string.ascii_upercase',
 ' (a) t',
 ' (c) \\njavat\\npoint',
 ' (a) 33',
 ' (d) Error is generated',
 ' (d) Wick Nick',
 ' (b) -18',
 " (a) ['xy', 'yz']",
 ' (d) Invalid syntax',
 ' (b) 1 2 3 4 5 6',
 ' (c) 0 1 2',
 ' (c) 0 1 2 0',
 ' (b) No output',
 ' (b) pqrs',
 ' (b) 0 1 2',
 ' (b) 0 1 2',
 ' (c) Class',
 ' (a) NamaError',
 ' (d) indentationError',
 ' (c) List',
 ' (a) False',
 ' (a) invalid code ',
 ' (d) All of the above']

In [123]:
#retrieving every 4th element from the master list to a separate list based on the position
a = []
a.append(o[::4])
b = []
b.append(o[1::4])
c = []
c.append(o[2::4])
d = []
d.append(o[3::4])

In [208]:
#function to flatten the nested list into a separate list 
cccorrect_choice = []
def reemovNestings(correct_choice):
    for i in correct_choice:
        if type(i) == list:
            reemovNestings(i)
        else:
            cccorrect_choice.append(i)
  
# Driver code
#print ('The original list: ', a)
reemovNestings(correct_choice)
print ('The list after removing nesting: ', cccorrect_choice)

The list after removing nesting:  ['d', 'b', 'd', 'b', 'a', 'a', 'c', 'c', 'b', 'b', 'b', 'd', 'c', 'a', 'b', 'b', 'c', 'b', 'a', 'b', 'd', 'b', 'd', 'c', 'a', 'a', 'a', 'a', 'd', 'b', 'b', 'c', 'd', 'a', 'c', 'a', 'd', 'd', 'b', 'a', 'd', 'b', 'c', 'c', 'b', 'b', 'b', 'b', 'c', 'a', 'd', 'c', 'a', 'a', 'd']

In [103]:
#using regex to remove the string Answer from the list
K = "Answer:"
  
# using remove() to
# Remove K String from String List
while(K in answ) :
    answ.remove(K)

In [161]:
#retrieving elements from the list which are in brackets
correct_choice = []

for i in answ:
    #print(i)
    #.str.extract(r'\(([^()]+)\)')
    res = re.findall(r'\(([^()])\)', i)
    correct_choice.append(res)

In [222]:
#formalising a dataframe 
for i in range(1,len(df)):
    df = pd.DataFrame({'question_text':ques,'question_type':1,'choice_A_text':A,'choice_B_text':bb,'choice_C_text':cc,'choice_D_text':D,'choice_E_text':' ','correct_choice':cccorrect_choice,
                       'correct_puzzle_answer':" ",'difficulty_level':1,'is_deleted':0}) 
    df.insert(0, 'id', range(1, 1 + len(df)))
    df.to_csv('basic_quiz.csv', index=False, encoding='utf-8')

In [223]:
df

,id,question_text,question_type,choice_A_text,choice_B_text,choice_C_text,choice_D_text,choice_E_text,correct_choice,correct_puzzle_answer,difficulty_level,is_deleted
0,1,1) What is the maximum possible length of an i...,1,16,32,64,None of these above,,d,,1,0
1,2,2) Who developed the Python language?,1,Zim Den,Guido van Rossum,Niene Stom,Wick van Rossum,,b,,1,0
2,3,3) In which year was the Python language devel...,1,1995,1972,1981,1989,,d,,1,0
3,4,4) In which language is Python written?,1,English,PHP,C,All of the above,,b,,1,0
4,5,5) Which one of the following is the correct e...,1,.py,.python,.p,None of these,,a,,1,0
5,6,6) In which year was the Python 3.0 version de...,1,2008,2000,2010,2005,,a,,1,0
6,7,7) What do we use to define a block of code in...,1,Key,Brackets,Indentation,None of these,,c,,1,0
7,8,8) Which character is used in Python to make a...,1,/,//,#,!,,c,,1,0
8,9,9) Which of the following statements is correc...,1,Classes are real-world entities while objects ...,Objects are real-world entities while classes ...,Both objects and classes are real-world entities,All of the above,,b,,1,0
9,10,10) Which of the following statements is corre...,1,It will throw the error as multiple references...,id(name1) and id(name2) will have same value,Both name1 and name2 will have reference to tw...,All of the above,,b,,1,0
10,11,11) What is the method inside the class in pyt...,1,Object,Function,Attribute,Argument,,b,,1,0
11,12,12) Which of the following declarations is inc...,1,_x = 2,__x = 3,__xyz__ = 5,None of these,,d,,1,0
12,13,13) Why does the name of local variables start...,1,To identify the variable,It confuses the interpreter,It indicates a private variable of a class,None of these,,c,,1,0
13,14,14) Which of the following is not a keyword in...,1,val,raise,try,with,,a,,1,0
14,15,15) Which of the following statements is corre...,1,All variable names must begin with an underscore.,Unlimited length,The variable name length is a maximum of 2.,All of the above,,b,,1,0
15,16,16) Which of the following declarations is inc...,1,"xyzp = 5,000,000",x y z p = 5000 6000 7000 8000,"x,y,z,p = 5000, 6000, 7000, 8000","x_y_z_p = 5,000,000",,b,,1,0
16,17,17) Which of the following words cannot be a v...,1,_val,val,try,_try_,,c,,1,0
17,18,18) Which of the following operators is the co...,1,a ^ b,a**b,a ^ ^ b,a ^ * b,,b,,1,0
18,19,19) Which of the following precedence order is...,1,"Parentheses, Exponential, Multiplication, Divi...","Multiplication, Division, Addition, Subtractio...","Division, Multiplication, Addition, Subtractio...","Exponential, Parentheses, Multiplication, Divi...",,a,,1,0
19,20,20) Which one of the following has the same pr...,1,"Division, Power, Multiplication, Addition and ...",Division and Multiplication,Subtraction and Division,Power and Division,,b,,1,0
20,21,21) Which one of the following has the highest...,1,Division,Subtraction,Power,Parentheses,,d,,1,0
21,22,22) Which of the following functions is a buil...,1,val(),print(),print(),None of these,,b,,1,0
22,23,23) Study the following function:,1,4,5,576,5,,d,,1,0
23,24,24) Which of the following is correctly evalua...,1,(x**y) / z,(x / y) * z,(x**y) % z,(x / y) / z,,c,,1,0
24,25,25) Study the following function:,1,False,True,0,Invalid code,,a,,1,0
25,26,26) Study the following program:,1,error,2 1,0 3 1,None of these,,a,,1,0
26,27,27) Which one of the following syntaxes is the...,1,"Infile = open(''d:\\java.txt'', ''r'')","Infile = open(file=''d:\\\java.txt'', ''r'')","Infile = open(''d:\java.txt'',''r'')","Infile = open.file(''d:\\java.txt'',''r'')",,a,,1,0
27,28,28) Study the following code:,1,"['XX', 'YY']","['xx', 'yy']","[XX, yy]",None of these,,a,,1,0
28,29,29) Study the following function:,1,Error,-6,6,6.0,,d,,1,0
29,30,30) Study the following function:,1,False,Ture,Invalid code,None of these,,b,,1,0
30,31,31) Study the following statement:,1,a+bc,abc,a bc,a,,b,,1,0
31,32,32) Study the following code:,1,javatpoint,java,point,None of these,,c,,1,0
32,33,33) The output to execute string.ascii_letters...,1,character,ascii_lowercase_string.digits,lowercase_string.upercase,ascii_lowercase+string.ascii_upercase,,d,,1,0
33,34,34) Study the following statements:,1,t,j,point,java,,a,,1,0
34,35,35) Study the following code:,1,javapoint,java point,\njavat\npoint,Print the letter r and then javat and then point,,c,,1,0
35,36,36) Study the following statements:,1,33,63,0xA + 0xB + 0xC,None of these,,a,,1,0
36,37,37) Study the following program:,1,32,32 32,32 None,Error is generated,,d,,1,0
37,38,38) Study the following program:,1,Ann Bob,Ann Nick,Wick Bob,Wick Nick,,d,,1,0
38,39,39) Study the following statements:,1,18,-18,17,-17,,b,,1,0
39,40,40) Study the following program:,1,"['xy', 'yz']","['XY', 'YZ']","[None, None]",None of these,,a,,1,0
40,41,41) Study the following program:,1,1 2 3,3 2 1,1 2,Invalid syntax,,d,,1,0
41,42,42) Study the following program:,1,1 2 3 4 5,1 2 3 4 5 6,1 2 3 4 5 6 7,Invalid syntax,,b,,1,0
42,43,43) Study the following program:,1,1 2 3,0 1 2 3,0 1 2,3 2 1,,c,,1,0
43,44,44) Study the following program:,1,0 1,0 1 2,0 1 2 0,0 1 2 3,,c,,1,0
44,45,45) Study the following program:,1,xyz,No output,x y z,j j j j j j j..,,b,,1,0
45,46,46) Study the following program:,1,PQRS,pqrs,qrs,None of these,,b,,1,0
46,47,47) Study the following program:,1,a b c,0 1 2,0 a 1 b 2 c,None of these above,,b,,1,0
47,48,48) Study the following program:,1,"{0, 1, 2} {0, 1, 2} {0, 1, 2}",0 1 2,Syntax_Error,None of these above,,b,,1,0
48,49,49) Which of the following option is not a cor...,1,Dictionary,Lists,Class,All of the above,,c,,1,0
49,50,50) What error will occur when you execute the...,1,NameError,SyntaxError,TypeError,ValueError,,a,,1,0
50,51,51) Study the following program:,1,hello2hello2,hello2,Cannot perform mathematical operation on strings,indentationError,,d,,1,0
51,52,52) Which of the following data types is shown...,1,Dictionary,Tuple,List,Stack,,c,,1,0
52,53,53) What happens when '2' == 2 is executed?,1,False,Ture,ValueError occurs,TypeError occurs,,a,,1,0
53,54,54) Study the following program:,1,invalid code,JavaTpoint has not exist,JavaTpoint has exist,none of these above,,a,,1,0
54,55,55) Study the following statement,1,x dictionary z is created,x and y are the keys of dictionary z,0 and 1 are the values of dictionary z,All of the above,,d,,1,0